Tornado cash abstractions edits
duneanalytics/spellbook pull request #1412
Opened 2022-08-22 17:35 UTC by dot2dotseurat

Brief comments on the purpose of your changes:
Follow on from Hildobby's PR. Moving to a new branch since I couldn't push back to remote. 

*For Dune Engine V2*
I've checked that:

* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

2022-08-22 17:40 UTC, dot2dotseurat commented
@hildobby I've edited the tests to look at unique sets of columns rather than the custom test you had. 

Looks like there are 532 duplicates in tornado_cash_deposits. 
17:28:28  5 of 6 FAIL 532 dbt_utils_unique_combination_of_columns_tornado_cash_deposits_depositor__amount__blockchain__currency_contract__currency_symbol__block_time__evt_index  [FAIL 532 in 1299.25s]
 
 That table is queryable under  dbt_meghan_tornado_cash.deposits. Can you take a look and see if you can figure out where the duplicates are coming from?

2022-08-24 18:36 UTC, jeff-dude requested changes

2022-08-24 18:36 UTC, jeff-dude commented on models/tornado_cash/tornado_cash_deposits.sql
> +        AND tc.evt_block_time >= (select max(block_time) from {{ this }})
should be 'WHERE' since it's on base table

2022-08-24 18:36 UTC, jeff-dude commented on models/tornado_cash/tornado_cash_deposits.sql
> +        LEFT JOIN {{ source('ethereum','transactions_0006') }} et ON et.hash=tc.evt_tx_hash
should have a second if is incremental, 'AND et.block_time >= (select max(block_time) from {{ this }})'
to be safe, double check the column name, assuming it drops the 'evt' preface

2022-08-24 18:36 UTC, jeff-dude commented on models/tornado_cash/tornado_cash_deposits.sql
> +        AND tc.evt_block_time >= (select max(block_time) from {{ this }})
same two comments from above

2022-08-24 18:36 UTC, jeff-dude commented on models/tornado_cash/tornado_cash_deposits.sql
> +        AND tc.evt_block_time >= (select max(block_time) from {{ this }})
same two comments from above

2022-08-24 18:36 UTC, jeff-dude commented on models/tornado_cash/tornado_cash_deposits.sql
> +        AND tc.evt_block_time >= (select max(block_time) from {{ this }})
same two comments from above

2022-08-24 18:36 UTC, jeff-dude commented on models/tornado_cash/tornado_cash_deposits.sql
> +        AND tc.evt_block_time >= (select max(block_time) from {{ this }})
same two comments from above

2022-08-24 18:36 UTC, jeff-dude commented on models/tornado_cash/tornado_cash_deposits.sql
> +        AND tc.evt_block_time >= (select max(block_time) from {{ this }})
same two comments from above

2022-08-25 19:50 UTC, jeff-dude commented
@hildobby i'm having issues locally with dbt, but meghan helped me build and you should see objects at:
```
select count(1), min(block_time), max(block_time)
from dbt_meghan_tornado_cash.deposits
;

select count(1), min(block_time), max(block_time)
from dbt_meghan_tornado_cash.withdrawals
;
```

feel free to query those tables and ensure it looks as expected (ignore block_date column, a recent commit fixed the nulls), then ideally we can resolve some local issues and get this merged.

2022-08-29 17:36 UTC, jeff-dude approved these changes

2022-08-29 17:36 UTC, jeff-dude commented
thank you @hildobby for the patience, this PR along with another helped us find an underlying issue that seems to be resolved. this should get deployed some time this week.

2022-08-29 17:37 UTC, merged

2022-08-30 03:53 UTC, soispoke commented
folloz up on this one here: https://github.com/duneanalytics/spellbook/pull/1460