Add Optimism Tables to Dune Explorer UI
duneanalytics/spellbook pull request #1429
Opened 2022-08-25 03:44 UTC by chuxinh

Brief comments on the purpose of your changes:

Adding recently added and existing OP tables to front end explorer UI. 
Also updated the alias of `transfers_optimism_eth` to `eth`. Want it to show up as `eth` as table name instead of the following
![image](https://user-images.githubusercontent.com/30974572/186569357-23c82096-7f53-42ee-a6dd-88f8fb65bdb7.png)

Hope this won't break anything 🙏 

*For Dune Engine V2*
I've checked that:

* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

2022-08-25 19:58 UTC, jeff-dude requested changes

2022-08-25 19:58 UTC, jeff-dude commented on macros/alter_table_properties.sql
> +ALTER TABLE uniswap_v3_optimism.pools SET TBLPROPERTIES ('dune.public'='true',
from what i can tell in the dbt project file (defaults to view) and model itself (no override in config), this object is a view, not table. if that's expected, this should be updated to ALTER VIEW

2022-08-25 19:59 UTC, jeff-dude commented
changing the name to 'eth' is fine, it'll create a new view and the old one will linger. we will need to manually clean that up post-deploy

2022-08-26 03:08 UTC, chuxinh commented
Thanks @jeff-dude updated everything here.
If you can let me know how i can bring up those csv files related to OVM1 I'd like to add them here too. Or a separate PR :D

2022-08-26 17:25 UTC, jeff-dude commented
> s related to OVM1 I'd like to add them here too. Or a sepa

i think this relates to what we're talking about in TG, right? let's follow up there

2022-08-26 17:25 UTC, jeff-dude commented
> i think this relates to what we're talking about in TG, right? let's follow up there



> Thanks @jeff-dude updated everything here. If you can let me know how i can bring up those csv files related to OVM1 I'd like to add them here too. Or a separate PR :D

i think this relates to what we're talking about in TG, right? let's follow up there

2022-08-26 17:26 UTC, jeff-dude approved these changes

2022-08-26 17:34 UTC, merged