Add and Load `ovm1` data to V2
duneanalytics/spellbook pull request #1528
Opened 2022-09-08 06:41 UTC by chuxinh

Adding `ovm1` data as sql files to add to Dune V2. Some files are quite large that I got large file warnings :p 

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if adding a new model, I edited the alter table macro to display new database object (table or view) in UI explorer
* [ ] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2022-09-08 06:41 UTC, dune-eng commented
Workflow run id 3012979440 approved.

2022-09-08 07:57 UTC, soispoke requested changes
What's currently missing from this PR is a ovm1_schema.yml file that contains the tags, column descripitons, model names, etc...
Much like this file here but for all models:
https://github.com/duneanalytics/spellbook/pull/1529/files#diff-75dad4f33d458e82aa08edf723de059f6daab2855317f8ca4c9f5c864fe1c7a8

2022-09-08 10:13 UTC, dune-eng commented
Workflow run id 3014242298 approved.

2022-09-08 10:18 UTC, soispoke requested changes

2022-09-08 10:18 UTC, soispoke commented on models/ovm1/optimism/ovm1_optimism_schema.yml
> +      - &name: contract_address
- &name: contract_name

should be replaced by 

- &contract_name
        name: contract_name

in all & instances in this file

2022-09-08 11:07 UTC, dune-eng commented
Workflow run id 3014563273 approved.

2022-09-08 11:08 UTC, dune-eng commented
Workflow run id 3014572735 approved.

2022-09-12 10:29 UTC, dune-eng commented
Workflow run id 3036526283 approved.

2022-09-14 06:44 UTC, soispoke requested changes
Hi @chuxinh sorry for the late feedback (as you know we're all preparing for DuneCon), here are two errors that need fixing before I can approve this PR:
- The number of columns defined in `ovm1_optimism_contracts` doesn't match the number of values 
- There is a `nan` as an input in `ovm1_optimism_q1_user_address_daily_transactions` that isn't accepted

2022-09-14 06:45 UTC, soispoke commented
Error screenshot: 
<img width="485" alt="Capture d’écran 2022-09-14 à 08 41 40" src="https://user-images.githubusercontent.com/66172107/190080060-05ba3593-c7f3-47f3-8c7d-ce1e8dcca960.png">

2022-09-16 11:41 UTC, dune-eng commented
Workflow run id 3067570831 approved.

2022-09-16 11:58 UTC, dune-eng commented
Workflow run id 3067667301 approved.

2022-09-16 11:59 UTC, chuxinh commented
> Hi @chuxinh sorry for the late feedback (as you know we're all preparing for DuneCon), here are two errors that need fixing before I can approve this PR:
> 
> * The number of columns defined in `ovm1_optimism_contracts` doesn't match the number of values
> * There is a `nan` as an input in `ovm1_optimism_q1_user_address_daily_transactions` that isn't accepted

Thanks for checking! Should be fixed for those now

2022-09-16 12:35 UTC, soispoke approved these changes
thanks @chuxinh, lgtm

2022-09-17 07:18 UTC, merged