Add Sushiswap to dex.trades on Arrakis
duneanalytics/spellbook pull request #1539
Opened 2022-09-09 15:11 UTC by augustog

Brief comments on the purpose of your changes:
- Add support for sushiswap on dex.trades on Arrakis

Tasks:
* [ x ] Port Sushiswap model from Caladan to Arrakis
* [ x ] Integrate into dex.trades
* [ x ] Update metadata
* [ ] Write tests

*For Dune Engine V2*
I've checked that:
General checks:
* [ x ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ x ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ x ] the filename is unique and ends with .sql
* [ x ] each sql file is a select statement and has only one view, table or function defined  
* [ x ] column names are `lowercase_snake_cased`
* [ x ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ x ] if adding a new model, I edited the alter table macro to display new database object (table or view) in UI explorer
* [ x ] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [ x ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ x ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ x ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ x ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ x ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2022-09-14 12:13 UTC, dune-eng commented
Workflow run id 3052696648 approved.

2022-09-20 09:03 UTC, dune-eng commented
Workflow run id 3088806311 approved.

2022-09-20 19:30 UTC, jeff-dude requested changes

2022-09-20 19:30 UTC, jeff-dude commented on models/sushiswap/ethereum/sushiswap_ethereum_schema.yml
> +        tests:
in order for this test to run, you'll need to add sushiswap tx's to our dex trades seed file:
https://github.com/duneanalytics/spellbook/blob/main/seeds/dex/trades/dex_trades_seed.csv

there are uniswap examples in there. typically on the app UI, you can find an analytics page, maybe this one:
https://analytics.sushi.com/
which links to tx's ideally, where you can grab info and apply to seed file

2022-09-20 20:35 UTC, jeff-dude commented
there are also some dupes based on logic for unique identifiers -- may be worth a look into source data:
```
select
    unique_trade_id as unique_field,
    count(*) as n_records

from dbt_jeff_sushiswap_ethereum.trades
where unique_trade_id is not null
group by unique_trade_id
having count(*) > 1
```

2022-10-03 17:20 UTC, jeff-dude commented
@augustog are you comfortable continuing this PR? it'd be helpful to merge main into your branch, get latest changes from spellbook included, then start to look into pieces of feedback.

happy to help, if needed, just let me know 👍

2022-10-14 16:13 UTC, jeff-dude commented on models/sushiswap/ethereum/sushiswap_ethereum_schema.yml
> +        tests:
that's a tough one to find in etherscan (at least for me too). i believe it's under the ```logs``` tab -- you can use v1 engine to query that ```tx_hash```, find ```evt_index``` values and try to find on that tab in etherscan

2022-10-14 18:06 UTC, augustog commented
mistakes were made with version management (I am evidently rusty with git)
will clean up and create a new PR

2022-10-14 18:06 UTC, closed without merging