Add Foundation NFT Marketplace
duneanalytics/spellbook pull request #1543
Opened 2022-09-10 15:36 UTC by hildobby

Brief comments on the purpose of your changes:

Add Foundation to v2

*For Dune Engine V2*
I've checked that:
General checks:
* [X] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [XI used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [X] if adding a new model, I added a test
* [X] the filename is unique and ends with .sql
* [X] each sql file is a select statement and has only one view, table or function defined  
* [X] column names are `lowercase_snake_cased`
* [X] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [X] if adding a new model, I edited the alter table macro to display new database object (table or view) in UI explorer
* [X] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [X] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [X] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [X] where block_time >= date_trunc("day", now() - interval '1 week')
* [X] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [X] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2022-09-19 08:44 UTC, soispoke requested changes

2022-09-19 08:44 UTC, soispoke commented on models/foundation/ethereum/foundation_ethereum_sources.yml
> +      error_after: { count: 24, period: hour }
could you remove the `error_after` line here ? We're moving away from errors thrown because of source freshness (but keeping warnings)

2022-09-19 08:44 UTC, soispoke commented on models/foundation/ethereum/foundation_ethereum_events.sql
> +AND all_foundation_trades.block_time >= (select max(block_time) from {{ this }})
Column `all_foundation_trades.block_time` does not exist.

2022-09-20 06:53 UTC, soispoke commented
Thanks for your submission @hildobby !

2022-09-20 16:37 UTC, dot2dotseurat commented on macros/optimize_tables.sql
> +
Add end set here

2022-09-21 06:34 UTC, soispoke approved these changes

2022-09-21 06:35 UTC, soispoke commented
everything lgtm now, thanks @hildobby !

2022-09-21 06:36 UTC, merged

2022-09-21 07:29 UTC, bh2smith commented
This PRs tests are failing and causing all others based on it to fail as well.

E.g. #1587 and failing tests: https://github.com/duneanalytics/spellbook/actions/runs/3095778142/jobs/5010564050

2022-09-21 07:43 UTC, bh2smith commented on tests/foundation/ethereum/foundation_ethereum_assert_trades.sql
> +  AND f.evt_block_time < NOW() - interval '1 day' -- allow some head desync
This is the error in the test. Remove the commented date here...

PR with syntax error fix #1589