Spellbook workshop submission
duneanalytics/spellbook pull request #1558
Opened 2022-09-15 15:12 UTC by bernatfp

Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if adding a new model, I edited the alter table macro to display new database object (table or view) in UI explorer
* [ ] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2022-09-15 15:17 UTC, bernatfp commented
Don't merge, this is just demonstrative. Wanted to try it out end to end.

2022-09-15 15:30 UTC, masquot requested changes

2022-09-15 15:30 UTC, masquot commented on models/balancer/balancer_ethereum_balances.sql
> +        WHERE e.`to` = '0xBA12222222228d8Ba445958a75a0704d566BF2C8'
Here and below as well, you need a lower-case address. Simple way to convert:
https://dune.com/queries/1274287

2022-09-15 15:30 UTC, masquot commented on macros/alter_table_properties.sql
> +                                                   'dune.data_explorer.contributors'='["you"]');
update contributor field to your user name

2022-09-15 15:53 UTC, closed without merging

2022-09-26 17:35 UTC, dot2dotseurat commented
Thank you for participating in our Spellbook workshop competition! It was a close race and although your submission didn't win, there will be future opportunities to participate in Spellbook hackathons and bounties (launching soon). we hope you learned something new and had some fun. and that you will support team abstract in building an in browser IDE.