Add arbitrage trader labels for ethereal
duneanalytics/spellbook pull request #1576
Opened 2022-09-19 07:49 UTC by AlexTheLion123

Brief comments on the purpose of your changes:

Add labels for all wallets engaging in arbitrage activity on ethereal

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if adding a new model, I edited the alter table macro to display new database object (table or view) in UI explorer
* [ ] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2022-09-19 07:49 UTC, dune-eng commented
Workflow run id 3080737240 approved.

2022-09-19 07:59 UTC, soispoke requested changes
Thanks @AlexTheLion123 for your submission

2022-09-19 07:59 UTC, soispoke commented on models/labels/arb_traders/labels_arb_traders_ethereum.sql
> +  "arb trader" AS name,
I would suggest changing `arb trader` to `Arbitrage Trader` for label's name

2022-09-19 07:59 UTC, soispoke commented on models/labels/arb_traders/labels_arb_traders_schema.yml
> +        description: "Address of known arbitrage trader"
Please make sure you add a name and description for all columns

2022-09-19 07:59 UTC, soispoke commented on models/labels/arb_traders/labels_arb_traders_ethereum.sql
> +{{config(alias='arb_traders_ethereum')}}
This model needs to be moved under the models/labels/arb_trades/ethereum directory

2022-09-19 07:59 UTC, soispoke commented on macros/alter_table_properties.sql
> +ALTER VIEW labels.nft SET TBLPROPERTIES('dune.public'='true',
`ALTER VIEW labels.nft` needs to be changed into `ALTER TABLE labels.arb_traders` here

2022-09-19 10:13 UTC, dune-eng commented
Workflow run id 3081588373 approved.

2022-09-19 10:23 UTC, dune-eng commented
Workflow run id 3081643437 approved.

2022-10-03 17:26 UTC, jeff-dude commented
hi @AlexTheLion123 i've tagged this PR as ready for review. i'll revisit asap. let me know here if anything changes.

2022-10-03 18:04 UTC, AlexTheLion123 commented
hi @jeff-dude. I've been working on a much more accurate query for arbitrage traders. Will update soon. Current PR is not accurate, apologies.

2022-10-03 18:07 UTC, jeff-dude commented
no problem! good to know. i'm going to close this one, so we can start fresh :)

2022-10-03 18:07 UTC, closed without merging