create Balancer trades on Dune V2
duneanalytics/spellbook pull request #1642
Opened 2022-09-26 15:05 UTC by mendesfabio

Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)
* [ ] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2022-09-29 15:53 UTC, dune-eng commented
Workflow run id 3152758277 approved.

2022-09-29 19:26 UTC, jeff-dude commented
> should I add `balancer_trades` tables here as well? https://github.com/duneanalytics/spellbook/blob/main/macros/optimize_tables.sql

only objects materialized as tables, i.e. ```balancer_v1_ethereum.trades``` and ```balancer_v2_ethereum.trades```

2022-09-29 19:50 UTC, dune-eng commented
Workflow run id 3154161520 approved.

2022-09-29 19:50 UTC, mendesfabio commented
done, thanks @jeff-dude

2022-10-04 18:43 UTC, jeff-dude commented
@mendesfabio please merge our ```main``` into your branch again, you should see the optimize macro be deleted (it's handled in a global macro now, no need to reconfigure)

2022-10-04 20:23 UTC, jeff-dude requested changes

2022-10-04 20:23 UTC, jeff-dude commented on models/balancer/ethereum/balancer_ethereum_schema.yml
> +              dex_trades_seed: ref('dex_trades_seed')
in order for this test to run, you need to manually add rows to the seed file her for balancer (both v1 and v2):
https://github.com/duneanalytics/spellbook/blob/main/seeds/dex/trades/dex_trades_seed.csv

when i added for uniswap, i went to their app & opened their analytics page, found some tx's links to etherscan, grabbed all relevant info and added to seed file.

hopefully that's easy to do with balancer as well (for v1 and v2)

2022-10-04 20:23 UTC, jeff-dude commented
please also note this commit where i pushed some changes to help finalize:
https://github.com/duneanalytics/spellbook/pull/1642/commits/6c18bb665c6cd1755e6d1c608c83c1d679d8fbab

2022-10-28 17:32 UTC, jeff-dude commented
closing due to inactivity, please do open when ready and we'll be happy to help finalize 🙏

2022-10-28 17:32 UTC, closed without merging