fix symbol, add ibJPY and ibCHF
duneanalytics/spellbook pull request #1793
Opened 2022-10-18 06:35 UTC by mmibmm

Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2022-10-18 06:35 UTC, dune-eng commented
Workflow run id 3271108523 approved.

2022-10-18 15:00 UTC, jeff-dude requested changes
one token may be an issue. the others seem to be fine to move forward

2022-10-19 02:55 UTC, mmibmm commented on models/prices/prices_tokens.sql
> +    ("gyen-gyen", "ethereum", "ibJPY", "0x5555f75e3d5278082200fb451d1b6ba946d8e13b", 18),
@jeff-dude 
The property is_active is true and the last_data_at seems latest data. How do you think the token is inactive on coinpaprika API.

2022-10-19 08:41 UTC, dune-eng commented
Workflow run id 3280050429 approved.

2022-10-19 14:16 UTC, jeff-dude commented on models/prices/prices_tokens.sql
> +    ("gyen-gyen", "ethereum", "ibJPY", "0x5555f75e3d5278082200fb451d1b6ba946d8e13b", 18),
odd, i swear it was false yesterday when i posted 🤔 it may be good to go now, let me double check and get this merged if so

2022-10-19 14:34 UTC, jeff-dude commented
@mmibmm please fix merge conflicts & accept changes from both. prices has been edited outside of this PR, want to ensure those get merged in here.

2022-10-20 02:47 UTC, dune-eng commented
Workflow run id 3286448985 approved.

2022-10-20 02:47 UTC, dune-eng commented
Workflow run id 3286448988 approved.

2022-10-20 02:52 UTC, mmibmm commented
> @mmibmm please fix merge conflicts & accept changes from both. prices has been edited outside of this PR, want to ensure those get merged in here.

Conflict resolved.

2022-10-20 02:57 UTC, dune-eng commented
Workflow run id 3286482386 approved.

2022-10-20 02:57 UTC, dune-eng commented
Workflow run id 3286482590 approved.

2022-10-20 03:10 UTC, dune-eng commented
Workflow run id 3286525206 approved.

2022-10-20 03:10 UTC, dune-eng commented
Workflow run id 3286525205 approved.

2022-10-20 12:38 UTC, dune-eng commented
Workflow run id 3289642805 approved.

2022-10-20 12:38 UTC, dune-eng commented
Workflow run id 3289642913 approved.

2022-10-20 12:39 UTC, dune-eng commented
Workflow run id 3289650333 approved.

2022-10-20 12:39 UTC, dune-eng commented
Workflow run id 3289650335 approved.

2022-10-20 15:06 UTC, jeff-dude approved these changes

2022-10-20 15:06 UTC, merged