Dex trades Fraxswap Avalanche (C-Chain)
duneanalytics/spellbook pull request #1853
Opened 2022-10-30 04:09 UTC by zhongyiio

Brief comments on the purpose of your changes:

Fraxswap trades on Avalanche (C-Chain). Also, add FRAX and FXS tokens to prices.usd.

*For Dune Engine V2*
I've checked that:
General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

Pricing checks:
* [x] `coin_id` represents the ID of the coin on coinpaprika.com
* [x] all the coins are active on coinpaprika.com (please remove inactive ones)

Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
* [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2022-10-30 04:09 UTC, dune-eng commented
Workflow run id 3354038098 approved.

2022-10-30 04:09 UTC, dune-eng commented
Workflow run id 3354038099 approved.

2022-10-30 04:35 UTC, dune-eng commented
Workflow run id 3354102461 approved.

2022-10-30 04:35 UTC, dune-eng commented
Workflow run id 3354102462 approved.

2022-10-30 12:59 UTC, 0xBoxer requested changes
left some comments in line, please work with the decoded contract data once it is decoded.

also for some reason our 'WAVAX' price insert is broken, I'll bring this up with the team internally.

2022-10-30 13:29 UTC, zhongyiio commented on models/fraxswap/avalanche_c/fraxswap_avalanche_c_trades.sql
> +        AND l.block_time >= date_trunc("day", now() - interval '1 week')
I found some related contracts in the documentation and submitted them. I have seen this in Ethereum, but I didn't find the contract address and thought it didn't exist.

Haha, thank you for your help to submit, and I will modify it when the contract is decoded.

![image](https://user-images.githubusercontent.com/10026361/198880976-fe345da3-4e2b-4905-bfcd-1cf4153a1bc9.png)

2022-10-31 14:09 UTC, augustog commented
FYI @0xBoxer the failing test is a known issue on our side, it doesn't detect jinja variables as valid refs, we can safely ignore that error, but we should validate metadata a bit more closely.

2022-10-31 14:27 UTC, dune-eng commented
Workflow run id 3362055497 approved.

2022-10-31 14:27 UTC, dune-eng commented
Workflow run id 3362055502 approved.

2022-10-31 14:35 UTC, dune-eng commented
Workflow run id 3362116433 approved.

2022-10-31 14:35 UTC, dune-eng commented
Workflow run id 3362116466 approved.

2022-11-01 15:39 UTC, dune-eng commented
Workflow run id 3370727572 approved.

2022-11-01 15:39 UTC, dune-eng commented
Workflow run id 3370727577 approved.

2022-11-02 05:25 UTC, dune-eng commented
Workflow run id 3375040268 approved.

2022-11-02 05:25 UTC, dune-eng commented
Workflow run id 3375040254 approved.

2022-11-03 04:01 UTC, dune-eng commented
Workflow run id 3382913806 approved.

2022-11-03 04:01 UTC, dune-eng commented
Workflow run id 3382913807 approved.

2022-11-04 15:36 UTC, 0xBoxer commented
hey @jeff-dude this is ready to be merged

2022-11-04 16:01 UTC, 0xBoxer approved these changes
great stuff, thanks for implementing the changes @zhongyiio

2022-11-04 17:00 UTC, jeff-dude approved these changes

2022-11-04 17:11 UTC, jeff-dude commented
for reference, until we enhance our generic test for token bought, i like to check the query without false filter to ensure join is working as expected:
```
with
  unit_test as (
    select
      case
        when lower(m.token_bought_address) = lower(seed.token_bought_address) then True
        else False
      end as token_bought_test
    from
      test_schema.git_edae8c1d_fraxswap_avalanche_c_trades m
      inner join test_schema.git_edae8c1d_dex_trades_seed seed on m.tx_hash = seed.tx_hash
      and m.evt_index = seed.evt_index
      and m.block_date = seed.block_date
      and m.blockchain = seed.blockchain
      and m.project = seed.project
      and m.version = seed.version
  )
select
  *
from
  unit_test
```

future state of the generic test will ideally ensure the output row count from join matches the number of entries in seed file for that dex. this shows 8 results, all true, matching the count in seed file.

2022-11-04 17:12 UTC, merged