Add ens dao votes and proposals
duneanalytics/spellbook pull request #2027
Opened 2022-11-21 12:47 UTC by soispoke

Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2022-11-22 16:51 UTC, augustog requested changes
Overall looks good, I added a few inline comments (smol change requests)

Two points:
- Since this one includes most other DAOs, should we close the others and merge this one?
- Still a bit concerned about the incremental update of vote tallies... tell me if I understood this wrong:
  - Every incremental run will calculate vote tallies every time the incremental refresh runs, and that will happen only for proposals that were created since the last run
  - If we add a row for a new proposal that is still active, and new votes roll in afterwards, will it be updated?

2022-11-24 08:54 UTC, soispoke commented on models/dao/dao_proposals.sql
> +'uniswap_v3_ethereum_proposals',
Yes thanks for spotting! Done

2022-11-24 08:54 UTC, soispoke commented on models/dao/dao_votes.sql
> +'uniswap_v3_ethereum_votes',
Thanks, done as well

2022-11-24 08:54 UTC, soispoke commented on dbt_project.yml
> +    compound:
👍

2022-11-24 09:40 UTC, soispoke commented
Closing this PR and merging the AAVE one, will reopen if @augustog still has concerns around the incremental strategy

2022-11-24 09:40 UTC, closed without merging

2022-11-24 13:15 UTC, augustog commented
No need to reopen for the sake of this, but just to clarify my concern:
- I'm not worried the merge itself will not affect past records, but rather
- Whether the subset of records we filter to update may not miss new votes

Taking the example of `ens`, if the incremental refresh fitlers the entire subset to be merged on `ENSGovernor_evt_ProposalCreated.evt_block_time > (select max(created_at) from {{ this }})`, will this not mean that only new proposals land on that subset? (=> if there's an open proposal that gets new votes, we don't catch them)

If this is wrong, please ignore my comment :)