Fix LOP and Unoswap bugs
duneanalytics/spellbook pull request #2117
Opened 2022-11-25 18:26 UTC by fatayri

Brief comments on the purpose of your changes:

In the previous PR there were two bugs:

1. Unoswap trades had wrong datatypes in the pools columns
2. Maker and Taker amounts were in the wrong columns

Fixed both

2022-11-28 21:14 UTC, jeff-dude commented
@masquot are you working on this? i merged the old PR to reflect the current state of caladan, even with usd amounts amplified.

2022-11-28 21:14 UTC, jeff-dude commented
fyi @augustog on 1inch v1 engine

2022-11-30 08:48 UTC, masquot requested changes

2022-11-30 08:48 UTC, masquot commented on deprecated-dune-v1-abstractions/ethereum/dex/trades/insert_1inch.sql
> +            select "output_returnAmount", "amount", "srcToken", numeric2bytea(pools) as pools, "call_tx_hash", "call_trace_address", "call_block_time", "contract_address"
Thank you @fatayri. The code fails during runtime on ` numeric2bytea(pools)` with the following error:

> No function matches the given name and argument types. You might need to add explicit type casts.

2022-11-30 08:48 UTC, masquot commented on deprecated-dune-v1-abstractions/ethereum/dex/trades/insert_1inch.sql
> +            select "output_returnAmount", "amount", "srcToken", numeric2bytea(pools) as pools, "call_tx_hash", "call_trace_address", "call_block_time", "contract_address"
See comment above

2022-12-06 12:39 UTC, masquot commented on deprecated-dune-v1-abstractions/ethereum/dex/trades/insert_1inch.sql
> +            select "output_returnAmount", "amount", "srcToken", numeric2bytea(pools) as pools, "call_tx_hash", "call_trace_address", "call_block_time", "contract_address"
See also https://dune.com/queries/1714974:

> Error: Function numeric2bytea(numeric[]) does not exist at line 5, position 3.

2022-12-06 14:04 UTC, bh2smith commented
Tagging @fleupold who is also interested in the progress of this.

2022-12-06 14:07 UTC, bh2smith commented
Note also that this PR closes https://github.com/duneanalytics/spellbook/issues/2197

2022-12-08 08:59 UTC, gentrexha commented
Hey everyone, do you guys have an estimate when this will be fixed?

2022-12-12 17:11 UTC, fatayri commented
Just pushed a fix, sorry for the delay 

@gentrexha @bh2smith

2022-12-12 23:05 UTC, bh2smith commented
Now we just gotta get it merged before v1 is over! Wen V2?

2022-12-13 23:06 UTC, jacubcub commented
@masquot can this be merged now?

2022-12-14 15:49 UTC, jeff-dude commented
@dot2dotseurat fyi on v1 PR

2022-12-14 18:44 UTC, dot2dotseurat commented
Hi, sorry for the inconvenience but all abstractions in the deprecated-dune-v1-abstractions have been migrated to https://github.com/duneanalytics/dune-v1-abstractions. 

Can these changes be re-opened as a PR there?

2022-12-14 20:34 UTC, jacubcub commented
I made a PR in the new repo https://github.com/duneanalytics/dune-v1-abstractions/pull/2

2022-12-14 22:39 UTC, jeff-dude commented
closing due to new repo link above

2022-12-14 22:39 UTC, closed without merging