Add Cow protocol price improvement data
duneanalytics/spellbook pull request #2501
Opened 2023-01-17 18:16 UTC by josojo

Replaces: https://github.com/duneanalytics/spellbook/pull/2478. Most of the work was done by @gentrexha !

**For Dune Engine V2**
The results generated by this query are very similar to the ones of the old v1 version:
Histogram slippage
v1: https://dune.com/queries/1039434/1792834
v2: https://dune.com/queries/1901957
Sum daily slippage:
v1: https://dune.com/queries/1035637/1786462
v2: https://dune.com/queries/1902617
I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory) See here: https://dune.com/queries/1902930?d=1
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [x] `coin_id` represents the ID of the coin on coinpaprika.com
* [x] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2023-01-17 18:16 UTC, dune-eng commented
Workflow run id 3942102618 approved.

2023-01-17 18:16 UTC, dune-eng commented
Workflow run id 3942102619 approved.

2023-01-17 18:20 UTC, dune-eng commented
Workflow run id 3942132421 approved.

2023-01-17 18:20 UTC, dune-eng commented
Workflow run id 3942132414 approved.

2023-01-21 07:44 UTC, bh2smith approved these changes
Looks good but missing block number which should be included. 

I think there are a bunch of unnecessary columns in this table that can easily be acquired with a join on trades.  Specifically I would suggest removing prices, trade value, token decimals amounts and atoms bought/sold. Thus table should contain information on top of what is already in the trades table.

2023-01-21 07:44 UTC, bh2smith commented on models/cow_protocol/ethereum/cow_protocol_ethereum_price_improvement.sql
> +        post_hook='{{ expose_spells_hide_trino(\'["ethereum"]\',
Do you explicitly want to make this unavailable in duneSQL?

2023-01-21 07:44 UTC, bh2smith commented on models/cow_protocol/ethereum/cow_protocol_ethereum_schema.yml
> +        name: buy_decimals
I really don't think decimals are necessary to keep around here.

2023-01-21 07:44 UTC, bh2smith commented on models/cow_protocol/ethereum/cow_protocol_ethereum_schema.yml
> +      - *units_bought
These are already part of the trades table. Why keep them here?

2023-01-21 07:44 UTC, bh2smith commented on models/cow_protocol/ethereum/cow_protocol_ethereum_schema.yml
> +    columns:
Missing block number! Please include.

2023-01-21 07:45 UTC, bh2smith requested changes
Add block number

2023-02-03 09:42 UTC, bh2smith commented
How is this coming along @josojo?

2023-02-03 13:35 UTC, dune-eng commented
Workflow run id 4084652572 approved.

2023-02-03 13:35 UTC, dune-eng commented
Workflow run id 4084652568 approved.

2023-02-03 13:40 UTC, bh2smith commented on models/cow_protocol/ethereum/cow_protocol_ethereum_schema.yml
> +      is called price improvement and is measured as percentage or in absolte dollars.
```suggestion
      is called price improvement and is measured as percentage or in absolute dollars.
```

2023-02-03 13:40 UTC, bh2smith commented on models/cow_protocol/ethereum/cow_protocol_ethereum_price_improvement.sql
> +select * from results
```suggestion
select * from results

```

2023-02-03 13:40 UTC, bh2smith approved these changes
Looks pretty good to me! I would say its ready for merge!

2023-02-03 13:41 UTC, dune-eng commented
Workflow run id 4084696252 approved.

2023-02-03 13:41 UTC, dune-eng commented
Workflow run id 4084696238 approved.

2023-02-03 13:41 UTC, dune-eng commented
Workflow run id 4084697148 approved.

2023-02-03 13:41 UTC, dune-eng commented
Workflow run id 4084697149 approved.

2023-02-03 14:35 UTC, dune-eng commented
Workflow run id 4085127734 approved.

2023-02-03 14:36 UTC, dune-eng commented
Workflow run id 4085127757 approved.

2023-02-07 15:49 UTC, soispoke approved these changes
lgtm!

2023-02-07 15:50 UTC, merged