Add Compound v2 lending supply and borrow
duneanalytics/spellbook pull request #2503
Opened 2023-01-17 22:45 UTC by bizzyvinci

Brief comments on the purpose of your changes:
Adding compound v2 supply and borrow
* cTokens: [query](https://dune.com/queries/1903614)
* Supply: [query](https://dune.com/queries/1903672)
    - [x] Mints (or deposit)
    - [ ] redeem
    - [ ] liquidation
* Borrow
    - [ ] borrow
    - [ ] repay
    - [ ] liquidation

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2023-01-17 22:45 UTC, dune-eng commented
Workflow run id 3943935420 approved.

2023-01-17 22:45 UTC, dune-eng commented
Workflow run id 3943935418 approved.

2023-01-18 21:53 UTC, dune-eng commented
Workflow run id 3953231262 approved.

2023-01-18 21:53 UTC, dune-eng commented
Workflow run id 3953231273 approved.

2023-01-18 21:56 UTC, dune-eng commented
Workflow run id 3953245234 approved.

2023-01-18 21:56 UTC, dune-eng commented
Workflow run id 3953245233 approved.

2023-01-19 23:24 UTC, dune-eng commented
Workflow run id 3963250522 approved.

2023-01-19 23:24 UTC, dune-eng commented
Workflow run id 3963250524 approved.

2023-01-19 23:46 UTC, bizzyvinci commented
What's the purpose of adding liquidations to lending supply.

There are 2 scenarios in AAVE based on the [receiveAToken parameter](https://github.com/aave/protocol-v2/blob/master/contracts/protocol/lendingpool/LendingPool.sol#L422) in liquidateCall.

1. There's a withdrawal and hence less supply in the pool when `receiveAToken = False`
2. There's constant supply--if there's no fee--in the pool when `receiveAToken = True`, but the owner of the position changes from the borrower to the liquidator

There's no if statement to separate the 2 scenarios in [AAVE model](https://github.com/duneanalytics/spellbook/blob/main/models/aave/ethereum/aave_v2_ethereum_supply.sql#L66)

Now, back to compound. All liquidations are scenario 2 in which positions of collateral--cTokens--are transferred from the borrower to the liquidator. And adding liquidation to supply is complicated for 2 reasons
1. underlying asset amount is not provided in call and events
2. Not all cToken is transferred to liquidator as some goes into reserve.

For reference, [this section](https://github.com/compound-finance/compound-protocol/blob/master/contracts/CToken.sol#L793-L840) is where the collateral transfer occurs.

2023-01-24 12:07 UTC, Hosuke requested changes
Hi @bizzyvinci 

We may need to fix the test first.
[v2 test sql query](https://dune.com/queries/1922843?d=1)
[dbt test info](https://github.com/duneanalytics/spellbook/actions/runs/3995917855/jobs/6855347144#step:10:21)

2023-01-24 12:07 UTC, Hosuke commented on tests/compound/ethereum/compound_v2_borrow_test.sql
> +where test = false
We can use `union all` for the detailed info.
```suggestion
select * from (
    select 'test1' as test_no, * from unit_test1
    union all
    select 'test2' as test_no, * from unit_test2
    union all
    select 'test3' as test_no, * from unit_test3
    union all
    select 'test4' as test_no, * from unit_test4
)
where test = false
```

2023-01-24 20:20 UTC, dune-eng commented
Workflow run id 4000087158 approved.

2023-01-24 20:20 UTC, dune-eng commented
Workflow run id 4000087155 approved.

2023-01-24 20:39 UTC, bizzyvinci commented
@Hosuke, done

2023-01-25 14:39 UTC, Hosuke commented
In the next few commits, I will try to further update the sql to incremental views.

2023-01-25 15:45 UTC, Hosuke requested changes
Hi @bizzyvinci, I try to define the unique key combination for borrow and supply model, as incremental merge based on the unique key. However I may get the unique key combination wrong.

Can you help me to define the unique key combination for these views?

Thanks.

2023-01-25 15:45 UTC, Hosuke commented on models/compound/ethereum/compound_ethereum_schema.yml
> +            - repayer
Can you help me to define the `unique key` combination for `compound_v2_ethereum_borrow`?

2023-01-25 15:45 UTC, Hosuke commented on models/compound/ethereum/compound_ethereum_schema.yml
> +            - withdrawn_to
Also can you help me to define the `unique key` combination for `compound_v2_ethereum_supply`?
We can add uniqueness tests in the schema file.

2023-01-25 18:08 UTC, dune-eng commented
Workflow run id 4008700138 approved.

2023-01-25 18:08 UTC, dune-eng commented
Workflow run id 4008700134 approved.

2023-01-25 18:27 UTC, bizzyvinci commented
@Hosuke, done.

There is another set of wizards, they don't write SQL queries, they send transactions to the blockchain. Running the following would show [this transaction](https://etherscan.io/tx/0x9fdf7b3c0846629f0d469cb86af117a97f73c63d4ad3caf46b119a06e7159a89) in which the same address borrowed the same token 12 times 🤯

```sql
select evt_tx_hash, borrower, contract_address, count(*)
from compound_v2_ethereum.cErc20_evt_Borrow
group by 1, 2, 3
order by 4 desc
limit 100
```

Using block_number and evt_index is always a safe unique key when they are available. You can add back the other keys if they'll help queries to run faster like indexing.

2023-01-27 03:26 UTC, Hosuke approved these changes
LGTM.✅
Thank you @bizzyvinci

This PR adds one static table [`compound_v2_ethereum_ctokens`](https://github.com/duneanalytics/spellbook/pull/2503/files#diff-c7980b9ff32186dbd31ed104741bb221e97bf790d32fc490f36bf0b474a3acba), and two incremental views [[`compound_v2_ethereum_borrow.sql`](https://github.com/duneanalytics/spellbook/pull/2503/files#diff-505900ad0ee6e5931995e50a8f9b32910a0cf1b3d50121830825c3b5ae2af32e), [`compound_v2_ethereum_supply`](https://github.com/duneanalytics/spellbook/pull/2503/files#diff-adf4666fb8c26afafe82fb36c4dcffe4e5cad3cd4aa6d127e2da2e957153e042)]

I have reviewed the PR and here is the summary:
- Metadata & naming conventions look good ✅
- Config blocks match uniqueness tests in schema files ✅
- Tests added for the new models ✅
- Incremental filters added when joining large tables ✅
- Contract addresses are lowercased ✅

2023-01-27 18:18 UTC, jeff-dude commented
CI failing due to irrevelant test from another merged PR. will try again shortly.

2023-01-27 20:56 UTC, jeff-dude approved these changes

2023-01-27 20:56 UTC, merged