Add AXL to prices_tokens.sql
duneanalytics/spellbook pull request #2543
Opened 2023-01-24 00:44 UTC by fahimahmedx

Brief comments on the purpose of your changes:
These tokens are the lowercase contract addresses taken from: https://docs.axelar.dev/resources/mainnet#assets
The addresses exist on etherscan its variants for other chains.
A concern is that AXL is not active on coinpaprika. Could the address still be added, and if not how would AXL be set to active on coinpaprika?

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2023-01-24 00:45 UTC, dune-eng commented
Workflow run id 3991912067 approved.

2023-01-24 00:45 UTC, dune-eng commented
Workflow run id 3991912070 approved.

2023-01-24 00:45 UTC, dune-eng commented
Workflow run id 3991912065 approved.

2023-01-24 13:20 UTC, Hosuke requested changes
Hi @fahimahmedx , sorry we could not add `axl-axelar` as this token-id is not available in coinpaprika api.

( Moreover `AXL` may have token-id `axl-axelar-network` but it is not active as well. 
API: https://api.coinpaprika.com/v1/coins/axl-axelar-network )

Please fix the usdc and usdt token-id as well.
axlUSDC API: https://api.coinpaprika.com/v1/coins/axlusdc-axelar-usd-coin
axlUSDT API: https://api.coinpaprika.com/v1/coins/axlusdt-axelar-usd-tether
axlATOM API: https://api.coinpaprika.com/v1/coins/axlatom-axelar-wrapped-atom

2023-01-24 13:20 UTC, Hosuke commented on models/prices/prices_tokens.sql
> +    ("axlatom-axelar-wrapped-atom","arbitrum","axlATOM","0x06bee9e7238a331b68d83df3b5b9b16d5dba83ff",6),
```suggestion
    ("axlusdc-axelar-usd-coin","arbitrum","axlUSDC","0xeb466342c4d449bc9f53a865d5cb90586f405215",6),
    ("axlusdt-axelar-usd-tether","arbitrum","axlUSDT","0x7f5373ae26c3e8ffc4c77b7255df7ec1a9af52a6",6),
    ("axlatom-axelar-wrapped-atom","arbitrum","axlATOM","0x06bee9e7238a331b68d83df3b5b9b16d5dba83ff",6),
```

2023-01-24 22:13 UTC, dune-eng commented
Workflow run id 4000865929 approved.

2023-01-24 22:13 UTC, dune-eng commented
Workflow run id 4000865935 approved.

2023-01-24 22:13 UTC, dune-eng commented
Workflow run id 4000865936 approved.

2023-01-24 22:13 UTC, dune-eng commented
Workflow run id 4000867111 approved.

2023-01-24 22:13 UTC, dune-eng commented
Workflow run id 4000867113 approved.

2023-01-24 22:13 UTC, dune-eng commented
Workflow run id 4000867122 approved.

2023-01-25 14:32 UTC, Hosuke approved these changes
LGTM.✅
- `token_id` matches coinpaprika id ✅
- `is_active: true` ✅
- contract addresses are lowercase and correct ✅

Thank you @fahimahmedx

2023-01-25 14:32 UTC, Hosuke commented on models/prices/prices_tokens.sql
> +    ("axlatom-axelar-wrapped-atom","arbitrum","axlATOM","0x06bee9e7238a331b68d83df3b5b9b16d5dba83ff",6),
Contract confirmation:
axlUSDC: https://arbiscan.io/token/0xeb466342c4d449bc9f53a865d5cb90586f405215
axlUSDT: https://arbiscan.io/token/0x7f5373ae26c3e8ffc4c77b7255df7ec1a9af52a6
axlATOM: https://arbiscan.io/token/0x06bee9e7238a331b68d83df3b5b9b16d5dba83ff

2023-01-25 14:32 UTC, Hosuke commented on models/prices/prices_tokens.sql
> +    ("axlatom-axelar-wrapped-atom", "avalanche_c", "axlATOM", "0x80d18b1c9ab0c9b5d6a6d5173575417457d00a12", 6),
Contract confirmation:
axlUSDC: https://snowtrace.io/token/0xfab550568c688d5d8a52c7d794cb93edc26ec0ec
axlUSDT: https://snowtrace.io/token/0xf976ba91b6bb3468c91e4f02e68b37bc64a57e66
axlATOM: https://snowtrace.io/token/0x80d18b1c9ab0c9b5d6a6d5173575417457d00a12

2023-01-25 14:32 UTC, Hosuke commented on models/prices/prices_tokens.sql
> +    ("axlusdc-axelar-usd-coin", "bnb", "axlUSDC", "0x4268b8f0b87b6eae5d897996e6b845ddbd99adf3", 6),
Contract confirmation:
axlUSDC: https://bscscan.com/token/0x4268b8f0b87b6eae5d897996e6b845ddbd99adf3

2023-01-25 14:32 UTC, Hosuke commented on models/prices/prices_tokens.sql
> +    ("axlatom-axelar-wrapped-atom", "ethereum", "axlATOM", "0x27292cf0016e5df1d8b37306b2a98588acbd6fca", 6),
Contract confirmation:
axlATOM: https://etherscan.io/token/0x27292cf0016e5df1d8b37306b2a98588acbd6fca

2023-01-25 14:32 UTC, Hosuke commented on models/prices/prices_tokens.sql
> +    ("axlatom-axelar-wrapped-atom", "polygon", "axlATOM", "0x33f8a5029264bcfb66e39157af3fea3e2a8a5067", 6),
Contract confirmation:
axlUSDC: https://polygonscan.com/token/0x750e4c4984a9e0f12978ea6742bc1c5d248f40ed
axlUSDT: https://polygonscan.com/token/0xceed2671d8634e3ee65000edbbee66139b132fbf
axlATOM: https://polygonscan.com/token/0x33f8a5029264bcfb66e39157af3fea3e2a8a5067

2023-01-25 14:32 UTC, Hosuke commented on models/prices/prices_tokens.sql
> +    ("axlatom-axelar-wrapped-atom", "fantom", "axlATOM", "0x3bb68cb55fc9c22511467c18e42d14e8c959c4da", 6),
Contract confirmation:
axlUSDC: https://ftmscan.com/token/0x1b6382dbdea11d97f24495c9a90b7c88469134a4
axlUSDT: https://ftmscan.com/token/0xd226392c23fb3476274ed6759d4a478db3197d82
axlATOM: https://ftmscan.com/token/0x3bb68cb55fc9c22511467c18e42d14e8c959c4da

2023-01-25 15:56 UTC, dot2dotseurat approved these changes

2023-01-30 17:53 UTC, merged