Add Liquidifty to nft trades
duneanalytics/spellbook pull request #2544
Opened 2023-01-24 01:16 UTC by bizzyvinci

Brief comments on the purpose of your changes:
Add liquidity to nft trades. Model queries are [bnb](https://dune.com/queries/1918105), [eth](https://dune.com/queries/1921406) and [all](https://dune.com/queries/1921415)

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2023-01-24 01:16 UTC, dune-eng commented
Workflow run id 3992086248 approved.

2023-01-24 01:16 UTC, dune-eng commented
Workflow run id 3992086290 approved.

2023-01-24 01:21 UTC, dune-eng commented
Workflow run id 3992112954 approved.

2023-01-24 01:21 UTC, dune-eng commented
Workflow run id 3992112955 approved.

2023-01-26 00:12 UTC, dune-eng commented
Workflow run id 4011071167 approved.

2023-01-26 00:29 UTC, dune-eng commented
Workflow run id 4011168884 approved.

2023-01-26 00:29 UTC, dune-eng commented
Workflow run id 4011168880 approved.

2023-01-31 23:01 UTC, bizzyvinci commented
LGTM @0xRobin

2023-02-07 10:16 UTC, 0xRobin requested changes
Thanks for the PR!
I left some comments on the v3 code, it would be great if you could try to also use the `Buy` event there. Do you think that's possible?

Another thing is we'd like to see is a seed file with some example trades for each model.
You can see an example here:
https://github.com/duneanalytics/spellbook/blob/main/seeds/nftrade/bnb/nftrade_nft_trades_samples.csv
And this is how that seed test is configured:
https://github.com/duneanalytics/spellbook/blob/14fc92d7ce110f73286ebc5f383ef64dcde7f802/models/nftrade/bnb/nftrade_bnb_schema.yml#L19-L28

Let me know if that makes sense, ideally we have a seed for each chain which has trade examples from all the different marketplace versions. 

--

Another comment is that currently you have made a `trades` table which does not include any fee information. Is there info on marketplace fees or royalty fees from liquidifty that we could get from the calls/events? Ideally we make an `events` table which does include that information.

2023-02-07 10:16 UTC, 0xRobin commented on models/liquidifty/bnb/liquidifty_bnb_trades.sql
> +        cast(null as varchar(5)) as buyer,
We can get the buyer from the `Buy` event in v3

2023-02-07 10:16 UTC, 0xRobin commented on models/liquidifty/bnb/liquidifty_bnb_trades.sql
> +        get_json_object(order, '$.signer') as seller,
This might not always hold when the order is a buy order? (offer accepted)
We can get the seller from the `Buy` event.

2023-02-07 10:16 UTC, 0xRobin commented on models/liquidifty/bnb/liquidifty_bnb_trades.sql
> +        concat(cast(call_block_number as varchar(5)), '-', call_tx_hash, cast(array_join(call_trace_address, ',') as varchar(5))) as unique_trade_id,
if we pull in the `Buy` event, we can use that event index here instead of the trace address of the call.

2023-02-07 10:16 UTC, 0xRobin commented on models/liquidifty/bnb/liquidifty_bnb_trades.sql
> +            )
Can we join this info with the `Buy` event, should be possible to match them with the provided `orderHashes`?

2023-02-07 10:16 UTC, 0xRobin commented on models/liquidifty/ethereum/liquidifty_ethereum_trades.sql
> +        cast(null as varchar(5)) as buyer,
same comment as bnb model

2023-02-07 10:16 UTC, 0xRobin commented on models/liquidifty/ethereum/liquidifty_ethereum_trades.sql
> +        concat(cast(call_block_number as varchar(5)), '-', call_tx_hash, cast(array_join(call_trace_address, ',') as varchar(5))) as unique_trade_id,
same comment as bnb model

2023-02-07 10:16 UTC, 0xRobin commented on models/liquidifty/ethereum/liquidifty_ethereum_trades.sql
> +            )
same comment as bnb model

2023-02-08 19:31 UTC, bizzyvinci commented
Should I remove the present test when adding seed?
And in what ways are seed better or prefered?

2023-02-08 19:34 UTC, 0xRobin commented
@bizzyvinci thanks for the thorough explanation and context, with that info I'm satisfied with the current setup using the buy call for v3. :+1: 

Concerning the tests, seeds are preferred when comparing the model to manually selected examples.
They are more easily checked and verified and provide some consistency across the repo. 
You can indeed discard the current test if you implement seed tests.

2023-02-08 19:40 UTC, bizzyvinci commented
Ok.
Seed incoming.

2023-02-08 20:21 UTC, dune-eng commented
Workflow run id 4128082893 approved.

2023-02-08 20:21 UTC, dune-eng commented
Workflow run id 4128082899 approved.

2023-02-08 20:32 UTC, bizzyvinci commented
I need help @0xRobin cause `tokens_ethereum_erc20` schema does exist.

2023-02-14 17:38 UTC, 0xRobin approved these changes
@bizzyvinci I pushed some commits to materialize the models and make them incremental.
(which was a bit of a struggle as you can see)

:heavy_check_mark: Tests are passing and data looks good, this is ready to be merged.
Thanks for the contribution!

2023-02-17 15:25 UTC, merged