Add impossible IDO pools
duneanalytics/spellbook pull request #2646
Opened 2023-02-08 07:41 UTC by 0xKARTOD

Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2023-02-08 07:42 UTC, dune-eng commented
Workflow run id 4121869073 approved.

2023-02-08 07:42 UTC, dune-eng commented
Workflow run id 4121869075 approved.

2023-02-08 12:32 UTC, dune-eng commented
Workflow run id 4124123901 approved.

2023-02-08 12:32 UTC, dune-eng commented
Workflow run id 4124123913 approved.

2023-02-20 08:28 UTC, Hosuke approved these changes
LGTM.✅
Thank you @0xKARTOD 

This PR adds a static view of `impossible_finance_IDO_pools` on bnb chain.

(Also please have a look to this PR https://github.com/duneanalytics/spellbook/pull/2593 if you have time)

2023-02-23 16:30 UTC, jeff-dude requested changes
thank you @0xKARTOD for the PR. please see below proposed changes prior to merge

2023-02-23 16:30 UTC, jeff-dude commented on dbt_project.yml
> +      +schema: impossible_finance
please add subdirectory for bnb here, as that is where model lives & add schema for `impossible_finance_bnb`

2023-02-23 16:30 UTC, jeff-dude commented on models/impossible_finance/bnb/impossible_finance_IDO_pools.sql
> +        alias='IDO_pools',
please use lowercase on `IDO` for consistency across spellbook. this also applies to the file name itself.

2023-02-23 16:30 UTC, jeff-dude commented on models/impossible_finance/bnb/impossible_finance_IDO_pools.sql
> +       lower(address) AS pool_address,
to be safe, something i've tried to push for new static models, can we add `trim()` function here too?

2023-02-23 16:30 UTC, jeff-dude commented on models/impossible_finance/bnb/impossible_finance_IDO_pools.sql
> +       lower(address) AS pool_address,
`trim()` could be used on most string columns

2023-02-23 16:30 UTC, jeff-dude commented on models/impossible_finance/bnb/impossible_finance_IDO_pools.sql
> +    (array('bnb'),'0x69b9737aff26bc528ffee4cc3257407be6a13252', 'Openswap', 'Openswap', 'Standard Sale', 1, timestamp('2021-08-30'), timestamp('2021-08-26'), timestamp('2021-08-26')),
we've moved away from forcing `array()` usage on `blockchain` column -- please do remove

2023-02-23 16:30 UTC, jeff-dude commented on models/impossible_finance/bnb/impossible_finance_bnb_schema.yml
> +  - name: impossible_finance_IDO_pools
lowercase

2023-02-23 16:30 UTC, jeff-dude commented on models/impossible_finance/bnb/impossible_finance_bnb_schema.yml
> +      - &pool_address
can we apply a unique test on just address?
if not only address, then use `unique_combo_of_columns` test

2023-02-24 15:17 UTC, jeff-dude requested changes
i've fixed the test to run & now there appears to be duplicates. please determine if address alone is valid for unique or there is truly a duplicate.

2023-02-24 15:21 UTC, Hosuke commented on models/impossible_finance/bnb/impossible_finance_bnb_ido_pools.sql
> +    ('bnb','0x98fF066BB5041DF3e8299Ce2eAf44d5a9E4f32E4', 'IDIA', 'IDIA', 'SDO Standard Sale', 9, timestamp('2022-01-10'), timestamp('2021-12-23'), timestamp('2022-02-19')),
@0xKARTOD Line #58 and Line #64 are having the same address. Please check.

2023-03-19 08:04 UTC, jeff-dude commented
closing due to inactivity

2023-03-19 08:04 UTC, closed without merging