Magiceden polygon nft trades
duneanalytics/spellbook pull request #2849
Opened 2023-02-28 13:21 UTC by springzh

Brief comments on the purpose of your changes:

This is for Magic Eden marketplace on Polygon.

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2023-02-28 13:21 UTC, dune-eng commented
Workflow run id 4293411247 approved.

2023-02-28 13:21 UTC, dune-eng commented
Workflow run id 4293411246 approved.

2023-03-01 06:41 UTC, dune-eng commented
Workflow run id 4300802032 approved.

2023-03-01 06:41 UTC, dune-eng commented
Workflow run id 4300802034 approved.

2023-03-01 09:24 UTC, dune-eng commented
Workflow run id 4301984486 approved.

2023-03-01 09:24 UTC, dune-eng commented
Workflow run id 4301984492 approved.

2023-03-01 09:32 UTC, dune-eng commented
Workflow run id 4302057722 approved.

2023-03-01 09:32 UTC, dune-eng commented
Workflow run id 4302057724 approved.

2023-03-03 17:03 UTC, 0xRobin requested changes
Hi sir,
Mostly the same comments is in the other PRs.
- remove mints model
- add uniqueness tests
- improve prices/tokens sources setup

Overall really great additions to the polygon dataset if we can tackle the open concerns and maybe also add in some seed tests later to validate data correctness of some crucial columns with some sample transactions. 

And sorry if any of my comment/remarks are a bit short/bold, just trying to push these reviews through before the weekend so you can move forward with them! :)

2023-03-06 09:12 UTC, dune-eng commented
Workflow run id 4341735292 approved.

2023-03-06 09:12 UTC, dune-eng commented
Workflow run id 4341735275 approved.

2023-03-08 12:22 UTC, 0xBoxer commented
Hey @springzh, thanks for tackling these!

I think we should be able to include the royalty payments into the magic eden model.

https://polygonscan.com/tx/0xc55e0fee57f076d1944f1e9d22932c9e89e37debaee70572c56c86aca969c1af

The order of: 
- first token transfer -> payment
- second token transfer -> marketplace fee
- third token transfer -> royalty payment is consistent between all trades

Please incorporate royalty and marketplace fees into this PR

2023-03-09 04:30 UTC, dune-eng commented
Workflow run id 4371099775 approved.

2023-03-09 04:30 UTC, dune-eng commented
Workflow run id 4371099778 approved.

2023-03-09 04:30 UTC, springzh commented on models/magiceden/polygon/magiceden_polygon_events.sql
> +        AND contract_address IN ( SELECT DISTINCT currency_contract FROM all_events)
Updated.

2023-03-09 04:30 UTC, springzh commented on models/magiceden/polygon/magiceden_polygon_events.sql
> +  CASE WHEN p.symbol = 'WMATIC' THEN 'MATIC' ELSE p.symbol END AS currency_symbol,
Updated.

2023-03-09 04:30 UTC, springzh commented on models/magiceden/polygon/magiceden_polygon_events.sql
> +  p.contract_address AS currency_contract,
Updated.

2023-03-09 04:30 UTC, springzh commented on models/magiceden/polygon/magiceden_polygon_fees.sql
> +CAST(number_of_items AS DECIMAL(38,0)) AS number_of_items,
Updated.

2023-03-09 04:30 UTC, springzh commented on models/magiceden/polygon/magiceden_polygon_mints.sql
> +;
Updated.

2023-03-09 04:31 UTC, springzh commented on models/magiceden/polygon/magiceden_polygon_schema.yml
> +    columns:
Added to unique_trade_id field.

2023-03-09 04:32 UTC, springzh commented
> Hey @springzh, thanks for tackling these!
> 
> I think we should be able to include the royalty payments into the magic eden model.
> 
> https://polygonscan.com/tx/0xc55e0fee57f076d1944f1e9d22932c9e89e37debaee70572c56c86aca969c1af
> 
> The order of:
> 
> * first token transfer -> payment
> * second token transfer -> marketplace fee
> * third token transfer -> royalty payment is consistent between all trades
> 
> Please incorporate royalty and marketplace fees into this PR

I've refactored it to get raw amount from evt_Transfer for erc20 payment and from traces for native token payment.

2023-03-09 04:42 UTC, dune-eng commented
Workflow run id 4371157486 approved.

2023-03-09 04:42 UTC, dune-eng commented
Workflow run id 4371157483 approved.

2023-03-17 16:49 UTC, 0xRobin approved these changes
:heavy_check_mark: lgtm!

2023-03-20 17:31 UTC, jeff-dude approved these changes

2023-03-20 17:46 UTC, merged