Fixnolimits
duneanalytics/spellbook pull request #2932
Opened 2023-03-09 18:45 UTC by RantumBits

Brief comments on the purpose of your changes: update fee recipient address on each chain 

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2023-03-09 18:51 UTC, dune-eng commented
Workflow run id 4377779306 approved.

2023-03-09 18:51 UTC, dune-eng commented
Workflow run id 4377779300 approved.

2023-03-09 20:16 UTC, dune-eng commented
Workflow run id 4378410948 approved.

2023-03-09 20:16 UTC, dune-eng commented
Workflow run id 4378410946 approved.

2023-03-09 20:17 UTC, dune-eng commented
Workflow run id 4378420522 approved.

2023-03-09 20:21 UTC, dune-eng commented
Workflow run id 4378450191 approved.

2023-03-09 20:21 UTC, dune-eng commented
Workflow run id 4378450185 approved.

2023-03-09 20:31 UTC, dune-eng commented
Workflow run id 4378524244 approved.

2023-03-09 20:31 UTC, dune-eng commented
Workflow run id 4378524241 approved.

2023-03-09 20:39 UTC, dune-eng commented
Workflow run id 4378588462 approved.

2023-03-09 20:39 UTC, dune-eng commented
Workflow run id 4378588457 approved.

2023-03-09 21:26 UTC, dune-eng commented
Workflow run id 4378921359 approved.

2023-03-09 21:26 UTC, dune-eng commented
Workflow run id 4378921354 approved.

2023-03-09 21:35 UTC, dune-eng commented
Workflow run id 4378985829 approved.

2023-03-09 21:35 UTC, dune-eng commented
Workflow run id 4378985832 approved.

2023-03-09 21:42 UTC, dune-eng commented
Workflow run id 4379028578 approved.

2023-03-09 21:42 UTC, dune-eng commented
Workflow run id 4379028580 approved.

2023-03-09 21:55 UTC, dune-eng commented
Workflow run id 4379115592 approved.

2023-03-09 21:55 UTC, dune-eng commented
Workflow run id 4379115595 approved.

2023-03-09 22:02 UTC, dune-eng commented
Workflow run id 4379158898 approved.

2023-03-09 22:02 UTC, dune-eng commented
Workflow run id 4379158890 approved.

2023-03-09 22:12 UTC, dune-eng commented
Workflow run id 4379237055 approved.

2023-03-09 22:12 UTC, dune-eng commented
Workflow run id 4379237057 approved.

2023-03-10 19:41 UTC, dune-eng commented
Workflow run id 4387885340 approved.

2023-03-10 19:41 UTC, dune-eng commented
Workflow run id 4387885318 approved.

2023-03-10 20:47 UTC, RantumBits commented
this is a small update to addresses in api_fills models @jeff-dude

2023-03-10 20:48 UTC, dune-eng commented
Workflow run id 4388324839 approved.

2023-03-10 20:48 UTC, dune-eng commented
Workflow run id 4388324836 approved.

2023-03-13 16:15 UTC, dune-eng commented
Workflow run id 4407116758 approved.

2023-03-13 16:15 UTC, dune-eng commented
Workflow run id 4407116759 approved.

2023-03-14 23:12 UTC, dune-eng commented
Workflow run id 4421040332 approved.

2023-03-14 23:12 UTC, dune-eng commented
Workflow run id 4421040331 approved.

2023-03-14 23:20 UTC, dune-eng commented
Workflow run id 4421095322 approved.

2023-03-14 23:20 UTC, dune-eng commented
Workflow run id 4421095317 approved.

2023-03-15 03:24 UTC, Hosuke approved these changes
LGTM.✅
Thank you @RantumBits 
Also remember to update the schema when you update the model selection columns.

2023-03-16 15:56 UTC, dune-eng commented
Workflow run id 4439049848 approved.

2023-03-20 15:55 UTC, dune-eng commented
Workflow run id 4470217400 approved.

2023-03-20 15:58 UTC, jeff-dude requested changes

2023-03-21 17:15 UTC, dune-eng commented
Workflow run id 4481920131 approved.

2023-03-21 17:15 UTC, dune-eng commented
Workflow run id 4481920141 approved.

2023-03-21 17:46 UTC, RantumBits commented on models/zeroex/arbitrum/zeroex_arbitrum_api_fills.sql
> +            (fills.feeRecipient in
this PR updates addresses and adds a contract_address field, which will be used in https://github.com/duneanalytics/spellbook/pull/2958

Address updates should not have been included in the other PR. I will revise that PR

2023-03-21 20:59 UTC, jeff-dude approved these changes

2023-03-21 20:59 UTC, merged