Create Aragon dao addresses Models - Ready for review
duneanalytics/spellbook pull request #3006
Opened 2023-03-22 10:49 UTC by henrystats

This pr creates a new Aragon model for dao addresses, I'll be separating out all the dao_creator_tools so they're under individual project files. 

Starting with Aragon as the Aragon team wants to add a new column to the addresses_model for Aragon.

2023-03-22 10:50 UTC, dune-eng commented
Workflow run id 4489015918 approved.

2023-03-22 10:50 UTC, dune-eng commented
Workflow run id 4489015917 approved.

2023-03-22 12:18 UTC, dune-eng commented
Workflow run id 4489733966 approved.

2023-03-22 12:35 UTC, dune-eng commented
Workflow run id 4489880254 approved.

2023-03-22 12:35 UTC, dune-eng commented
Workflow run id 4489880256 approved.

2023-04-03 09:55 UTC, Hosuke approved these changes
LGTM.✅
Thank you @henrystats 

This PR adds aragon dao addresses spells, which consists of [`app_dao_addresses`, `client_dao_addresses`] on [`ethereum`, `gnosis`, `polygon`] chains.

2023-04-11 13:04 UTC, dune-eng commented
Workflow run id 4667841111 approved.

2023-04-11 13:04 UTC, dune-eng commented
Workflow run id 4667841112 approved.

2023-04-12 17:19 UTC, jeff-dude requested changes

2023-04-12 17:19 UTC, jeff-dude commented on models/aragon/gnosis/aragon_gnosis_dao_addresses.sql
> +ref('aragon_polygon_client_dao_addresses')
assume this should be `gnosis`?

2023-04-13 00:42 UTC, henrystats commented on models/aragon/gnosis/aragon_gnosis_dao_addresses.sql
> +ref('aragon_polygon_client_dao_addresses')
yes :( updated now ser ty

2023-04-13 00:42 UTC, dune-eng commented
Workflow run id 4684259550 approved.

2023-04-13 00:42 UTC, dune-eng commented
Workflow run id 4684259548 approved.

2023-04-13 00:42 UTC, dune-eng commented
Workflow run id 4684261226 approved.

2023-04-13 00:42 UTC, dune-eng commented
Workflow run id 4684261227 approved.

2023-04-13 14:57 UTC, jeff-dude approved these changes
thank you

2023-04-13 14:58 UTC, merged