Add flashloans
duneanalytics/spellbook pull request #3096
Opened 2023-03-31 15:33 UTC by Jam516

Brief comments on the purpose of your changes:

Adding labels for wallets that have used flashloans on Aave, Uniswap and Balancer.

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2023-03-31 15:33 UTC, dune-eng commented
Workflow run id 4576704402 approved.

2023-03-31 15:33 UTC, dune-eng commented
Workflow run id 4576704396 approved.

2023-03-31 15:34 UTC, dune-eng commented
Workflow run id 4576707655 approved.

2023-03-31 15:44 UTC, dune-eng commented
Workflow run id 4576789323 approved.

2023-03-31 15:44 UTC, dune-eng commented
Workflow run id 4576789325 approved.

2023-04-03 21:32 UTC, dune-eng commented
Workflow run id 4601518924 approved.

2023-04-03 21:32 UTC, dune-eng commented
Workflow run id 4601518916 approved.

2023-04-04 09:59 UTC, Hosuke approved these changes
LGTM.✅
Thank you @Jam516

2023-04-10 20:12 UTC, jeff-dude commented
please revisit why the accepted values test from `labels_infrastrucutre.sql` is failing here

2023-04-11 08:58 UTC, Hosuke commented
> please revisit why the accepted values test from `labels_infrastrucutre.sql` is failing here

I am trying to figure out this problem.

2023-04-11 09:46 UTC, Hosuke commented
Hi @jeff-dude, do you think this may be a transient server problem?

All records with `category` field value `infrastructure` in `test_schema.git_e69cb4f4_labels_flashloans_ethereum`:
https://dune.com/queries/2355450

While there are still records with `category` field values other than `infrastructure` in `test_schema.git_e69cb4f4_labels_infrastructure`:
https://dune.com/queries/2355468

2023-04-12 19:52 UTC, jeff-dude requested changes

2023-04-12 19:52 UTC, jeff-dude commented on models/labels/addresses/infrastructure/persona/flashloans/labels_flashloans_ethereum.sql
> +SELECT *
@Hosuke it looks like it's column order in the select here is incorrect, which is then union'ed into the `labels_infrastructure` spell. in your [query](https://dune.com/queries/2355468), you can see values aren't in the right category. please ensure this spell follows this pattern:
- blockchain
- address
- name
- category
- contributor
- source
- created_at
- updated_at
- model_name
- label_type

2023-04-13 05:26 UTC, Hosuke commented on models/labels/addresses/infrastructure/persona/flashloans/labels_flashloans_ethereum.sql
> +SELECT *
I see, using `select *` in roll-up spell is a dangerous practice.
I will try to solve all ambiguous column matching issues under `labels_infrastructure` in this PR.

2023-04-13 18:32 UTC, jeff-dude commented on models/labels/addresses/infrastructure/persona/flashloans/labels_flashloans_ethereum.sql
> +SELECT *
dangerous indeed :)

2023-04-13 18:35 UTC, jeff-dude approved these changes
thanks for using this to help clean up 🤝 and thanks for contributing @Jam516

2023-04-13 18:35 UTC, merged