[WIP] Paraswap dex add more blockchain
duneanalytics/spellbook pull request #3288
Opened 2023-05-05 12:02 UTC by springzh

Brief comments on the purpose of your changes:

This PR is to add 5 new blockchains data for ParaSwap. 
Also include some minor tweak to previous created ParaSwap spells.

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2023-05-05 12:03 UTC, dune-eng commented
Workflow run id 4893134916 approved.

2023-05-05 12:03 UTC, dune-eng commented
Workflow run id 4893134915 approved.

2023-05-05 12:12 UTC, dune-eng commented
Workflow run id 4893220484 approved.

2023-05-05 12:12 UTC, dune-eng commented
Workflow run id 4893220489 approved.

2023-05-08 09:22 UTC, dune-eng commented
Workflow run id 4913569498 approved.

2023-05-08 09:22 UTC, dune-eng commented
Workflow run id 4913569499 approved.

2023-05-08 10:19 UTC, dune-eng commented
Workflow run id 4914059062 approved.

2023-05-08 10:19 UTC, dune-eng commented
Workflow run id 4914059066 approved.

2023-05-09 03:45 UTC, dune-eng commented
Workflow run id 4922099910 approved.

2023-05-09 03:45 UTC, dune-eng commented
Workflow run id 4922099907 approved.

2023-05-09 03:52 UTC, dune-eng commented
Workflow run id 4922132903 approved.

2023-05-09 03:52 UTC, dune-eng commented
Workflow run id 4922132914 approved.

2023-05-09 05:13 UTC, dune-eng commented
Workflow run id 4922584338 approved.

2023-05-09 05:13 UTC, dune-eng commented
Workflow run id 4922584336 approved.

2023-05-09 08:23 UTC, dune-eng commented
Workflow run id 4923963049 approved.

2023-05-09 08:23 UTC, dune-eng commented
Workflow run id 4923963053 approved.

2023-05-09 08:55 UTC, Hosuke approved these changes
LGTM.✅
Thank you @springzh 

There are some trades with 0 as`evt_index`, as paraswap did not emit some events to save gas.
https://dune.com/queries/2455736?d=1

2023-05-09 14:41 UTC, springzh commented
From Mounir (CEO of ParaSwap):
"Also, some functions in Ethereum don’t emit events (for gas optimisation)".

For reference, here are some sample transactions that don't emit their own events:
-- swap_type, block_number, tx_hash
-- erc20 to erc20, 13302850, 0x34777d43e267d17862375293bb2e3cc4e8bd44abe7dca761891690c290eebee0
-- eth to erc20, 13512018, 0xf196c5393f402cef9cbe01341d55ab90d2233b650b4cb1381dffb21f2ff6bb73
-- erc20 to eth, 13300892, 0x99d61733a0e8f4bf5d1fdf25e4929de987ac883e4b70c81f01af4a53ca3d800f

The "Swap" or similar events we can find in the above transactions are not emitted from ParaSwap contract. They are from other contracts such as Uniswap.

2023-05-10 14:24 UTC, jeff-dude requested changes
minor feedback below, but great stuff here!

2023-05-11 08:31 UTC, dune-eng commented
Workflow run id 4945733576 approved.

2023-05-11 08:31 UTC, dune-eng commented
Workflow run id 4945733571 approved.

2023-05-11 14:05 UTC, springzh commented on models/paraswap/ethereum/paraswap_v4_ethereum_trades.sql
> +            CAST(0 AS bigint) AS evt_index
Done. Updated to -1.

2023-05-11 14:05 UTC, springzh commented on models/paraswap/ethereum/paraswap_v4_ethereum_trades.sql
> +            CAST(0 AS bigint) AS evt_index
Done. Updated to -1.

2023-05-11 14:05 UTC, springzh commented on models/paraswap/ethereum/paraswap_v5_ethereum_trades.sql
> +            CAST(0 AS bigint) AS evt_index
Done. Updated to -1.

2023-05-11 14:05 UTC, springzh commented on models/paraswap/ethereum/paraswap_v5_ethereum_trades.sql
> +            CAST(0 AS bigint) AS evt_index
Done. Updated to -1.

2023-05-16 15:58 UTC, jeff-dude approved these changes
thanks all

2023-05-16 18:45 UTC, merged