Add clipper.exchange Coves
duneanalytics/spellbook pull request #3318
Opened 2023-05-09 19:22 UTC by amalashkevich

Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2023-05-12 14:45 UTC, Hosuke requested changes
Thank you @amalashkevich 
Here are some minor feedbacks about tests

2023-05-12 17:53 UTC, amalashkevich commented on models/clipper/arbitrum/clipper_arbitrum_schema.yml
> +      - *blockchain
Thanks, fixed

2023-05-12 17:53 UTC, amalashkevich commented on models/clipper/polygon/clipper_polygon_schema.yml
> +          version: coves_v1
Thanks, fixed

2023-05-15 07:03 UTC, Hosuke approved these changes
LGTM.✅
Thank you @amalashkevich

2023-05-17 19:35 UTC, jeff-dude approved these changes
thanks all

2023-05-17 19:35 UTC, merged