Add xchange dex trades objects for ethereum
duneanalytics/spellbook pull request #3535
Opened 2023-06-14 14:46 UTC by mike-x7f

Brief comments on the purpose of your changes:
Addition of xchange ethereum trades views for pair creation and swaps.

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

2023-06-14 14:46 UTC, dune-eng commented
Workflow run id 5268644669 approved.

2023-06-14 14:46 UTC, dune-eng commented
Workflow run id 5268644670 approved.

2023-06-14 15:06 UTC, dune-eng commented
Workflow run id 5268866749 approved.

2023-06-14 15:20 UTC, dune-eng commented
Workflow run id 5269030828 approved.

2023-06-14 15:20 UTC, dune-eng commented
Workflow run id 5269030826 approved.

2023-06-15 13:52 UTC, dune-eng commented
Workflow run id 5279663871 approved.

2023-06-15 14:59 UTC, dune-eng commented
Workflow run id 5280394202 approved.

2023-06-15 14:59 UTC, dune-eng commented
Workflow run id 5280394193 approved.

2023-06-15 16:15 UTC, dune-eng commented
Workflow run id 5281171736 approved.

2023-06-15 16:28 UTC, dune-eng commented
Workflow run id 5281287250 approved.

2023-06-15 16:28 UTC, dune-eng commented
Workflow run id 5281287300 approved.

2023-06-15 16:28 UTC, dune-eng commented
Workflow run id 5281287249 approved.

2023-06-15 18:49 UTC, Hosuke requested changes

2023-06-15 18:49 UTC, Hosuke commented on models/xchange/ethereum/xchange_ethereum_schema.yml
> +          version: 1
In order for `check_dex_seed` to work, you need to add seed records in the following file:
https://github.com/duneanalytics/spellbook/blob/main/seeds/dex/trades/dex_trades_seed.csv

2023-06-15 18:49 UTC, Hosuke commented on seeds/xchange/xchange_trades_seed.csv
> +ethereum,xchange,1,2023-06-12,0x4eba2bbed2a473a3a6b2fbfc1d784940b5157afc285c35aff1200e491ea1346a,115,0xDBc7945C5403c589Ec39A9Aa8C5AF234C706f6a2,14049529527.028758241707276441,0xC02aaA39b223FE8D0A0e5C
You can move/copy these records into the dex_trades.seed file:
https://github.com/duneanalytics/spellbook/blob/main/seeds/dex/trades/dex_trades_seed.csv

2023-06-15 20:36 UTC, mike-x7f commented
I added tests to dex_trades_seed, but I'm not sure these will work because I don't intend for this new model to be part of dex.trades and I haven't modified the dex trades model to include xchange_ethereum_trades.  I will be creating additional xchange trades models for 4 other chains and then have one xchange_trades which combines all 5 chains.  This is similar to the uniswap model.  I committed the changes and will see what happens with the dbt test.

2023-06-16 05:45 UTC, Hosuke commented
> I added tests to dex_trades_seed, but I'm not sure these will work because I don't intend for this new model to be part of dex.trades and I haven't modified the dex trades model to include xchange_ethereum_trades. I will be creating additional xchange trades models for 4 other chains and then have one xchange_trades which combines all 5 chains. This is similar to the uniswap model. I committed the changes and will see what happens with the dbt test.

I see, if you do not want to add this new model into dex.trades, you can use `check_seed` test as an alternative.

2023-06-16 13:01 UTC, mike-x7f commented
I've changed to check_seed test.  How can we re-run dbt-test? And I can't seem to figure out how to remove this from draft status.  
Thanks, Mike

2023-06-16 18:04 UTC, Hosuke commented
> I've changed to check_seed test. How can we re-run dbt-test? And I can't seem to figure out how to remove this from draft status. Thanks, Mike

I just resolved the conflicts and merge the main branch into current PR.
The test can be triggered normally now.

2023-06-16 19:09 UTC, dune-eng commented
Workflow run id 5293396023 approved.

2023-06-16 19:09 UTC, dune-eng commented
Workflow run id 5293396010 approved.

2023-06-16 19:45 UTC, dune-eng commented
Workflow run id 5293643237 approved.

2023-06-16 19:45 UTC, dune-eng commented
Workflow run id 5293643236 approved.

2023-06-16 20:24 UTC, dune-eng commented
Workflow run id 5293924404 approved.

2023-06-16 20:24 UTC, dune-eng commented
Workflow run id 5293924403 approved.

2023-06-17 01:15 UTC, dune-eng commented
Workflow run id 5295520849 approved.

2023-06-17 01:15 UTC, dune-eng commented
Workflow run id 5295520850 approved.

2023-06-17 02:54 UTC, dune-eng commented
Workflow run id 5295966452 approved.

2023-06-17 02:54 UTC, dune-eng commented
Workflow run id 5295966453 approved.

2023-06-17 03:13 UTC, mike-x7f commented
@Hosuke is there anything I can do to get these dbt checks to run faster? They were finishing in a reasonable amount of time before today, but now it keeps timing out when I try to rerun it.  Not sure if it's something I added or changed that's causing the slowness.

2023-06-17 04:31 UTC, dune-eng commented
Workflow run id 5296336425 approved.

2023-06-17 04:31 UTC, dune-eng commented
Workflow run id 5296336426 approved.

2023-06-17 17:22 UTC, dune-eng commented
Workflow run id 5299327352 approved.

2023-06-17 17:22 UTC, dune-eng commented
Workflow run id 5299327356 approved.

2023-06-17 17:22 UTC, dune-eng commented
Workflow run id 5299327381 approved.

2023-06-17 17:22 UTC, dune-eng commented
Workflow run id 5299327379 approved.

2023-06-17 17:24 UTC, dune-eng commented
Workflow run id 5299340358 approved.

2023-06-17 17:24 UTC, dune-eng commented
Workflow run id 5299340357 approved.

2023-06-18 00:46 UTC, Hosuke commented
> @Hosuke is there anything I can do to get these dbt checks to run faster? They were finishing in a reasonable amount of time before today, but now it keeps timing out when I try to rerun it. Not sure if it's something I added or changed that's causing the slowness.

Sorry @mike-x7f, currently I am not very sure about the reason of why the dbt-test is so slow.

2023-06-18 02:30 UTC, mike-x7f commented
Does it have anything to do with the gas fee traces changes that got added and reverted because according to @jeff-dude they were too much and causing failures? They are showing up in my tests but I didn't make any changes to those models. Is there any way I can remove those from my test so I can get my checks to pass and have this merged before the migration freeze next week?

![image](https://github.com/duneanalytics/spellbook/assets/136265900/db5c5167-9cfe-4e51-8021-3c573f03e853)

2023-06-18 08:05 UTC, jeff-dude commented
> Does it have anything to do with the gas fee traces changes that got added and reverted because according to @jeff-dude they were too much and causing failures? They are showing up in my tests but I didn't make any changes to those models. Is there any way I can remove those from my test so I can get my checks to pass and have this merged before the migration freeze next week?
> 
> ![image](https://user-images.githubusercontent.com/136265900/246640239-db5c5167-9cfe-4e51-8021-3c573f03e853.jpeg)

yes @mike-x7f, that's right. the gh action which commits a dbt manifest file post-merge to main branch had failed after those `fees_traces` PRs. link [here](https://github.com/duneanalytics/spellbook/actions/runs/5293700658) for reference. since this manifest didn't commit, the PR CI tests didn't recognize that the models were removed, therefore thinking they had to run in your PR (and all other PRs).

just a few minutes ago, i had merged a PR into `main` again, and the `commit-manifest` gh action succeeded as expected. you can easily find these runs in the actions section. 

now this PR should behave as normal, following a new commit to kick off the gh actions again.

fyi @Hosuke, this commit-manifest gh action will be a place to check if models outside of any given PR are running when they shouldn't be. keep in mind, if that gh action is running (due to merge to main), while the action is in progress, other active PRs will pick up those models until the manifest uploads successfully and that action completes. this is fairly common if users are actively building while we are merging. it should resolve itself on most occasions by just giving it some time to complete.

2023-06-18 08:25 UTC, jeff-dude commented
and we're back, it ran as expected this time

2023-06-18 12:15 UTC, mike-x7f commented
Awesome, thanks @jeff-dude!

@Hosuke the tests look good, so this is ready to merge if everything looks good to you.

2023-06-18 15:31 UTC, Hosuke approved these changes
LGTM.✅
Thank you @mike-x7f 

[Sample xchange_ethereum_trades](https://dune.com/queries/2645108?d=1)

2023-06-18 15:31 UTC, Hosuke commented on seeds/xchange/xchange_trades_seed.csv
There may be some unused seed files in this PR.
i.e.
`seeds/xchange/ethereum/xchange_ethereum_native_trades_seed.csv`
`seeds/xchange/xchange_trades_seed.csv`

2023-06-18 15:51 UTC, mike-x7f commented on seeds/xchange/xchange_trades_seed.csv
> 
Let me know if it's okay to keep those.  The native trades seed uses new tokens that weren't in tokens.erc20.  I'm adding them in this PR so that seed file should work in the future.  The other one xchange_trades_seed was intended for when I add other chains besides ethereum and have them roll into the master xchange_trades view.  But that will feed into dex.trades and as you said before, I can just use the dex_trades_seed.

2023-06-19 12:21 UTC, jeff-dude approved these changes
thank you @mike-x7f -- look forward to seeing more get integrated!

2023-06-19 12:35 UTC, merged

2023-06-19 14:11 UTC, mike-x7f commented
Hi @jeff-dude I think the merge may have had issues.  I still don't see the new table in dune and I noticed this job failure:
https://github.com/duneanalytics/spellbook/actions/runs/5311934577
Is this something you can help with?

2023-06-19 14:17 UTC, jeff-dude commented
> Hi @jeff-dude I think the merge may have had issues. I still don't see the new table in dune and I noticed this job failure: https://github.com/duneanalytics/spellbook/actions/runs/5311934577 Is this something you can help with?

a more recent run of that action has completed, so no worries. that was a backend issue that we quickly resolved. this also doesn't impact production, only the PR dev process.

prod is currently still running, as it included lots of spells in this latest batch of merges. please give it a little more time.