Update arbitrum tigris trades pair -- quick fix
duneanalytics/spellbook pull request #3744
Opened 2023-07-13 23:54 UTC by henrystats

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-07-13 23:54 UTC, dune-eng commented
Workflow run id 5548982544 approved.

2023-07-13 23:58 UTC, dune-eng commented
Workflow run id 5548997279 approved.

2023-07-14 15:09 UTC, jeff-dude approved these changes

2023-07-18 14:57 UTC, jeff-dude requested changes
@henrystats with the universal change to add legacy files, this is now out of date and needs the changes pushed to the legacy file instead. please update and we can look to merge

2023-07-18 15:49 UTC, dune-eng commented
Workflow run id 5589606697 approved.

2023-07-18 16:41 UTC, henrystats commented
fixed ser @jeff-dude

2023-07-18 16:47 UTC, jeff-dude approved these changes
nice -- thanks for migrating too!

2023-07-18 16:48 UTC, merged