Adding GHO to ethereum tokens
duneanalytics/spellbook pull request #3773
Opened 2023-07-17 14:10 UTC by xmc2

This PR adds the GHO token to the Tokens spell.

2023-07-18 01:19 UTC, Hosuke approved these changes
LGTM.✅
Thank you @xmc2

2023-07-18 01:19 UTC, Hosuke commented on models/tokens/ethereum/tokens_ethereum_erc20.sql
> +        ,(0x40d16fc0246ad3160ccc09b8d0d3a2cd28ae6c2f, 'GHO',18)
https://etherscan.io/token/0x40d16fc0246ad3160ccc09b8d0d3a2cd28ae6c2f

2023-07-18 14:46 UTC, jeff-dude requested changes
thank you @xmc2 -- for the duration of the migration, can you look to add the token to both the dunesql and spark version of the file? you should see the same file with `_legacy.sql` in the same directory.

example here #3747 

note that spark one still contains the quotes on the address

2023-07-19 17:21 UTC, xmc2 commented
@jeff-dude - updated. Thanks!

2023-07-21 02:28 UTC, xmc2 commented
Thanks @jeff-dude 
Replace with #3821

2023-07-21 02:28 UTC, closed without merging