Add Maverick and Biswap v3 on BNB chain to dex.trades (DuneSQL)
duneanalytics/spellbook pull request #3810
Opened 2023-07-20 08:15 UTC by chef-seaweed

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

This is an updated version of this PR https://github.com/duneanalytics/spellbook/pull/3722. 
Main change is to keep out of dex lineage (SparkSQL spells) which are in the process of migration.

2023-07-20 08:30 UTC, dune-eng commented
Workflow run id 5608705592 approved.

2023-07-23 14:02 UTC, dune-eng commented
Workflow run id 5636863850 approved.

2023-07-23 14:37 UTC, dune-eng commented
Workflow run id 5637035452 approved.

2023-07-25 01:51 UTC, dune-eng commented
Workflow run id 5651722954 approved.

2023-07-26 07:19 UTC, dune-eng commented
Workflow run id 5665840397 approved.

2023-07-27 15:32 UTC, dune-eng commented
Workflow run id 5682524306 approved.

2023-07-30 07:48 UTC, dune-eng commented
Workflow run id 5705039091 approved.

2023-08-01 03:09 UTC, dune-eng commented
Workflow run id 5722125045 approved.

2023-08-01 03:09 UTC, dune-eng commented
Workflow run id 5722125144 approved.

2023-08-01 13:59 UTC, Hosuke requested changes

2023-08-01 13:59 UTC, Hosuke commented on models/biswap/bnb/biswap_v3_bnb_trades.sql
Hi @chef-seaweed,
you can create a dummy _legacy model for this spell.
The file name would be `biswap_v3_bnb_trades_legacy.sql`.
https://github.com/duneanalytics/spellbook/actions/runs/5722125144/job/15504724973?pr=3810#step:8:14

2023-08-01 13:59 UTC, Hosuke commented on models/maverick/bnb/maverick_v1_bnb_trades.sql
A dummy _legacy model for this spell as well.

2023-08-02 03:28 UTC, chef-seaweed commented
I have read the CLA Document and I hereby sign the CLA

2023-08-02 03:30 UTC, dune-eng commented
Workflow run id 5734419198 approved.

2023-08-02 03:30 UTC, dune-eng commented
Workflow run id 5734419273 approved.

2023-08-02 03:47 UTC, dune-eng commented
Workflow run id 5734504251 approved.

2023-08-02 03:47 UTC, dune-eng commented
Workflow run id 5734504316 approved.

2023-08-02 03:55 UTC, chef-seaweed commented on models/biswap/bnb/biswap_v3_bnb_trades.sql
Hi @Hosuke, I've added dummy _legacy models for the spells, but now I have this error
> Common models between DuneSQL and Spark:
spellbook.biswap.bnb.biswap_v3_bnb_trades_legacy
![Screenshot 2023-08-02 at 11 55 02 AM](https://github.com/duneanalytics/spellbook/assets/121569855/61289c9a-cfe6-4f2b-b97e-7507f96157f8)

spellbook.maverick.bnb.maverick_v1_bnb_trades_legacy

2023-08-02 04:00 UTC, dune-eng commented
Workflow run id 5734560873 approved.

2023-08-02 04:20 UTC, dune-eng commented
Workflow run id 5734686550 approved.

2023-08-02 04:20 UTC, dune-eng commented
Workflow run id 5734686629 approved.

2023-08-02 05:51 UTC, dune-eng commented
Workflow run id 5735224613 approved.

2023-08-02 05:51 UTC, dune-eng commented
Workflow run id 5735224672 approved.

2023-08-02 06:06 UTC, dune-eng commented
Workflow run id 5735324255 approved.

2023-08-02 06:06 UTC, dune-eng commented
Workflow run id 5735324386 approved.

2023-08-02 06:28 UTC, dune-eng commented
Workflow run id 5735497742 approved.

2023-08-02 06:28 UTC, dune-eng commented
Workflow run id 5735497647 approved.

2023-08-02 07:27 UTC, dune-eng commented
Workflow run id 5735972779 approved.

2023-08-02 07:27 UTC, dune-eng commented
Workflow run id 5735972850 approved.

2023-08-02 07:42 UTC, dune-eng commented
Workflow run id 5736105409 approved.

2023-08-02 07:42 UTC, dune-eng commented
Workflow run id 5736105576 approved.

2023-08-02 08:06 UTC, chef-seaweed commented on models/biswap/bnb/biswap_v3_bnb_trades.sql
Thanks for suggestion @Hosuke. The checks seem fine now 🙏

2023-08-02 10:43 UTC, Hosuke approved these changes
LGTM.✅
Thank you @chef-seaweed for adding complete legacy models

2023-08-03 03:27 UTC, dune-eng commented
Workflow run id 5746283348 approved.

2023-08-03 03:27 UTC, dune-eng commented
Workflow run id 5746283336 approved.

2023-08-03 08:47 UTC, Hosuke commented
Hi @chef-seaweed, if you want to add these spells into their meta-tables, like `biswap.trades`, you may need to further migrate the meta-table spells and their models on other chains/versions.

2023-08-03 09:27 UTC, chef-seaweed commented
> Hi @chef-seaweed, if you want to add these spells into their meta-tables, like `biswap.trades`, you may need to further migrate the meta-table spells and their models on other chains/versions.

@Hosuke  okay previously I thought I shouldn't touch them as I assumed Dune team were already working on the migration of existing spells. so it's okay to let me work on them now right?

2023-08-03 09:38 UTC, Hosuke commented
> > Hi @chef-seaweed, if you want to add these spells into their meta-tables, like `biswap.trades`, you may need to further migrate the meta-table spells and their models on other chains/versions.
> 
> @Hosuke okay previously I thought I shouldn't touch them as I assumed Dune team were already working on the migration of existing spells. so it's okay to let me work on them now right?

Yes, you can migrate any spell you familiar.

2023-08-03 13:52 UTC, chef-seaweed commented
> Yes, you can migrate any spell you familiar.

Noted, thanks. Can we review and merge this PR first. I think I will work on their meta-tables and models on other chains/versions later, thanks.

2023-08-04 17:35 UTC, jeff-dude requested changes

2023-08-04 17:35 UTC, jeff-dude commented on models/biswap/bnb/biswap_v3_bnb_trades.sql
> +        ,CAST(NULL as array<bigint>) AS trace_address
we are moving forward with removing this field from `dex.trades` lineage, as it's not used in any models (only aggregators). you can look at uniswap / sushiswap / pancakeswap spells which have been migrated as reference.

plz do remove this field in all spells here and the schema files. also includes unique keys, unique combo of columns test, etc.

2023-08-04 17:35 UTC, jeff-dude commented on models/biswap/bnb/biswap_v3_bnb_trades_legacy.sql
for `_legacy` files on spark, we'd prefer that the spell itself is just a dummy statement to avoid extra processing on new spells that are initiated on dunesql.

example:
https://github.com/duneanalytics/spellbook/blob/main/models/oneinch/arbitrum/oneinch_arbitrum_ar_calls_transfers_legacy.sql

the key is to ensure schema / alias match the dunesql version

2023-08-04 17:35 UTC, jeff-dude commented on tests/generic/check_dex_seed.sql
> -    {%- set seed_matching_columns = ['block_date','blockchain','project','version','tx_hash','evt_index'] -%}
lets keep `block_date` here

2023-08-04 17:35 UTC, jeff-dude commented on models/biswap/bnb/biswap_v3_bnb_trades_legacy.sql
this applies to other dex as well

2023-08-04 17:35 UTC, jeff-dude commented on models/biswap/bnb/biswap_v3_bnb_trades.sql
> +        ,CAST(NULL as array<bigint>) AS trace_address
this applies to other dex as well

2023-08-05 12:55 UTC, Hosuke commented on tests/generic/check_dex_seed.sql
> -    {%- set seed_matching_columns = ['block_date','blockchain','project','version','tx_hash','evt_index'] -%}
Recovered.

2023-08-07 13:17 UTC, dune-eng commented
Workflow run id 5785626678 approved.

2023-08-07 13:17 UTC, dune-eng commented
Workflow run id 5785626701 approved.

2023-08-07 15:09 UTC, dune-eng commented
Workflow run id 5786814065 approved.

2023-08-07 18:48 UTC, jeff-dude approved these changes

2023-08-07 18:48 UTC, merged