zeroex - add celo txns
duneanalytics/spellbook pull request #3819
Opened 2023-07-20 19:43 UTC by RantumBits

zereoex celo - non-deduped & deduped

2023-07-20 19:44 UTC, dune-eng commented
Workflow run id 5615229634 approved.

2023-07-20 19:59 UTC, dune-eng commented
Workflow run id 5615340474 approved.

2023-07-20 20:04 UTC, dune-eng commented
Workflow run id 5615387293 approved.

2023-07-20 20:10 UTC, dune-eng commented
Workflow run id 5615440837 approved.

2023-07-20 20:14 UTC, dune-eng commented
Workflow run id 5615476741 approved.

2023-07-20 20:19 UTC, dune-eng commented
Workflow run id 5615521403 approved.

2023-07-21 14:47 UTC, dune-eng commented
Workflow run id 5623606388 approved.

2023-07-21 14:57 UTC, dune-eng commented
Workflow run id 5623688299 approved.

2023-07-21 15:04 UTC, dune-eng commented
Workflow run id 5623763113 approved.

2023-07-21 15:21 UTC, dune-eng commented
Workflow run id 5623927394 approved.

2023-07-21 15:29 UTC, dune-eng commented
Workflow run id 5623997933 approved.

2023-07-21 15:38 UTC, dune-eng commented
Workflow run id 5624078412 approved.

2023-07-21 15:51 UTC, dune-eng commented
Workflow run id 5624179868 approved.

2023-07-21 15:59 UTC, dune-eng commented
Workflow run id 5624239396 approved.

2023-07-21 16:04 UTC, dune-eng commented
Workflow run id 5624289846 approved.

2023-07-21 16:10 UTC, dune-eng commented
Workflow run id 5624345305 approved.

2023-07-21 16:20 UTC, dune-eng commented
Workflow run id 5624433452 approved.

2023-07-21 16:29 UTC, dune-eng commented
Workflow run id 5624504329 approved.

2023-07-21 16:49 UTC, dune-eng commented
Workflow run id 5624673881 approved.

2023-07-21 16:53 UTC, dune-eng commented
Workflow run id 5624705365 approved.

2023-07-21 17:03 UTC, dune-eng commented
Workflow run id 5624781881 approved.

2023-07-21 17:09 UTC, dune-eng commented
Workflow run id 5624834966 approved.

2023-07-21 17:16 UTC, dune-eng commented
Workflow run id 5624894126 approved.

2023-07-21 17:24 UTC, RantumBits commented
What's the best way to handle this error? 
Access Denied: Cannot select from table hive.tokens.erc20

2023-07-24 13:48 UTC, dune-eng commented
Workflow run id 5645666916 approved.

2023-07-26 22:50 UTC, dune-eng commented
Workflow run id 5674456460 approved.

2023-07-26 23:56 UTC, dune-eng commented
Workflow run id 5674851882 approved.

2023-07-31 23:00 UTC, dune-eng commented
Workflow run id 5720469490 approved.

2023-07-31 23:00 UTC, dune-eng commented
Workflow run id 5720469526 approved.

2023-08-01 17:33 UTC, dune-eng commented
Workflow run id 5730012286 approved.

2023-08-01 17:33 UTC, dune-eng commented
Workflow run id 5730012492 approved.

2023-08-01 17:37 UTC, dune-eng commented
Workflow run id 5730047469 approved.

2023-08-01 17:37 UTC, dune-eng commented
Workflow run id 5730047602 approved.

2023-08-01 18:17 UTC, dune-eng commented
Workflow run id 5730402717 approved.

2023-08-01 18:17 UTC, dune-eng commented
Workflow run id 5730402667 approved.

2023-08-01 18:17 UTC, dune-eng commented
Workflow run id 5730402797 approved.

2023-08-01 19:13 UTC, dune-eng commented
Workflow run id 5730907007 approved.

2023-08-01 19:13 UTC, dune-eng commented
Workflow run id 5730907209 approved.

2023-08-01 19:24 UTC, dune-eng commented
Workflow run id 5730999966 approved.

2023-08-01 22:37 UTC, dune-eng commented
Workflow run id 5732537728 approved.

2023-08-01 22:37 UTC, dune-eng commented
Workflow run id 5732537927 approved.

2023-08-01 22:40 UTC, dune-eng commented
Workflow run id 5732557915 approved.

2023-08-01 22:40 UTC, dune-eng commented
Workflow run id 5732557843 approved.

2023-08-01 23:06 UTC, dune-eng commented
Workflow run id 5732716687 approved.

2023-08-01 23:06 UTC, dune-eng commented
Workflow run id 5732716782 approved.

2023-08-03 04:06 UTC, dune-eng commented
Workflow run id 5746486593 approved.

2023-08-03 04:07 UTC, dune-eng commented
Workflow run id 5746486725 approved.

2023-08-03 04:10 UTC, dune-eng commented
Workflow run id 5746507222 approved.

2023-08-03 04:10 UTC, dune-eng commented
Workflow run id 5746507309 approved.

2023-08-07 21:27 UTC, dune-eng commented
Workflow run id 5790070371 approved.

2023-08-07 21:27 UTC, dune-eng commented
Workflow run id 5790070374 approved.

2023-08-08 17:48 UTC, dune-eng commented
Workflow run id 5800255965 approved.

2023-08-08 17:48 UTC, dune-eng commented
Workflow run id 5800256055 approved.

2023-08-08 19:46 UTC, dune-eng commented
Workflow run id 5801272096 approved.

2023-08-08 20:00 UTC, dune-eng commented
Workflow run id 5801381654 approved.

2023-08-08 21:08 UTC, dune-eng commented
Workflow run id 5801959408 approved.

2023-08-08 21:08 UTC, dune-eng commented
Workflow run id 5801959323 approved.

2023-08-08 21:12 UTC, dune-eng commented
Workflow run id 5801992453 approved.

2023-08-08 21:12 UTC, dune-eng commented
Workflow run id 5801992457 approved.

2023-08-08 21:23 UTC, dune-eng commented
Workflow run id 5802084308 approved.

2023-08-08 21:23 UTC, dune-eng commented
Workflow run id 5802084542 approved.

2023-08-08 21:53 UTC, dune-eng commented
Workflow run id 5802294671 approved.

2023-08-08 21:53 UTC, dune-eng commented
Workflow run id 5802294809 approved.

2023-08-08 22:02 UTC, dune-eng commented
Workflow run id 5802354386 approved.

2023-08-08 22:02 UTC, dune-eng commented
Workflow run id 5802354324 approved.

2023-08-08 22:05 UTC, dune-eng commented
Workflow run id 5802382320 approved.

2023-08-08 22:05 UTC, dune-eng commented
Workflow run id 5802382447 approved.

2023-08-08 22:14 UTC, dune-eng commented
Workflow run id 5802458819 approved.

2023-08-08 22:14 UTC, dune-eng commented
Workflow run id 5802458914 approved.

2023-08-08 22:29 UTC, dune-eng commented
Workflow run id 5802585692 approved.

2023-08-08 22:29 UTC, dune-eng commented
Workflow run id 5802585754 approved.

2023-08-08 22:43 UTC, dune-eng commented
Workflow run id 5802686297 approved.

2023-08-08 22:43 UTC, dune-eng commented
Workflow run id 5802686435 approved.

2023-08-08 22:56 UTC, dune-eng commented
Workflow run id 5802764440 approved.

2023-08-08 22:56 UTC, dune-eng commented
Workflow run id 5802764526 approved.

2023-08-09 16:52 UTC, Hosuke commented on seeds/zeroex/celo/_schema.yml
> +        # TODO: Add column types here
Hi @RantumBits,
please define the column types here.
You may move this schema file into `seeds/zeroex/` if you want.

2023-08-09 17:04 UTC, dune-eng commented
Workflow run id 5811973063 approved.

2023-08-09 17:17 UTC, dune-eng commented
Workflow run id 5812095980 approved.

2023-08-09 17:28 UTC, dune-eng commented
Workflow run id 5812204121 approved.

2023-08-09 17:28 UTC, dune-eng commented
Workflow run id 5812204322 approved.

2023-08-09 19:24 UTC, dune-eng commented
Workflow run id 5813231324 approved.

2023-08-09 19:24 UTC, dune-eng commented
Workflow run id 5813231742 approved.

2023-08-09 20:23 UTC, dune-eng commented
Workflow run id 5813712702 approved.

2023-08-09 20:23 UTC, dune-eng commented
Workflow run id 5813713128 approved.

2023-08-09 20:28 UTC, dune-eng commented
Workflow run id 5813760414 approved.

2023-08-09 20:28 UTC, dune-eng commented
Workflow run id 5813760550 approved.

2023-08-10 00:01 UTC, RantumBits commented
@Hosuke Can you advise on how to handle error with the dummy legacy model?

2023-08-10 16:40 UTC, dune-eng commented
Workflow run id 5823795971 approved.

2023-08-10 16:40 UTC, dune-eng commented
Workflow run id 5823796202 approved.

2023-08-10 21:09 UTC, dune-eng commented
Workflow run id 5826123495 approved.

2023-08-10 21:09 UTC, dune-eng commented
Workflow run id 5826123645 approved.

2023-08-11 16:45 UTC, dune-eng commented
Workflow run id 5835006076 approved.

2023-08-11 16:45 UTC, dune-eng commented
Workflow run id 5835006177 approved.

2023-08-11 16:52 UTC, dune-eng commented
Workflow run id 5835055656 approved.

2023-08-11 17:23 UTC, dune-eng commented
Workflow run id 5835330895 approved.

2023-08-11 17:23 UTC, dune-eng commented
Workflow run id 5835331045 approved.

2023-08-11 17:52 UTC, dune-eng commented
Workflow run id 5835555749 approved.

2023-08-11 17:52 UTC, dune-eng commented
Workflow run id 5835555740 approved.

2023-08-11 18:07 UTC, dune-eng commented
Workflow run id 5835675323 approved.

2023-08-11 18:07 UTC, dune-eng commented
Workflow run id 5835675487 approved.

2023-08-11 18:17 UTC, dune-eng commented
Workflow run id 5835764240 approved.

2023-08-11 18:17 UTC, dune-eng commented
Workflow run id 5835764514 approved.

2023-08-11 18:34 UTC, dune-eng commented
Workflow run id 5835910781 approved.

2023-08-11 18:34 UTC, dune-eng commented
Workflow run id 5835910934 approved.

2023-08-11 18:46 UTC, dune-eng commented
Workflow run id 5836003932 approved.

2023-08-11 18:46 UTC, dune-eng commented
Workflow run id 5836003833 approved.

2023-08-11 19:01 UTC, dune-eng commented
Workflow run id 5836110514 approved.

2023-08-11 19:02 UTC, dune-eng commented
Workflow run id 5836110595 approved.

2023-08-11 19:26 UTC, dune-eng commented
Workflow run id 5836307372 approved.

2023-08-11 19:26 UTC, dune-eng commented
Workflow run id 5836307543 approved.

2023-08-11 19:37 UTC, dune-eng commented
Workflow run id 5836395843 approved.

2023-08-11 19:37 UTC, dune-eng commented
Workflow run id 5836395947 approved.

2023-08-11 19:47 UTC, dune-eng commented
Workflow run id 5836459897 approved.

2023-08-11 19:47 UTC, dune-eng commented
Workflow run id 5836460044 approved.

2023-08-11 20:21 UTC, dune-eng commented
Workflow run id 5836728423 approved.

2023-08-11 20:21 UTC, dune-eng commented
Workflow run id 5836728616 approved.

2023-08-11 20:37 UTC, dune-eng commented
Workflow run id 5836847350 approved.

2023-08-11 20:37 UTC, dune-eng commented
Workflow run id 5836847448 approved.

2023-08-11 21:00 UTC, dune-eng commented
Workflow run id 5836993795 approved.

2023-08-11 21:00 UTC, dune-eng commented
Workflow run id 5836993721 approved.

2023-08-11 21:04 UTC, dune-eng commented
Workflow run id 5837034318 approved.

2023-08-11 21:04 UTC, dune-eng commented
Workflow run id 5837034451 approved.

2023-08-11 21:10 UTC, dune-eng commented
Workflow run id 5837082643 approved.

2023-08-11 21:10 UTC, dune-eng commented
Workflow run id 5837082828 approved.

2023-08-11 21:39 UTC, dune-eng commented
Workflow run id 5837278309 approved.

2023-08-11 21:39 UTC, dune-eng commented
Workflow run id 5837278413 approved.

2023-08-11 21:56 UTC, dune-eng commented
Workflow run id 5837368246 approved.

2023-08-11 21:57 UTC, dune-eng commented
Workflow run id 5837368322 approved.

2023-08-11 22:17 UTC, Hosuke commented on models/zeroex/celo/zeroex_celo_schema.yml
> +      - check_seed_legacy:
```suggestion
      - check_seed:
```

2023-08-11 22:33 UTC, dune-eng commented
Workflow run id 5837621803 approved.

2023-08-11 22:33 UTC, dune-eng commented
Workflow run id 5837621956 approved.

2023-08-24 07:42 UTC, Hosuke requested changes
Minor suggestions, we can use `block_month` to improve storage efficiency.

2023-08-24 07:42 UTC, Hosuke commented on models/zeroex/celo/zeroex_celo_api_fills_deduped.sql
> +      , CAST(b.maker_token_amount_raw AS DECIMAL(38,0)) AS maker_token_amount_raw
Maybe without casting to decimal(38,0) is ok.
```suggestion
      , b.taker_token_amount_raw AS taker_token_amount_raw
      , b.maker_token_amount_raw AS maker_token_amount_raw
```

2023-08-24 07:42 UTC, Hosuke commented on models/zeroex/celo/zeroex_celo_api_fills_deduped.sql
> +        partition_by = ['block_date'],
We can add a new field `block_month` to use in partition:
```suggestion
        partition_by = ['block_month'],
```

2023-08-24 07:42 UTC, Hosuke commented on models/zeroex/celo/zeroex_celo_api_fills_deduped.sql
> +      , a.block_time
```suggestion
      , a.block_time
      , CAST(date_trunc('month', a.block_time) as DATE) as block_month, 
```

2023-08-24 07:42 UTC, Hosuke commented on models/zeroex/celo/zeroex_celo_api_fills.sql
> +        partition_by = ['block_date'],
We can use `block_month` here as well.
```suggestion
        partition_by = ['block_month'],
```

2023-08-31 21:49 UTC, dune-eng commented
Workflow run id 6042783289 approved.

2023-08-31 21:49 UTC, dune-eng commented
Workflow run id 6042783406 approved.

2023-08-31 21:51 UTC, dune-eng commented
Workflow run id 6042799595 approved.

2023-08-31 21:51 UTC, dune-eng commented
Workflow run id 6042799642 approved.

2023-08-31 22:00 UTC, dune-eng commented
Workflow run id 6042849258 approved.

2023-08-31 22:19 UTC, RantumBits reviewed
ty, all set

2023-08-31 22:21 UTC, dune-eng commented
Workflow run id 6043031610 approved.

2023-08-31 22:21 UTC, dune-eng commented
Workflow run id 6043031810 approved.

2023-08-31 22:40 UTC, dune-eng commented
Workflow run id 6043166550 approved.

2023-08-31 22:40 UTC, dune-eng commented
Workflow run id 6043166598 approved.

2023-08-31 22:54 UTC, dune-eng commented
Workflow run id 6043243353 approved.

2023-08-31 22:54 UTC, dune-eng commented
Workflow run id 6043243403 approved.

2023-09-01 01:01 UTC, dune-eng commented
Workflow run id 6044109756 approved.

2023-09-01 01:01 UTC, dune-eng commented
Workflow run id 6044109958 approved.

2023-09-01 02:26 UTC, RantumBits commented
thanks @Hosuke  - all set with these updates

2023-09-01 05:19 UTC, Hosuke commented on models/zeroex/celo/zeroex_celo_schema.yml
> +      - &maker
```suggestion
      - &block_date
        name: block_date
        description: "UTC event block date of each trade"
      - &block_month
        name: block_month
        description: "UTC event block month of each trade"
      - &maker
```

2023-09-01 05:20 UTC, Hosuke commented on models/zeroex/celo/zeroex_celo_schema.yml
> +      - &taker_symbol
```suggestion
      - *block_time
      - *block_month
      - &taker_symbol
```

2023-09-01 05:51 UTC, Hosuke reviewed
Hi @RantumBits,
it seems these two views do not have any records.
Is this expected?

[Sample zeroex_celo_api_fills](https://dune.com/queries/2989206)
[Sample zeroex_celo_api_fills_deduped](https://dune.com/queries/2989202)

2023-09-01 05:51 UTC, Hosuke commented on seeds/zeroex/celo/zeroex_celo_api_fills_deduped_sample.csv
Seems this seed is currently unused.
You can add a simple `check_seed` test in the schema to use this seed file.

2023-09-01 21:00 UTC, RantumBits commented on seeds/zeroex/celo/zeroex_celo_api_fills_deduped_sample.csv
No, that's not expected. Expecting results like test model: https://dune.com/queries/2755822

2023-09-01 21:29 UTC, dune-eng commented
Workflow run id 6054154764 approved.

2023-09-01 21:29 UTC, dune-eng commented
Workflow run id 6054154838 approved.

2023-09-04 08:44 UTC, Hosuke commented on seeds/zeroex/celo/zeroex_celo_api_fills_deduped_sample.csv
Do you have any idea how to fix this issue?

2023-09-05 16:48 UTC, RantumBits commented on seeds/zeroex/celo/zeroex_celo_api_fills_deduped_sample.csv
No, I have not been able to identify the problem yet

2023-09-05 16:51 UTC, dune-eng commented
Workflow run id 6087463512 approved.

2023-09-05 16:51 UTC, dune-eng commented
Workflow run id 6087463699 approved.

2023-09-05 22:45 UTC, dune-eng commented
Workflow run id 6090517827 approved.

2023-09-05 22:45 UTC, dune-eng commented
Workflow run id 6090517831 approved.

2023-09-05 22:46 UTC, dune-eng commented
Workflow run id 6090528287 approved.

2023-09-05 22:46 UTC, dune-eng commented
Workflow run id 6090528381 approved.

2023-09-05 23:01 UTC, dune-eng commented
Workflow run id 6090605896 approved.

2023-09-05 23:01 UTC, dune-eng commented
Workflow run id 6090605905 approved.

2023-09-06 15:45 UTC, RantumBits commented on seeds/zeroex/celo/zeroex_celo_api_fills_deduped_sample.csv
This is resolved. Had the wrong proxy contract address

2023-09-06 15:46 UTC, dune-eng commented
Workflow run id 6099365993 approved.

2023-09-06 16:53 UTC, Hosuke approved these changes
LGTM.✅
Thank you @RantumBits 

[Sample zeroex_celo_api_fills](https://dune.com/queries/2989206)
[Sample zeroex_celo_api_fills_deduped](https://dune.com/queries/2989202)

2023-09-06 20:05 UTC, jeff-dude approved these changes

2023-09-06 20:16 UTC, merged