ethereum pools lido liquidity migration
duneanalytics/spellbook pull request #3829
Opened 2023-07-21 14:55 UTC by ppclunghe

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-07-21 14:55 UTC, dune-eng commented
Workflow run id 5623675400 approved.

2023-07-21 15:26 UTC, dune-eng commented
Workflow run id 5623970362 approved.

2023-07-21 16:08 UTC, dune-eng commented
Workflow run id 5624332268 approved.

2023-07-21 16:53 UTC, dune-eng commented
Workflow run id 5624704206 approved.

2023-07-21 17:15 UTC, dune-eng commented
Workflow run id 5624881565 approved.

2023-07-21 17:28 UTC, dune-eng commented
Workflow run id 5624999381 approved.

2023-07-22 15:44 UTC, dune-eng commented
Workflow run id 5631466975 approved.

2023-07-22 16:17 UTC, dune-eng commented
Workflow run id 5631594318 approved.

2023-07-22 16:26 UTC, dune-eng commented
Workflow run id 5631630956 approved.

2023-07-22 17:11 UTC, dune-eng commented
Workflow run id 5631813361 approved.

2023-07-22 17:12 UTC, dune-eng commented
Workflow run id 5631816611 approved.

2023-07-23 11:28 UTC, dune-eng commented
Workflow run id 5636162462 approved.

2023-07-23 12:18 UTC, dune-eng commented
Workflow run id 5636367115 approved.

2023-07-23 12:23 UTC, dune-eng commented
Workflow run id 5636396032 approved.

2023-07-23 12:35 UTC, dune-eng commented
Workflow run id 5636458596 approved.

2023-07-23 15:53 UTC, dune-eng commented
Workflow run id 5637346131 approved.

2023-07-26 19:49 UTC, jeff-dude commented
@ppclunghe looks like this one may need broken out further? seems some dependencies are missing, since they aren't all merged yet

2023-07-26 20:45 UTC, ppclunghe commented
@jeff-dude yes, seems that upstream spell doesn't pass the tests because not all downstream spells are merged yet, can we merge it without tests passing? or what else we can do with it?

2023-07-26 22:04 UTC, jeff-dude commented on models/lido/lido_liquidity.sql
can you remove this one from this PR?
then we will follow-up with a PR for the cross-chain/cross-project spell once all others are merged and stable
CI should pass without this one here

2023-07-27 06:17 UTC, dune-eng commented
Workflow run id 5677204648 approved.

2023-07-27 06:24 UTC, dune-eng commented
Workflow run id 5677263857 approved.

2023-07-27 06:28 UTC, dune-eng commented
Workflow run id 5677288942 approved.

2023-07-27 06:32 UTC, dune-eng commented
Workflow run id 5677323537 approved.

2023-07-27 07:43 UTC, dune-eng commented
Workflow run id 5677885801 approved.

2023-07-27 08:01 UTC, dune-eng commented
Workflow run id 5678028518 approved.

2023-07-27 08:52 UTC, dune-eng commented
Workflow run id 5678514222 approved.

2023-07-27 08:58 UTC, dune-eng commented
Workflow run id 5678573622 approved.

2023-07-27 09:16 UTC, ppclunghe commented on models/lido/lido_liquidity.sql
I removed upstream spell, CI passed

2023-07-27 21:05 UTC, jeff-dude requested changes
apologies for any confusion, but see comments below. the idea is that the non-legacy file will sit in the repo with no modifications, until a follow-up PR later when ready, where you'll apply the dunesql tag and such. without tags, it'll just sit there, which is fine.

2023-07-27 21:05 UTC, jeff-dude commented on models/lido/lido_liquidity.sql
this file should remain in the repo, but just don't make any modifications on it so that it doesn't appear in the PR here

2023-07-27 21:05 UTC, jeff-dude commented on models/lido/lido_schema.yml
similar, you can keep this in the schema file. it'll be there and ready when you modify the cross-chain spell in follow-up PR soon

2023-07-27 21:17 UTC, ppclunghe commented on models/lido/lido_liquidity.sql
I have tried to keep this file non-legacy lido_liquidity file without tag, but test doesn't pass in this way
https://github.com/duneanalytics/spellbook/actions/runs/5677885801/job/15387001473#step:10:14
so I decided to delete this file to get tests passed
am I right that once downstreem PRs will be merged I can re-create lido_liquidity ?

2023-07-27 21:32 UTC, jeff-dude commented on models/lido/lido_liquidity.sql
but if the file is left in the repo, and not modified in your branch, it shouldn't show up in the PR, therefore it won't be checked in that `check tags` step. we want it to have no tag for now, until it's ready (after this PR and all other liquidity ones)

2023-07-27 21:38 UTC, ppclunghe commented on models/lido/lido_liquidity.sql
ok, I am going to close this PR and create the new one where lido_liquidity file will not be modified

2023-07-28 12:49 UTC, closed without merging