Migrate Chainlink PriceFeeds to DuneSQL
duneanalytics/spellbook pull request #3832
Opened 2023-07-21 18:41 UTC by anon-r-7

- Migrate Chainlink Price Feeds to DuneSQL

@jeff-dude This is the first of potentially a few PRs for Chainlink as we discussed. This focuses just on migrating the Chainlink model to DuneSQL. I've backtested the data from this PR against the legacy and everything lines up. A few major changes were needed due to some functions no longer being supported.

You'll notice I've renamed the oracle_addresses files to be prefixed with `price_feed`. This is to maintain clear structure given we are going to be adding many more types of metrics for Chainlink in the future, the first of which being OCR, followed by FM, Keepers, Automation, CCIP and LLO. Each set of queries that support a given metric should be prefixed accordingly. 

In a followup PR, we will also be adding extending the price feed models by (a) updating the oracle addresses to include all known feeds, and (b) adding support for all evm chains. Here's a roadmap for PRs you should expect to see from us between today and the next few weeks

- PR#1: PriceFeed DuneSQL Migration (code complete, PR submitted)
- PR#2: OCR for all EVM chains (code complete, waiting to submit PR until this one is finished)
- PR#3: Extend PriceFeeds (WIP)
- PR#4: FM for all EVM chains
- PR#5: Keeper for all EVM chains

2023-07-21 18:42 UTC, dune-eng commented
Workflow run id 5625568088 approved.

2023-07-25 20:23 UTC, jeff-dude requested changes
submitting initial feedback on bnb and cross-chain spells.

assuming other chains are similar.

2023-07-25 20:23 UTC, jeff-dude commented on models/chainlink/bnb/chainlink_bnb_price_feeds.sql
> +    alias='price_feeds',
please keep the alias macro here:
`alias = alias('price_feeds'),`

notice the non-legacy files don't pass the second param in, as it defaults to false. while the legacy files pass in the second flag and set to true.

this is needed for our orchestration to configure behind-the-scenes

2023-07-25 20:23 UTC, jeff-dude commented on models/chainlink/bnb/chainlink_bnb_price_feeds.sql
> +    alias='price_feeds',
this will apply universally, only commenting here

2023-07-25 20:23 UTC, jeff-dude commented on models/chainlink/bnb/chainlink_bnb_price_feeds.sql
> +        cast(date_trunc('day', l.block_time) as date) as block_date,
if `block_date` is used solely for the partition, we are looking to universally change this to a higher level of granularity, `block_month`.

can you update to be `'month'` instead, then rename column and partition in config to `block_month`?

if you use `block_date` for more than the partition, then you can simply add new column instead. in fact, that may be safer if downstream queries on the app depend on this column for whatever reason.

2023-07-25 20:23 UTC, jeff-dude commented on models/chainlink/bnb/chainlink_bnb_price_feeds.sql
> +        cast(date_trunc('day', l.block_time) as date) as block_date,
this would also apply universally, only commenting here

2023-07-25 20:23 UTC, jeff-dude commented on models/chainlink/bnb/chainlink_bnb_schema.yml
> +    # Tempoarily Disable, test_data not found.
we can re-enable this by forcing an update to the seed file (`chainlink_get_price_seed.sql`), so it pushes to this PR.

then for the columns listed, both match and check, you can create a schema file in the seeds directory path which calls out their datatype and applies a `tag:dunesql`. here is an example: 
https://github.com/duneanalytics/spellbook/blob/main/seeds/_sector/nft/_schema.yml#L1-L15

2023-07-25 20:23 UTC, jeff-dude commented on models/chainlink/bnb/chainlink_bnb_schema.yml
> +    # Tempoarily Disable, test_data not found.
you only need to add columns which leverage unique dunesql data types typically (varbinary, uint256, etc)

2023-07-26 17:51 UTC, dune-eng commented
Workflow run id 5672070007 approved.

2023-07-26 18:24 UTC, jeff-dude commented on seeds/chainlink/_schema.yml
> +  - name: chainlink_bnb_price_feeds
this must be the name of the seed file, not model name -- is that set correctly?

2023-07-26 18:36 UTC, dune-eng commented
Workflow run id 5672471744 approved.

2023-07-26 19:01 UTC, dune-eng commented
Workflow run id 5672673679 approved.

2023-07-26 19:29 UTC, dune-eng commented
Workflow run id 5672918000 approved.

2023-07-26 19:48 UTC, dune-eng commented
Workflow run id 5673068367 approved.

2023-07-26 22:07 UTC, jeff-dude commented on models/chainlink/bnb/chainlink_bnb_price_feeds.sql
> +    partition_by=['block_date'],
looks like you built `block_month`, but forgot the partition on some?

2023-07-26 22:09 UTC, jeff-dude commented
one final comment above, but otherwise it's looking good!
thanks again for the patience and help pushing these along.

2023-07-26 22:50 UTC, dune-eng commented
Workflow run id 5674456500 approved.

2023-07-27 20:41 UTC, jeff-dude approved these changes
let's give this a go!

one last thank you for the patience and working with us here to keep the migration clean. look forward to seeing your further contribution.

2023-07-27 20:44 UTC, merged

2023-08-28 16:39 UTC, MSilb7 commented
Update here: This broke some downstream queries because `underlying_token_address` column was dropped. Is it possible to edit the spell to re-add this column in? @anon-r-7

2023-08-28 16:43 UTC, jeff-dude commented
also tagging @AnonJon as another chainlink spell contributor

2023-08-28 17:05 UTC, MSilb7 commented
> > Update here: This broke some downstream queries because `underlying_token_address` column was dropped. Is it possible to edit the spell to re-add this column in? @anon-r-7
> 
> Hey mslib. That particular field was removed because it was not relevant in 99.9999% of use cases. We've refactored this such that the equivalent prices are calculated without requiring the manual work to find this address. Reason for this decision is that it wasn't practical to find, and keep up to date, this address manually for every feed on every network. And in fact, for some of the feeds, the underlying address was incorrect. This is more of a data availability and verification problem then it is a code problem. The trade off decision here was (1) stick to keeping it and have support for just a few feeds on 3 chains or (2) provide support for all feeds on all chains. Given that in many cases it's not relevant we went with option two. The benefit is it no longer requires manual work to add or keep up to date these feeds, a script runs that can do all this programmatically say once a month and then create a PR. I recommend updating downstream tables accordingly.
> 
> We did think through the use cases for this and therefore added columns for base and quote so the user could join based on some pair of they wanted to without having the underlying address in the table (or other such use cases).

got it, yeah maybe i'll just remove this from queries. the old logic for token prices was:

1. Check in prices.usd
2. If doesn't exist, check in Chainlink feeds.
3. If doesn't exist, check in dex trades prices (high error rate).

So I can just cut out the Chainlink step.