Init Base NFT Folder
duneanalytics/spellbook pull request #3897
Opened 2023-07-30 15:33 UTC by MSilb7

Copy Optimism NFT -> Base.

Find and replace Optimism for Base. This is a prereq for https://github.com/duneanalytics/spellbook/pull/3896

2023-07-30 15:33 UTC, dune-eng commented
Workflow run id 5707035730 approved.

2023-07-30 15:34 UTC, dune-eng commented
Workflow run id 5707038126 approved.

2023-07-30 16:08 UTC, dune-eng commented
Workflow run id 5707164842 approved.

2023-07-30 16:11 UTC, dune-eng commented
Workflow run id 5707181329 approved.

2023-07-30 16:17 UTC, dune-eng commented
Workflow run id 5707207674 approved.

2023-07-30 16:24 UTC, dune-eng commented
Workflow run id 5707239505 approved.

2023-07-30 16:32 UTC, dune-eng commented
Workflow run id 5707272529 approved.

2023-07-30 16:41 UTC, dune-eng commented
Workflow run id 5707310609 approved.

2023-07-30 16:41 UTC, dune-eng commented
Workflow run id 5707311811 approved.

2023-07-30 16:46 UTC, dune-eng commented
Workflow run id 5707326256 approved.

2023-07-30 16:50 UTC, dune-eng commented
Workflow run id 5707340791 approved.

2023-07-30 16:56 UTC, dune-eng commented
Workflow run id 5707362374 approved.

2023-07-30 17:02 UTC, dune-eng commented
Workflow run id 5707383475 approved.

2023-07-30 17:16 UTC, dune-eng commented
Workflow run id 5707456301 approved.

2023-07-30 17:23 UTC, dune-eng commented
Workflow run id 5707496296 approved.

2023-07-30 17:37 UTC, dune-eng commented
Workflow run id 5707551716 approved.

2023-07-30 17:42 UTC, MSilb7 commented
Do these tag errors mean I'm forced to migrate all upstream spells to dunesql? Same errors as https://github.com/duneanalytics/spellbook/pull/3898 & https://github.com/duneanalytics/spellbook/pull/3842

2023-07-30 22:40 UTC, dune-eng commented
Workflow run id 5708745889 approved.

2023-07-30 22:42 UTC, dune-eng commented
Workflow run id 5708750811 approved.

2023-07-30 22:51 UTC, dune-eng commented
Workflow run id 5708780900 approved.

2023-07-30 22:53 UTC, dune-eng commented
Workflow run id 5708787043 approved.

2023-07-30 22:59 UTC, dune-eng commented
Workflow run id 5708801961 approved.

2023-07-30 23:14 UTC, dune-eng commented
Workflow run id 5708878776 approved.

2023-07-30 23:18 UTC, dune-eng commented
Workflow run id 5708896304 approved.

2023-07-30 23:29 UTC, dune-eng commented
Workflow run id 5708935720 approved.

2023-07-30 23:35 UTC, dune-eng commented
Workflow run id 5708960688 approved.

2023-07-30 23:40 UTC, dune-eng commented
Workflow run id 5708982253 approved.

2023-07-30 23:41 UTC, dune-eng commented
Workflow run id 5708985132 approved.

2023-07-30 23:49 UTC, dune-eng commented
Workflow run id 5709010441 approved.

2023-07-30 23:56 UTC, dune-eng commented
Workflow run id 5709030372 approved.

2023-07-31 00:11 UTC, dune-eng commented
Workflow run id 5709108612 approved.

2023-07-31 00:24 UTC, dune-eng commented
Workflow run id 5709180919 approved.

2023-07-31 00:36 UTC, dune-eng commented
Workflow run id 5709247083 approved.

2023-07-31 00:38 UTC, dune-eng commented
Workflow run id 5709262179 approved.

2023-07-31 00:44 UTC, dune-eng commented
Workflow run id 5709290292 approved.

2023-07-31 00:45 UTC, dune-eng commented
Workflow run id 5709299705 approved.

2023-07-31 01:01 UTC, dune-eng commented
Workflow run id 5709388845 approved.

2023-07-31 11:39 UTC, dune-eng commented
Workflow run id 5714204053 approved.

2023-07-31 11:39 UTC, dune-eng commented
Workflow run id 5714204213 approved.

2023-07-31 18:26 UTC, dune-eng commented
Workflow run id 5718255819 approved.

2023-07-31 18:26 UTC, dune-eng commented
Workflow run id 5718255805 approved.

2023-07-31 18:55 UTC, dune-eng commented
Workflow run id 5718508981 approved.

2023-07-31 18:55 UTC, dune-eng commented
Workflow run id 5718508989 approved.

2023-07-31 19:00 UTC, dune-eng commented
Workflow run id 5718555795 approved.

2023-07-31 19:00 UTC, dune-eng commented
Workflow run id 5718555830 approved.

2023-07-31 19:03 UTC, dune-eng commented
Workflow run id 5718585494 approved.

2023-07-31 19:05 UTC, dune-eng commented
Workflow run id 5718601693 approved.

2023-07-31 19:05 UTC, dune-eng commented
Workflow run id 5718601678 approved.

2023-07-31 21:42 UTC, dune-eng commented
Workflow run id 5719923810 approved.

2023-07-31 21:42 UTC, dune-eng commented
Workflow run id 5719923877 approved.

2023-08-01 11:54 UTC, dune-eng commented
Workflow run id 5726394669 approved.

2023-08-01 11:54 UTC, dune-eng commented
Workflow run id 5726394921 approved.

2023-08-01 11:54 UTC, dune-eng commented
Workflow run id 5726396310 approved.

2023-08-01 11:54 UTC, dune-eng commented
Workflow run id 5726396534 approved.

2023-08-01 11:56 UTC, dune-eng commented
Workflow run id 5726410719 approved.

2023-08-01 11:56 UTC, dune-eng commented
Workflow run id 5726410592 approved.

2023-08-01 12:01 UTC, dune-eng commented
Workflow run id 5726461457 approved.

2023-08-01 12:02 UTC, dune-eng commented
Workflow run id 5726461957 approved.

2023-08-01 12:20 UTC, dune-eng commented
Workflow run id 5726661544 approved.

2023-08-01 12:20 UTC, dune-eng commented
Workflow run id 5726661666 approved.

2023-08-01 15:00 UTC, dune-eng commented
Workflow run id 5728452016 approved.

2023-08-01 15:00 UTC, dune-eng commented
Workflow run id 5728451864 approved.

2023-08-02 00:16 UTC, dune-eng commented
Workflow run id 5733150004 approved.

2023-08-02 00:16 UTC, dune-eng commented
Workflow run id 5733149952 approved.

2023-08-03 18:04 UTC, jeff-dude requested changes

2023-08-03 18:04 UTC, jeff-dude commented on models/tokens/base/tokens_base_nft_curated_legacy.sql
can we use the dummy approach here? no need to build on spark, as it's a new spell

2023-08-03 18:04 UTC, jeff-dude commented on models/tokens/base/tokens_base_nft_legacy.sql
can we use the dummy approach here? no need to build on spark, as it's a new spell

2023-08-03 18:04 UTC, jeff-dude commented on models/tokens/base/tokens_base_nft_standards_legacy.sql
can we use the dummy approach here? no need to build on spark, as it's a new spell

2023-08-03 18:04 UTC, jeff-dude commented on models/tokens/base/tokens_base_nft_curated.sql
> +  contract_address, name, cast(NULL as varchar) as symbol
you'll never use symbol? or will edit later?

2023-08-07 16:30 UTC, MSilb7 commented on models/tokens/base/tokens_base_nft_standards_legacy.sql
editing

2023-08-07 16:31 UTC, MSilb7 commented on models/tokens/base/tokens_base_nft_curated_legacy.sql
done

2023-08-07 16:33 UTC, MSilb7 commented
I have read the CLA Document and I hereby sign the CLA

2023-08-07 16:33 UTC, dune-eng commented
Workflow run id 5787624820 approved.

2023-08-07 16:33 UTC, dune-eng commented
Workflow run id 5787626975 approved.

2023-08-07 16:33 UTC, dune-eng commented
Workflow run id 5787626896 approved.

2023-08-07 16:36 UTC, MSilb7 commented
I have read the CLA Document and I hereby sign the CLA

2023-08-07 16:37 UTC, dune-eng commented
Workflow run id 5787664487 approved.

2023-08-07 16:37 UTC, dune-eng commented
Workflow run id 5787664625 approved.

2023-08-07 17:42 UTC, MSilb7 commented
I have read the CLA Document and I hereby sign the CLA

2023-08-07 17:42 UTC, MSilb7 commented
recheck

2023-08-07 17:47 UTC, MSilb7 commented
recheck

2023-08-07 18:37 UTC, jeff-dude requested changes

2023-08-07 18:37 UTC, jeff-dude commented on models/tokens/base/tokens_base_nft_legacy.sql
we can continue to simplify here. no need to mimic the logic / joins between two legacy files. rather, just continue to use `select 1` on all legacy files

if that means you can simply the others too (`tokens_base_nft_standards_legacy`, `tokens_base_nft_curated_legacy`) to write less columns, that is good too. i assume you had added multiple columns in those to help the joins here. that won't be needed once this one is just `select 1` again

2023-08-07 18:37 UTC, jeff-dude commented on models/tokens/base/tokens_base_nft_legacy.sql
can also simplify config block to just schema/alias/tags. as it stands now, with table materialization, it'll run daily when we don't need it to. should also avoid exposing in data explorer.

2023-08-07 19:30 UTC, MSilb7 commented on models/tokens/base/tokens_base_nft_legacy.sql
updating

2023-08-07 19:31 UTC, dune-eng commented
Workflow run id 5789137522 approved.

2023-08-07 19:31 UTC, dune-eng commented
Workflow run id 5789137533 approved.

2023-08-07 19:46 UTC, jeff-dude approved these changes

2023-08-08 13:44 UTC, merged