ERC20 All Tokens Table + Transfers + Chains Macro
duneanalytics/spellbook pull request #3898
Opened 2023-07-30 15:37 UTC by MSilb7

This adds a table for "all" ERC20 tokens (not just ones we've identified) and a total chains ERC20 transfers table with other relevant information.

This is a prereq for https://github.com/duneanalytics/spellbook/pull/3896 since we need to be able to identify what is and isn't a token contract.

This also fixes the chains macro (duped in #3896 as well)

2023-07-30 15:38 UTC, dune-eng commented
Workflow run id 5707055217 approved.

2023-07-30 15:39 UTC, MSilb7 commented
The Macro created here can be used in the https://github.com/duneanalytics/spellbook/pull/3653 upgrade/simplification as well.

2023-07-30 15:39 UTC, dune-eng commented
Workflow run id 5707057502 approved.

2023-07-30 15:41 UTC, dune-eng commented
Workflow run id 5707063252 approved.

2023-07-30 16:09 UTC, dune-eng commented
Workflow run id 5707169474 approved.

2023-07-30 16:14 UTC, dune-eng commented
Workflow run id 5707196831 approved.

2023-07-30 16:21 UTC, dune-eng commented
Workflow run id 5707227603 approved.

2023-07-30 16:36 UTC, dune-eng commented
Workflow run id 5707292458 approved.

2023-07-30 16:48 UTC, dune-eng commented
Workflow run id 5707332875 approved.

2023-07-30 16:55 UTC, dune-eng commented
Workflow run id 5707359321 approved.

2023-07-30 16:56 UTC, dune-eng commented
Workflow run id 5707361124 approved.

2023-07-30 16:58 UTC, dune-eng commented
Workflow run id 5707368790 approved.

2023-07-30 17:14 UTC, MSilb7 commented
Tags issue carrying over here as well. the base spells are all net new, so dependency errors are odd.

2023-07-30 17:15 UTC, dune-eng commented
Workflow run id 5707453185 approved.

2023-07-30 17:22 UTC, MSilb7 commented
> Tags issue carrying over here as well. the base spells are all net new, so dependency errors are odd.

Yeah, this `transfers_base_erc20` model that's throwing tags errors only depends on itself, and there's a legacy model.

May be a test issue?

2023-07-30 17:23 UTC, dune-eng commented
Workflow run id 5707493662 approved.

2023-07-30 17:34 UTC, dune-eng commented
Workflow run id 5707536813 approved.

2023-07-30 22:53 UTC, dune-eng commented
Workflow run id 5708788187 approved.

2023-07-30 23:04 UTC, dune-eng commented
Workflow run id 5708828256 approved.

2023-07-30 23:17 UTC, dune-eng commented
Workflow run id 5708890517 approved.

2023-07-30 23:31 UTC, dune-eng commented
Workflow run id 5708940960 approved.

2023-07-30 23:41 UTC, dune-eng commented
Workflow run id 5708984218 approved.

2023-07-30 23:50 UTC, dune-eng commented
Workflow run id 5709013523 approved.

2023-07-30 23:55 UTC, dune-eng commented
Workflow run id 5709029395 approved.

2023-07-31 00:11 UTC, dune-eng commented
Workflow run id 5709106454 approved.

2023-07-31 00:28 UTC, dune-eng commented
Workflow run id 5709202546 approved.

2023-07-31 00:32 UTC, dune-eng commented
Workflow run id 5709222722 approved.

2023-07-31 00:40 UTC, dune-eng commented
Workflow run id 5709271823 approved.

2023-07-31 01:01 UTC, MSilb7 commented
spell initial build times out, but it should run fine.

2023-07-31 11:39 UTC, dune-eng commented
Workflow run id 5714204598 approved.

2023-07-31 11:39 UTC, dune-eng commented
Workflow run id 5714204671 approved.

2023-07-31 18:29 UTC, dune-eng commented
Workflow run id 5718287601 approved.

2023-07-31 19:01 UTC, dune-eng commented
Workflow run id 5718560003 approved.

2023-07-31 19:01 UTC, dune-eng commented
Workflow run id 5718559934 approved.

2023-07-31 21:48 UTC, dune-eng commented
Workflow run id 5719968490 approved.

2023-07-31 21:48 UTC, dune-eng commented
Workflow run id 5719968468 approved.

2023-07-31 21:52 UTC, dune-eng commented
Workflow run id 5719995236 approved.

2023-07-31 21:52 UTC, dune-eng commented
Workflow run id 5719995218 approved.

2023-07-31 21:53 UTC, dune-eng commented
Workflow run id 5719998406 approved.

2023-07-31 21:53 UTC, dune-eng commented
Workflow run id 5719998422 approved.

2023-08-01 11:57 UTC, dune-eng commented
Workflow run id 5726424362 approved.

2023-08-01 11:57 UTC, dune-eng commented
Workflow run id 5726424525 approved.

2023-08-01 12:02 UTC, dune-eng commented
Workflow run id 5726467771 approved.

2023-08-01 12:02 UTC, dune-eng commented
Workflow run id 5726467872 approved.

2023-08-01 12:04 UTC, dune-eng commented
Workflow run id 5726494862 approved.

2023-08-01 12:04 UTC, dune-eng commented
Workflow run id 5726495030 approved.

2023-08-01 12:20 UTC, dune-eng commented
Workflow run id 5726654929 approved.

2023-08-01 12:45 UTC, dune-eng commented
Workflow run id 5726922750 approved.

2023-08-01 15:00 UTC, dune-eng commented
Workflow run id 5728451312 approved.

2023-08-01 15:00 UTC, dune-eng commented
Workflow run id 5728451556 approved.

2023-08-01 19:57 UTC, jeff-dude commented on macros/public/all_evm_testnet_chains.sql
this macro can be stored in the same sql file as the mainnet macro. as long as macro names remain the same and unique, we can group them in same file and then rename file to something more generic. there should be other examples of this in macros you can see.

2023-08-01 20:02 UTC, jeff-dude commented on macros/public/all_evm_mainnets_testnets_chains.sql
ditto to this macro, all can be one file

2023-08-01 20:28 UTC, jeff-dude commented on profiles.yml
this seems accidental -- can you revert?

2023-08-01 20:33 UTC, jeff-dude commented on models/transfers/transfers_erc20.md
if we already have all the blockchain-specific erc20 transfers spells, why are we reading from the sources again here in a loop? i don't think we'll ever be able to build this as-is. we'll need to do the normal blockchain version spell for each, then a union of them after they are materialized

2023-08-01 20:33 UTC, jeff-dude commented on models/transfers/transfers_erc20.md
can we remove all markdown files and just push them to another branch on your fork, save for later? this will take some more consideration

2023-08-01 20:44 UTC, dune-eng commented
Workflow run id 5731662500 approved.

2023-08-01 20:44 UTC, dune-eng commented
Workflow run id 5731662677 approved.

2023-08-01 20:45 UTC, dune-eng commented
Workflow run id 5731675930 approved.

2023-08-01 20:45 UTC, dune-eng commented
Workflow run id 5731676048 approved.

2023-08-01 22:49 UTC, dune-eng commented
Workflow run id 5732606979 approved.

2023-08-01 22:49 UTC, dune-eng commented
Workflow run id 5732607089 approved.

2023-08-02 00:16 UTC, dune-eng commented
Workflow run id 5733149729 approved.

2023-08-02 00:16 UTC, dune-eng commented
Workflow run id 5733149728 approved.

2023-08-02 11:17 UTC, MSilb7 commented on models/transfers/transfers_erc20.md
a benefit here would be to not have to copy and paste the same spell for every chain (i.e. some are missing from the chain-specific folders). But yeah I'll port out to a new branch.

As a general thought - I'd be a fan of having chain names in a macro, and we run that through spells, versus having folders for each chain (a lot of overhead to manage).

2023-08-02 11:19 UTC, dune-eng commented
Workflow run id 5738160429 approved.

2023-08-02 11:19 UTC, dune-eng commented
Workflow run id 5738160500 approved.

2023-08-02 11:19 UTC, dune-eng commented
Workflow run id 5738165329 approved.

2023-08-02 11:19 UTC, dune-eng commented
Workflow run id 5738165479 approved.

2023-08-02 11:20 UTC, MSilb7 commented on models/transfers/transfers_erc20.md
maybe for now we can add the missing chains from erc20 transfers (Base, Gnosis, Goerli)

2023-08-02 11:26 UTC, MSilb7 commented on models/transfers/transfers_erc20.md
The purpose for the overall transfers table and token was replaced with hitting the transfers event table every time in https://github.com/duneanalytics/spellbook/pull/3896 - so extended really isn't necessary yet (although it's easy to copy and paste

(So we don't have to create tables that collide with future token automation)

2023-08-02 11:31 UTC, dune-eng commented
Workflow run id 5738260947 approved.

2023-08-02 15:51 UTC, dune-eng commented
Workflow run id 5741013449 approved.

2023-08-02 15:51 UTC, dune-eng commented
Workflow run id 5741013282 approved.

2023-08-02 20:31 UTC, dune-eng commented
Workflow run id 5743518335 approved.

2023-08-02 20:31 UTC, dune-eng commented
Workflow run id 5743518531 approved.

2023-08-03 17:49 UTC, jeff-dude requested changes

2023-08-03 17:49 UTC, jeff-dude commented on models/transfers/base/transfers_base_eth_legacy.sql
why do we need to build this out fully on spark, rather than a dummy approach similar to other legacy in this PR?

2023-08-07 16:49 UTC, MSilb7 commented on models/transfers/base/transfers_base_eth_legacy.sql
changing. just a leftover from the source folder

2023-08-07 16:49 UTC, MSilb7 commented on models/transfers/base/transfers_base_schema.yml
> +      - name: unique_transfer_id
adding

2023-08-07 16:51 UTC, dune-eng commented
Workflow run id 5787778745 approved.

2023-08-07 16:51 UTC, dune-eng commented
Workflow run id 5787778947 approved.

2023-08-07 17:46 UTC, dune-eng commented
Workflow run id 5788264041 approved.

2023-08-07 17:46 UTC, dune-eng commented
Workflow run id 5788264167 approved.

2023-08-07 17:47 UTC, dune-eng commented
Workflow run id 5788270583 approved.

2023-08-07 17:47 UTC, dune-eng commented
Workflow run id 5788270422 approved.

2023-08-07 18:55 UTC, jeff-dude approved these changes

2023-08-07 18:55 UTC, merged