lido liquidity test incremental model
duneanalytics/spellbook pull request #3919
Opened 2023-08-01 20:34 UTC by ppclunghe

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-08-01 20:35 UTC, dune-eng commented
Workflow run id 5731595489 approved.

2023-08-01 20:35 UTC, dune-eng commented
Workflow run id 5731595621 approved.

2023-08-01 20:37 UTC, dune-eng commented
Workflow run id 5731610834 approved.

2023-08-01 20:37 UTC, dune-eng commented
Workflow run id 5731610943 approved.

2023-08-01 20:37 UTC, ppclunghe commented
I have read the CLA Document and I hereby sign the CLA

2023-08-01 20:57 UTC, dune-eng commented
Workflow run id 5731768598 approved.

2023-08-01 20:57 UTC, dune-eng commented
Workflow run id 5731768698 approved.

2023-08-01 21:11 UTC, dune-eng commented
Workflow run id 5731892170 approved.

2023-08-01 21:11 UTC, dune-eng commented
Workflow run id 5731892167 approved.

2023-08-01 22:00 UTC, dune-eng commented
Workflow run id 5732249719 approved.

2023-08-01 22:06 UTC, dune-eng commented
Workflow run id 5732300881 approved.

2023-08-01 22:06 UTC, dune-eng commented
Workflow run id 5732300886 approved.

2023-08-01 22:14 UTC, dune-eng commented
Workflow run id 5732360290 approved.

2023-08-01 22:14 UTC, dune-eng commented
Workflow run id 5732360361 approved.

2023-08-01 22:29 UTC, dune-eng commented
Workflow run id 5732480176 approved.

2023-08-01 22:29 UTC, dune-eng commented
Workflow run id 5732480272 approved.

2023-08-02 09:16 UTC, dune-eng commented
Workflow run id 5737002313 approved.

2023-08-02 09:33 UTC, dune-eng commented
Workflow run id 5737168359 approved.

2023-08-02 09:33 UTC, dune-eng commented
Workflow run id 5737168557 approved.

2023-08-02 09:54 UTC, dune-eng commented
Workflow run id 5737357200 approved.

2023-08-02 09:54 UTC, dune-eng commented
Workflow run id 5737357323 approved.

2023-08-02 20:15 UTC, dune-eng commented
Workflow run id 5743383852 approved.

2023-08-02 20:15 UTC, dune-eng commented
Workflow run id 5743383854 approved.

2023-08-02 20:31 UTC, dune-eng commented
Workflow run id 5743520842 approved.

2023-08-02 20:31 UTC, dune-eng commented
Workflow run id 5743520895 approved.

2023-08-02 21:27 UTC, dune-eng commented
Workflow run id 5743966318 approved.

2023-08-02 21:27 UTC, dune-eng commented
Workflow run id 5743966329 approved.

2023-08-02 21:58 UTC, dune-eng commented
Workflow run id 5744176437 approved.

2023-08-02 21:58 UTC, dune-eng commented
Workflow run id 5744176363 approved.

2023-08-06 15:18 UTC, dune-eng commented
Workflow run id 5777361754 approved.

2023-08-06 15:18 UTC, dune-eng commented
Workflow run id 5777361760 approved.

2023-08-06 15:33 UTC, dune-eng commented
Workflow run id 5777424184 approved.

2023-08-06 15:33 UTC, dune-eng commented
Workflow run id 5777424177 approved.

2023-08-06 15:44 UTC, dune-eng commented
Workflow run id 5777463689 approved.

2023-08-06 15:44 UTC, dune-eng commented
Workflow run id 5777463688 approved.

2023-08-06 16:09 UTC, dune-eng commented
Workflow run id 5777557967 approved.

2023-08-06 16:09 UTC, dune-eng commented
Workflow run id 5777557908 approved.

2023-08-06 16:41 UTC, dune-eng commented
Workflow run id 5777703006 approved.

2023-08-06 16:41 UTC, dune-eng commented
Workflow run id 5777703055 approved.

2023-08-06 21:53 UTC, dune-eng commented
Workflow run id 5778944816 approved.

2023-08-06 21:53 UTC, dune-eng commented
Workflow run id 5778944781 approved.

2023-08-08 08:54 UTC, dune-eng commented
Workflow run id 5794844536 approved.

2023-08-08 08:54 UTC, dune-eng commented
Workflow run id 5794844656 approved.

2023-08-08 09:20 UTC, dune-eng commented
Workflow run id 5795120040 approved.

2023-08-08 09:20 UTC, dune-eng commented
Workflow run id 5795119912 approved.

2023-08-10 22:10 UTC, dune-eng commented
Workflow run id 5826578809 approved.

2023-08-10 22:10 UTC, dune-eng commented
Workflow run id 5826578868 approved.

2023-08-10 22:22 UTC, dune-eng commented
Workflow run id 5826674297 approved.

2023-08-10 22:22 UTC, dune-eng commented
Workflow run id 5826674315 approved.

2023-08-10 22:33 UTC, dune-eng commented
Workflow run id 5826766444 approved.

2023-08-10 22:33 UTC, dune-eng commented
Workflow run id 5826766503 approved.

2023-08-11 07:25 UTC, dune-eng commented
Workflow run id 5830026175 approved.

2023-08-11 08:13 UTC, dune-eng commented
Workflow run id 5830393632 approved.

2023-08-11 08:13 UTC, dune-eng commented
Workflow run id 5830393607 approved.

2023-08-11 09:15 UTC, dune-eng commented
Workflow run id 5830923377 approved.

2023-08-11 09:15 UTC, dune-eng commented
Workflow run id 5830923522 approved.

2023-08-11 13:35 UTC, dune-eng commented
Workflow run id 5833232579 approved.

2023-08-11 13:35 UTC, dune-eng commented
Workflow run id 5833232728 approved.

2023-08-11 13:47 UTC, dune-eng commented
Workflow run id 5833332420 approved.

2023-08-11 14:26 UTC, dune-eng commented
Workflow run id 5833726796 approved.

2023-08-11 14:26 UTC, dune-eng commented
Workflow run id 5833726769 approved.

2023-08-11 14:58 UTC, dune-eng commented
Workflow run id 5834027342 approved.

2023-08-11 16:25 UTC, dune-eng commented
Workflow run id 5834830030 approved.

2023-08-11 16:25 UTC, dune-eng commented
Workflow run id 5834830009 approved.

2023-08-11 17:32 UTC, dune-eng commented
Workflow run id 5835404799 approved.

2023-08-11 17:32 UTC, dune-eng commented
Workflow run id 5835404863 approved.

2023-08-11 18:20 UTC, dune-eng commented
Workflow run id 5835788149 approved.

2023-08-11 18:20 UTC, dune-eng commented
Workflow run id 5835788328 approved.

2023-08-11 18:36 UTC, dune-eng commented
Workflow run id 5835933774 approved.

2023-08-11 18:36 UTC, dune-eng commented
Workflow run id 5835933773 approved.

2023-08-11 18:49 UTC, dune-eng commented
Workflow run id 5836023389 approved.

2023-08-11 18:49 UTC, dune-eng commented
Workflow run id 5836023402 approved.

2023-08-13 10:37 UTC, dune-eng commented
Workflow run id 5846835817 approved.

2023-08-13 10:37 UTC, dune-eng commented
Workflow run id 5846835818 approved.

2023-08-13 11:50 UTC, dune-eng commented
Workflow run id 5847118901 approved.

2023-08-13 11:50 UTC, dune-eng commented
Workflow run id 5847118897 approved.

2023-08-13 20:54 UTC, dune-eng commented
Workflow run id 5849485853 approved.

2023-08-13 20:54 UTC, dune-eng commented
Workflow run id 5849485890 approved.

2023-08-13 21:16 UTC, dune-eng commented
Workflow run id 5849586827 approved.

2023-08-13 21:16 UTC, dune-eng commented
Workflow run id 5849586842 approved.

2023-08-15 21:13 UTC, jeff-dude requested changes
i focused only on `lido_liquidity_arbitrum_balancer_pools.sql` for initial review, assuming all others (other than final cross-chain spell) follow a similar pattern of changes. i left a few minor notes in review.

overall, the idea is:
- each upstream spell is an incremental model, which would then be refreshed hourly
- the final cross-chain spell is a view, which starts with the dates CTE to get a running list of dates since project start, then left joins the upstream spells to get up-to-date data on the incremental refresh schedule

have you been able to thoroughly test the output CI tables to ensure the data is as you expected in the new setup?

2023-08-15 21:13 UTC, jeff-dude commented on models/lido/liquidity/arbitrum/lido_liquidity_arbitrum_balancer_pools.sql
> +    {% if is_incremental() %}
minor: can replace the end/if with just `else`, so it's one line vs. two

2023-08-15 21:13 UTC, jeff-dude commented on models/lido/liquidity/arbitrum/lido_liquidity_arbitrum_balancer_pools.sql
> +    {% if is_incremental() %}
will only comment here for that

2023-08-15 21:13 UTC, jeff-dude commented on models/lido/liquidity/arbitrum/lido_liquidity_arbitrum_balancer_pools.sql
> +    from delta_prod.balancer_v2_arbitrum.Vault_evt_Swap s
please switch back to jinja syntax

2023-08-17 09:54 UTC, dune-eng commented
Workflow run id 5889405397 approved.

2023-08-17 09:54 UTC, dune-eng commented
Workflow run id 5889405484 approved.

2023-08-17 10:52 UTC, dune-eng commented
Workflow run id 5889965733 approved.

2023-08-17 10:52 UTC, dune-eng commented
Workflow run id 5889965764 approved.

2023-08-17 11:02 UTC, dune-eng commented
Workflow run id 5890052772 approved.

2023-08-17 11:02 UTC, dune-eng commented
Workflow run id 5890052911 approved.

2023-08-17 11:14 UTC, dune-eng commented
Workflow run id 5890174949 approved.

2023-08-17 11:14 UTC, dune-eng commented
Workflow run id 5890174958 approved.

2023-08-17 11:42 UTC, ppclunghe commented
@jeff-dude thanks a lot, your description of the incremental model is correct 
I checked the output CI tables, data seems to be correct, fixed endif/else issue in all spells

2023-08-18 15:54 UTC, jeff-dude approved these changes
let's give this a go!

thanks for taking this initiative on

2023-08-18 15:57 UTC, merged