T-32185 Migrate Ellipsis Finance
duneanalytics/spellbook pull request #3981
Opened 2023-08-08 15:14 UTC by antonio-mendes

Migrating Ellipsis Finance to DuneSQL.

Marking as WIP since I'm having issues with fields from a decoded table and need to dig further.

2023-08-10 13:30 UTC, antonio-mendes commented
I have read the CLA Document and I hereby sign the CLA

2023-08-10 13:30 UTC, antonio-mendes commented
recheck

2023-08-11 15:50 UTC, jeff-dude commented
rebasing with main helped get past the tag issue (those models were merged last night)

2023-08-14 09:03 UTC, antonio-mendes commented
@jeff-dude this issue is no longer showing up on my personal env even after forcing a full-refresh for the `ellipsis_finance_bnb_pool` model. Let's maybe sync later and try to figure it out

2023-08-17 14:06 UTC, jeff-dude commented
> @antonio-mendes looks like there are some failing tests here

curve is hitting similar failures. just needs some seed/generic test fixing on the pools. let's ensure only one of us goes ahead to fix, then can apply on the other

2023-08-22 15:09 UTC, aalan3 commented on models/ellipsis_finance/bnb/ellipsis_finance_bnb_pool_tokens.sql
> -    partition_by = ['pool'],
Should partition by `block_month`

2023-09-01 13:35 UTC, jeff-dude requested changes
lfg. one minor note below

2023-09-01 13:35 UTC, jeff-dude commented on models/ellipsis_finance/ellipsis_finance_trades.sql
you should add `block_month` in this spell, then also add `ellipsis_finance_trades` to `dex_trades_migration_beta` -- it already exists there, just sitting in comments instead, we can move to actual code and see it run successfully here 🤝

2023-09-01 14:16 UTC, antonio-mendes commented
I think we might be good now @jeff-dude ?

2023-09-01 14:22 UTC, jeff-dude commented
> I think we might be good now @jeff-dude ?

yep, let's just let CI ride to be sure

2023-09-01 14:22 UTC, jeff-dude approved these changes

2023-09-01 14:46 UTC, merged