[Base][Dex Trades] Add base chain dex trades about uniswap-v3
duneanalytics/spellbook pull request #3998
Opened 2023-08-10 03:28 UTC by CsyIGy

I realized that no one has integrated the table for Dex Trades for Base chains into Dune yet, so I wanted to be a part of this part of the build!

2023-08-10 03:29 UTC, dune-eng commented
Workflow run id 5816619416 approved.

2023-08-10 04:57 UTC, CsyIGy commented
> **CLA Assistant Lite 机器人：** 感谢您的提交，我们非常感谢。与许多开源项目一样，我们要求您签署我们的[贡献者许可协议](https://github.com/duneanalytics/spellbook/blob/main/CLA.md)，然后我们才能接受您的贡献。您只需发布与以下格式相同的 Pull 请求评论即可签署 CLA。
> 
> 我已阅读 CLA 文件并特此签署 CLA
> 
> 您可以通过在此 Pull 请求中评论**重新检查来重新触发此机器人**



> I have read the CLA Document and I hereby sign the CLA

I have read the CLA Document and I hereby sign the CLA

2023-08-10 05:01 UTC, CsyIGy commented
I have read the CLA Document and I hereby sign the CLA

2023-08-10 05:13 UTC, dune-eng commented
Workflow run id 5817210658 approved.

2023-08-10 05:13 UTC, dune-eng commented
Workflow run id 5817210661 approved.

2023-08-10 07:24 UTC, dune-eng commented
Workflow run id 5818179956 approved.

2023-08-10 07:24 UTC, dune-eng commented
Workflow run id 5818180114 approved.

2023-08-10 07:26 UTC, dune-eng commented
Workflow run id 5818193336 approved.

2023-08-10 07:26 UTC, dune-eng commented
Workflow run id 5818193440 approved.

2023-08-10 09:08 UTC, dune-eng commented
Workflow run id 5819152289 approved.

2023-08-10 09:08 UTC, dune-eng commented
Workflow run id 5819152747 approved.

2023-08-10 09:18 UTC, dune-eng commented
Workflow run id 5819260836 approved.

2023-08-10 09:18 UTC, dune-eng commented
Workflow run id 5819260955 approved.

2023-08-10 10:52 UTC, dune-eng commented
Workflow run id 5820166189 approved.

2023-08-10 10:52 UTC, dune-eng commented
Workflow run id 5820166283 approved.

2023-08-10 11:27 UTC, dune-eng commented
Workflow run id 5820483734 approved.

2023-08-10 11:27 UTC, dune-eng commented
Workflow run id 5820483832 approved.

2023-08-10 12:09 UTC, Hosuke requested changes

2023-08-10 12:09 UTC, Hosuke commented on models/uniswap/base/uniswap_v3_base_trades.sql
> +    partition_by = ['block_date'],
We may add a column `block_month` similar to `block_date` and partition by `block_month`
```suggestion
    partition_by = ['block_month'],
```

2023-08-11 02:32 UTC, dune-eng commented
Workflow run id 5828306639 approved.

2023-08-11 02:32 UTC, dune-eng commented
Workflow run id 5828306756 approved.

2023-08-11 09:26 UTC, dune-eng commented
Workflow run id 5831019223 approved.

2023-08-11 09:26 UTC, dune-eng commented
Workflow run id 5831019426 approved.

2023-08-11 11:09 UTC, dune-eng commented
Workflow run id 5831891691 approved.

2023-08-11 11:09 UTC, dune-eng commented
Workflow run id 5831891549 approved.

2023-08-11 11:27 UTC, CsyIGy commented
I have read the CLA Document and I hereby sign the CLA

2023-08-11 11:36 UTC, CsyIGy commented
recheck

2023-08-11 11:36 UTC, CsyIGy commented
I have read the CLA Document and I hereby sign the CLA

2023-08-11 11:55 UTC, CsyIGy commented
I have read the CLA Document and I hereby sign the CLA

2023-08-11 15:13 UTC, dune-eng commented
Workflow run id 5834184058 approved.

2023-08-11 15:13 UTC, dune-eng commented
Workflow run id 5834184235 approved.

2023-08-11 15:43 UTC, CsyIGy commented
I have read the CLA Document and I hereby sign the CLA

2023-08-11 15:46 UTC, closed without merging