Perpetuals Migration - #1 - Migrate tests & seed - Ready for review
duneanalytics/spellbook pull request #4011
Opened 2023-08-10 12:31 UTC by henrystats

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-08-10 12:32 UTC, dune-eng commented
Workflow run id 5821103507 approved.

2023-08-10 12:32 UTC, dune-eng commented
Workflow run id 5821103403 approved.

2023-08-10 12:46 UTC, dune-eng commented
Workflow run id 5821241998 approved.

2023-08-10 12:46 UTC, dune-eng commented
Workflow run id 5821242104 approved.

2023-08-10 16:38 UTC, dune-eng commented
Workflow run id 5823772919 approved.

2023-08-10 16:38 UTC, dune-eng commented
Workflow run id 5823773029 approved.

2023-08-14 08:37 UTC, Hosuke requested changes

2023-08-14 08:37 UTC, Hosuke commented on tests/generic/perpetual_trades_market_address_legacy.sql
Same as above.

2023-08-14 13:27 UTC, henrystats commented on tests/generic/check_perpetuals_seed_legacy.sql
@Hosuke

2023-08-16 18:53 UTC, jeff-dude approved these changes

2023-08-16 18:53 UTC, jeff-dude commented on tests/generic/check_perpetuals_seed_legacy.sql
yes, this is a process @henrystats and i have been taking to prep for following PRs
it helps keeps test runs clean on follow-up PRs

2023-08-16 18:56 UTC, merged