Thena migration
duneanalytics/spellbook pull request #4019
Opened 2023-08-10 13:51 UTC by couralex6

2023-08-11 09:37 UTC, Hosuke commented on models/thena/bnb/thena_v1_bnb_trades.sql
> +        INNER JOIN {{ source('thena_bnb', 'PairFactoryUpgradeable_evt_PairCreated') }} f
Currently there is only a decoded source `thena_fi_bnb.PairFactoryUpgradeable_evt_PairCreated` available.

2023-08-11 10:01 UTC, couralex6 commented
Thanks @Hosuke !

2023-08-11 17:59 UTC, jeff-dude requested changes

2023-08-11 17:59 UTC, jeff-dude commented on models/thena/bnb/thena_v1_bnb_trades.sql
> +        0x                                                                              AS maker,
cast null as varbinary?

2023-08-17 11:27 UTC, aalan3 approved these changes

2023-08-17 12:49 UTC, antonio-mendes approved these changes
lgtm

2023-08-17 13:18 UTC, merged