zeroex - refactor eth models [FOR REVIEW]
duneanalytics/spellbook pull request #4075
Opened 2023-08-14 16:15 UTC by RantumBits

refactor ethereum models

2023-08-14 16:16 UTC, dune-eng commented
Workflow run id 5858061272 approved.

2023-08-14 16:16 UTC, dune-eng commented
Workflow run id 5858061050 approved.

2023-08-14 16:56 UTC, dune-eng commented
Workflow run id 5858429902 approved.

2023-08-14 17:09 UTC, dune-eng commented
Workflow run id 5858564751 approved.

2023-08-14 17:09 UTC, dune-eng commented
Workflow run id 5858564903 approved.

2023-08-14 17:25 UTC, dune-eng commented
Workflow run id 5858721417 approved.

2023-08-14 17:25 UTC, dune-eng commented
Workflow run id 5858721235 approved.

2023-08-14 18:15 UTC, dune-eng commented
Workflow run id 5859155387 approved.

2023-08-14 18:50 UTC, dune-eng commented
Workflow run id 5859472893 approved.

2023-08-14 18:50 UTC, dune-eng commented
Workflow run id 5859472967 approved.

2023-08-14 18:59 UTC, dune-eng commented
Workflow run id 5859546182 approved.

2023-08-14 18:59 UTC, dune-eng commented
Workflow run id 5859546269 approved.

2023-08-14 19:50 UTC, dune-eng commented
Workflow run id 5859994563 approved.

2023-08-14 19:50 UTC, dune-eng commented
Workflow run id 5859994763 approved.

2023-08-14 23:26 UTC, dune-eng commented
Workflow run id 5861696032 approved.

2023-08-14 23:26 UTC, dune-eng commented
Workflow run id 5861696183 approved.

2023-08-15 00:31 UTC, dune-eng commented
Workflow run id 5862136930 approved.

2023-08-15 00:32 UTC, dune-eng commented
Workflow run id 5862137034 approved.

2023-08-15 01:01 UTC, dune-eng commented
Workflow run id 5862348900 approved.

2023-08-15 01:01 UTC, dune-eng commented
Workflow run id 5862348838 approved.

2023-08-15 17:06 UTC, dune-eng commented
Workflow run id 5869686978 approved.

2023-08-15 17:08 UTC, dune-eng commented
Workflow run id 5869687233 approved.

2023-08-15 17:58 UTC, dune-eng commented
Workflow run id 5869990579 approved.

2023-08-15 18:02 UTC, dune-eng commented
Workflow run id 5869990702 approved.

2023-08-15 20:08 UTC, dune-eng commented
Workflow run id 5871124036 approved.

2023-08-15 20:17 UTC, dune-eng commented
Workflow run id 5871124473 approved.

2023-08-15 21:14 UTC, dune-eng commented
Workflow run id 5871807890 approved.

2023-08-15 21:14 UTC, dune-eng commented
Workflow run id 5871807967 approved.

2023-08-15 21:44 UTC, dune-eng commented
Workflow run id 5872038193 approved.

2023-08-15 21:44 UTC, dune-eng commented
Workflow run id 5872038291 approved.

2023-08-15 22:02 UTC, dune-eng commented
Workflow run id 5872156654 approved.

2023-08-15 22:02 UTC, dune-eng commented
Workflow run id 5872156665 approved.

2023-08-15 22:14 UTC, dune-eng commented
Workflow run id 5872261577 approved.

2023-08-15 22:14 UTC, dune-eng commented
Workflow run id 5872261800 approved.

2023-08-15 23:01 UTC, dune-eng commented
Workflow run id 5872572459 approved.

2023-08-15 23:01 UTC, dune-eng commented
Workflow run id 5872572698 approved.

2023-08-15 23:15 UTC, dune-eng commented
Workflow run id 5872684689 approved.

2023-08-15 23:15 UTC, dune-eng commented
Workflow run id 5872684518 approved.

2023-08-15 23:26 UTC, dune-eng commented
Workflow run id 5872756738 approved.

2023-08-15 23:26 UTC, dune-eng commented
Workflow run id 5872756818 approved.

2023-08-15 23:37 UTC, dune-eng commented
Workflow run id 5872820865 approved.

2023-08-15 23:37 UTC, dune-eng commented
Workflow run id 5872820993 approved.

2023-08-15 23:49 UTC, dune-eng commented
Workflow run id 5872887301 approved.

2023-08-15 23:49 UTC, dune-eng commented
Workflow run id 5872887336 approved.

2023-08-15 23:59 UTC, dune-eng commented
Workflow run id 5872934872 approved.

2023-08-15 23:59 UTC, dune-eng commented
Workflow run id 5872934822 approved.

2023-08-16 17:47 UTC, dune-eng commented
Workflow run id 5882111655 approved.

2023-08-16 17:47 UTC, dune-eng commented
Workflow run id 5882111893 approved.

2023-08-16 18:16 UTC, dune-eng commented
Workflow run id 5882378205 approved.

2023-08-16 19:35 UTC, dune-eng commented
Workflow run id 5883077138 approved.

2023-08-16 19:35 UTC, dune-eng commented
Workflow run id 5883077350 approved.

2023-09-06 17:37 UTC, dune-eng commented
Workflow run id 6100486484 approved.

2023-09-06 17:37 UTC, dune-eng commented
Workflow run id 6100486933 approved.

2023-09-06 17:37 UTC, dune-eng commented
Workflow run id 6100489064 approved.

2023-09-06 17:37 UTC, dune-eng commented
Workflow run id 6100489354 approved.

2023-09-06 18:01 UTC, RantumBits commented
this is ready for review @jeff-dude

2023-09-06 19:41 UTC, jeff-dude requested changes

2023-09-06 19:41 UTC, jeff-dude commented on models/zeroex/ethereum/zeroex_ethereum_api_fills.sql
>          partition_by = ['block_date'],
please update partition to `block_month`

2023-09-06 19:41 UTC, jeff-dude commented on models/zeroex/ethereum/zeroex_ethereum_api_fills_deduped.sql
> +      , TRY_CAST(ARRAY[-1] AS ARRAY(BIGINT)) AS trace_address
this can be just `ARRAY[-1] as trace_address`

2023-09-06 19:41 UTC, jeff-dude commented on models/zeroex/ethereum/zeroex_ethereum_api_fills.sql
> +            cast(fills.makerAssetFilledAmount  as int256)AS maker_token_amount_raw,
we've been writing `amount_raw` fields as `uint256` in the entire `dex.trades` lineage, which this eventually feeds into. can you universally update that in this spell?

2023-09-06 20:18 UTC, dune-eng commented
Workflow run id 6102005149 approved.

2023-09-06 20:18 UTC, dune-eng commented
Workflow run id 6102005161 approved.

2023-09-06 20:22 UTC, dune-eng commented
Workflow run id 6102043948 approved.

2023-09-06 20:22 UTC, dune-eng commented
Workflow run id 6102044041 approved.

2023-09-06 20:34 UTC, dune-eng commented
Workflow run id 6102144426 approved.

2023-09-06 20:34 UTC, dune-eng commented
Workflow run id 6102144561 approved.

2023-09-06 20:47 UTC, dune-eng commented
Workflow run id 6102249836 approved.

2023-09-06 20:52 UTC, dune-eng commented
Workflow run id 6102292694 approved.

2023-09-06 21:57 UTC, dune-eng commented
Workflow run id 6102812229 approved.

2023-09-06 21:57 UTC, dune-eng commented
Workflow run id 6102812433 approved.

2023-09-06 22:22 UTC, dune-eng commented
Workflow run id 6103022707 approved.

2023-09-06 22:22 UTC, dune-eng commented
Workflow run id 6103022939 approved.

2023-09-06 22:30 UTC, dune-eng commented
Workflow run id 6103080658 approved.

2023-09-06 22:30 UTC, dune-eng commented
Workflow run id 6103080723 approved.

2023-09-07 15:48 UTC, dune-eng commented
Workflow run id 6111961095 approved.

2023-09-07 15:48 UTC, dune-eng commented
Workflow run id 6111961461 approved.

2023-09-07 16:24 UTC, dune-eng commented
Workflow run id 6112318757 approved.

2023-09-07 16:24 UTC, dune-eng commented
Workflow run id 6112318854 approved.

2023-09-07 19:25 UTC, RantumBits commented
requested changes are complete  @jeff-dude

2023-09-08 17:16 UTC, jeff-dude requested changes

2023-09-08 17:16 UTC, jeff-dude commented on models/zeroex/ethereum/zeroex_ethereum_api_fills.sql
> +        cast(maker_token_amount_raw as int256) as maker_token_amount_raw,
it looks like you reverted back to `int256` for raw amounts all throughout. is there any reason why? can we at minimum cast at the very end here to `uint256`?

i'm afraid when we merge into `dex.trades` it'll fail in the union on different data types

2023-09-12 21:27 UTC, dune-eng commented
Workflow run id 6165044412 approved.

2023-09-12 21:27 UTC, dune-eng commented
Workflow run id 6165044368 approved.

2023-09-12 21:27 UTC, dune-eng commented
Workflow run id 6165046141 approved.

2023-09-12 21:27 UTC, dune-eng commented
Workflow run id 6165046242 approved.

2023-09-13 19:57 UTC, jeff-dude approved these changes
thank you!

do you plan to continue on all blockchains?
i've started [this PR](https://github.com/duneanalytics/spellbook/pull/4320) to migrate the sector level spell, which has a dependency on all 0x spells to be migrated first

2023-09-13 19:58 UTC, jeff-dude commented
> thank you!
> 
> do you plan to continue on all blockchains? i've started [this PR](https://github.com/duneanalytics/spellbook/pull/4320) to migrate the sector level spell, which has a dependency on all 0x spells to be migrated first

curious if we should help you continue on other blockchains, or if you have already started

2023-09-13 19:58 UTC, merged