update logic to dunesql
duneanalytics/spellbook pull request #4093
Opened 2023-08-16 09:46 UTC by sharkxff

I have read the CLA Document and I hereby sign the CLA

2023-08-16 09:47 UTC, dune-eng commented
Workflow run id 5877233802 approved.

2023-08-16 09:47 UTC, dune-eng commented
Workflow run id 5877233854 approved.

2023-08-16 10:02 UTC, sharkxff commented
@Hosuke @jeff-dude Previously the pr was closed, re-pulled the items, and the checks all worked in this pr

2023-08-16 14:00 UTC, Hosuke requested changes

2023-08-16 14:00 UTC, Hosuke commented on models/nexusmutual/ethereum/nexusmutual_ethereum_quotation_trades.sql
>      partition_by = ['block_date'],
You can modify this spell to partition_by block_month

2023-08-16 14:00 UTC, Hosuke commented on models/nexusmutual/ethereum/nexusmutual_ethereum_quotation_trades.sql
> +           cast('0xd7c49cee7e9188cca6ad8ff264c1da2e69d4cf3b' as varbinary) as token
`0xd7c49cee7e9188cca6ad8ff264c1da2e69d4cf3b` is varbinary type.
```suggestion
           0xd7c49cee7e9188cca6ad8ff264c1da2e69d4cf3b as token
```

2023-08-17 03:05 UTC, dune-eng commented
Workflow run id 5886287078 approved.

2023-08-17 03:05 UTC, dune-eng commented
Workflow run id 5886286935 approved.

2023-08-17 03:23 UTC, sharkxff commented
@Hosuke I have followed the comments to change, the data type of token here, because as the association condition of the join, do not change the data type will report an error:Cannot apply operator: varchar(42) = varbinary, now in the on here to do processing

2023-08-18 08:51 UTC, dune-eng commented
Workflow run id 5900706125 approved.

2023-08-18 08:51 UTC, dune-eng commented
Workflow run id 5900706316 approved.

2023-08-20 15:49 UTC, Hosuke commented on models/nexusmutual/ethereum/nexusmutual_ethereum_quotation_trades.sql
> +    ON from_hex(quo_evt.evt_tx_hash) = tx.hash
We use `from_hex()` to convert hexstring varchar to varbinary.

2023-08-20 16:10 UTC, Hosuke approved these changes
LGTM.✅
Thank you @sharkxff 

[Sample nexusmutual_ethereum_quotation_trades](https://dune.com/queries/2930595)

2023-08-20 16:12 UTC, Hosuke commented on models/nexusmutual/ethereum/nexusmutual_ethereum_schema.yml
>      columns:
By the way you can add a `check_seed` test here.

2023-08-21 09:30 UTC, dune-eng commented
Workflow run id 5924492172 approved.

2023-08-21 09:30 UTC, dune-eng commented
Workflow run id 5924492270 approved.

2023-08-21 10:02 UTC, dune-eng commented
Workflow run id 5924797945 approved.

2023-08-21 10:02 UTC, dune-eng commented
Workflow run id 5924797815 approved.

2023-08-21 10:13 UTC, sharkxff commented
@Hosuke    I'm getting this error :backquoted identifiers are not supported; use double quotes to quote identifiers", but there is no such identifier in the nexusmutual_ethereum_schema.yml file, please help me to check where the problem is!

2023-08-21 14:50 UTC, Hosuke commented on models/nexusmutual/ethereum/nexusmutual_ethereum_schema.yml
> +      - check_seed_legacy:
```suggestion
      - check_seed:
```

2023-08-21 15:17 UTC, Hosuke approved these changes

2023-08-21 18:07 UTC, jeff-dude approved these changes
thank you!

2023-08-21 18:08 UTC, merged