Added Tokemak to Dune Spells and added list of relevant Tokemak tokens.
duneanalytics/spellbook pull request #4101
Opened 2023-08-16 20:57 UTC by addmorebass

Added Tokemak as a project and added the first Tokemak spell.

2023-08-16 20:58 UTC, dune-eng commented
Workflow run id 5883770840 approved.

2023-08-16 20:58 UTC, dune-eng commented
Workflow run id 5883770917 approved.

2023-08-16 21:20 UTC, dune-eng commented
Workflow run id 5883968765 approved.

2023-08-16 21:22 UTC, addmorebass commented
I have read the CLA Document and I hereby sign the CLA

2023-08-16 21:22 UTC, addmorebass commented
recheck

2023-08-16 21:22 UTC, addmorebass commented
recheck

2023-08-16 21:46 UTC, dune-eng commented
Workflow run id 5884158757 approved.

2023-08-16 21:46 UTC, dune-eng commented
Workflow run id 5884158894 approved.

2023-08-16 21:52 UTC, dune-eng commented
Workflow run id 5884196976 approved.

2023-08-16 21:52 UTC, dune-eng commented
Workflow run id 5884197067 approved.

2023-08-16 22:22 UTC, dune-eng commented
Workflow run id 5884427395 approved.

2023-08-16 22:22 UTC, dune-eng commented
Workflow run id 5884427472 approved.

2023-08-16 22:54 UTC, dune-eng commented
Workflow run id 5884639208 approved.

2023-08-16 22:54 UTC, dune-eng commented
Workflow run id 5884639311 approved.

2023-08-16 23:13 UTC, dune-eng commented
Workflow run id 5884767078 approved.

2023-08-16 23:13 UTC, dune-eng commented
Workflow run id 5884767230 approved.

2023-08-16 23:40 UTC, dune-eng commented
Workflow run id 5884935846 approved.

2023-08-17 00:16 UTC, dune-eng commented
Workflow run id 5885152264 approved.

2023-08-17 00:16 UTC, dune-eng commented
Workflow run id 5885152140 approved.

2023-08-17 00:28 UTC, dune-eng commented
Workflow run id 5885245090 approved.

2023-08-17 00:34 UTC, dune-eng commented
Workflow run id 5885293433 approved.

2023-08-17 00:34 UTC, dune-eng commented
Workflow run id 5885293292 approved.

2023-08-17 00:44 UTC, dune-eng commented
Workflow run id 5885366756 approved.

2023-08-17 00:44 UTC, dune-eng commented
Workflow run id 5885366836 approved.

2023-08-17 13:34 UTC, dune-eng commented
Workflow run id 5891636352 approved.

2023-08-17 13:34 UTC, dune-eng commented
Workflow run id 5891636589 approved.

2023-08-17 13:59 UTC, dune-eng commented
Workflow run id 5891882755 approved.

2023-08-24 08:53 UTC, Hosuke requested changes
Hi @addmorebass,
thank you for your contribution.

For the static spell, we may use the similar format to this:
https://github.com/duneanalytics/spellbook/blob/main/models/tokens/arbitrum/tokens_arbitrum_erc20.sql

2023-08-24 08:53 UTC, Hosuke commented on models/tokemak/ethereum/tokemak_ethereum_view_tokemak_lookup_reactors.sql
> +    SELECT '0xD3B5D9a561c293Fb42b446FE7e237DaA9BF9AA84' as reactor_address, '0xdBdb4d16EdA451D0503b854CF79D55697F90c8DF' as underlyer_address, 'ALCX Reactor', true
We can use varbinary type for hexstring addresses.
```suggestion
    SELECT 0xD3B5D9a561c293Fb42b446FE7e237DaA9BF9AA84 as reactor_address, 0xdBdb4d16EdA451D0503b854CF79D55697F90c8DF as underlyer_address, 'ALCX Reactor', true
```

2023-08-29 17:16 UTC, Hosuke commented on models/tokemak/ethereum/tokemak_ethereum_view_tokemak_lookup_reactors.sql
> +    tags=['dunesql'],
```suggestion
    tags=['dunesql', 'static'],
```

2023-08-30 07:46 UTC, Hosuke requested changes

2023-08-30 07:46 UTC, Hosuke commented on models/tokemak/ethereum/tokemak_ethereum_view_lookup_tokens.sql
> +WITH tokemak_ethereum_view_lookup_tokens(symbol, display_name, address, pricing_contract, decimals, is_pool, is_active, is_liability, is_dollar_stable) AS
Hi @addmorebass,

I have transform tokemak_ethereum_view_tokemak_lookup_reactors.sql into `select ... from (values ...)` format:
https://github.com/duneanalytics/spellbook/blob/3456338155e4b868a00c1fe244301b153aea08fe/models/tokemak/ethereum/tokemak_ethereum_view_tokemak_lookup_reactors.sql

You can follow this format to transform this spell as well.

2023-08-30 19:50 UTC, dune-eng commented
Workflow run id 6029398228 approved.

2023-08-30 19:50 UTC, dune-eng commented
Workflow run id 6029398446 approved.

2023-08-31 16:29 UTC, Hosuke commented on models/tokemak/ethereum/tokemak_ethereum_view_lookup_tokens.sql
> +    alias = alias('view_lookup_tokens'),
Maybe we can shorten the alias?
```suggestion
    alias = alias('lookup_tokens'),
```

2023-08-31 16:33 UTC, dune-eng commented
Workflow run id 6040019879 approved.

2023-08-31 16:33 UTC, dune-eng commented
Workflow run id 6040020009 approved.

2023-08-31 16:33 UTC, addmorebass commented
Thanks for the help @Hosuke - we should be good to go now?

2023-08-31 16:38 UTC, addmorebass commented
谢谢

2023-08-31 16:54 UTC, Hosuke commented
> Thanks for the help @Hosuke - we should be good to go now?

I will fix the schema and sync the new alias first.

2023-08-31 17:07 UTC, Hosuke approved these changes
LGTM.✅
Thank you @addmorebass

2023-08-31 17:07 UTC, Hosuke commented on models/tokemak/ethereum/tokemak_ethereum_lookup_tokens.sql
Maybe we can use `csv upload` function for this file in the future.

2023-08-31 18:22 UTC, jeff-dude approved these changes
removed the source file, as i believe no sources are used & the listed object was a spell `tokemak_ethereum_lookup_tokens`, which should be a `{{ref()}}` in spellbook instead

2023-08-31 18:45 UTC, merged