zeroex - refactor poly
duneanalytics/spellbook pull request #4273
Opened 2023-09-06 19:27 UTC by RantumBits

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-09-06 19:28 UTC, dune-eng commented
Workflow run id 6101558647 approved.

2023-09-06 19:28 UTC, dune-eng commented
Workflow run id 6101558721 approved.

2023-09-06 19:32 UTC, dune-eng commented
Workflow run id 6101591356 approved.

2023-09-06 19:32 UTC, dune-eng commented
Workflow run id 6101591476 approved.

2023-09-06 20:03 UTC, dune-eng commented
Workflow run id 6101856783 approved.

2023-09-06 20:03 UTC, dune-eng commented
Workflow run id 6101857091 approved.

2023-09-06 20:29 UTC, dune-eng commented
Workflow run id 6102099797 approved.

2023-09-06 20:29 UTC, dune-eng commented
Workflow run id 6102100019 approved.

2023-09-06 20:51 UTC, dune-eng commented
Workflow run id 6102278638 approved.

2023-09-06 20:51 UTC, dune-eng commented
Workflow run id 6102278579 approved.

2023-09-06 22:02 UTC, dune-eng commented
Workflow run id 6102851040 approved.

2023-09-06 22:02 UTC, dune-eng commented
Workflow run id 6102851123 approved.

2023-09-06 22:04 UTC, dune-eng commented
Workflow run id 6102867117 approved.

2023-09-06 22:04 UTC, dune-eng commented
Workflow run id 6102867183 approved.

2023-09-06 22:16 UTC, dune-eng commented
Workflow run id 6102963784 approved.

2023-09-06 22:16 UTC, dune-eng commented
Workflow run id 6102963867 approved.

2023-09-06 22:19 UTC, dune-eng commented
Workflow run id 6102986993 approved.

2023-09-06 22:19 UTC, dune-eng commented
Workflow run id 6102986897 approved.

2023-09-06 22:30 UTC, dune-eng commented
Workflow run id 6103075594 approved.

2023-09-06 22:30 UTC, dune-eng commented
Workflow run id 6103075828 approved.

2023-09-07 15:50 UTC, dune-eng commented
Workflow run id 6111976219 approved.

2023-09-07 15:50 UTC, dune-eng commented
Workflow run id 6111976471 approved.

2023-09-07 16:25 UTC, dune-eng commented
Workflow run id 6112328060 approved.

2023-09-07 16:25 UTC, dune-eng commented
Workflow run id 6112328242 approved.

2023-09-07 16:26 UTC, dune-eng commented
Workflow run id 6112334157 approved.

2023-09-07 16:26 UTC, dune-eng commented
Workflow run id 6112334325 approved.

2023-09-07 19:16 UTC, dune-eng commented
Workflow run id 6113880994 approved.

2023-09-07 19:16 UTC, dune-eng commented
Workflow run id 6113880794 approved.

2023-09-07 19:27 UTC, dune-eng commented
Workflow run id 6113962032 approved.

2023-09-07 19:27 UTC, dune-eng commented
Workflow run id 6113962203 approved.

2023-09-07 20:16 UTC, dune-eng commented
Workflow run id 6114359881 approved.

2023-09-07 20:16 UTC, dune-eng commented
Workflow run id 6114360082 approved.

2023-09-07 21:06 UTC, dune-eng commented
Workflow run id 6114774901 approved.

2023-09-07 21:06 UTC, dune-eng commented
Workflow run id 6114775132 approved.

2023-09-07 21:36 UTC, dune-eng commented
Workflow run id 6115011116 approved.

2023-09-07 21:36 UTC, dune-eng commented
Workflow run id 6115011207 approved.

2023-09-07 22:18 UTC, dune-eng commented
Workflow run id 6115307776 approved.

2023-09-07 22:18 UTC, dune-eng commented
Workflow run id 6115308030 approved.

2023-09-08 09:22 UTC, Hosuke requested changes

2023-09-08 09:22 UTC, Hosuke commented on h origin -d bnb2 bnbB bnbuni brew chainflag chainflagPoly chainflageth cln contract dedup
I think we may need to remove this file from the PR.

2023-09-08 09:22 UTC, Hosuke commented on h origin -d fixc fixnolimits ftm ftm-mim layer_1_btc_view layer_1_eth_view main matcha-fee
Same as above.

2023-09-08 09:22 UTC, Hosuke commented on seeds/zeroex/polygon/_schema.yml
> +seeds:
We are missing `zeroex_polygon_api_fills_deduped_sample` definition here.

2023-09-08 15:42 UTC, dune-eng commented
Workflow run id 6123713574 approved.

2023-09-08 15:42 UTC, dune-eng commented
Workflow run id 6123714252 approved.

2023-09-08 15:43 UTC, dune-eng commented
Workflow run id 6123726924 approved.

2023-09-08 16:13 UTC, dune-eng commented
Workflow run id 6124003673 approved.

2023-09-08 16:13 UTC, dune-eng commented
Workflow run id 6124003886 approved.

2023-09-08 16:14 UTC, dune-eng commented
Workflow run id 6124011450 approved.

2023-09-08 16:14 UTC, dune-eng commented
Workflow run id 6124011568 approved.

2023-09-08 16:21 UTC, dune-eng commented
Workflow run id 6124074221 approved.

2023-09-08 16:21 UTC, dune-eng commented
Workflow run id 6124074448 approved.

2023-09-08 16:21 UTC, dune-eng commented
Workflow run id 6124077055 approved.

2023-09-08 16:21 UTC, dune-eng commented
Workflow run id 6124077174 approved.

2023-09-08 16:22 UTC, dune-eng commented
Workflow run id 6124083954 approved.

2023-09-18 16:24 UTC, dune-eng commented
Workflow run id 6225284982 approved.

2023-09-18 16:24 UTC, dune-eng commented
Workflow run id 6225285490 approved.

2023-09-18 17:32 UTC, Hosuke commented on seeds/zeroex/polygon/zeroex_polygon_api_fills_deduped_sample.csv
> +polygon,2023-01-01,2023-01-01 13:32,USDT,USDC,USDC-USDT,0.009999,0.009991,9999,9991,0.009996804771,0xc2132d05d31c914a87c6611c10748aeb04b58e8f,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0xfd896db057f2
Seems the `taker` and `maker` fields are not matched with the query results.
Do you want to recheck the seed here?

2023-09-19 21:12 UTC, jeff-dude commented
thanks @Hosuke for helping pick this up 🙏

2023-09-21 03:34 UTC, Hosuke commented on seeds/zeroex/polygon/zeroex_polygon_api_fills_deduped_sample.csv
> +polygon,2023-01-01,2023-01-01 14:16,WMATIC,0x6948bad33a52ab0bed5cd0bc867fb091c3d920c7,,3.8250945851720997,,3.8250945851720996e+18,5.050003892548732e+19,2.8917705005779997,0x0d500b1d8e8ef31e21c99d1db9
Seems this line is having mismatched `evt_index` and `maker`:
https://dune.com/queries/3040806

2023-09-21 03:47 UTC, Hosuke commented on seeds/zeroex/polygon/zeroex_polygon_api_fills_deduped_sample.csv
> +polygon,2023-01-01,2023-01-01 14:16,WMATIC,0x6948bad33a52ab0bed5cd0bc867fb091c3d920c7,,3.8250945851720997,,3.8250945851720996e+18,5.050003892548732e+19,2.8917705005779997,0x0d500b1d8e8ef31e21c99d1db9
I will modify the seed based on this query result:
https://dune.com/queries/3040835

Currently only 2 records with tx_hash in the query results.

2023-09-21 09:14 UTC, Hosuke approved these changes
LGTM.✅
Thank you @RantumBits 

I adjusted seeds in seeds/zeroex/polygon/zeroex_polygon_api_fills_deduped_sample.csv to match query results.

[Sample zeroex_polygon_api_fills_deduped](https://dune.com/queries/3041494)
[Sample zeroex_polygon_api_fills](https://dune.com/queries/3041571)

2023-09-21 14:45 UTC, Hosuke commented
I am fixing the topic index shifting and going to retry the original seed records.

2023-09-21 23:30 UTC, dune-eng commented
Workflow run id 6268167701 approved.

2023-09-21 23:30 UTC, dune-eng commented
Workflow run id 6268167855 approved.

2023-09-21 23:52 UTC, dune-eng commented
Workflow run id 6268293323 approved.

2023-09-21 23:52 UTC, dune-eng commented
Workflow run id 6268293456 approved.

2023-09-22 00:01 UTC, dune-eng commented
Workflow run id 6268336629 approved.

2023-09-22 00:01 UTC, dune-eng commented
Workflow run id 6268336942 approved.

2023-09-23 02:39 UTC, Hosuke commented on seeds/zeroex/polygon/zeroex_polygon_api_fills_deduped_sample.csv
> +polygon,0x API,2023-01-01,2023-01-01 0:19,USDC,CRV,CRV-USDC,50,95.0201732,50000000,95020173202461750000,50.00704359,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x172370d5cd63279efa6d502dab29171933a610
Event 94 in this transaction is exchange of WETH and CRV:
https://polygonscan.com/tx/0x02c241e84f97f5389550c94b46ee9187a846401cf887e0d42002bb4e1c458c10#eventlog

I will update the taker token address.

2023-09-23 03:02 UTC, Hosuke approved these changes
LGTM.✅
Thank you @RantumBits 

[Sample zeroex polygon api fills](https://dune.com/queries/3046345)
[Sample zeroex polygon api fills deduped]()

2023-09-26 19:15 UTC, jeff-dude approved these changes
thanks again to you both 🙌

2023-09-26 19:36 UTC, merged