Add PNDC to Tokens and Price
duneanalytics/spellbook pull request #4274
Opened 2023-09-06 21:23 UTC by timmaycastags

This request is to add the contract for PNDC to the ETH Tokens and Price tables.

2023-09-06 21:23 UTC, dune-eng commented
Workflow run id 6102563593 approved.

2023-09-06 21:23 UTC, dune-eng commented
Workflow run id 6102563592 approved.

2023-09-06 21:24 UTC, dune-eng commented
Workflow run id 6102563524 approved.

2023-09-06 21:28 UTC, timmaycastags commented
I have read the CLA Document and I hereby sign the CLA

2023-09-07 00:31 UTC, dune-eng commented
Workflow run id 6103881186 approved.

2023-09-07 00:31 UTC, dune-eng commented
Workflow run id 6103881219 approved.

2023-09-07 00:31 UTC, dune-eng commented
Workflow run id 6103881220 approved.

2023-09-07 00:48 UTC, dune-eng commented
Workflow run id 6103998517 approved.

2023-09-07 00:48 UTC, dune-eng commented
Workflow run id 6103998577 approved.

2023-09-07 00:48 UTC, dune-eng commented
Workflow run id 6103998576 approved.

2023-09-07 12:01 UTC, dune-eng commented
Workflow run id 6109400880 approved.

2023-09-07 12:01 UTC, dune-eng commented
Workflow run id 6109400850 approved.

2023-09-07 12:01 UTC, dune-eng commented
Workflow run id 6109400877 approved.

2023-09-07 16:21 UTC, jeff-dude requested changes
no need to apologize for exploring spellbook -- thank you for contributing!
i've left one comment for change below

2023-09-07 16:21 UTC, jeff-dude commented on models/prices/ethereum/prices_ethereum_tokens_legacy.sql
for prices, we no longer use the legacy files / engine. please add this value to the file in the same directory that is non-legacy, dunesql version

you can then remove this change from this file 👍

2023-09-07 16:31 UTC, dune-eng commented
Workflow run id 6112385631 approved.

2023-09-07 16:31 UTC, dune-eng commented
Workflow run id 6112385515 approved.

2023-09-07 16:37 UTC, timmaycastags commented on models/prices/ethereum/prices_ethereum_tokens_legacy.sql
Thanks Jeff,  The non-legacy price file already has the pndc coin added.  I will remove the legacy update and no change for price is needed.

2023-09-07 16:44 UTC, jeff-dude commented on models/prices/ethereum/prices_ethereum_tokens_legacy.sql
sounds good!
looks like your second commit re-added it back. please do look to remove, so there are only two files in the PR (tokens files)

2023-09-07 16:57 UTC, closed without merging