More CEX addresses
duneanalytics/spellbook pull request #4307
Opened 2023-09-10 12:18 UTC by hildobby

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-09-11 09:54 UTC, Hosuke commented on models/cex/ethereum/cex_ethereum_addresses.sql
> +    , ('ethereum', 0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208, 'IDEX', 'IDEX 1', 'hildobby', date '2023-09-08') -
```suggestion
    , ('ethereum', 0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208, 'IDEX', 'IDEX 1', 'hildobby', date '2023-09-08')
```

2023-09-11 09:57 UTC, Hosuke approved these changes

2023-09-13 03:34 UTC, Hosuke requested changes

2023-09-13 03:34 UTC, Hosuke commented on models/cex/ethereum/cex_ethereum_addresses.sql
> +    , ('ethereum', 0xd7b9a9b2f665849c4071ad5af77d8c76aa30fb32, 'EXMO', 'EXMO 1', 'hildobby', date '2023-09-12')
Duped line:
https://github.com/duneanalytics/spellbook/blob/3fe30ef1aaa61965227a2abcd7ca3cb6b35b0ff0/models/cex/ethereum/cex_ethereum_addresses.sql#L471

2023-09-13 03:34 UTC, Hosuke commented on models/cex/ethereum/cex_ethereum_addresses.sql
> +    , ('ethereum', 0x58b704065b7aff3ed351052f8560019e05925023, 'Bitso', 'Bitso 3', 'hildobby', date '2023-09-12')
Duped line:
https://github.com/duneanalytics/spellbook/blob/3fe30ef1aaa61965227a2abcd7ca3cb6b35b0ff0/models/cex/ethereum/cex_ethereum_addresses.sql#L392

2023-09-13 03:34 UTC, Hosuke commented on models/cex/ethereum/cex_ethereum_addresses.sql
> +    , ('ethereum', 0x50be13b54f3eebbe415d20250598d81280e56772, 'Phemex', 'Phemex 3', 'hildobby', date '2023-09-12')
These 2 lines are duplicated.

2023-09-13 03:34 UTC, Hosuke commented on models/cex/ethereum/cex_ethereum_addresses.sql
> +    , ('ethereum', 0x1fd6267f0d86f62d88172b998390afee2a1f54b6, 'EXMO', 'EXMO 5', 'hildobby', date '2023-09-12')
Duped line:
https://github.com/duneanalytics/spellbook/blob/3fe30ef1aaa61965227a2abcd7ca3cb6b35b0ff0/models/cex/ethereum/cex_ethereum_addresses.sql#L470

2023-09-15 09:37 UTC, hildobby commented on models/cex/ethereum/cex_ethereum_addresses.sql
> +    , ('ethereum', 0x1fd6267f0d86f62d88172b998390afee2a1f54b6, 'EXMO', 'EXMO 5', 'hildobby', date '2023-09-12')
fixed

2023-09-15 09:37 UTC, hildobby commented on models/cex/ethereum/cex_ethereum_addresses.sql
> +    , ('ethereum', 0x50be13b54f3eebbe415d20250598d81280e56772, 'Phemex', 'Phemex 3', 'hildobby', date '2023-09-12')
fixed

2023-09-15 09:37 UTC, hildobby commented on models/cex/ethereum/cex_ethereum_addresses.sql
> +    , ('ethereum', 0x58b704065b7aff3ed351052f8560019e05925023, 'Bitso', 'Bitso 3', 'hildobby', date '2023-09-12')
fixed

2023-09-15 09:37 UTC, hildobby commented on models/cex/ethereum/cex_ethereum_addresses.sql
> +    , ('ethereum', 0xd7b9a9b2f665849c4071ad5af77d8c76aa30fb32, 'EXMO', 'EXMO 1', 'hildobby', date '2023-09-12')
fixed

2023-09-18 03:53 UTC, Hosuke approved these changes
LGTM.✅
Thank you @hildobby

2023-09-19 21:17 UTC, jeff-dude approved these changes

2023-09-19 21:21 UTC, jeff-dude commented
since wash trades use this downstream, let's wait to merge this with that PR (one outstanding minor question there)

2023-09-21 09:01 UTC, merged