"feat_keep3r"
duneanalytics/spellbook pull request #4314
Opened 2023-09-11 21:48 UTC by m-r-g-t

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-09-11 21:48 UTC, dune-eng commented
Workflow run id 6152124104 approved.

2023-09-11 21:49 UTC, dune-eng commented
Workflow run id 6152124345 approved.

2023-09-11 21:54 UTC, dune-eng commented
Workflow run id 6152161084 approved.

2023-09-11 21:54 UTC, dune-eng commented
Workflow run id 6152161196 approved.

2023-09-11 22:02 UTC, dune-eng commented
Workflow run id 6152221509 approved.

2023-09-11 22:02 UTC, dune-eng commented
Workflow run id 6152221429 approved.

2023-09-12 21:47 UTC, m-r-g-t commented
I need some assistant to detect what is the problem on the sql.

error message it is not very clear,

22:07:49  Database Error in model keep3r_network_addLiquidityToJob (models/keep3r_network/keep3r_network_addLiquidityToJob.sql)
22:07:49    TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 26:9: mismatched input '{'. Expecting: '(', 'JSON_TABLE', 'LATERAL', 'TABLE', 'UNNEST', <identifier>", query_id=20230911_220749_19553_caqi8)

could you please give me a hand or point me in the correct direction?

2023-09-14 22:10 UTC, dune-eng commented
Workflow run id 6191382151 approved.

2023-09-14 22:10 UTC, dune-eng commented
Workflow run id 6191382230 approved.

2023-09-19 21:25 UTC, jeff-dude requested changes

2023-09-19 21:25 UTC, jeff-dude commented on models/keep3r_network/keep3r_network_addLiquidityToJob.sql
> +      , alias = alias('etv_addliquiditytoJob')
we universally use `lower_case_with_underscore` for naming standard, for files/directories/aliases/schemas/columns, can you ensure all here is updated to reflect that?

2023-09-19 21:25 UTC, jeff-dude commented on models/keep3r_network/keep3r_network_addLiquidityToJob.sql
> +        { source(
you are missing a `{` here, which is why you see the error. jinja syntax requires two of them, like your example on line 18

2023-09-19 21:25 UTC, jeff-dude commented on models/keep3r_network/keep3r_network_addLiquidityToJob.sql
> +        { source(
same here

2023-09-19 21:25 UTC, jeff-dude commented on models/keep3r_network/keep3r_network_addLiquidityToJob.sql
> +        { source(
same here

2023-09-22 19:15 UTC, dune-eng commented
Workflow run id 6278239528 approved.

2023-09-22 19:15 UTC, dune-eng commented
Workflow run id 6278239654 approved.

2023-09-23 14:21 UTC, dune-eng commented
Workflow run id 6284251958 approved.

2023-09-23 14:21 UTC, dune-eng commented
Workflow run id 6284252003 approved.

2023-09-23 14:57 UTC, dune-eng commented
Workflow run id 6284390804 approved.

2023-09-23 14:57 UTC, dune-eng commented
Workflow run id 6284390893 approved.

2023-09-23 15:22 UTC, dune-eng commented
Workflow run id 6284522707 approved.

2023-09-23 15:22 UTC, dune-eng commented
Workflow run id 6284522749 approved.

2023-09-23 16:11 UTC, dune-eng commented
Workflow run id 6284723314 approved.

2023-09-23 16:11 UTC, dune-eng commented
Workflow run id 6284723398 approved.

2023-09-23 17:06 UTC, dune-eng commented
Workflow run id 6284963087 approved.

2023-09-23 17:06 UTC, dune-eng commented
Workflow run id 6284963036 approved.

2023-09-23 23:07 UTC, dune-eng commented
Workflow run id 6286502178 approved.

2023-09-23 23:07 UTC, dune-eng commented
Workflow run id 6286502126 approved.

2023-09-24 21:34 UTC, dune-eng commented
Workflow run id 6292519495 approved.

2023-09-24 21:34 UTC, dune-eng commented
Workflow run id 6292519530 approved.

2023-09-25 18:05 UTC, jeff-dude requested changes

2023-09-25 18:05 UTC, jeff-dude commented on models/keep3r_network/keep3r_network_token_price_legacy.sql
> +  alias = alias('token_price', legacy_model=True),
minor: looks like dummy legacy file here is missing `s` at the end. dunesql version uses `token_prices`
this applies to both alias here and file name

2023-09-25 18:05 UTC, jeff-dude commented on dbt_project.yml
> +      +schema: keep3r_network
can you remove lines 829/830 altogether, then add schema property to each model config block next to alias instead?

we're moving towards a cleaner `dbt_project` file in the future, with removing schemas being a big part. easier to keep in the model itself for quick reference to full table name

2023-09-25 18:05 UTC, jeff-dude commented on models/keep3r_network/keep3r_network_job_migration.sql
> +    , unique_key = ['blockchain', 'block_time']
minor: unique key configs on all spells in this PR are not really needed, as they are views. most important for incremental spells.

2023-09-25 23:44 UTC, dune-eng commented
Workflow run id 6306113560 approved.

2023-09-25 23:44 UTC, dune-eng commented
Workflow run id 6306113563 approved.

2023-09-26 12:32 UTC, dune-eng commented
Workflow run id 6312667611 approved.

2023-09-26 12:32 UTC, dune-eng commented
Workflow run id 6312667704 approved.

2023-09-27 20:03 UTC, dune-eng commented
Workflow run id 6330850737 approved.

2023-09-27 20:03 UTC, dune-eng commented
Workflow run id 6330850996 approved.

2023-09-27 20:22 UTC, dune-eng commented
Workflow run id 6331030091 approved.

2023-09-27 20:22 UTC, dune-eng commented
Workflow run id 6331030336 approved.

2023-09-27 20:22 UTC, dune-eng commented
Workflow run id 6331035436 approved.

2023-09-27 20:22 UTC, dune-eng commented
Workflow run id 6331035566 approved.

2023-09-27 20:22 UTC, dune-eng commented
Workflow run id 6331038180 approved.

2023-09-27 20:22 UTC, dune-eng commented
Workflow run id 6331038631 approved.

2023-09-28 09:24 UTC, dune-eng commented
Workflow run id 6337029888 approved.

2023-09-28 09:24 UTC, dune-eng commented
Workflow run id 6337029910 approved.

2023-09-28 12:15 UTC, dune-eng commented
Workflow run id 6338714353 approved.

2023-09-28 12:15 UTC, dune-eng commented
Workflow run id 6338714629 approved.

2023-09-28 12:42 UTC, dune-eng commented
Workflow run id 6339016974 approved.

2023-09-28 12:42 UTC, dune-eng commented
Workflow run id 6339016813 approved.

2023-09-28 17:39 UTC, merged