Updating a RWA Jar Address
duneanalytics/spellbook pull request #4321
Opened 2023-09-12 22:55 UTC by K-Lascar

Hi Dune Team and Contributors, I am apart of the Steakhouse team, we identified an address within the maker accounting ethereum, and have replaced it with the correct address.

2023-09-12 22:56 UTC, dune-eng commented
Workflow run id 6165715207 approved.

2023-09-12 22:56 UTC, dune-eng commented
Workflow run id 6165715295 approved.

2023-09-13 02:15 UTC, Hosuke requested changes

2023-09-13 02:15 UTC, Hosuke commented on models/maker/ethereum/maker_ethereum_accounting.sql
Hi @K-Lascar,
we may need to migrate this spell into dune sql format.

2023-09-13 02:39 UTC, K-Lascar commented on models/maker/ethereum/maker_ethereum_accounting.sql
Hey Hosuke, sure a thing will take a look at revising it into dune sql format.

2023-09-13 03:14 UTC, dune-eng commented
Workflow run id 6167518770 approved.

2023-09-13 03:15 UTC, dune-eng commented
Workflow run id 6167525298 approved.

2023-09-13 03:15 UTC, dune-eng commented
Workflow run id 6167525385 approved.

2023-09-13 05:46 UTC, dune-eng commented
Workflow run id 6168472786 approved.

2023-09-13 05:46 UTC, dune-eng commented
Workflow run id 6168472873 approved.

2023-09-13 06:43 UTC, dune-eng commented
Workflow run id 6168923075 approved.

2023-09-13 06:43 UTC, dune-eng commented
Workflow run id 6168923158 approved.

2023-09-13 07:50 UTC, K-Lascar commented on models/maker/ethereum/maker_ethereum_accounting.sql
Fixed Hosuke, let me know if we're good

2023-09-13 11:12 UTC, dune-eng commented
Workflow run id 6171659826 approved.

2023-09-13 11:12 UTC, dune-eng commented
Workflow run id 6171659832 approved.

2023-09-13 11:54 UTC, Hosuke commented
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/duneanalytics/spellbook/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

Hi @K-Lascar,
you may need to follow instructions here and sign the license agreement before merging.

2023-09-13 11:59 UTC, Hosuke commented on models/maker/ethereum/maker_ethereum_accounting.sql
Do you want to migrate this spell? As legacy spells will be deprecated soon.

2023-09-13 13:41 UTC, jeff-dude approved these changes

2023-09-13 13:42 UTC, jeff-dude commented
gm @K-Lascar thanks for helping contribute in spellbook!

as hosuke mentioned, plz post a gh comment on this PR with the one sentence from the bot above in order to sign the spellbook license agreement. we can't merge until done :)

2023-09-14 01:10 UTC, K-Lascar commented
I have read the CLA Document and I hereby sign the CLA

2023-09-14 01:13 UTC, K-Lascar commented
Thanks Jeff and Hosuke for your help

2023-09-14 17:03 UTC, jeff-dude commented
@Hosuke do you mind migrating this to dunesql in a separate PR?

that way we can keep the history here of a clean edit to legacy file, then we will have a clean history of migration as well

you could pull over to new branch, then start new PR, then revert changes here?

2023-09-15 02:23 UTC, Hosuke commented
> @Hosuke do you mind migrating this to dunesql in a separate PR?
> 
> that way we can keep the history here of a clean edit to legacy file, then we will have a clean history of migration as well
> 
> you could pull over to new branch, then start new PR, then revert changes here?

I have recovered `models/maker/ethereum/maker_ethereum_accounting.sql` from the main branch.

2023-09-15 13:00 UTC, jeff-dude commented
> > @Hosuke do you mind migrating this to dunesql in a separate PR?
> > that way we can keep the history here of a clean edit to legacy file, then we will have a clean history of migration as well
> > you could pull over to new branch, then start new PR, then revert changes here?
> 
> I have recovered `models/maker/ethereum/maker_ethereum_accounting.sql` from the main branch.

thank you!

plz tag me and @web3lyt in the new PR, if you end up migrating 🙏

2023-09-15 16:48 UTC, jeff-dude approved these changes

2023-09-15 16:48 UTC, merged