Migrate some nft ethereum spells
duneanalytics/spellbook pull request #4339
Opened 2023-09-14 17:21 UTC by henrystats

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-09-14 17:22 UTC, dune-eng commented
Workflow run id 6188831091 approved.

2023-09-14 17:22 UTC, dune-eng commented
Workflow run id 6188831272 approved.

2023-09-14 17:36 UTC, dune-eng commented
Workflow run id 6188972137 approved.

2023-09-14 17:36 UTC, dune-eng commented
Workflow run id 6188972310 approved.

2023-09-14 17:45 UTC, dune-eng commented
Workflow run id 6189050265 approved.

2023-09-14 17:45 UTC, dune-eng commented
Workflow run id 6189050352 approved.

2023-09-14 18:02 UTC, dune-eng commented
Workflow run id 6189196016 approved.

2023-09-14 18:02 UTC, dune-eng commented
Workflow run id 6189196329 approved.

2023-09-14 18:23 UTC, dune-eng commented
Workflow run id 6189416980 approved.

2023-09-14 18:23 UTC, dune-eng commented
Workflow run id 6189417082 approved.

2023-09-14 20:16 UTC, dune-eng commented
Workflow run id 6190441595 approved.

2023-09-14 20:16 UTC, dune-eng commented
Workflow run id 6190441859 approved.

2023-09-14 20:25 UTC, dune-eng commented
Workflow run id 6190530596 approved.

2023-09-14 20:25 UTC, dune-eng commented
Workflow run id 6190530695 approved.

2023-09-18 08:13 UTC, 0xRobin requested changes
1 minor comment about the `number_of_items` comparison.

2023-09-18 08:13 UTC, 0xRobin commented on models/nft/ethereum/nft_ethereum_collection_stats.sql
> +        AND CAST(number_of_items as DOUBLE) = 1
```suggestion
        AND number_of_items = UINT256 '1'
```

2023-09-18 08:13 UTC, 0xRobin commented on models/nft/ethereum/nft_ethereum_top_sales.sql
> +        AND CAST(number_of_items as double) = 1
```suggestion
        AND number_of_items = UINT256 '1'
```

2023-09-18 08:13 UTC, 0xRobin commented on models/nft/ethereum/nft_ethereum_wallet_pnl.sql
> +        AND CAST(number_of_items as DOUBLE) = 1
```suggestion
        AND number_of_items = UINT256 '1'
```

2023-09-18 08:13 UTC, 0xRobin commented on models/nft/ethereum/nft_ethereum_wallet_pnl.sql
> +        AND CAST(number_of_items as DOUBLE) = 1
```suggestion
        AND number_of_items = UINT256 '1'
```

2023-09-18 08:13 UTC, 0xRobin commented on models/nft/ethereum/nft_ethereum_wallet_pnl.sql
> +        AND CAST(src.number_of_items as DOUBLE) = 1
```suggestion
        AND src.number_of_items = UINT256 '1'
```

2023-09-18 08:13 UTC, 0xRobin commented on models/nft/ethereum/nft_ethereum_wallet_pnl.sql
> +        AND CAST(src.number_of_items as DOUBLE) = 1
```suggestion
        AND src.number_of_items = UINT256 '1'
```

2023-09-18 08:13 UTC, 0xRobin commented on models/nft/ethereum/nft_ethereum_wallet_pnl.sql
> +        AND CAST(src.number_of_items as DOUBLE) = 1
```suggestion
        AND src.number_of_items = UINT256 '1'
```

2023-09-18 08:13 UTC, 0xRobin commented on models/nft/ethereum/nft_ethereum_wallet_pnl.sql
> +        AND CAST(src.number_of_items as DOUBLE) = 1
```suggestion
        AND src.number_of_items = UINT256 '1'
```

2023-09-19 23:57 UTC, henrystats commented
thank you ser I'll update shortly @0xRobin, the test is failing because the data is different from the spell & the test. Not sure who set up the tests (so I could check against their sources).

But I'll verify against nft.trades data and ensure that the query runs correctly and that the figures are correct from nft.trades at least.

2023-09-20 06:59 UTC, 0xRobin commented
> Not sure who set up the tests (so I could check against their sources).

You set up the test. :smile: 
Note that ` approx_percentile` might produce some different results than the spark equivalent. It is also not deterministic. (the same run might not always result in the exact same result)

2023-09-21 01:30 UTC, dune-eng commented
Workflow run id 6256040277 approved.

2023-09-21 01:30 UTC, dune-eng commented
Workflow run id 6256040375 approved.

2023-09-21 01:31 UTC, dune-eng commented
Workflow run id 6256042857 approved.

2023-09-21 01:31 UTC, dune-eng commented
Workflow run id 6256042875 approved.

2023-09-21 01:41 UTC, dune-eng commented
Workflow run id 6256118461 approved.

2023-09-21 01:41 UTC, dune-eng commented
Workflow run id 6256118679 approved.

2023-09-21 01:42 UTC, dune-eng commented
Workflow run id 6256125029 approved.

2023-09-21 01:42 UTC, dune-eng commented
Workflow run id 6256125084 approved.

2023-09-21 02:10 UTC, dune-eng commented
Workflow run id 6256338252 approved.

2023-09-21 02:10 UTC, dune-eng commented
Workflow run id 6256338184 approved.

2023-09-21 02:27 UTC, dune-eng commented
Workflow run id 6256451455 approved.

2023-09-21 02:27 UTC, dune-eng commented
Workflow run id 6256451410 approved.

2023-09-21 02:44 UTC, henrystats commented
thank you ser @0xRobin this is now ready for review... I actually don't/didn't remember writing this particular test for collection stats, I remembered writing the spells but I must have missed the tests somehow 😆 so I'm thinking someone else wrote them.

At the time the test was written, some trades weren't included in nft.trades (not sure if it was specific projects trades missing or the project had not been added to nft.trades). I double checked the data and trades and saw that they were correct so I updated the test target values.

2023-09-21 08:49 UTC, 0xRobin approved these changes
great work!

2023-09-27 11:03 UTC, 0xRobin commented
@jeff-dude @antonio-mendes @couralex6 let's merge this in.

2023-09-27 13:55 UTC, merged