[WIP] Celo Mento Protocol trades
duneanalytics/spellbook pull request #4413
Opened 2023-09-24 15:34 UTC by tomfutago

Aim: add Mento Protocol to dex.trades

2023-09-24 15:35 UTC, dune-eng commented
Workflow run id 6290937343 approved.

2023-09-24 15:35 UTC, dune-eng commented
Workflow run id 6290937357 approved.

2023-09-25 14:59 UTC, dune-eng commented
Workflow run id 6301154240 approved.

2023-09-25 15:10 UTC, dune-eng commented
Workflow run id 6301302269 approved.

2023-09-25 15:34 UTC, dune-eng commented
Workflow run id 6301582904 approved.

2023-09-25 15:34 UTC, dune-eng commented
Workflow run id 6301583123 approved.

2023-09-25 16:19 UTC, dune-eng commented
Workflow run id 6302060948 approved.

2023-09-25 16:19 UTC, dune-eng commented
Workflow run id 6302061021 approved.

2023-09-25 16:28 UTC, dune-eng commented
Workflow run id 6302152615 approved.

2023-09-25 16:28 UTC, dune-eng commented
Workflow run id 6302152743 approved.

2023-09-25 16:31 UTC, dune-eng commented
Workflow run id 6302186809 approved.

2023-09-25 16:31 UTC, dune-eng commented
Workflow run id 6302186885 approved.

2023-09-26 09:10 UTC, dune-eng commented
Workflow run id 6310528458 approved.

2023-09-26 10:02 UTC, dune-eng commented
Workflow run id 6311087439 approved.

2023-09-26 10:02 UTC, dune-eng commented
Workflow run id 6311087642 approved.

2023-09-26 10:10 UTC, dune-eng commented
Workflow run id 6311179188 approved.

2023-09-26 10:10 UTC, dune-eng commented
Workflow run id 6311179400 approved.

2023-09-26 10:43 UTC, dune-eng commented
Workflow run id 6311527296 approved.

2023-09-26 10:43 UTC, dune-eng commented
Workflow run id 6311527210 approved.

2023-10-04 20:53 UTC, jeff-dude commented
thank you as always @tomfutago 🤝 

we'll let @Hosuke give this a review for ya

2023-10-05 09:29 UTC, Hosuke commented
Given that this PR involves changes to the `dex.trades` macro architecture, I'll be reviewing its compatibility in detail.

2023-10-05 13:53 UTC, jeff-dude commented
> Given that this PR involves changes to the `dex.trades` macro architecture, I'll be reviewing its compatibility in detail.

agreed. we are working internally on redesign of `dex.trades`, so let's pause this a bit until we finalize the uniswap example we're working on here #4533

2023-10-05 23:23 UTC, tomfutago commented
Cool, no worries. I like what's been done under #4533, great work @Hosuke ! Once it's finalised I can update my code to follow the same pattern (when I'm back from holiday next week).

2023-11-06 19:16 UTC, jeff-dude commented
apologies for the delay here, we will try to finalize the linked dex PR this week 🙏

2023-11-10 09:36 UTC, Hosuke requested changes
Hi @tomfutago,
There are some changes need to make to this PR.

Also PR #4533 is ready.

2023-11-10 09:36 UTC, Hosuke commented on models/mento/celo/mento_celo_pools_legacy.sql
We may remove all these `*_legacy.sql` files now.

2023-11-10 09:36 UTC, Hosuke commented on models/mento/celo/mento_celo_pools.sql
> +    alias = alias('pools'),
We can also drop `alias()` functions in all config blocks.
```suggestion
    alias = 'pools',
```

2023-11-11 10:30 UTC, dune-eng commented
Workflow run id 6833695697 approved.

2023-11-11 10:30 UTC, dune-eng commented
Workflow run id 6833695696 approved.

2023-11-11 10:43 UTC, dune-eng commented
Workflow run id 6833748921 approved.

2023-11-11 10:43 UTC, dune-eng commented
Workflow run id 6833748915 approved.

2023-11-11 10:50 UTC, dune-eng commented
Workflow run id 6833771825 approved.

2023-11-11 10:50 UTC, dune-eng commented
Workflow run id 6833771826 approved.

2023-11-11 14:39 UTC, dune-eng commented
Workflow run id 6834865506 approved.

2023-11-11 14:39 UTC, dune-eng commented
Workflow run id 6834865639 approved.

2023-11-11 15:02 UTC, dune-eng commented
Workflow run id 6834953152 approved.

2023-11-11 15:02 UTC, dune-eng commented
Workflow run id 6834953140 approved.

2023-11-11 15:15 UTC, dune-eng commented
Workflow run id 6835027557 approved.

2023-11-11 15:15 UTC, dune-eng commented
Workflow run id 6835027608 approved.

2023-11-11 15:53 UTC, dune-eng commented
Workflow run id 6835187794 approved.

2023-11-11 15:53 UTC, dune-eng commented
Workflow run id 6835187800 approved.

2023-11-11 16:14 UTC, dune-eng commented
Workflow run id 6835288575 approved.

2023-11-11 16:14 UTC, dune-eng commented
Workflow run id 6835288655 approved.

2023-11-11 16:47 UTC, dune-eng commented
Workflow run id 6835435625 approved.

2023-11-11 16:47 UTC, dune-eng commented
Workflow run id 6835435630 approved.

2023-11-11 16:59 UTC, dune-eng commented
Workflow run id 6835475841 approved.

2023-11-11 16:59 UTC, dune-eng commented
Workflow run id 6835475840 approved.

2023-11-12 13:04 UTC, Hosuke approved these changes
LGTM.✅
Thank you @tomfutago 

Clean and nice!

2023-11-12 14:39 UTC, dune-eng commented
Workflow run id 6841328340 approved.

2023-11-12 14:39 UTC, dune-eng commented
Workflow run id 6841328369 approved.

2023-11-12 15:50 UTC, Hosuke approved these changes

2023-11-13 20:59 UTC, jeff-dude reviewed
thank you for the PR 🙏 

a few questions:
- the current state here only feeds into the new `dex.trades_beta`, is that okay for the short term until it replaces `dex.trades` completely? or do you need to add here to include in existing `dex.trades` structure?
- what's the end goal for the `mento_celo_pools` spells?
  - one main reason i ask is due to usage of tokens erc20 metadata within the spells. you are materializing them at the most upstream level with this metadata, which is a pattern we're moving away from in new sector designs, especially since token metadata will soon flip to a source rather than ref (more to come on this!)
  - the goal will be to have all spells which read from them to be a view and/or the end of the dbt lineage, to avoid long lineages and full refresh dependencies all over in orchestration.

2023-11-14 13:32 UTC, tomfutago commented
> * the current state here only feeds into the new `dex.trades_beta`, is that okay for the short term until it replaces `dex.trades` completely? or do you need to add here to include in existing `dex.trades` structure?

yes, adding to `dex.trades_beta` is fine for now

> * what's the end goal for the `mento_celo_pools` spells?
>   
>   * one main reason i ask is due to usage of tokens erc20 metadata within the spells. you are materializing them at the most upstream level with this metadata, which is a pattern we're moving away from in new sector designs, especially since token metadata will soon flip to a source rather than ref (more to come on this!)
>   * the goal will be to have all spells which read from them to be a view and/or the end of the dbt lineage, to avoid long lineages and full refresh dependencies all over in orchestration.

agreed! will remove tokens erc20 refs and bring pool models to follow `dex_pools` model

2023-11-14 13:33 UTC, dune-eng commented
Workflow run id 6864368405 approved.

2023-11-14 13:33 UTC, dune-eng commented
Workflow run id 6864368552 approved.

2023-11-14 15:26 UTC, dune-eng commented
Workflow run id 6865783322 approved.

2023-11-14 15:27 UTC, dune-eng commented
Workflow run id 6865783518 approved.

2023-11-14 15:29 UTC, dune-eng commented
Workflow run id 6865808669 approved.

2023-11-14 15:29 UTC, dune-eng commented
Workflow run id 6865808959 approved.

2023-11-14 15:50 UTC, tomfutago commented
pools updated now

>   * one main reason i ask is due to usage of tokens erc20 metadata within the spells. you are materializing them at the most upstream level with this metadata, which is a pattern we're moving away from in new sector designs, especially since token metadata will soon flip to a source rather than ref (more to come on this!)

on that last bit - exciting stuff! but does it mean my #4762 doesn't have a chance to get in before new magic starts flowing?

2023-11-14 16:08 UTC, jeff-dude reviewed
few comments below

also, this shouldn't happen in this PR, but seems like `dex.pools` is a nice candidate for a redesign like `dex.trades` -- should be a bit easier to do, on number of models alone

2023-11-14 16:08 UTC, jeff-dude commented on models/mento/celo/mento_celo_pools.sql
> +  ref('mento_celo_pools_v2')
similar to `dex.trades` lineage, should these be named as below?
`mento_v1_celo_pools`
`mento_v2_celo_pools`

2023-11-14 16:08 UTC, jeff-dude commented on models/mento/celo/mento_celo_pools.sql
> +  ref('mento_celo_pools_v2')
would mean changes to file names, config settings, refs, etc etc

2023-11-14 16:08 UTC, jeff-dude commented on models/mento/celo/mento_celo_pools_v1.sql
> +  'v1' as version,
can you do me a favor and double check the usage of `version` in other dex pool models? do they preface with `v` in front of the version number?

2023-11-14 16:08 UTC, jeff-dude commented on models/mento/celo/mento_celo_pools_v1.sql
> +    materialized = 'table'
any reason v1 is full table refresh each time, while v2 is incremental?

2023-11-14 16:09 UTC, jeff-dude commented
> on that last bit - exciting stuff! but does it mean my #4762 doesn't have a chance to get in before new magic starts flowing?

nope, these will continue until that work is final. it's in a PoC phase at the moment. i'll get it merged soon 🤝

2023-11-14 16:59 UTC, jeff-dude commented on models/mento/celo/mento_celo_pools_v1.sql
> +  'v1' as version,
yeah, we can fix in later PR for others, no worries

2023-11-14 17:01 UTC, jeff-dude commented
> @hildobby do you want to take it over as you were the one who created dex.pools originally?

no rush here. if not prioritized, dune team will get to it eventually. just focusing on most commonly used ones first

2023-11-14 18:19 UTC, jeff-dude approved these changes
looks good -- thank you!

2023-11-14 18:20 UTC, jeff-dude commented
fyi @Hosuke 
after this is merged, you may want to pull in from main branch into your open PR for cleaning up seed tests on dex trades new lineage for the mento project here

2023-11-14 21:21 UTC, merged