Add zkSync to `nft.transfers`
duneanalytics/spellbook pull request #4529
Opened 2023-10-05 00:31 UTC by hildobby

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-10-05 15:56 UTC, aalan3 commented on models/nft/zksync/nft_zksync_transfers_legacy.sql
> +{{ config(
This file can just be a dummy.

2023-10-05 16:02 UTC, hildobby commented on models/nft/chains/nft_zksync_transfers.sql
> +        pre_hook='{{ enforce_join_distribution("PARTITIONED") }}'
sure sg, just copied the spell from another chain here but I'll remove it

2023-10-19 18:25 UTC, aalan3 approved these changes

2023-10-19 21:55 UTC, jeff-dude requested changes

2023-10-19 21:55 UTC, jeff-dude commented on models/_sector/nft/transfers/legacy/nft_zksync_transfers_legacy.sql
you can remove the legacy file now 🙏

2023-10-19 21:55 UTC, jeff-dude commented on models/_sector/nft/transfers/legacy/nft_transfers_legacy.sql
you can remove this modification, we will remove all existing legacy files soon

2023-10-19 23:47 UTC, jeff-dude approved these changes

2023-10-19 23:47 UTC, merged