Add zkSync to `prices`
duneanalytics/spellbook pull request #4551
Opened 2023-10-06 21:27 UTC by lgingerich

2023-10-06 21:27 UTC, dune-eng commented
Workflow run id 6436637208 approved.

2023-10-06 21:27 UTC, dune-eng commented
Workflow run id 6436637198 approved.

2023-10-06 21:27 UTC, dune-eng commented
Workflow run id 6436637060 approved.

2023-10-07 03:37 UTC, Hosuke commented
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/duneanalytics/spellbook/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

GM @lgingerich , thank you for your contribution, but first you may need to follow the instruction and sign the CLA before we continue processing the PR.

2023-10-11 13:10 UTC, lgingerich commented
recheck

2023-10-11 15:06 UTC, Hosuke commented
BTW currently `zksync` data may not be supported on dune.

2023-10-13 18:26 UTC, lgingerich commented
@Hosuke thanks, I see what you mean.

`token-prices-test` fails because CoinPaprika doesn't currently support zkSync Era as a contract platform.

Do you have contact with CoinPaprika so that we can get zkSync added?

2023-10-14 09:51 UTC, Hosuke commented
> @Hosuke thanks, I see what you mean.
> 
> `token-prices-test` fails because CoinPaprika doesn't currently support zkSync Era as a contract platform.
> 
> Do you have contact with CoinPaprika so that we can get zkSync added?

I can fix that if the tokens you added are also available on other chains(multi-chains).

2023-10-14 10:50 UTC, Hosuke approved these changes
LGTM.✅
Thank you @lgingerich

2023-10-18 20:47 UTC, jeff-dude requested changes

2023-10-18 20:47 UTC, jeff-dude commented on models/prices/prices_tokens.sql
> +        post_hook = '{{ expose_spells(\'["ethereum", "solana", "arbitrum", "gnosis", "optimism", "bnb", "avalanche_c", "polygon", "fantom", "celo", "base", "lgingerich"]\',
looks like copy/paste typo here?

2023-10-18 20:47 UTC, jeff-dude commented on models/prices/zksync/prices_zksync_tokens_legacy.sql
we no longer need legacy files, as we've turned off legacy spark dbt jobs 🙌 
you can safely remove here (and any future/current PRs)
we will try to get readme updated and some sort of communication out

2023-10-22 20:15 UTC, dune-eng commented
Workflow run id 6605981047 approved.

2023-10-22 20:15 UTC, dune-eng commented
Workflow run id 6605981046 approved.

2023-10-22 20:15 UTC, dune-eng commented
Workflow run id 6605981049 approved.

2023-10-22 20:15 UTC, dune-eng commented
Workflow run id 6605981048 approved.

2023-10-22 20:20 UTC, lgingerich commented on models/prices/prices_tokens.sql
> +        post_hook = '{{ expose_spells(\'["ethereum", "solana", "arbitrum", "gnosis", "optimism", "bnb", "avalanche_c", "polygon", "fantom", "celo", "base", "lgingerich"]\',
ahh yes, thank you! fixed

2023-10-22 20:23 UTC, dune-eng commented
Workflow run id 6606018672 approved.

2023-10-22 20:23 UTC, dune-eng commented
Workflow run id 6606018667 approved.

2023-10-22 20:23 UTC, dune-eng commented
Workflow run id 6606018671 approved.

2023-10-22 20:23 UTC, dune-eng commented
Workflow run id 6606018629 approved.

2023-10-23 16:06 UTC, jeff-dude approved these changes

2023-10-23 16:16 UTC, merged