Add dodo base
duneanalytics/spellbook pull request #4559
Opened 2023-10-08 09:28 UTC by owen05

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-10-08 09:29 UTC, dune-eng commented
Workflow run id 6446804391 approved.

2023-10-08 09:29 UTC, dune-eng commented
Workflow run id 6446804504 approved.

2023-10-08 09:49 UTC, dune-eng commented
Workflow run id 6446885871 approved.

2023-10-08 09:49 UTC, dune-eng commented
Workflow run id 6446885925 approved.

2023-10-08 10:02 UTC, dune-eng commented
Workflow run id 6446935634 approved.

2023-10-08 10:03 UTC, dune-eng commented
Workflow run id 6446935670 approved.

2023-10-08 10:11 UTC, dune-eng commented
Workflow run id 6446983144 approved.

2023-10-08 10:11 UTC, dune-eng commented
Workflow run id 6446983187 approved.

2023-10-08 10:24 UTC, dune-eng commented
Workflow run id 6447055535 approved.

2023-10-08 10:24 UTC, dune-eng commented
Workflow run id 6447055606 approved.

2023-10-08 11:16 UTC, dune-eng commented
Workflow run id 6447282519 approved.

2023-10-08 11:16 UTC, dune-eng commented
Workflow run id 6447282581 approved.

2023-10-08 14:32 UTC, dune-eng commented
Workflow run id 6448230448 approved.

2023-10-08 14:32 UTC, dune-eng commented
Workflow run id 6448230481 approved.

2023-10-08 15:08 UTC, dune-eng commented
Workflow run id 6448382308 approved.

2023-10-08 15:08 UTC, dune-eng commented
Workflow run id 6448382126 approved.

2023-10-10 00:14 UTC, Hosuke requested changes
The `project` using as a joining column with seed is varchar typed, hence it is case sensitive in the setting.

2023-10-10 00:14 UTC, Hosuke commented on models/dodo/arbitrum/dodo_arbitrum_schema.yml
> +          project: DODO
Since `project` is varchar typed, it is case-sensitive.
```suggestion
          project: dodo
```

2023-10-10 00:14 UTC, Hosuke commented on models/dodo/polygon/dodo_polygon_schema.yml
> +          project: DODO
Same as here.
```suggestion
          project: dodo
```

2023-10-10 00:14 UTC, Hosuke commented on models/dodo/ethereum/dodo_ethereum_schema.yml
> +          project: DODO
Here also.
```suggestion
          project: dodo
```

2023-10-10 00:14 UTC, Hosuke commented on models/dodo/bnb/dodo_bnb_schema.yml
> +          project: DODO
```suggestion
          project: dodo
```

2023-10-10 00:14 UTC, Hosuke commented on models/dodo/base/dodo_base_schema.yml
> +          project: DODO
```suggestion
          project: dodo
```

2023-10-10 00:14 UTC, Hosuke commented on models/dodo/base/dodo_base_schema.yml
> +          project: DODO
```suggestion
          project: dodo
```

2023-10-10 00:37 UTC, Hosuke requested changes
There may be some unmatched seed records.
Please verify the seed.

2023-10-10 03:48 UTC, dune-eng commented
Workflow run id 6464481781 approved.

2023-10-10 03:48 UTC, dune-eng commented
Workflow run id 6464481885 approved.

2023-10-10 05:03 UTC, Hosuke requested changes

2023-10-10 05:03 UTC, Hosuke commented on seeds/dex/aggregator/dex_aggregator_seed.csv
> +ethereum,DODO_X,0,2022-10-30,0x24d3b64dca789018552b6f61eeed88632635dae60ec6762c437d61a57053eb90,285,,0xdac17f958d2ee523a2206206994597c13d831ec7,3271.009257,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,
If you use `DODO X` in the model, then due to join condition, this would be `DODO X` not `DODO_X` as well?

2023-10-10 05:22 UTC, dune-eng commented
Workflow run id 6465083921 approved.

2023-10-10 05:22 UTC, dune-eng commented
Workflow run id 6465083998 approved.

2023-10-10 06:05 UTC, dune-eng commented
Workflow run id 6465362864 approved.

2023-10-10 06:05 UTC, dune-eng commented
Workflow run id 6465362974 approved.

2023-10-10 06:44 UTC, dune-eng commented
Workflow run id 6465689993 approved.

2023-10-10 06:44 UTC, dune-eng commented
Workflow run id 6465689885 approved.

2023-10-10 08:05 UTC, dune-eng commented
Workflow run id 6466444428 approved.

2023-10-10 08:05 UTC, dune-eng commented
Workflow run id 6466444539 approved.

2023-10-10 08:41 UTC, dune-eng commented
Workflow run id 6466844437 approved.

2023-10-10 08:41 UTC, dune-eng commented
Workflow run id 6466844289 approved.

2023-10-10 09:23 UTC, dune-eng commented
Workflow run id 6467316095 approved.

2023-10-10 09:23 UTC, dune-eng commented
Workflow run id 6467316383 approved.

2023-10-10 12:23 UTC, dune-eng commented
Workflow run id 6469199782 approved.

2023-10-10 12:23 UTC, dune-eng commented
Workflow run id 6469199865 approved.

2023-10-10 13:34 UTC, dune-eng commented
Workflow run id 6470074817 approved.

2023-10-10 13:34 UTC, dune-eng commented
Workflow run id 6470075028 approved.

2023-10-10 13:57 UTC, dune-eng commented
Workflow run id 6470350668 approved.

2023-10-10 13:57 UTC, dune-eng commented
Workflow run id 6470351078 approved.

2023-10-10 14:07 UTC, dune-eng commented
Workflow run id 6470479784 approved.

2023-10-11 04:04 UTC, Hosuke approved these changes
LGTM.✅
Thank you @owen05 

[Sample dodo_pools_base_trades](https://dune.com/queries/3095273)
[Sample dodo_aggregator_base_trades](https://dune.com/queries/3095275)

2023-10-16 18:28 UTC, jeff-dude approved these changes

2023-10-16 19:10 UTC, merged