feat: add Camelot v3 trades spellbook
duneanalytics/spellbook pull request #4605
Opened 2023-10-14 21:11 UTC by whalehunting

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-10-14 21:12 UTC, dune-eng commented
Workflow run id 6519988735 approved.

2023-10-14 21:12 UTC, dune-eng commented
Workflow run id 6519988655 approved.

2023-10-15 17:02 UTC, dune-eng commented
Workflow run id 6525357957 approved.

2023-10-15 17:02 UTC, dune-eng commented
Workflow run id 6525357881 approved.

2023-10-15 17:11 UTC, dune-eng commented
Workflow run id 6525403647 approved.

2023-10-15 17:11 UTC, dune-eng commented
Workflow run id 6525403696 approved.

2023-10-15 17:12 UTC, dune-eng commented
Workflow run id 6525410108 approved.

2023-10-15 17:12 UTC, dune-eng commented
Workflow run id 6525410254 approved.

2023-10-15 17:15 UTC, dune-eng commented
Workflow run id 6525427845 approved.

2023-10-15 17:15 UTC, dune-eng commented
Workflow run id 6525427889 approved.

2023-10-15 17:39 UTC, dune-eng commented
Workflow run id 6525547689 approved.

2023-10-15 17:39 UTC, dune-eng commented
Workflow run id 6525547620 approved.

2023-10-15 18:08 UTC, dune-eng commented
Workflow run id 6525666568 approved.

2023-10-15 18:08 UTC, dune-eng commented
Workflow run id 6525666447 approved.

2023-10-15 18:27 UTC, dune-eng commented
Workflow run id 6525774023 approved.

2023-10-15 18:27 UTC, dune-eng commented
Workflow run id 6525774070 approved.

2023-10-15 18:36 UTC, dune-eng commented
Workflow run id 6525819203 approved.

2023-10-15 18:36 UTC, dune-eng commented
Workflow run id 6525819269 approved.

2023-10-15 18:45 UTC, dune-eng commented
Workflow run id 6525856745 approved.

2023-10-15 18:45 UTC, dune-eng commented
Workflow run id 6525856777 approved.

2023-10-15 18:47 UTC, dune-eng commented
Workflow run id 6525861743 approved.

2023-10-15 18:47 UTC, dune-eng commented
Workflow run id 6525861784 approved.

2023-10-15 19:26 UTC, dune-eng commented
Workflow run id 6526038922 approved.

2023-10-15 19:26 UTC, dune-eng commented
Workflow run id 6526038960 approved.

2023-10-18 03:07 UTC, Hosuke commented on models/camelot/arbitrum/camelot_arbitrum_trades_legacy.sql
Since this is an existed legacy spell, we can keep this file untouched.

2023-10-18 03:28 UTC, Hosuke requested changes

2023-10-18 03:28 UTC, Hosuke commented on models/camelot/arbitrum/camelot_v3_arbitrum_trades.sql
> +  WHERE swaps.evt_block_time >= date_trunc('day', now() - interval '7' day)
We can use `incremental_predicate` to rewrite these incremental filters:
```suggestion
  WHERE {{incremental_predicate('swaps.evt_block_time')}}
```

2023-10-18 03:48 UTC, Hosuke approved these changes
LGTM.✅
Thank you @whalehunting 

[Sample camelot_v3_arbitrum_trades]()

2023-10-18 17:38 UTC, jeff-dude approved these changes
awesome -- welcome to spellbook!

thanks for the PR & to @Hosuke for the support as always 🙌

2023-10-18 17:39 UTC, jeff-dude commented
for your awareness, we are in the process of redesigning the `dex.trades` spell lineage, so this will change a bit in the near future. no changes needed now, but will be nice for ya to follow along as we proceed to make future contributions smooth 🤝

2023-10-18 17:39 UTC, merged