Feature/read requests
duneanalytics/spellbook pull request #4617
Opened 2023-10-16 21:20 UTC by AnonJon

Add Chainlink Read Requests
- requests on feeds daily
- requesters daily to see what protocol are using the feeds

2023-10-16 21:21 UTC, dune-eng commented
Workflow run id 6539409126 approved.

2023-10-16 21:21 UTC, dune-eng commented
Workflow run id 6539409494 approved.

2023-10-16 21:30 UTC, dune-eng commented
Workflow run id 6539489138 approved.

2023-10-16 21:30 UTC, dune-eng commented
Workflow run id 6539489235 approved.

2023-10-16 22:00 UTC, dune-eng commented
Workflow run id 6539716283 approved.

2023-10-16 22:00 UTC, dune-eng commented
Workflow run id 6539716198 approved.

2023-10-16 22:30 UTC, dune-eng commented
Workflow run id 6539990341 approved.

2023-10-16 22:30 UTC, dune-eng commented
Workflow run id 6539990261 approved.

2023-10-17 01:08 UTC, dune-eng commented
Workflow run id 6541179253 approved.

2023-10-17 01:08 UTC, dune-eng commented
Workflow run id 6541179443 approved.

2023-10-17 01:40 UTC, dune-eng commented
Workflow run id 6541411455 approved.

2023-10-17 01:50 UTC, dune-eng commented
Workflow run id 6541490606 approved.

2023-10-17 01:50 UTC, dune-eng commented
Workflow run id 6541490660 approved.

2023-10-17 02:02 UTC, dune-eng commented
Workflow run id 6541580299 approved.

2023-10-17 02:02 UTC, dune-eng commented
Workflow run id 6541580544 approved.

2023-10-17 02:20 UTC, dune-eng commented
Workflow run id 6541717409 approved.

2023-10-17 02:20 UTC, dune-eng commented
Workflow run id 6541717472 approved.

2023-10-17 02:21 UTC, dune-eng commented
Workflow run id 6541726964 approved.

2023-10-17 02:21 UTC, dune-eng commented
Workflow run id 6541726860 approved.

2023-10-17 02:36 UTC, dune-eng commented
Workflow run id 6541824911 approved.

2023-10-17 02:36 UTC, dune-eng commented
Workflow run id 6541825072 approved.

2023-10-17 02:53 UTC, dune-eng commented
Workflow run id 6541925704 approved.

2023-10-17 02:53 UTC, dune-eng commented
Workflow run id 6541925741 approved.

2023-10-17 03:13 UTC, dune-eng commented
Workflow run id 6542054336 approved.

2023-10-17 03:13 UTC, dune-eng commented
Workflow run id 6542054486 approved.

2023-10-17 12:53 UTC, dune-eng commented
Workflow run id 6547449137 approved.

2023-10-17 12:53 UTC, dune-eng commented
Workflow run id 6547449324 approved.

2023-10-17 13:30 UTC, dune-eng commented
Workflow run id 6547933425 approved.

2023-10-17 13:30 UTC, dune-eng commented
Workflow run id 6547933575 approved.

2023-10-17 14:00 UTC, dune-eng commented
Workflow run id 6548291676 approved.

2023-10-17 14:47 UTC, dune-eng commented
Workflow run id 6548911234 approved.

2023-10-17 14:47 UTC, dune-eng commented
Workflow run id 6548911131 approved.

2023-10-17 23:38 UTC, dune-eng commented
Workflow run id 6554099734 approved.

2023-10-17 23:38 UTC, dune-eng commented
Workflow run id 6554099882 approved.

2023-10-18 15:21 UTC, dune-eng commented
Workflow run id 6563034949 approved.

2023-10-18 15:21 UTC, dune-eng commented
Workflow run id 6563035194 approved.

2023-10-18 17:21 UTC, dune-eng commented
Workflow run id 6564366311 approved.

2023-10-18 17:21 UTC, dune-eng commented
Workflow run id 6564366360 approved.

2023-10-18 20:24 UTC, dune-eng commented
Workflow run id 6566173539 approved.

2023-10-18 20:24 UTC, dune-eng commented
Workflow run id 6566173762 approved.

2023-10-19 13:18 UTC, dune-eng commented
Workflow run id 6575199016 approved.

2023-10-19 13:18 UTC, dune-eng commented
Workflow run id 6575199317 approved.

2023-10-19 15:43 UTC, dune-eng commented
Workflow run id 6577021310 approved.

2023-10-19 15:43 UTC, dune-eng commented
Workflow run id 6577021453 approved.

2023-10-19 23:48 UTC, jeff-dude commented
@Hosuke another one in the chainlink directory, should be similar to the last one 👍  thank you!

2023-10-19 23:53 UTC, Hosuke requested changes

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/arbitrum/chainlink_arbitrum_read_requests_feeds_daily.sql
> +   date_start >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
We can use `incremental_predicate` to rewrite all the incremental filters:
i.e.
```suggestion
   {{ incremental_predicate('date_start') }}
```

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/arbitrum/chainlink_arbitrum_read_requests_requester_daily.sql
> +  WHERE read_requests_requester.date_start >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
Same as above.

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/avalanche_c/chainlink_avalanche_c_read_requests_feeds_daily.sql
> +   date_start >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
Same as above.

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/avalanche_c/chainlink_avalanche_c_read_requests_requester_daily.sql
> +  WHERE read_requests_requester.date_start >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
Same as above.

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/bnb/chainlink_bnb_read_requests_feeds_daily.sql
> +   date_start >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
Same as above.

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/bnb/chainlink_bnb_read_requests_requester_daily.sql
> +  WHERE read_requests_requester.date_start >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
Same as above.

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/ethereum/chainlink_ethereum_read_requests_feeds_daily.sql
> +   date_start >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
Same as above.

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/ethereum/chainlink_ethereum_read_requests_requester_daily.sql
> +  WHERE read_requests_requester.date_start >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
Same as above.

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/optimism/chainlink_optimism_read_requests_feeds_daily.sql
> +   date_start >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
Same as above.

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/optimism/chainlink_optimism_read_requests_requester_daily.sql
> +  WHERE read_requests_requester.date_start >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
Same as above.

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/polygon/chainlink_polygon_read_requests_feeds_daily.sql
> +   date_start >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
Same as above.

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/polygon/chainlink_polygon_read_requests_requester_daily.sql
> +  WHERE read_requests_requester.date_start >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
Same as above.

2023-10-19 23:53 UTC, Hosuke commented on models/chainlink/polygon/chainlink_polygon_read_requests_requester_daily.sql
> +{% set incremental_interval = '7' %}
After `incremantal_predicate` used, we can remove these jinja variables.
```suggestion
```

2023-10-20 01:06 UTC, dune-eng commented
Workflow run id 6582067908 approved.

2023-10-20 01:06 UTC, dune-eng commented
Workflow run id 6582068032 approved.

2023-10-20 01:38 UTC, AnonJon commented
Requested changes have been added.

2023-10-20 04:33 UTC, Hosuke approved these changes
LGTM.✅
Thank you @AnonJon

2023-10-20 13:32 UTC, dune-eng commented
Workflow run id 6588415859 approved.

2023-10-20 13:32 UTC, dune-eng commented
Workflow run id 6588415880 approved.

2023-10-20 18:25 UTC, jeff-dude approved these changes
thanks both!

2023-10-20 18:26 UTC, merged