Add staking entities
duneanalytics/spellbook pull request #4621
Opened 2023-10-17 19:18 UTC by hildobby

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-10-23 16:01 UTC, jeff-dude requested changes

2023-10-23 16:01 UTC, jeff-dude commented on models/staking/ethereum/entities/staking_ethereum_entities_withdrawal_credentials.sql
does this need to be incremental? seems static?

2023-10-23 16:04 UTC, hildobby commented on models/staking/ethereum/entities/staking_ethereum_entities_withdrawal_credentials.sql
Ah good call, just changed it to a static spell

2023-10-24 16:39 UTC, jeff-dude approved these changes

2023-10-24 16:39 UTC, jeff-dude commented on models/staking/ethereum/staking_ethereum_schema.yml
> +                where: "depositor_address is not null"
thanks again @0xRobin for help here -- this will be another good example to include in a "best practices guide" to spellbook

2023-10-25 14:00 UTC, merged