added openocean dex
duneanalytics/spellbook pull request #4632
Opened 2023-10-19 05:00 UTC by ARDev097

added trades data for openocean dex

2023-10-19 05:01 UTC, dune-eng commented
Workflow run id 6570071986 approved.

2023-10-19 05:06 UTC, ARDev097 commented
Hello @Hosuke ,
I have added spellbook for openocean dex, but all checks are not running due to some conflicts. Please look into it.

2023-10-19 05:17 UTC, dune-eng commented
Workflow run id 6570195265 approved.

2023-10-19 05:17 UTC, dune-eng commented
Workflow run id 6570195381 approved.

2023-10-19 05:29 UTC, dune-eng commented
Workflow run id 6570288801 approved.

2023-10-19 05:29 UTC, dune-eng commented
Workflow run id 6570288861 approved.

2023-10-19 14:01 UTC, Hosuke requested changes

2023-10-19 14:01 UTC, Hosuke commented on models/openocean/optimism/openocean_v2_optimism_trades.sql
> +    AND p_bought.minute >= date_trunc('day', now() - interval '7' day)
Here as well.

2023-10-19 14:01 UTC, Hosuke commented on models/openocean/optimism/openocean_v2_optimism_trades.sql
> +    AND p_sold.minute >= date_trunc('day', now() - interval '7' day)
Same as above.

2023-10-20 03:55 UTC, dune-eng commented
Workflow run id 6583172883 approved.

2023-10-20 03:55 UTC, dune-eng commented
Workflow run id 6583173027 approved.

2023-10-20 04:16 UTC, dune-eng commented
Workflow run id 6583307544 approved.

2023-10-20 04:16 UTC, dune-eng commented
Workflow run id 6583307622 approved.

2023-10-20 04:32 UTC, dune-eng commented
Workflow run id 6583403920 approved.

2023-10-20 04:32 UTC, dune-eng commented
Workflow run id 6583403979 approved.

2023-10-20 09:59 UTC, Hosuke requested changes

2023-10-20 09:59 UTC, Hosuke commented on models/openocean/optimism/openocean_optimism_schema.yml
> +  - name: openocean_v2_optimism_trades
We can add roll-up spells like `openocean.trades` or `openocean_optimism.trades`, if there will be other versions of the dex.

2023-10-20 11:29 UTC, dune-eng commented
Workflow run id 6587107599 approved.

2023-10-20 11:29 UTC, dune-eng commented
Workflow run id 6587107676 approved.

2023-10-20 11:32 UTC, dune-eng commented
Workflow run id 6587131794 approved.

2023-10-20 11:33 UTC, dune-eng commented
Workflow run id 6587147075 approved.

2023-10-20 11:39 UTC, dune-eng commented
Workflow run id 6587207707 approved.

2023-10-20 11:43 UTC, dune-eng commented
Workflow run id 6587246538 approved.

2023-10-20 11:43 UTC, dune-eng commented
Workflow run id 6587246429 approved.

2023-10-21 03:04 UTC, dune-eng commented
Workflow run id 6594869850 approved.

2023-10-21 03:04 UTC, dune-eng commented
Workflow run id 6594870020 approved.

2023-10-21 03:23 UTC, dune-eng commented
Workflow run id 6594975579 approved.

2023-10-21 03:23 UTC, dune-eng commented
Workflow run id 6594975503 approved.

2023-10-21 03:25 UTC, dune-eng commented
Workflow run id 6594983024 approved.

2023-10-21 03:25 UTC, dune-eng commented
Workflow run id 6594983050 approved.

2023-10-21 04:18 UTC, dune-eng commented
Workflow run id 6595198269 approved.

2023-10-21 04:18 UTC, dune-eng commented
Workflow run id 6595198359 approved.

2023-10-21 04:47 UTC, dune-eng commented
Workflow run id 6595321195 approved.

2023-10-21 04:47 UTC, dune-eng commented
Workflow run id 6595321241 approved.

2023-10-21 11:18 UTC, Hosuke commented on models/openocean/optimism/openocean_optimism_trades.sql
> +    schema = 'openocean_v2_optimism',
```suggestion
    schema = 'openocean_optimism',
```

2023-10-21 11:19 UTC, Hosuke approved these changes
LGTM.✅
Thank you @ARDev097 

[Sample openocean_optimism_trades](https://dune.com/queries/3132468)

2023-10-22 04:02 UTC, dune-eng commented
Workflow run id 6601552944 approved.

2023-10-22 04:02 UTC, dune-eng commented
Workflow run id 6601552972 approved.

2023-10-23 03:52 UTC, Hosuke commented on models/openocean/optimism/openocean_optimism_trades.sql
> +    )
By the way we may add a post_hook here to expose this model.
And `trace_address` may not be needed anymore.
```suggestion
    unique_key = ['block_date', 'blockchain', 'project', 'version', 'tx_hash', 'evt_index'],
    post_hook='{{ expose_spells(\'["optimism"]\',
                                "project",
                                "openocean",
                                \'["ARDev097"]\') }}'
    )
```

2023-10-23 03:53 UTC, Hosuke commented on models/openocean/optimism/openocean_optimism_schema.yml
> +            - trace_address
```suggestion
```

2023-10-23 15:43 UTC, jeff-dude approved these changes
we can remove `trace_address` when we refactor for new design in the near future, otherwise lgtm and we can merge 👍

2023-10-23 16:15 UTC, merged