Add Zora to Tokens Tables
duneanalytics/spellbook pull request #4798
Opened 2023-11-15 14:43 UTC by MSilb7

Adds Zora to ERC20/NFT tokens tables - based on a copy of Base.

2023-11-15 14:44 UTC, dune-eng commented
Workflow run id 6878827847 approved.

2023-11-15 14:44 UTC, dune-eng commented
Workflow run id 6878827692 approved.

2023-11-15 15:00 UTC, dune-eng commented
Workflow run id 6879013095 approved.

2023-11-15 15:00 UTC, dune-eng commented
Workflow run id 6879013445 approved.

2023-11-15 22:53 UTC, dune-eng commented
Workflow run id 6883866594 approved.

2023-11-15 22:53 UTC, dune-eng commented
Workflow run id 6883866445 approved.

2023-11-17 19:19 UTC, jeff-dude requested changes

2023-11-17 19:19 UTC, jeff-dude commented on models/tokens/tokens_erc20.sql
> +SELECT 'zksync' as blockchain, contract_address, symbol, decimals FROM {{ ref('tokens_zora_erc20') }}
update blockchain to zora plz

2023-11-17 22:58 UTC, MSilb7 commented on models/tokens/tokens_erc20.sql
> +SELECT 'zksync' as blockchain, contract_address, symbol, decimals FROM {{ ref('tokens_zora_erc20') }}
lol whoops

2023-11-17 22:58 UTC, dune-eng commented
Workflow run id 6909923451 approved.

2023-11-17 22:58 UTC, MSilb7 commented
resolved @jeff-dude

2023-11-17 22:58 UTC, dune-eng commented
Workflow run id 6909923587 approved.

2023-11-17 22:59 UTC, dune-eng commented
Workflow run id 6909924919 approved.

2023-11-17 22:59 UTC, dune-eng commented
Workflow run id 6909924927 approved.

2023-11-20 19:07 UTC, jeff-dude approved these changes
thank you ser 🤝

2023-11-21 14:50 UTC, merged