Arbitrum bridges
duneanalytics/spellbook pull request #4809
Opened 2023-11-16 01:20 UTC by RantumBits

Arbitrum bridges

2023-11-16 01:21 UTC, dune-eng commented
Workflow run id 6885035278 approved.

2023-11-16 01:21 UTC, dune-eng commented
Workflow run id 6885035496 approved.

2023-11-16 01:36 UTC, dune-eng commented
Workflow run id 6885147761 approved.

2023-11-16 01:36 UTC, dune-eng commented
Workflow run id 6885147885 approved.

2023-11-16 01:47 UTC, dune-eng commented
Workflow run id 6885236146 approved.

2023-11-16 01:47 UTC, dune-eng commented
Workflow run id 6885236243 approved.

2023-11-17 18:56 UTC, dune-eng commented
Workflow run id 6907965150 approved.

2023-11-17 18:56 UTC, dune-eng commented
Workflow run id 6907965232 approved.

2023-11-17 19:17 UTC, dune-eng commented
Workflow run id 6908162713 approved.

2023-11-17 19:17 UTC, dune-eng commented
Workflow run id 6908162627 approved.

2023-11-17 19:43 UTC, dune-eng commented
Workflow run id 6908375415 approved.

2023-11-17 19:43 UTC, dune-eng commented
Workflow run id 6908375574 approved.

2023-11-20 20:48 UTC, jeff-dude requested changes
plz apply same requested changes from #4827

2023-11-20 22:53 UTC, dune-eng commented
Workflow run id 6936753079 approved.

2023-11-20 22:53 UTC, dune-eng commented
Workflow run id 6936753206 approved.

2023-11-21 20:51 UTC, RantumBits commented
merged with #4810

2023-11-21 20:51 UTC, closed without merging