Polygon bridges
duneanalytics/spellbook pull request #4810
Opened 2023-11-16 01:57 UTC by RantumBits

Polygon bridges

2023-11-16 01:58 UTC, dune-eng commented
Workflow run id 6885316786 approved.

2023-11-16 01:58 UTC, dune-eng commented
Workflow run id 6885317013 approved.

2023-11-16 02:14 UTC, dune-eng commented
Workflow run id 6885445548 approved.

2023-11-16 02:14 UTC, dune-eng commented
Workflow run id 6885445856 approved.

2023-11-17 19:39 UTC, dune-eng commented
Workflow run id 6908349064 approved.

2023-11-17 19:39 UTC, dune-eng commented
Workflow run id 6908349108 approved.

2023-11-17 19:39 UTC, dune-eng commented
Workflow run id 6908349948 approved.

2023-11-17 19:40 UTC, dune-eng commented
Workflow run id 6908350031 approved.

2023-11-17 20:00 UTC, dune-eng commented
Workflow run id 6908509162 approved.

2023-11-17 20:00 UTC, dune-eng commented
Workflow run id 6908509227 approved.

2023-11-20 20:48 UTC, jeff-dude requested changes
plz apply same requested changes from #4827

2023-11-20 23:00 UTC, dune-eng commented
Workflow run id 6936800247 approved.

2023-11-20 23:00 UTC, dune-eng commented
Workflow run id 6936800394 approved.

2023-11-20 23:15 UTC, dune-eng commented
Workflow run id 6936938052 approved.

2023-11-20 23:15 UTC, dune-eng commented
Workflow run id 6936938272 approved.

2023-11-20 23:32 UTC, dune-eng commented
Workflow run id 6937070927 approved.

2023-11-20 23:50 UTC, dune-eng commented
Workflow run id 6937199285 approved.

2023-11-20 23:50 UTC, dune-eng commented
Workflow run id 6937199309 approved.

2023-11-20 23:57 UTC, dune-eng commented
Workflow run id 6937238805 approved.

2023-11-20 23:57 UTC, dune-eng commented
Workflow run id 6937238872 approved.

2023-11-21 14:55 UTC, jeff-dude approved these changes

2023-11-21 15:04 UTC, jeff-dude commented
@RantumBits can we merge all your open PRs for bridges into one? normally, breaking out is the ideal approach, but the labels spell is failing due to others not existing (yet, since it was just merged and not run in prod yet). otherwise, merging each will take awhile to wait for each to be created in prod.

2023-11-21 18:15 UTC, dune-eng commented
Workflow run id 6947927971 approved.

2023-11-21 18:15 UTC, dune-eng commented
Workflow run id 6947928087 approved.

2023-11-21 20:41 UTC, dune-eng commented
Workflow run id 6949327864 approved.

2023-11-21 20:41 UTC, dune-eng commented
Workflow run id 6949327641 approved.

2023-11-21 20:48 UTC, RantumBits commented
merged #4810 (poly bridges) and #4809 (arb bridges) here @jeff-dude. bnb is WIP

2023-11-21 20:51 UTC, dune-eng commented
Workflow run id 6949406537 approved.

2023-11-21 20:51 UTC, dune-eng commented
Workflow run id 6949409889 approved.

2023-11-22 15:29 UTC, jeff-dude approved these changes

2023-11-22 16:03 UTC, merged