Add polygon mooar nft models
duneanalytics/spellbook pull request #4835
Opened 2023-11-20 05:21 UTC by BennyFeng

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-11-20 05:22 UTC, dune-eng commented
Workflow run id 6925900121 approved.

2023-11-20 05:22 UTC, dune-eng commented
Workflow run id 6925900423 approved.

2023-11-21 04:55 UTC, springzh commented
I have read the CLA Document and I hereby sign the CLA

2023-11-21 04:58 UTC, springzh commented
@Hosuke @jeff-dude We're working on some NFT marketplaces for Polygon. The Mooar marketplace is a fork of Seaport v1.5. To reduce duplicated code, we are trying to reuse the `seaport_v4_trades` macro. Since we need different contract address, so there is some modification to the macro. Please review and advise. Thank you.

2023-11-21 14:30 UTC, jeff-dude commented
> @Hosuke @jeff-dude We're working on some NFT marketplaces for Polygon. The Mooar marketplace is a fork of Seaport v1.5. To reduce duplicated code, we are trying to reuse the `seaport_v4_trades` macro. Since we need different contract address, so there is some modification to the macro. Please review and advise. Thank you.

love the usage of the macro(s)!

i've tagged @0xRobin for a quick review, but i think leveraging those is the correct approach.

2023-11-21 15:24 UTC, 0xRobin requested changes

2023-11-21 15:24 UTC, 0xRobin commented on macros/models/_sector/nft/platforms/seaport_v4_trades.sql
There is a `seaport_fork_trades()` macro that does exactly what your trying to do here, but for seaport v3.
(adapt the seaport macro to also support deployed forks)

Can you remove the changes from this macro and move this to a new (`seaport_v4_fork_trades`) macro, might be best to also do a name change for `seaport_fork_trades` -> `seaport_v3_fork_trades` to make the version distinction clear?  
You will need to add parameters to pass in the project and project version.

2023-11-21 15:26 UTC, 0xRobin commented on macros/models/_sector/nft/platforms/seaport_v4_trades.sql
The main reason I went with this setup is to keep the seaport macro's clear of any fork logic
(they are already complex enough on their own)

2023-11-21 15:57 UTC, springzh commented on macros/models/_sector/nft/platforms/seaport_v4_trades.sql
Sounds good. We'll create a seaport_v4_fork_trades and handle rename for seaport_v3_fork_trades. Thanks.

2023-11-22 03:46 UTC, dune-eng commented
Workflow run id 6952613320 approved.

2023-11-22 03:46 UTC, dune-eng commented
Workflow run id 6952613350 approved.

2023-11-22 05:27 UTC, BennyFeng commented on macros/models/_sector/nft/platforms/seaport_v4_trades.sql
Updated.

2023-11-22 08:09 UTC, 0xRobin approved these changes
thanks for incorporating the changes, this looks good now! :ok_hand:

2023-11-22 08:54 UTC, dune-eng commented
Workflow run id 6954955498 approved.

2023-11-22 08:54 UTC, dune-eng commented
Workflow run id 6954955440 approved.

2023-11-22 15:31 UTC, jeff-dude approved these changes

2023-11-22 15:31 UTC, merged