add tokenlon rfqv2 trades
duneanalytics/spellbook pull request #4862
Opened 2023-11-23 09:59 UTC by 0xkeen

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-11-23 10:00 UTC, dune-eng commented
Workflow run id 6968145366 approved.

2023-11-23 10:00 UTC, dune-eng commented
Workflow run id 6968145332 approved.

2023-11-23 10:50 UTC, dune-eng commented
Workflow run id 6968694851 approved.

2023-11-23 10:50 UTC, dune-eng commented
Workflow run id 6968695000 approved.

2023-11-24 02:49 UTC, dune-eng commented
Workflow run id 6976306224 approved.

2023-11-24 02:49 UTC, dune-eng commented
Workflow run id 6976306294 approved.

2023-11-24 05:24 UTC, dune-eng commented
Workflow run id 6977189039 approved.

2023-11-24 05:24 UTC, dune-eng commented
Workflow run id 6977189004 approved.

2023-11-24 06:37 UTC, dune-eng commented
Workflow run id 6977654787 approved.

2023-11-24 06:37 UTC, dune-eng commented
Workflow run id 6977654824 approved.

2023-11-28 04:06 UTC, dune-eng commented
Workflow run id 7014055421 approved.

2023-11-28 04:06 UTC, dune-eng commented
Workflow run id 7014055567 approved.

2023-11-30 01:46 UTC, dune-eng commented
Workflow run id 7040893752 approved.

2023-11-30 01:46 UTC, dune-eng commented
Workflow run id 7040894184 approved.

2023-11-30 01:54 UTC, 0xkeen commented
@Hosuke pls review

2023-12-01 01:45 UTC, dune-eng commented
Workflow run id 7054615701 approved.

2023-12-01 01:45 UTC, dune-eng commented
Workflow run id 7054615810 approved.

2023-12-01 06:21 UTC, Hosuke commented
I am thinking if we can make the macro version of `tokenlon.trades_beta` in this PR.

2023-12-01 06:24 UTC, Hosuke commented on models/tokenlon/ethereum/tokenlon_v5_ethereum_rfq_v2_trades.sql
> +        CAST(ARRAY[] as array<bigint>) AS trace_address,
We may use CAST(ARRAY[-1] as array<bigint>) for null trace_address here:
```suggestion
        CAST(ARRAY[-1] as array<bigint>) as trace_address,
```

2023-12-01 06:25 UTC, Hosuke commented on models/tokenlon/ethereum/tokenlon_v5_ethereum_rfq_v2_trades.sql
> +        "user"                AS taker,
Is `"` needed for these fields? Or is it logically equivalent without `"`?
```suggestion
        user                AS taker,
```

2023-12-01 06:27 UTC, Hosuke commented on models/tokenlon/ethereum/tokenlon_v5_ethereum_rfq_v2_trades.sql
> +    WHERE evt_block_time >= date_trunc('day', now() - interval '7' day)
We can use `incremental_predicate` here and in other incremental filters:
```suggestion
    WHERE {{ incremental_predicate('evt_block_time') }} 
```

2023-12-01 06:29 UTC, Hosuke requested changes
Hi @0xkeen, do you want to add more seed records for tokenlon in this file:
https://github.com/duneanalytics/spellbook/blob/main/seeds/dex/aggregator/dex_aggregator_seed.csv

Then we can apply the `check_dex_aggregator_seed` test to `tokenlon_v5_ethereum_rfq_v2_trades`.

2023-12-01 09:02 UTC, dune-eng commented
Workflow run id 7057910949 approved.

2023-12-01 09:02 UTC, dune-eng commented
Workflow run id 7057911310 approved.

2023-12-01 10:37 UTC, dune-eng commented
Workflow run id 7058920665 approved.

2023-12-05 02:05 UTC, dune-eng commented
Workflow run id 7095198896 approved.

2023-12-05 02:05 UTC, dune-eng commented
Workflow run id 7095199025 approved.

2023-12-05 03:16 UTC, dune-eng commented
Workflow run id 7095712189 approved.

2023-12-05 03:16 UTC, dune-eng commented
Workflow run id 7095712450 approved.

2023-12-05 03:27 UTC, dune-eng commented
Workflow run id 7095794946 approved.

2023-12-05 03:27 UTC, dune-eng commented
Workflow run id 7095795220 approved.

2023-12-05 03:39 UTC, 0xkeen commented
@Hosuke the test case has passed, please review~

2023-12-05 13:39 UTC, Hosuke approved these changes
LGTM.✅
Thank you @0xkeen 

[Sample tokenlon_v5_ethereum_rfq_v2_trades](https://dune.com/queries/3256317)

2023-12-07 00:32 UTC, jeff-dude approved these changes
thank you 🙏

2023-12-07 01:28 UTC, dune-eng commented
Workflow run id 7122539985 approved.

2023-12-07 01:28 UTC, dune-eng commented
Workflow run id 7122539977 approved.

2023-12-07 13:13 UTC, merged