Consolidate lending sector - flashloans macro
duneanalytics/spellbook pull request #4873
Opened 2023-11-24 16:08 UTC by tomfutago

2023-11-24 16:08 UTC, dune-eng commented
Workflow run id 6982860462 approved.

2023-11-24 16:08 UTC, dune-eng commented
Workflow run id 6982860724 approved.

2023-11-24 16:18 UTC, dune-eng commented
Workflow run id 6982940932 approved.

2023-11-24 16:18 UTC, dune-eng commented
Workflow run id 6982941084 approved.

2023-11-24 16:28 UTC, dune-eng commented
Workflow run id 6983025515 approved.

2023-11-24 16:28 UTC, dune-eng commented
Workflow run id 6983025649 approved.

2023-11-24 16:37 UTC, dune-eng commented
Workflow run id 6983100030 approved.

2023-11-24 16:37 UTC, dune-eng commented
Workflow run id 6983100187 approved.

2023-11-24 16:56 UTC, dune-eng commented
Workflow run id 6983243026 approved.

2023-11-24 16:56 UTC, dune-eng commented
Workflow run id 6983243098 approved.

2023-11-24 17:08 UTC, dune-eng commented
Workflow run id 6983347553 approved.

2023-11-24 17:09 UTC, dune-eng commented
Workflow run id 6983347727 approved.

2023-12-15 21:33 UTC, jeff-dude reviewed
similar feedback here as the lending supply PR 🙏

2024-01-12 13:53 UTC, dune-eng commented
Workflow run id 7503072743 approved.

2024-01-12 13:53 UTC, dune-eng commented
Workflow run id 7503072988 approved.

2024-01-19 14:09 UTC, dune-eng commented
Workflow run id 7584869544 approved.

2024-01-19 14:20 UTC, dune-eng commented
Workflow run id 7585000718 approved.

2024-01-19 14:20 UTC, dune-eng commented
Workflow run id 7585000962 approved.

2024-01-19 14:42 UTC, dune-eng commented
Workflow run id 7585267280 approved.

2024-01-19 14:42 UTC, dune-eng commented
Workflow run id 7585267364 approved.

2024-01-19 14:51 UTC, dune-eng commented
Workflow run id 7585358776 approved.

2024-01-19 14:51 UTC, dune-eng commented
Workflow run id 7585358925 approved.

2024-01-19 16:20 UTC, jeff-dude commented
i'll stay away from breaking merge conflicts this time 🫣

2024-01-19 16:25 UTC, jeff-dude requested changes

2024-01-19 16:58 UTC, dune-eng commented
Workflow run id 7586790307 approved.

2024-01-19 16:58 UTC, dune-eng commented
Workflow run id 7586790502 approved.

2024-01-19 16:59 UTC, tomfutago commented on macros/models/_sector/lending/lending_enrich_flashloans.sql
> +    and erc20.symbol = p.symbol
ah yes, will do

2024-01-19 17:12 UTC, dune-eng commented
Workflow run id 7586956106 approved.

2024-01-19 17:12 UTC, dune-eng commented
Workflow run id 7586956360 approved.

2024-01-19 18:24 UTC, jeff-dude approved these changes

2024-01-19 18:24 UTC, merged