Added firebird_finance dex
duneanalytics/spellbook pull request #4907
Opened 2023-11-30 09:07 UTC by ARDev097

Added trades data for firebird_finance_dex using macro approach.

2023-11-30 09:07 UTC, dune-eng commented
Workflow run id 7044265822 approved.

2023-11-30 09:07 UTC, dune-eng commented
Workflow run id 7044265640 approved.

2023-12-01 04:22 UTC, dune-eng commented
Workflow run id 7055729961 approved.

2023-12-02 11:08 UTC, dune-eng commented
Workflow run id 7069814815 approved.

2023-12-02 11:08 UTC, dune-eng commented
Workflow run id 7069814864 approved.

2023-12-02 11:34 UTC, dune-eng commented
Workflow run id 7069928450 approved.

2023-12-02 11:34 UTC, dune-eng commented
Workflow run id 7069928550 approved.

2023-12-02 11:48 UTC, dune-eng commented
Workflow run id 7069978470 approved.

2023-12-02 11:48 UTC, dune-eng commented
Workflow run id 7069978430 approved.

2023-12-02 13:15 UTC, dune-eng commented
Workflow run id 7070450864 approved.

2023-12-02 13:15 UTC, dune-eng commented
Workflow run id 7070450986 approved.

2023-12-03 06:50 UTC, Hosuke approved these changes
LGTM.✅
Thank you @ARDev097

2023-12-03 10:05 UTC, Hosuke commented
By the way, please add the `firebird_finance` info in this file:
https://github.com/duneanalytics/spellbook/blob/main/models/dex/dex_info.sql

(Maybe also add the `mummy_finance` please)

2023-12-03 10:05 UTC, Hosuke requested changes
By the way, please add the `firebird_finance` info in this file:
https://github.com/duneanalytics/spellbook/blob/main/models/dex/dex_info.sql

(Maybe also add the `mummy_finance` please)

2023-12-04 04:25 UTC, dune-eng commented
Workflow run id 7082010642 approved.

2023-12-04 04:25 UTC, dune-eng commented
Workflow run id 7082010715 approved.

2023-12-04 07:06 UTC, dune-eng commented
Workflow run id 7083172085 approved.

2023-12-04 07:06 UTC, dune-eng commented
Workflow run id 7083172191 approved.

2023-12-04 09:16 UTC, Hosuke commented on models/dex/dex_trades.sql
> +,ref('firebird_finance_optimism_trades')
Do you think we can put `firebird_finance_optimism_trades` into `dex_aggregator.trades`?

2023-12-12 13:00 UTC, dune-eng commented
Workflow run id 7181803909 approved.

2023-12-14 12:16 UTC, ARDev097 commented
Hello @Hosuke,

I have made the required changes as suggested in the PR. Please resolve these conflicts so that these checks can be completed. Let me know if any further changes are required from my end.

2023-12-18 03:31 UTC, Hosuke commented on models/_sector/dex/trades/optimism/dex_optimism_base_trades.sql
> +    , ref('firebird_finance_optimism_base_trades')
If `firebird_finance_optimism_base_trades` is under `dex_aggregator.trades`, then we can remove it from `dex.base_trades`. (As currently dex.base_trades should only contain trades in dex.trades)

2023-12-18 03:32 UTC, Hosuke requested changes

2023-12-18 03:32 UTC, Hosuke commented on seeds/dex/trades/dex_trades_seed.csv
> +optimism,firebird_finance,1,2022-09-27,0x77266a3fb99476be6859436eb0000ec1d0a0a78400149195317a65e2a70a5577,11,0x7f5c764cbc14f9669b88837ca1490cca17c31607,400,0x4200000000000000000000000000000000000042,
Also you can move those seed records into this file:
https://github.com/duneanalytics/spellbook/blob/main/seeds/dex/aggregator/dex_aggregator_seed.csv

2023-12-18 04:50 UTC, dune-eng commented
Workflow run id 7243763633 approved.

2023-12-18 04:55 UTC, dune-eng commented
Workflow run id 7243789684 approved.

2023-12-18 04:55 UTC, dune-eng commented
Workflow run id 7243789797 approved.

2023-12-18 05:23 UTC, dune-eng commented
Workflow run id 7244002193 approved.

2023-12-18 05:23 UTC, dune-eng commented
Workflow run id 7244002324 approved.

2023-12-18 05:53 UTC, dune-eng commented
Workflow run id 7244195199 approved.

2023-12-18 05:53 UTC, dune-eng commented
Workflow run id 7244195251 approved.

2023-12-18 06:10 UTC, dune-eng commented
Workflow run id 7244321477 approved.

2023-12-18 06:10 UTC, dune-eng commented
Workflow run id 7244321591 approved.

2023-12-18 06:21 UTC, dune-eng commented
Workflow run id 7244407386 approved.

2023-12-18 06:21 UTC, dune-eng commented
Workflow run id 7244407764 approved.

2023-12-18 06:31 UTC, dune-eng commented
Workflow run id 7244488957 approved.

2023-12-18 06:31 UTC, dune-eng commented
Workflow run id 7244489092 approved.

2023-12-18 06:35 UTC, dune-eng commented
Workflow run id 7244519864 approved.

2023-12-18 06:35 UTC, dune-eng commented
Workflow run id 7244519967 approved.

2023-12-18 06:56 UTC, dune-eng commented
Workflow run id 7244668257 approved.

2023-12-18 06:56 UTC, dune-eng commented
Workflow run id 7244668442 approved.

2023-12-18 07:22 UTC, dune-eng commented
Workflow run id 7244887274 approved.

2023-12-18 07:22 UTC, dune-eng commented
Workflow run id 7244887484 approved.

2023-12-18 08:01 UTC, dune-eng commented
Workflow run id 7245191219 approved.

2023-12-18 08:01 UTC, dune-eng commented
Workflow run id 7245191071 approved.

2023-12-18 08:16 UTC, dune-eng commented
Workflow run id 7245348443 approved.

2023-12-18 08:16 UTC, dune-eng commented
Workflow run id 7245348527 approved.

2023-12-18 08:52 UTC, ARDev097 commented
Hello @Hosuke ,
I have made the requested changes; please check them.

2023-12-18 10:06 UTC, Hosuke commented
I will remove `firebird_finance` from dex.base_trades first.

2023-12-18 10:24 UTC, Hosuke commented on models/firebird_finance/optimism/firebird_finance_optimism_schema.yml
> +      - check_dex_seed:
```suggestion
      - check_dex_aggregator_seed:
```

2023-12-18 10:36 UTC, Hosuke requested changes

2023-12-20 05:59 UTC, dune-eng commented
Workflow run id 7271586909 approved.

2023-12-20 05:59 UTC, dune-eng commented
Workflow run id 7271586967 approved.

2023-12-20 06:40 UTC, dune-eng commented
Workflow run id 7271918531 approved.

2023-12-20 06:40 UTC, dune-eng commented
Workflow run id 7271918627 approved.

2023-12-20 07:55 UTC, dune-eng commented
Workflow run id 7272504433 approved.

2023-12-20 07:55 UTC, dune-eng commented
Workflow run id 7272504510 approved.

2023-12-20 08:55 UTC, dune-eng commented
Workflow run id 7273089242 approved.

2023-12-20 08:55 UTC, dune-eng commented
Workflow run id 7273089353 approved.

2023-12-20 13:07 UTC, Hosuke approved these changes
LGTM.✅
Thank you @ARDev097 

[Sample firebird_finance_optimism_trades]()

2023-12-20 19:19 UTC, jeff-dude approved these changes
thanks for the collab here, lgtm 🤝

2023-12-22 14:48 UTC, merged