Add arbitrum to aragon dao spells - WIP
duneanalytics/spellbook pull request #5016
Opened 2023-12-17 16:01 UTC by henrystats

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2023-12-17 16:01 UTC, dune-eng commented
Workflow run id 7239565259 approved.

2023-12-17 16:01 UTC, dune-eng commented
Workflow run id 7239565175 approved.

2023-12-17 16:17 UTC, dune-eng commented
Workflow run id 7239654732 approved.

2023-12-17 16:17 UTC, dune-eng commented
Workflow run id 7239654790 approved.

2023-12-17 16:47 UTC, dune-eng commented
Workflow run id 7239793568 approved.

2023-12-17 16:47 UTC, dune-eng commented
Workflow run id 7239793692 approved.

2023-12-17 17:01 UTC, dune-eng commented
Workflow run id 7239846594 approved.

2023-12-17 17:01 UTC, dune-eng commented
Workflow run id 7239846721 approved.

2023-12-17 17:15 UTC, dune-eng commented
Workflow run id 7239924546 approved.

2023-12-17 17:15 UTC, dune-eng commented
Workflow run id 7239924562 approved.

2023-12-17 21:47 UTC, dune-eng commented
Workflow run id 7241181253 approved.

2023-12-17 21:47 UTC, dune-eng commented
Workflow run id 7241181278 approved.

2023-12-18 13:35 UTC, dune-eng commented
Workflow run id 7248832277 approved.

2023-12-18 13:35 UTC, dune-eng commented
Workflow run id 7248832481 approved.

2023-12-18 13:56 UTC, dune-eng commented
Workflow run id 7249060579 approved.

2023-12-18 13:56 UTC, dune-eng commented
Workflow run id 7249060683 approved.

2023-12-18 13:57 UTC, dune-eng commented
Workflow run id 7249077329 approved.

2023-12-18 13:57 UTC, dune-eng commented
Workflow run id 7249077441 approved.

2023-12-18 19:05 UTC, dune-eng commented
Workflow run id 7252634001 approved.

2023-12-18 19:05 UTC, dune-eng commented
Workflow run id 7252634217 approved.

2023-12-18 19:06 UTC, henrystats commented
Hola ser @jeff-dude - I saw you added the WIP label so just wanted to tag you that this was already ready for review. I forgot to update the naming.

It's a pretty straight forward update and no changes to code structure, I just added a new chain and removed the highlighted comment where dex prices was commented out as it hadn't been migrated.

2023-12-19 18:49 UTC, jeff-dude requested changes
in addition to comments below, here are some general feedback thoughts. considering there are other spells already live in this lineage, i won't consider this list blockers for this PR. it would be nice over time to rework the entire lineage though to clean it up:
- add incremental predicate in config block to filter target rows to match source rows, example [here](https://github.com/duneanalytics/spellbook/blob/main/models/_sector/dex/trades/arbitrum/platforms/airswap_arbitrum_base_trades.sql#L9), where you can replace column name as needed to a date/time field in the target
- update query incremental filters to use incremental predicate, this keeps source and target filters in sync and controlled in one location, example [here](https://github.com/duneanalytics/spellbook/blob/main/macros/models/_sector/dex/uniswap_compatible_trades.sql#L31)
- instead of using `end if`, `if` we can simplify to just `else`
- move schema property directly into model config block, keep project file clean (universal cleanup in the future) and easier to find schema/name when searching repo
- potentially remove joins to tokens/prices/dex_prices/etc to the cross-chain spells only, to minimize impact on how often we run modified full refreshes on this lineage. this change would assume it's okay that chain-specific spells have raw amounts from the chain only, then the final cross-chain can perform transformations to build additional columns

2023-12-19 18:49 UTC, jeff-dude commented on models/aragon/arbitrum/aragon_arbitrum_schema.yml
> +      - dbt_utils.unique_combination_of_columns:
the test columns don't match the model columns, plz update one or the other to match and ensure uniquness

2023-12-19 18:49 UTC, jeff-dude commented on models/dao/addresses/arbitrum/dao_addresses_arbitrum_schema.yml
> +        tests:
i don't think we need the seed test here, right?
i believe this seed test is already running in the upstream spell

2023-12-19 21:47 UTC, dune-eng commented
Workflow run id 7267929547 approved.

2023-12-19 21:47 UTC, dune-eng commented
Workflow run id 7267929733 approved.

2023-12-19 21:47 UTC, dune-eng commented
Workflow run id 7267934647 approved.

2023-12-19 21:47 UTC, dune-eng commented
Workflow run id 7267934770 approved.

2023-12-19 22:17 UTC, henrystats commented
Thank you ser @jeff-dude, I've fixed the seed test and the unique combination of columns.

I'll submit a separate pr later to clean up/rework the entire lineage. So this can be reviewed. 

Seems there's a big spell running dbt test right now hence why the test is failing, will re trigger in a bit.

2023-12-19 22:27 UTC, jeff-dude commented
> Thank you ser @jeff-dude, I've fixed the seed test and the unique combination of columns.
> 
> I'll submit a separate pr later to clean up/rework the entire lineage. So this can be reviewed.
> 
> Seems there's a big spell running dbt test right now hence why the test is failing, will re trigger in a bit.

yes, that's likely me, my fault :) should be good now. i won't be running again tonight.

2023-12-19 22:32 UTC, dune-eng commented
Workflow run id 7268343591 approved.

2023-12-19 22:32 UTC, dune-eng commented
Workflow run id 7268343671 approved.

2023-12-19 23:23 UTC, jeff-dude approved these changes

2023-12-19 23:23 UTC, merged