Added Optimism Unidex Dex
duneanalytics/spellbook pull request #5040
Opened 2023-12-22 11:39 UTC by ARDev097

Added trades data for unidex dex.

2023-12-22 11:40 UTC, dune-eng commented
Workflow run id 7299456057 approved.

2023-12-22 11:43 UTC, dune-eng commented
Workflow run id 7299479371 approved.

2023-12-22 11:43 UTC, dune-eng commented
Workflow run id 7299479772 approved.

2023-12-25 04:09 UTC, dune-eng commented
Workflow run id 7318977286 approved.

2023-12-25 04:09 UTC, dune-eng commented
Workflow run id 7318977517 approved.

2023-12-26 06:20 UTC, Hosuke approved these changes
LGTM.✅
Thank you @ARDev097 

[Sample unidex_optimism_trades](https://dune.com/queries/3309032)

2024-01-02 18:56 UTC, jeff-dude requested changes
minor changes requested below

2024-01-02 18:56 UTC, jeff-dude commented on models/unidex/optimism/unidex_optimism_trades.sql
> +{% set firebird_finance_optimism_evt_trade_tables = [
```suggestion
{% set unidex_optimism_evt_trade_tables = [
```

2024-01-02 18:56 UTC, jeff-dude commented on models/unidex/optimism/unidex_optimism_trades.sql
> +    {% for evt_trade_table in firebird_finance_optimism_evt_trade_tables %}
```suggestion
    {% for evt_trade_table in unidex_optimism_evt_trade_tables %}
```

2024-01-03 04:45 UTC, dune-eng commented
Workflow run id 7393566661 approved.

2024-01-03 04:46 UTC, dune-eng commented
Workflow run id 7393570119 approved.

2024-01-03 04:46 UTC, dune-eng commented
Workflow run id 7393570181 approved.

2024-01-03 04:59 UTC, ARDev097 commented
Hello @jeff-dude, I have made the requested changes. Please let me know if anything else is required from my end.

2024-01-03 18:52 UTC, jeff-dude approved these changes

2024-01-03 21:16 UTC, merged