Add clipper to `dex.trades_beta`
duneanalytics/spellbook pull request #5043
Opened 2023-12-22 15:18 UTC by tomfutago

2023-12-22 15:18 UTC, dune-eng commented
Workflow run id 7301363929 approved.

2023-12-22 15:18 UTC, dune-eng commented
Workflow run id 7301364035 approved.

2023-12-22 15:54 UTC, dune-eng commented
Workflow run id 7301646881 approved.

2023-12-22 15:54 UTC, dune-eng commented
Workflow run id 7301646983 approved.

2023-12-25 09:18 UTC, Hosuke approved these changes
LGTM.✅
Thank you @tomfutago 

[Sample clipper_arbitrum_base_trades](https://dune.com/queries/3307859)
[Sample clipper_ethereum_base_trades](https://dune.com/queries/3307869)
[Sample clipper_optimism_base_trades](https://dune.com/queries/3307874)
[Sample clipper_polygon_base_trades](https://dune.com/queries/3307875)

2024-01-02 18:50 UTC, jeff-dude requested changes

2024-01-02 18:50 UTC, jeff-dude commented on models/_sector/dex/trades/ethereum/platforms/clipper_ethereum_base_trades.sql
looks like we forgot to add this one to `dex_ethereum.base_trades`?

all other chains seem to be fine

2024-01-03 11:04 UTC, dune-eng commented
Workflow run id 7396474910 approved.

2024-01-03 11:04 UTC, dune-eng commented
Workflow run id 7396475217 approved.

2024-01-03 11:18 UTC, dune-eng commented
Workflow run id 7396617001 approved.

2024-01-03 11:18 UTC, dune-eng commented
Workflow run id 7396617214 approved.

2024-01-03 11:25 UTC, tomfutago commented on models/_sector/dex/trades/ethereum/platforms/clipper_ethereum_base_trades.sql
fixed now

2024-01-03 21:15 UTC, merged