Add mummy finance perpetual trades
duneanalytics/spellbook pull request #5061
Opened 2023-12-27 14:50 UTC by kaiblade

I have read the CLA Document and I hereby sign the CLA

2023-12-27 14:51 UTC, dune-eng commented
Workflow run id 7339385435 approved.

2023-12-27 14:51 UTC, dune-eng commented
Workflow run id 7339385525 approved.

2023-12-27 14:54 UTC, dune-eng commented
Workflow run id 7339409693 approved.

2023-12-27 14:54 UTC, dune-eng commented
Workflow run id 7339409870 approved.

2023-12-27 14:58 UTC, dune-eng commented
Workflow run id 7339431872 approved.

2023-12-27 14:58 UTC, dune-eng commented
Workflow run id 7339431966 approved.

2023-12-27 15:08 UTC, dune-eng commented
Workflow run id 7339518015 approved.

2023-12-27 15:08 UTC, dune-eng commented
Workflow run id 7339517880 approved.

2023-12-27 15:18 UTC, dune-eng commented
Workflow run id 7339602951 approved.

2023-12-27 15:18 UTC, dune-eng commented
Workflow run id 7339603073 approved.

2023-12-27 15:26 UTC, dune-eng commented
Workflow run id 7339668367 approved.

2023-12-27 15:26 UTC, dune-eng commented
Workflow run id 7339668414 approved.

2023-12-27 15:39 UTC, dune-eng commented
Workflow run id 7339760843 approved.

2023-12-27 15:39 UTC, dune-eng commented
Workflow run id 7339760903 approved.

2023-12-27 15:51 UTC, dune-eng commented
Workflow run id 7339840762 approved.

2023-12-27 15:51 UTC, dune-eng commented
Workflow run id 7339840823 approved.

2023-12-27 20:16 UTC, dune-eng commented
Workflow run id 7341601228 approved.

2023-12-27 20:16 UTC, dune-eng commented
Workflow run id 7341601141 approved.

2023-12-27 20:23 UTC, dune-eng commented
Workflow run id 7341643398 approved.

2023-12-27 20:23 UTC, dune-eng commented
Workflow run id 7341643310 approved.

2023-12-28 05:13 UTC, dune-eng commented
Workflow run id 7344659189 approved.

2023-12-28 05:13 UTC, dune-eng commented
Workflow run id 7344659254 approved.

2023-12-28 05:20 UTC, dune-eng commented
Workflow run id 7344704633 approved.

2023-12-28 05:20 UTC, dune-eng commented
Workflow run id 7344704759 approved.

2023-12-28 05:24 UTC, dune-eng commented
Workflow run id 7344733133 approved.

2023-12-28 05:24 UTC, dune-eng commented
Workflow run id 7344733186 approved.

2023-12-28 05:27 UTC, dune-eng commented
Workflow run id 7344747795 approved.

2023-12-28 05:27 UTC, dune-eng commented
Workflow run id 7344747882 approved.

2023-12-28 07:45 UTC, dune-eng commented
Workflow run id 7345568473 approved.

2023-12-28 07:45 UTC, dune-eng commented
Workflow run id 7345568670 approved.

2023-12-28 07:52 UTC, dune-eng commented
Workflow run id 7345610624 approved.

2023-12-28 07:52 UTC, dune-eng commented
Workflow run id 7345610713 approved.

2023-12-28 21:56 UTC, dune-eng commented
Workflow run id 7351521310 approved.

2023-12-28 21:56 UTC, dune-eng commented
Workflow run id 7351521260 approved.

2023-12-28 22:12 UTC, dune-eng commented
Workflow run id 7351624604 approved.

2023-12-28 22:12 UTC, dune-eng commented
Workflow run id 7351624708 approved.

2023-12-28 23:24 UTC, dune-eng commented
Workflow run id 7352029532 approved.

2023-12-28 23:24 UTC, dune-eng commented
Workflow run id 7352029575 approved.

2023-12-29 09:08 UTC, dune-eng commented
Workflow run id 7355312451 approved.

2023-12-29 09:08 UTC, dune-eng commented
Workflow run id 7355312562 approved.

2023-12-29 13:54 UTC, dune-eng commented
Workflow run id 7357215447 approved.

2023-12-29 13:54 UTC, dune-eng commented
Workflow run id 7357215532 approved.

2023-12-29 16:06 UTC, dune-eng commented
Workflow run id 7358081531 approved.

2023-12-29 16:06 UTC, dune-eng commented
Workflow run id 7358082194 approved.

2023-12-29 16:17 UTC, dune-eng commented
Workflow run id 7358150645 approved.

2023-12-29 16:17 UTC, dune-eng commented
Workflow run id 7358150684 approved.

2024-01-02 18:39 UTC, dune-eng commented
Workflow run id 7389325999 approved.

2024-01-02 18:39 UTC, dune-eng commented
Workflow run id 7389326228 approved.

2024-01-03 18:51 UTC, dune-eng commented
Workflow run id 7401220911 approved.

2024-01-03 18:51 UTC, dune-eng commented
Workflow run id 7401221049 approved.

2024-01-03 20:09 UTC, dune-eng commented
Workflow run id 7401907875 approved.

2024-01-03 20:09 UTC, dune-eng commented
Workflow run id 7401907724 approved.

2024-01-04 08:44 UTC, dune-eng commented
Workflow run id 7407317327 approved.

2024-01-04 08:44 UTC, dune-eng commented
Workflow run id 7407317420 approved.

2024-01-04 13:58 UTC, Hosuke commented on models/avt/optimism/avt_optimism_v1_perpetual_trades.sql
> +  AND block_time >= DATE_TRUNC('DAY', NOW() - INTERVAL '7' Day)
You can use `incremental_predicate` in future:
```suggestion
  AND {{ incremental_predicate('block_time') }}
```

2024-01-04 14:07 UTC, Hosuke commented on models/fxdx/optimism/fxdx_optimism_v2_perpetual_trades.sql
> +          ON event.indexToken = tokens.contract_address
You can use `tokens_erc20` here with a filter for generic approach.
```suggestion
      INNER JOIN {{ ref('tokens_erc20') }} tokens
          ON event.indexToken = tokens.contract_address
          AND tokens.blockchain = 'optimism'
```

2024-01-04 15:02 UTC, Hosuke approved these changes
LGTM.✅
Thank you @kaiblade 

[Sample avt_optimism_v1_perpetual_trades](https://dune.com/queries/3328317)
[Sample fxdx_optimism_v2_perpetual_trades](https://dune.com/queries/3328326)
[Sample minerva_money_optimism_v1_perpetual_trades](https://dune.com/queries/3328330)
[Sample mummy_finance_optimism_v1_perpetual_trades](https://dune.com/queries/3328335)
[Sample nex_optimism_perpetual_trades](https://dune.com/queries/3328338)
[Sample opx_finance_optimism_v1_perpetual_trades](https://dune.com/queries/3328341)

2024-01-04 22:05 UTC, jeff-dude requested changes
i only left feedback for `avt`, but i imagine it applies universally in the PR. please do go ahead and make suggested changes

2024-01-04 22:05 UTC, jeff-dude commented on models/avt/optimism/avt_optimism_v1_perpetual_trades.sql
> +UNION
better performance on dunesql, if possible to do `union all`

2024-01-05 10:44 UTC, dune-eng commented
Workflow run id 7420894719 approved.

2024-01-05 10:44 UTC, dune-eng commented
Workflow run id 7420894837 approved.

2024-01-05 11:13 UTC, dune-eng commented
Workflow run id 7421154789 approved.

2024-01-05 11:13 UTC, dune-eng commented
Workflow run id 7421154949 approved.

2024-01-05 11:22 UTC, dune-eng commented
Workflow run id 7421243441 approved.

2024-01-05 11:22 UTC, dune-eng commented
Workflow run id 7421243542 approved.

2024-01-05 11:33 UTC, dune-eng commented
Workflow run id 7421339078 approved.

2024-01-05 11:33 UTC, dune-eng commented
Workflow run id 7421339161 approved.

2024-01-05 11:41 UTC, kaiblade commented on models/avt/optimism/avt_optimism_v1_perpetual_trades.sql
> +          {% if is_incremental() %}
@jeff-dude Addressed all changes.

2024-01-05 11:42 UTC, dune-eng commented
Workflow run id 7421409827 approved.

2024-01-05 11:42 UTC, dune-eng commented
Workflow run id 7421409971 approved.

2024-01-05 19:21 UTC, jeff-dude approved these changes
looks good now 🤝

2024-01-06 14:39 UTC, merged