Added Spell For Unidex Perpetual Trade
duneanalytics/spellbook pull request #5067
Opened 2023-12-28 12:50 UTC by ARDev097

Working on perps trade file for Unidex.

2023-12-28 12:51 UTC, dune-eng commented
Workflow run id 7347773209 approved.

2023-12-28 12:51 UTC, dune-eng commented
Workflow run id 7347773445 approved.

2023-12-29 08:34 UTC, dune-eng commented
Workflow run id 7355109157 approved.

2023-12-29 08:34 UTC, dune-eng commented
Workflow run id 7355109332 approved.

2023-12-29 08:45 UTC, dune-eng commented
Workflow run id 7355172156 approved.

2023-12-29 08:45 UTC, dune-eng commented
Workflow run id 7355172243 approved.

2023-12-29 08:58 UTC, dune-eng commented
Workflow run id 7355240022 approved.

2023-12-29 08:58 UTC, dune-eng commented
Workflow run id 7355240082 approved.

2023-12-29 12:29 UTC, dune-eng commented
Workflow run id 7356628612 approved.

2023-12-29 12:29 UTC, dune-eng commented
Workflow run id 7356628688 approved.

2023-12-30 05:55 UTC, dune-eng commented
Workflow run id 7362402072 approved.

2023-12-30 05:55 UTC, dune-eng commented
Workflow run id 7362402142 approved.

2023-12-30 13:41 UTC, dune-eng commented
Workflow run id 7364434530 approved.

2023-12-30 13:41 UTC, dune-eng commented
Workflow run id 7364434575 approved.

2024-01-01 10:25 UTC, Hosuke commented on models/unidex/optimism/unidex_optimism_perpetual_trades.sql
> +    alias = 'unidex_perpetual_trades',
```suggestion
    alias = 'perpetual_trades',
```

2024-01-01 10:25 UTC, Hosuke commented on models/unidex/optimism/unidex_optimism_perpetual_trades.sql
> +    schema= 'unidex_optimism_perpetual',
```suggestion
    schema= 'unidex_optimism',
```

2024-01-01 10:29 UTC, Hosuke commented
This PR may be merged after #5040, as they shared the common schema and source files.

2024-01-03 05:06 UTC, dune-eng commented
Workflow run id 7393676911 approved.

2024-01-03 05:06 UTC, dune-eng commented
Workflow run id 7393677010 approved.

2024-01-04 03:37 UTC, ARDev097 commented
Hello @Hosuke , the PR #5040 has been merged. Please check it and let me know whether anything is required from my end for this PR or not.

2024-01-04 08:59 UTC, Hosuke commented
> Hello @Hosuke , the PR #5040 has been merged. Please check it and let me know whether anything is required from my end for this PR or not.

Hi @ARDev097, you can resolve conflicts first and sync this PR with the main branch.

2024-01-05 05:28 UTC, dune-eng commented
Workflow run id 7418371427 approved.

2024-01-05 05:28 UTC, dune-eng commented
Workflow run id 7418371335 approved.

2024-01-05 08:46 UTC, Hosuke commented on models/unidex/unidex_perpetual_trades.sql
> +    schema = 'unidex_perpetual',
```suggestion
    schema = 'unidex',
    alias = 'perpetual_trades',
```

2024-01-05 08:58 UTC, Hosuke approved these changes
LGTM.✅
Thank you @ARDev097 

[Sample unidex_v1_optimism_perpetual_trades](https://dune.com/queries/3330304)
[Sample unidex_v2_optimism_perpetual_trades](https://dune.com/queries/3330306)
[Sample unidex_v3_optimism_perpetual_trades](https://dune.com/queries/3330308)

2024-01-05 19:49 UTC, jeff-dude requested changes

2024-01-05 19:49 UTC, jeff-dude commented on models/unidex/optimism/unidex_optimism_perpetual_trades.sql
> +                                    \'["ARDev097"]\') }}'
```suggestion

```

2024-01-05 19:49 UTC, jeff-dude commented on models/unidex/optimism/unidex_v1_optimism_perpetual_trades.sql
> +                                \'["ARDev097"]\') }}'
```suggestion

```

2024-01-05 19:49 UTC, jeff-dude commented on models/unidex/optimism/unidex_v1_optimism_perpetual_trades.sql
> +	WHERE evt_block_time >= DATE_TRUNC('DAY', NOW() - INTERVAL '7' Day)
```suggestion
	WHERE {{ incremental_predicate('evt_block_time') }}
```

2024-01-05 19:49 UTC, jeff-dude commented on models/unidex/optimism/unidex_v1_optimism_perpetual_trades.sql
> +	WHERE evt_block_time >= DATE_TRUNC('DAY', NOW() - INTERVAL '7' Day)
```suggestion
	WHERE {{ incremental_predicate('evt_block_time') }}
```

2024-01-05 19:49 UTC, jeff-dude commented on models/unidex/optimism/unidex_v1_optimism_perpetual_trades.sql
> +	{% if is_incremental() %}
```suggestion
	{% else %}
```

2024-01-05 19:49 UTC, jeff-dude commented on models/unidex/optimism/unidex_v1_optimism_perpetual_trades.sql
> +	AND tx.block_time >= DATE_TRUNC('DAY', NOW() - INTERVAL '7' Day)
```suggestion
	AND {{ incremental_predicate('tx.block_time') }}
```

2024-01-05 19:49 UTC, jeff-dude commented on models/unidex/unidex_perpetual_trades.sql
> +                                    \'["ARDev097"]\') }}'
```suggestion

```

2024-01-05 19:49 UTC, jeff-dude commented on models/unidex/optimism/unidex_v1_optimism_perpetual_trades.sql
> +                                \'["ARDev097"]\') }}'
plz apply to all version spells

2024-01-05 19:49 UTC, jeff-dude commented on models/unidex/optimism/unidex_v1_optimism_perpetual_trades.sql
> +	WHERE evt_block_time >= DATE_TRUNC('DAY', NOW() - INTERVAL '7' Day)
plz apply to all version spells

2024-01-05 19:49 UTC, jeff-dude commented on models/unidex/optimism/unidex_v1_optimism_perpetual_trades.sql
> +	WHERE evt_block_time >= DATE_TRUNC('DAY', NOW() - INTERVAL '7' Day)
plz apply to all version spells

2024-01-05 19:49 UTC, jeff-dude commented on models/unidex/optimism/unidex_v1_optimism_perpetual_trades.sql
> +	{% if is_incremental() %}
plz apply to all version spells

2024-01-05 19:49 UTC, jeff-dude commented on models/unidex/optimism/unidex_v1_optimism_perpetual_trades.sql
> +	AND tx.block_time >= DATE_TRUNC('DAY', NOW() - INTERVAL '7' Day)
plz apply to all version spells

2024-01-06 06:35 UTC, dune-eng commented
Workflow run id 7430019947 approved.

2024-01-06 06:35 UTC, dune-eng commented
Workflow run id 7430019899 approved.

2024-01-06 18:24 UTC, dune-eng commented
Workflow run id 7433246028 approved.

2024-01-06 18:24 UTC, dune-eng commented
Workflow run id 7433246068 approved.

2024-01-08 22:53 UTC, jeff-dude approved these changes

2024-01-09 15:20 UTC, merged