Add Solana DEXs to dex.info
duneanalytics/spellbook pull request #5070
Opened 2023-12-28 15:04 UTC by hildobby

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2024-01-02 17:43 UTC, jeff-dude requested changes

2024-01-02 17:43 UTC, jeff-dude commented on models/dex/dex_info.sql
> +        post_hook='{{ expose_spells(\'["ethereum", "polygon", "bnb", "avalanche_c", "gnosis", "fantom", "optimism", "arbitrum", "celo", "base", "soalana"]\',
```suggestion
        post_hook='{{ expose_spells(\'["ethereum", "polygon", "bnb", "avalanche_c", "gnosis", "fantom", "optimism", "arbitrum", "celo", "base", "solana"]\',
```

2024-01-02 17:44 UTC, jeff-dude commented
plz also fix outstanding merge conflicts

2024-01-03 19:01 UTC, jeff-dude approved these changes
this may not be needed, if the cow PR is merged first?

we'll merge main into this branch after that is merged, so how it looks

2024-01-17 16:27 UTC, jeff-dude commented
to be considered after #5071 is merged

2024-01-18 11:48 UTC, hildobby commented
> to be considered after #5071 is merged

closing chnges from here are included in https://github.com/duneanalytics/spellbook/pull/5071

2024-01-18 11:48 UTC, closed without merging