add loopring to rollup_economics, corrected imx + starkware proofs
duneanalytics/spellbook pull request #5099
Opened 2024-01-04 20:49 UTC by lorenz234

- added loopring to the models/rollup_economics/ethereum/l1_data_fees.sql table
- fixed imx, as it uses offchain DA. therefore moved all state update fees into l1_data_fees
- added starkware proofs to the models/rollup_economics/ethereum/l1_verification_fees.sql table
- double checked all proof sizes

2024-01-04 20:50 UTC, dune-eng commented
Workflow run id 7414689349 approved.

2024-01-04 20:50 UTC, dune-eng commented
Workflow run id 7414689443 approved.

2024-01-09 20:20 UTC, jeff-dude requested changes

2024-01-09 20:20 UTC, jeff-dude commented
i've also pushed a commit to update the spell(s) to filter on date ranges as expected, to see if that helps run time

2024-01-09 20:35 UTC, jeff-dude commented
> i've also pushed a commit to update the spell(s) to filter on date ranges as expected, to see if that helps run time

it's possible the previous CI test run was at the same time as other PRs, therefore less resources, but it's now running in ~17 minutes compared to almost an hour previously. this looks much better. i'd still suggest the above change, if you don't mind, prior to merge

2024-01-10 09:13 UTC, lorenz234 commented on models/rollup_economics/ethereum/l1_data_fees.sql
> +      AND cast(t.data as varchar) LIKE '0x77552641%'
Sure thing, I can do it!

2024-01-10 09:31 UTC, dune-eng commented
Workflow run id 7472874331 approved.

2024-01-10 10:09 UTC, lorenz234 commented
Now 18min lol. But did some query testing, and it does seem to reduce cpu time by around 50%. Should be ready for merge now!

2024-01-10 14:05 UTC, jeff-dude commented
> Now 18min lol. But did some query testing, and it does seem to reduce cpu time by around 50%. Should be ready for merge now!

we've likely hit the best we can get on this side, which is fine! thanks again for working with me on enhacements here.

2024-01-10 14:06 UTC, jeff-dude approved these changes

2024-01-10 14:06 UTC, merged