Update prices_ethereum_tokens.sql
duneanalytics/spellbook pull request #5136
Opened 2024-01-10 05:17 UTC by peterrliem

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2024-01-10 05:17 UTC, dune-eng commented
Workflow run id 7470654653 approved.

2024-01-10 05:17 UTC, dune-eng commented
Workflow run id 7470654655 approved.

2024-01-10 05:17 UTC, dune-eng commented
Workflow run id 7470654619 approved.

2024-01-10 14:32 UTC, Hosuke commented on models/prices/ethereum/prices_ethereum_tokens.sql
> +    ('mvd-metavault-dao', 'ethereum', 'MVD', 0x788b6d2b37aa51d916f2837ae25b05f0e61339d1, 9)
```suggestion
    ('tpy-thrupenny', 'ethereum', 'TPY', 0x968cbe62c830a0ccf4381614662398505657a2a9, 8),
    ('mvd-metavault-dao', 'ethereum', 'MVD', 0x788b6d2b37aa51d916f2837ae25b05f0e61339d1, 9)
```

2024-01-10 15:11 UTC, Hosuke commented on models/prices/ethereum/prices_ethereum_tokens.sql
> +    ('magic-magic-arbitrumk', 'ethereum', 'MAGIC', 0xb0c7a3ba49c7a6eaba6cd4a96c55a1391070ac9a, 18),
```suggestion
    ('magic-magic-arbitrum', 'ethereum', 'MAGIC', 0xb0c7a3ba49c7a6eaba6cd4a96c55a1391070ac9a, 18),
```

2024-01-10 15:58 UTC, Hosuke requested changes

2024-01-10 15:58 UTC, Hosuke commented on models/prices/ethereum/prices_ethereum_tokens.sql
> +    ('mvd-metavault-dao', 'ethereum', 'MVD', 0x788b6d2b37aa51d916f2837ae25b05f0e61339d1, 9)
There are some inactive(price feeds) tokens here, we may need to remove them:
https://github.com/duneanalytics/spellbook/actions/runs/7476909468/job/20348390637?pr=5136#step:6:42

2024-01-15 15:20 UTC, peterrliem commented
Let's get them removed then.

Thank you!

On Wed, Jan 10, 2024 at 11:58 PM Huang Geyang ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In models/prices/ethereum/prices_ethereum_tokens.sql
> <https://github.com/duneanalytics/spellbook/pull/5136#discussion_r1447588276>
> :
>
> > +    ('vee-zeeverse', 'ethereum', 'VEE', 0x7616113782AaDAB041d7B10d474F8A0c04EFf258, 18),
> +    ('noisegpt-noisegpt', 'ethereum', 'NOISEGPT', 0xf23a2BF7619Ad93300499c3fC7d7145A06CcA562, 18),
> +    ('tpy-thrupenny', 'ethereum', 'TPY', 0x968cbe62c830a0ccf4381614662398505657a2a9, 8),
> +    ('mvd-metavault-dao', 'ethereum', 'MVD', 0x788b6d2b37aa51d916f2837ae25b05f0e61339d1, 9)
>
> There are some inactive(price feeds) tokens here, we may need to remove
> them:
>
> https://github.com/duneanalytics/spellbook/actions/runs/7476909468/job/20348390637?pr=5136#step:6:42
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/duneanalytics/spellbook/pull/5136#pullrequestreview-1813565980>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL4L7YLKMWDUYFD56AUAUHTYN23DNAVCNFSM6AAAAABBUF3JTSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMJTGU3DKOJYGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-15 22:42 UTC, jeff-dude approved these changes
should be good now, we can ignore the symbol error as it looks like coinpaprika is incorrect

2024-01-16 13:57 UTC, merged