Add Mux protocol optimism to perpetual trades
duneanalytics/spellbook pull request #5141
Opened 2024-01-10 18:16 UTC by sophie-analytics

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

2024-01-10 18:17 UTC, dune-eng commented
Workflow run id 7479122406 approved.

2024-01-10 18:17 UTC, dune-eng commented
Workflow run id 7479122522 approved.

2024-01-10 18:45 UTC, dune-eng commented
Workflow run id 7479408308 approved.

2024-01-10 18:45 UTC, dune-eng commented
Workflow run id 7479408425 approved.

2024-01-10 18:46 UTC, dune-eng commented
Workflow run id 7479417195 approved.

2024-01-10 18:46 UTC, dune-eng commented
Workflow run id 7479417293 approved.

2024-01-10 18:47 UTC, henrystats commented
Hey @sophie-analytics

2024-01-11 17:41 UTC, dune-eng commented
Workflow run id 7492491964 approved.

2024-01-11 17:41 UTC, dune-eng commented
Workflow run id 7492492195 approved.

2024-01-11 17:51 UTC, dune-eng commented
Workflow run id 7492591412 approved.

2024-01-11 17:51 UTC, dune-eng commented
Workflow run id 7492591334 approved.

2024-01-11 18:00 UTC, dune-eng commented
Workflow run id 7492677542 approved.

2024-01-11 18:00 UTC, dune-eng commented
Workflow run id 7492677715 approved.

2024-01-11 19:10 UTC, dune-eng commented
Workflow run id 7493418263 approved.

2024-01-11 19:10 UTC, dune-eng commented
Workflow run id 7493418430 approved.

2024-01-15 22:46 UTC, jeff-dude requested changes

2024-01-15 22:46 UTC, jeff-dude commented on dbt_project.yml
> +        +schema: mux_protocol_optimism
can you remove any additions to this file and rather put schema directly in model config blocks?

2024-01-15 22:46 UTC, jeff-dude commented on models/mux_protocol/optimism/mux_protocol_optimism_perpetual_trades.sql
> +    post_hook='{{ expose_spells(\'["optimism"]\',
can we remove this post hook?
moving forward, we'd like to avoid this on spells which feed into final downstream spells

2024-01-15 22:46 UTC, jeff-dude commented on models/mux_protocol/optimism/mux_protocol_optimism_perpetual_trades.sql
> +    {% endif %}
can you update incremental logic across the whole PR to match our new design pattern?
target filter example [here](https://github.com/duneanalytics/spellbook/blob/main/models/_sector/dex/trades/avalanche_c/platforms/openocean_avalanche_c_base_trades.sql#L9)
source filter example [here](https://github.com/duneanalytics/spellbook/blob/main/models/_sector/dex/trades/avalanche_c/platforms/openocean_avalanche_c_base_trades.sql#L30-L32)

be sure the columns passed in for each are correct for each spell

2024-01-15 22:46 UTC, jeff-dude commented on models/mux_protocol/optimism/mux_protocol_optimism_perpetual_trades.sql
> +LEFT JOIN {{ source('optimism', 'transactions') }} b
can this be inner join?

2024-01-15 22:46 UTC, jeff-dude commented on package-lock.yml
> +sha1_hash: a158c48c59c2bb7d729d2a4e215aabe5bb4f3353
can you revert modifications to this file?

2024-01-17 10:10 UTC, dune-eng commented
Workflow run id 7554126459 approved.

2024-01-17 10:11 UTC, dune-eng commented
Workflow run id 7554134118 approved.

2024-01-17 10:11 UTC, dune-eng commented
Workflow run id 7554133989 approved.

2024-01-17 10:21 UTC, sophie-analytics commented
@jeff-dude I have made the necessary corrections to the spell. Kindly check it out

2024-01-17 16:44 UTC, jeff-dude approved these changes
good to go now 🤝

2024-01-17 16:44 UTC, merged