Add Goerli Token Tables
duneanalytics/spellbook pull request #5160
Opened 2024-01-12 22:58 UTC by MSilb7

Adding Token Tables for Goerli. Dependency for https://github.com/duneanalytics/spellbook/pull/5159

2024-01-12 22:58 UTC, dune-eng commented
Workflow run id 7508330987 approved.

2024-01-12 22:58 UTC, dune-eng commented
Workflow run id 7508330924 approved.

2024-01-12 23:08 UTC, dune-eng commented
Workflow run id 7508412783 approved.

2024-01-12 23:08 UTC, dune-eng commented
Workflow run id 7508412938 approved.

2024-01-14 07:13 UTC, Hosuke approved these changes
LGTM.✅
Thank you @MSilb7

2024-01-15 16:43 UTC, dune-eng commented
Workflow run id 7531795449 approved.

2024-01-15 16:43 UTC, dune-eng commented
Workflow run id 7531795542 approved.

2024-01-15 16:43 UTC, dune-eng commented
Workflow run id 7531796504 approved.

2024-01-15 16:43 UTC, dune-eng commented
Workflow run id 7531796546 approved.

2024-01-15 17:38 UTC, jeff-dude requested changes
can you put `schema` property into each model directly?

2024-01-16 16:55 UTC, merged