Added Apeswap, OasisSwap, Swaap_v2, Woofi, Smardex to dex.trades
duneanalytics/spellbook pull request #5177
Opened 2024-01-17 17:59 UTC by ARDev097

Added trades data for Apeswap, OasisSwap, Swaap_v2, Woofi, Smardex dexes on arbitrum.

2024-01-17 18:00 UTC, dune-eng commented
Workflow run id 7559851510 approved.

2024-01-17 18:00 UTC, dune-eng commented
Workflow run id 7559851362 approved.

2024-01-17 18:08 UTC, dune-eng commented
Workflow run id 7559952373 approved.

2024-01-17 18:08 UTC, dune-eng commented
Workflow run id 7559952524 approved.

2024-01-18 02:40 UTC, Hosuke commented on macros/models/_sector/dex/smardex_compatible_trdaes.sql
Smardex part may be duped with #5122

2024-01-18 02:44 UTC, Hosuke commented on macros/models/_sector/dex/smardex_compatible_trdaes.sql
I am trying to improve the macro compatibility in #5169.
We may wait after #5169 finished.

I believe we may utilize the existing macros to implement dexes in this PR.

2024-01-18 09:19 UTC, dune-eng commented
Workflow run id 7567814811 approved.

2024-01-18 09:19 UTC, dune-eng commented
Workflow run id 7567814946 approved.

2024-01-18 09:34 UTC, dune-eng commented
Workflow run id 7567994201 approved.

2024-01-18 09:34 UTC, dune-eng commented
Workflow run id 7567994372 approved.

2024-01-18 09:47 UTC, dune-eng commented
Workflow run id 7568133720 approved.

2024-01-18 09:47 UTC, dune-eng commented
Workflow run id 7568133635 approved.

2024-01-20 06:08 UTC, dune-eng commented
Workflow run id 7592610793 approved.

2024-01-20 06:08 UTC, dune-eng commented
Workflow run id 7592610723 approved.

2024-01-22 17:57 UTC, Hosuke commented
Hi @ARDev097,
please run `git merge main` to update this PR.

Thank you.

2024-01-23 06:06 UTC, dune-eng commented
Workflow run id 7621730890 approved.

2024-01-23 06:06 UTC, dune-eng commented
Workflow run id 7621730959 approved.

2024-01-23 07:29 UTC, dune-eng commented
Workflow run id 7622404408 approved.

2024-01-23 07:29 UTC, dune-eng commented
Workflow run id 7622404543 approved.

2024-01-23 09:12 UTC, dune-eng commented
Workflow run id 7623446847 approved.

2024-01-23 09:12 UTC, dune-eng commented
Workflow run id 7623447039 approved.

2024-01-23 10:59 UTC, dune-eng commented
Workflow run id 7624702675 approved.

2024-01-23 10:59 UTC, dune-eng commented
Workflow run id 7624702477 approved.

2024-01-23 13:53 UTC, Hosuke requested changes

2024-01-23 13:53 UTC, Hosuke commented on macros/models/_sector/dex/swaap_compatible_trades.sql
If only `swaap_v2_arbitrum_base_trades` is using this macro, we may implement in full in `models/_sector/dex/trades/arbitrum/platforms/swaap_v2_arbitrum_base_trades.sql`, without introducing the new macro here.

2024-01-23 14:01 UTC, Hosuke commented on models/_sector/dex/trades/arbitrum/platforms/woofi_arbitrum_base_trades.sql
Hi @tomfutago,
is it possible to use `generic_spot_v2_compatible_trades` to implement `woofi_arbitrum. base_trades`?

Currently I think the only problem is about the source naming `source('woofi_swap_arbitrum', 'WooPPV2_1_evt_WooSwap')`.

Also the current implementation may flip the bought/sold tokens?

2024-01-23 15:46 UTC, tomfutago commented on models/_sector/dex/trades/arbitrum/platforms/woofi_arbitrum_base_trades.sql
Yes generic macro can be used with small update to the macro and existing spells that are using this macro already. It can be implemented similar to `dodo_compatible_trades` macro:
* add new param: `decoded_project = ''` and update source from `source(project ~` to `source(decoded_project ~`
* update existing spells by copying `project = <name>` and adding new param as `decoded_project = <name>` (while for woofi on arbitrrum it'll be `project = woofi` and `decoded_project = 'woofi_swap'`)

Hope that 👆 makes senses, if not - I can put suggestions directly in the code.

And yes, I think current implementation in this PR is flipping bought/sold tokens. Something similar was already discussed under #5108 and #5129

2024-01-23 16:29 UTC, Hosuke commented on models/_sector/dex/trades/arbitrum/platforms/woofi_arbitrum_base_trades.sql
Noted.

2024-01-24 04:31 UTC, dune-eng commented
Workflow run id 7635536390 approved.

2024-01-24 04:31 UTC, dune-eng commented
Workflow run id 7635536501 approved.

2024-01-24 05:19 UTC, ARDev097 commented on macros/models/_sector/dex/swaap_compatible_trades.sql
Hello @Hosuke,

I have made the necessary changes to the `Swaap DEX`. Please review them and let me know if anything further is required from my end.

2024-01-24 11:48 UTC, Hosuke commented on models/_sector/dex/trades/arbitrum/platforms/woofi_arbitrum_base_trades.sql
I will try to update `generic_spot_v2_compatible_trades` in a new PR first.

2024-01-25 09:02 UTC, dune-eng commented
Workflow run id 7652147324 approved.

2024-01-25 09:02 UTC, dune-eng commented
Workflow run id 7652147132 approved.

2024-01-26 08:43 UTC, Hosuke requested changes

2024-01-26 08:43 UTC, Hosuke commented on models/_sector/dex/trades/arbitrum/platforms/woofi_arbitrum_base_trades.sql
Hi @ARDev097,
since `woofi_arbitrum.base_trades` may be a special case, we can just implement it in full without using the macro.

2024-01-26 08:43 UTC, Hosuke commented on macros/models/_sector/dex/woofi_compatible_trades.sql
After you reimplement woofi_arbitrum.base_trades, you can remove this macro from this PR.

2024-01-26 09:40 UTC, dune-eng commented
Workflow run id 7666387547 approved.

2024-01-26 09:40 UTC, dune-eng commented
Workflow run id 7666387631 approved.

2024-01-26 10:06 UTC, dune-eng commented
Workflow run id 7666638006 approved.

2024-01-26 10:06 UTC, dune-eng commented
Workflow run id 7666638181 approved.

2024-01-26 10:15 UTC, ARDev097 commented on macros/models/_sector/dex/woofi_compatible_trades.sql
Hello @Hosuke ,
I have made the requested changes.

2024-01-26 10:45 UTC, Hosuke requested changes

2024-01-26 10:45 UTC, Hosuke commented on models/_sector/dex/trades/arbitrum/platforms/woofi_arbitrum_base_trades.sql
> +            t.fromToken AS token_bought_address,
Please recheck that if the token_bought and sold are flipped in this case.

2024-01-26 10:46 UTC, Hosuke commented on seeds/_sector/dex/woofi_arbitrum_base_trades_seed.csv
> +arbitrum,woofi,2,2022-11-07,0xe4a9bccba29eb941b115a39622d83c8f0b2e73a541e0d7c13aa46c75d7af5afd,6,0xff970a61a04b1ca14834a43f5de4533ebddb5cc8,0x82af49447d8a07e3bd95bd0d56f35241523fbab1,35919293,9994000
SCAN: https://arbiscan.io/tx/0xe4a9bccba29eb941b115a39622d83c8f0b2e73a541e0d7c13aa46c75d7af5afd

2024-01-26 11:07 UTC, dune-eng commented
Workflow run id 7667269439 approved.

2024-01-26 11:17 UTC, ARDev097 commented on seeds/_sector/dex/woofi_arbitrum_base_trades_seed.csv
> +arbitrum,woofi,2,2022-11-07,0xe4a9bccba29eb941b115a39622d83c8f0b2e73a541e0d7c13aa46c75d7af5afd,6,0xff970a61a04b1ca14834a43f5de4533ebddb5cc8,0x82af49447d8a07e3bd95bd0d56f35241523fbab1,35919293,9994000
Done.

2024-01-26 15:18 UTC, Hosuke approved these changes
LGTM.✅
Thank you @ARDev097

2024-01-26 16:45 UTC, jeff-dude approved these changes

2024-01-26 16:48 UTC, jeff-dude commented
@ARDev097 plz do resolve merge conflicts, after other dex PRs were merged. we don't have access to do on your branch.

2024-01-26 17:45 UTC, dune-eng commented
Workflow run id 7671534887 approved.

2024-01-26 17:45 UTC, dune-eng commented
Workflow run id 7671535033 approved.

2024-01-26 17:55 UTC, ARDev097 commented
Hello @jeff-dude ,
I have resolved the merge conflicts.

2024-01-26 18:22 UTC, merged