Added woofi and kyberswap dexes on base
duneanalytics/spellbook pull request #5182
Opened 2024-01-18 06:13 UTC by Jason4276

Added trades data for woofi and kyberswap dex on base chain.

2024-01-18 06:14 UTC, dune-eng commented
Workflow run id 7566084970 approved.

2024-01-18 06:14 UTC, dune-eng commented
Workflow run id 7566084835 approved.

2024-01-19 10:31 UTC, dune-eng commented
Workflow run id 7582575492 approved.

2024-01-19 10:31 UTC, dune-eng commented
Workflow run id 7582575709 approved.

2024-01-19 10:51 UTC, dune-eng commented
Workflow run id 7582788061 approved.

2024-01-19 10:51 UTC, dune-eng commented
Workflow run id 7582788253 approved.

2024-01-19 10:58 UTC, dune-eng commented
Workflow run id 7582846705 approved.

2024-01-19 14:54 UTC, Hosuke commented on macros/models/_sector/dex/woofi_compatible_trades.sql
This macro is the same as in #5177

2024-01-19 15:01 UTC, Hosuke requested changes

2024-01-19 15:01 UTC, Hosuke commented on macros/models/_sector/dex/kyberswap_base_compatible_trades.sql
If only kyberswap_base.base_trades is using this macro, you can write full implementation in `kyberswap_base.base_trades` instead of creating a new macro.

Also there is already a macro `kyberswap_compatible_trades`.

2024-01-19 15:04 UTC, Hosuke commented on models/_sector/dex/trades/base/platforms/kyberswap_base_base_trades.sql
> +}}
```suggestion
{%
    set config_sources = [
        {
            'version': 'elastic',
            'source_evt_swap': 'ElasticPool_evt_Swap',
            'source_evt_factory': 'Elastic_Factory_evt_PoolCreated'
        }
    ]
%}

{{
        kyberswap_compatible_trades(
            blockchain = 'base',
            project = 'kyberswap',
            sources = config_sources
        )
}}
```

2024-01-20 11:52 UTC, Jason4276 commented on macros/models/_sector/dex/woofi_compatible_trades.sql
Yes

2024-01-20 12:19 UTC, dune-eng commented
Workflow run id 7594305623 approved.

2024-01-20 12:19 UTC, dune-eng commented
Workflow run id 7594305751 approved.

2024-01-20 12:26 UTC, dune-eng commented
Workflow run id 7594345477 approved.

2024-01-20 12:26 UTC, dune-eng commented
Workflow run id 7594345510 approved.

2024-01-20 18:02 UTC, Hosuke commented on models/_sector/dex/trades/base/platforms/velocimeter_v2_base_base_trades.sql
> +        , project = 'velocimeter'
If `velocimeter` is a new dex to add, you can update its information in `dex.info`.

2024-01-22 04:52 UTC, dune-eng commented
Workflow run id 7606622423 approved.

2024-01-22 04:52 UTC, dune-eng commented
Workflow run id 7606622522 approved.

2024-01-23 06:55 UTC, dune-eng commented
Workflow run id 7622112660 approved.

2024-01-23 14:04 UTC, Hosuke commented on macros/models/_sector/dex/woofi_compatible_trades.sql
Similar macro in #5177 as well.
This macro may flip the bought/sold tokens compared to the current woofi implementation.

Other parts in this PR seems good.

2024-01-24 04:51 UTC, dune-eng commented
Workflow run id 7635665736 approved.

2024-01-24 04:51 UTC, dune-eng commented
Workflow run id 7635665826 approved.

2024-01-24 11:51 UTC, Hosuke commented on models/_sector/dex/trades/base/platforms/woofi_base_base_trades.sql
> +}}
For this PR, (base chain specifically,)
You can use `generic_spot_v2_compatible_trades` to implement `woofi_base.base_trades`.

Related discussion here:
https://github.com/duneanalytics/spellbook/pull/5177#discussion_r1463328388

2024-01-24 18:32 UTC, Hosuke requested changes
I have suggested an implementation of `woofi_base.base_trades` using `generic_spot_v2_compatible_trades`.

Also we may need to flip the token_bought/sold in the seed records.

You can also verify woofi's token_bought/sold using woofi and the blockchain explorer.

2024-01-24 18:32 UTC, Hosuke commented on models/_sector/dex/trades/base/platforms/woofi_base_base_trades.sql
> +}}
```suggestion
{%
    set config_sources = [
        {
            'version': '2',
            'source': 'WooPPV2_evt_WooSwap'
        }
    ]
%}

{{
    generic_spot_v2_compatible_trades(
        blockchain = 'base',
        project = 'woofi',
        sources = config_sources,
        maker = '"from"'
    )
}}
```

2024-01-25 05:23 UTC, dune-eng commented
Workflow run id 7650260812 approved.

2024-01-25 05:23 UTC, dune-eng commented
Workflow run id 7650260982 approved.

2024-01-25 05:34 UTC, dune-eng commented
Workflow run id 7650343277 approved.

2024-01-25 05:34 UTC, dune-eng commented
Workflow run id 7650343344 approved.

2024-01-25 05:51 UTC, dune-eng commented
Workflow run id 7650454090 approved.

2024-01-25 05:51 UTC, dune-eng commented
Workflow run id 7650454386 approved.

2024-01-25 08:14 UTC, Hosuke requested changes

2024-01-25 08:14 UTC, Hosuke commented on macros/models/_sector/dex/woofi_compatible_trades.sql
Since I am not able to edit this PR,
you can remove this file from this PR, as it is currently not used by any spell.

Then this PR should be ready for final-review.

2024-01-25 08:30 UTC, dune-eng commented
Workflow run id 7651806950 approved.

2024-01-25 08:30 UTC, dune-eng commented
Workflow run id 7651807127 approved.

2024-01-25 09:06 UTC, Hosuke commented on macros/models/_sector/dex/woofi_compatible_trades.sql
You may allow the maintainers' edit in the next time.

2024-01-25 16:56 UTC, Hosuke approved these changes
LGTM.✅
Thank you @Jason4276

2024-01-26 08:44 UTC, Hosuke commented
Hi @Jason4276, you can run `git merge main` to update this PR.

2024-01-26 16:43 UTC, jeff-dude approved these changes

2024-01-26 16:48 UTC, merged