Added odos_v2 optimism dex
duneanalytics/spellbook pull request #5267
Opened 2024-01-31 10:25 UTC by ARDev097

Added trade data for `odos_v2` on `optimism` according to the new updated code (tokens-sub-project).

2024-01-31 10:25 UTC, dune-eng commented
Workflow run id 7724597808 approved.

2024-01-31 10:25 UTC, dune-eng commented
Workflow run id 7724598041 approved.

2024-01-31 16:34 UTC, jeff-dude requested changes
thank you for adapting to the new sub-project approach quickly.

can you update odos version spells to use the universal unique key for `dex_aggregator.trades` lineage?
https://github.com/duneanalytics/spellbook/blob/main/models/dex/dex_aggregator_trades.sql#L9

2024-02-01 03:49 UTC, dune-eng commented
Workflow run id 7735983115 approved.

2024-02-01 03:49 UTC, dune-eng commented
Workflow run id 7735983214 approved.

2024-02-01 04:31 UTC, dune-eng commented
Workflow run id 7736288048 approved.

2024-02-01 04:31 UTC, dune-eng commented
Workflow run id 7736288094 approved.

2024-02-02 05:12 UTC, dune-eng commented
Workflow run id 7751700228 approved.

2024-02-02 05:12 UTC, dune-eng commented
Workflow run id 7751700289 approved.

2024-02-02 05:30 UTC, dune-eng commented
Workflow run id 7751844869 approved.

2024-02-02 05:30 UTC, dune-eng commented
Workflow run id 7751844951 approved.

2024-02-02 05:55 UTC, ARDev097 commented on models/odos/optimism/odos_optimism_schema.yml
> +      - dbt_utils.unique_combination_of_columns:
Hello @jeff-dude ,
I have made the requested changes.

2024-02-02 16:32 UTC, jeff-dude approved these changes
thank you!

2024-02-02 16:32 UTC, merged