Add oneinch and zeroex as as-is models into dex.trades_beta
duneanalytics/spellbook pull request #5303
Opened 2024-02-06 11:00 UTC by Hosuke

# Thank you for contributing to Spellbook!

Thank you for taking the time to submit code in Spellbook. A few things to consider:
- If you are a first-time contributor, please sign the CLA by copy & pasting **_exactly_** what the bot mentions in PR comment
- Refer to [docs](#spellbook-contribution-docs) section below to answer questions
- Dune team will review submitted PRs as soon as possible

## Spellbook sub-projects

To prepare for Spellbook to scale in size, Dune team has started to pilot sub-projects:
- For a quick overview, see [the GH discussion on the topic](https://github.com/duneanalytics/spellbook/discussions/5238)
    - Please ask questions and continue the conversation there
- The first spell lineage to move: `tokens.erc20` and all upstream spells which help build it
    - **_Note_**: Please navigate to [tokens](https://github.com/duneanalytics/spellbook/tree/main/tokens) root directory to find tokens objects

## Spellbook contribution docs

The [docs](https://github.com/duneanalytics/spellbook/tree/main/docs) directory has been implemented to answer as many questions as possible. Please take the time to reference each `.md` file within this directory to understand how to efficiently contribute & why the repo is designed as it is 🪄

Example questions to be answered:
- What does each property in the [model config block](https://github.com/duneanalytics/spellbook/blob/main/docs/models/model_config_block.md) mean?
- What is the [CI test](https://github.com/duneanalytics/spellbook/blob/main/docs/ci_test/ci_test_overview.md) attached to PRs and how can I best utilize it?
- What are the Spellbook [best practices](https://github.com/duneanalytics/spellbook/blob/main/docs/general/best_practices.md)?

Please navigate through the [docs](https://github.com/duneanalytics/spellbook/tree/main/docs) directory to find as much info as you can.

**Note**: happy to take PRs to improve the docs, let us know 🤝

2024-02-12 10:01 UTC, Hosuke commented on models/zeroex/zeroex_native_trades.sql
cc. @RantumBits for review.

2024-02-12 10:07 UTC, Hosuke commented on models/oneinch/oneinch_lop_own_trades.sql
cc. @max-morrow for review.

2024-02-13 00:47 UTC, jeff-dude commented on models/oneinch/oneinch_lop_own_trades.sql
@grkhr may want to have a look as well

2024-02-13 00:50 UTC, jeff-dude requested changes
one minor comment below. i like keeping this pretty simple for 1inch / 0x lineage. i think there is room to improve 0x design, but that's for another day

2024-02-13 00:50 UTC, jeff-dude commented on models/_sector/dex/trades/dex_trades_beta.sql
> +{% set cte_to_union = ['curve', 'as_is_dexs', 'dexs'] %}
nice usage on the union of CTEs here

minor, but can you make the list one value per line?

```suggestion
{% set cte_to_union = [
    'curve'
    , 'as_is_dexs'
    , 'dexs'
    ] 
%}
```

2024-02-13 11:03 UTC, grkhr commented on models/oneinch/oneinch_lop_own_trades.sql
approve from us!

2024-02-13 20:39 UTC, jeff-dude approved these changes
updated the curve macro to use new `amount_usd` logic

this lgtm 🙏

2024-02-13 20:39 UTC, merged