Added solidly to dex.trades
duneanalytics/spellbook pull request #5477
Opened 2024-02-29 16:53 UTC by sophie-analytics

# Thank you for contributing to Spellbook!

Thank you for taking the time to submit code in Spellbook. A few things to consider:

- If you are a first-time contributor, please sign the CLA by copy & pasting **_exactly_** what the bot mentions in PR comment
- Refer to [docs](#spellbook-contribution-docs) section below to answer questions
- Dune team will review submitted PRs as soon as possible

## Spellbook sub-projects

To prepare for Spellbook to scale in size, Dune team has started to pilot sub-projects:

- For a quick overview, see [the GH discussion on the topic](https://github.com/duneanalytics/spellbook/discussions/5238)
  - Please ask questions and continue the conversation there
- The first spell lineage to move: `tokens.erc20` and all upstream spells which help build it
  - **_Note_**: Please navigate to [tokens](/tokens) root directory to find tokens objects

## Spellbook contribution docs

The [docs](docs) directory has been implemented to answer as many questions as possible. Please take the time to reference each `.md` file within this directory to understand how to efficiently contribute & why the repo is designed as it is 🪄

Example questions to be answered:

- What does each property in the [model config block](/docs/models/model_config_block.md) mean?
- What is the [CI test](/docs/ci_test/ci_test_overview.md) attached to PRs and how can I best utilize it?
- What are the Spellbook [best practices](/docs/general/best_practices.md)?

Please navigate through the [docs](/docs) directory to find as much info as you can.

**Note**: happy to take PRs to improve the docs, let us know 🤝

2024-02-29 16:53 UTC, dune-eng commented
Workflow run id 8099654510 approved.

2024-02-29 18:37 UTC, dune-eng commented
Workflow run id 8100978005 approved.

2024-02-29 18:37 UTC, dune-eng commented
Workflow run id 8100978188 approved.

2024-03-01 14:06 UTC, Hosuke requested changes

2024-03-01 14:06 UTC, Hosuke commented on seeds/_sector/dex/_schema.yml
> +  - name: solidly_v3_base_base_trades_seed
We may rename the seed name as `solidly_base_base_trades_seed`
```suggestion
  - name: solidly_base_base_trades_seed
```

2024-03-01 14:33 UTC, dune-eng commented
Workflow run id 8112899563 approved.

2024-03-01 14:33 UTC, dune-eng commented
Workflow run id 8112900169 approved.

2024-03-03 07:11 UTC, Hosuke approved these changes
LGTM.✅
Thank you @sophie-analytics 

[Sample solidly_v3_base_base_trades](https://dune.com/queries/3484973)

2024-03-04 11:37 UTC, jeff-dude approved these changes
left a minor comment below. nothing that blocks the code from being merged, but curious for long term if the schema should be cleaned up

2024-03-04 11:37 UTC, jeff-dude commented on sources/_sector/dex/trades/base/_sources.yml
> +  - name: solidly__base
wonder if this was a bug in decoding, to have two `_` in the schema name?

2024-03-04 14:41 UTC, merged