(SONNE FINANCE) ADD recent created USDC(native) market
duneanalytics/spellbook pull request #5738
Opened 2024-04-04 11:06 UTC by halfdoctor

This PR adds the recently started soTOKEN and underlying address for USDC(native) on Sonne Finance.
Accordingly bridged USDC has been labelled as USDCe.

2024-04-04 11:07 UTC, dune-eng commented
Workflow run id 8553605509 approved.

2024-04-04 11:08 UTC, halfdoctor commented
I have read the CLA Document and I hereby sign the CLA

2024-04-04 11:28 UTC, dune-eng commented
Workflow run id 8553870799 approved.

2024-04-04 11:29 UTC, dune-eng commented
Workflow run id 8553870878 approved.

2024-04-04 11:30 UTC, dune-eng commented
Workflow run id 8553885117 approved.

2024-04-04 11:30 UTC, dune-eng commented
Workflow run id 8553885212 approved.

2024-04-05 20:13 UTC, jeff-dude requested changes

2024-04-05 20:13 UTC, jeff-dude commented on sources/_sector/lending/supply/optimism/_sources.yml
> +      - name: soUSDCe_evt_Mint
it appears this decoded table source doesn't exist?
please see CI logs output to find error where query can't find this table

2024-04-30 16:35 UTC, jeff-dude commented
closing due to inactivity

2024-04-30 16:35 UTC, closed without merging