add in burned event
duneanalytics/spellbook pull request #5759
Opened 2024-04-09 18:46 UTC by AnonJon

- rename `ccip_tokens_locked` to `ccip_tokens_transferred`
- include `burned` in events in `ccip_tokens_transferred`
- include `tx_hash` in `ccip_send_requested`

2024-04-09 18:46 UTC, dune-eng commented
Workflow run id 8620763523 approved.

2024-04-09 18:46 UTC, dune-eng commented
Workflow run id 8620763610 approved.

2024-04-12 03:06 UTC, Hosuke requested changes

2024-04-12 03:06 UTC, Hosuke commented on models/chainlink/arbitrum/chainlink_arbitrum_ccip_tokens_transferred_logs.sql
> +  topic0 = 0x9f1ec8c880f76798e7b793325d625e9b60e4082a553c98f42b6cda368dd60008 -- Locked
Do you want to add incremental filters for selection from `logs` tables, as they are large tables.

2024-04-12 03:06 UTC, Hosuke commented on models/chainlink/arbitrum/chainlink_arbitrum_ccip_tokens_transferred_logs.sql
> +    materialized='view'
We can add schema in the config blocks and change the materialized strategy to `incremental`.

2024-04-12 21:07 UTC, dune-eng commented
Workflow run id 8667978535 approved.

2024-04-12 21:07 UTC, dune-eng commented
Workflow run id 8667979315 approved.

2024-04-12 21:08 UTC, AnonJon commented
@Hosuke I added in the filter. Let me know if that looks right.

2024-04-12 21:26 UTC, dune-eng commented
Workflow run id 8668165095 approved.

2024-04-12 21:26 UTC, dune-eng commented
Workflow run id 8668165189 approved.

2024-04-14 14:42 UTC, Hosuke commented on models/chainlink/avalanche_c/chainlink_avalanche_c_ccip_tokens_transferred_logs.sql
> +            AND block_time >= date_trunc('day', now() - interval '{{incremental_interval}}' day)
We can use the `incremental_predicate` here:
```suggestion
            AND {{ incremental_predicate('block_time') }}
```

2024-04-20 12:13 UTC, dune-eng commented
Workflow run id 8764920425 approved.

2024-04-20 12:13 UTC, dune-eng commented
Workflow run id 8764920460 approved.

2024-04-20 12:14 UTC, AnonJon commented
@Hosuke updated now with incremental_predicate

2024-04-20 13:30 UTC, Hosuke requested changes
Some adjustments needed for incremental views.

2024-04-20 13:30 UTC, Hosuke commented on models/chainlink/polygon/chainlink_polygon_ccip_tokens_transferred_logs.sql
> +    alias='ccip_tokens_transferred_logs',
You can add the schema in all config blocks now:
```suggestion
  config(
    schema='chainlink_polygon',
    alias='ccip_tokens_transferred_logs',
```

2024-04-20 13:30 UTC, Hosuke commented on models/chainlink/polygon/chainlink_polygon_ccip_tokens_transferred_logs.sql
> +  AND block_time >= CAST('2023-07-06' AS date)
We can introduce jinja var like `project_start_date` for the dates used in the sql:
i.e.
`{% set project_start_date = '2023-07-06' %}`
and
`AND block_time >= TIMESTAMP '{{project_start_date}}'`

2024-04-20 13:30 UTC, Hosuke commented on models/chainlink/polygon/chainlink_polygon_ccip_tokens_transferred_logs.sql
> +  )
You need to add the `unique_key` in the config blocks for incremental updates:
```suggestion
    incremental_strategy='merge',
    unique_key=['tx_hash', ...]
  )
```

2024-04-20 13:30 UTC, Hosuke commented on models/chainlink/polygon/chainlink_polygon_schema.yml
> +      Chainlink CCIP Tokens Transferred Logs
Remember to add tests for `unique_key`
```
tests:
      - dbt_utils.unique_combination_of_columns:
          - ...
```

2024-04-20 15:26 UTC, dune-eng commented
Workflow run id 8766032427 approved.

2024-04-20 15:26 UTC, dune-eng commented
Workflow run id 8766032472 approved.

2024-04-20 15:53 UTC, dune-eng commented
Workflow run id 8766155664 approved.

2024-04-20 15:53 UTC, dune-eng commented
Workflow run id 8766155781 approved.

2024-04-20 16:06 UTC, dune-eng commented
Workflow run id 8766225016 approved.

2024-04-20 16:06 UTC, dune-eng commented
Workflow run id 8766225193 approved.

2024-04-20 16:18 UTC, AnonJon commented
@Hosuke added in the unique tests

2024-04-22 10:20 UTC, Hosuke approved these changes
LGTM.✅
Thank you @AnonJon 

[Sample chainlink_ccip_tokens_transferred_logs](https://dune.com/queries/3660861)

Also please run `git merge main` to update this PR.

2024-04-23 13:26 UTC, Hosuke commented
Hi @AnonJon, please run `git merge main` to update this PR as well.

2024-04-23 13:53 UTC, dune-eng commented
Workflow run id 8801655237 approved.

2024-04-23 13:53 UTC, dune-eng commented
Workflow run id 8801655248 approved.

2024-04-23 20:59 UTC, jeff-dude approved these changes

2024-04-23 21:52 UTC, merged