add tokens transferred spell
duneanalytics/spellbook pull request #5845
Opened 2024-04-28 14:25 UTC by AnonJon

Add new tokens transferred spell to access token information.

2024-04-28 14:25 UTC, dune-eng commented
Workflow run id 8868272067 approved.

2024-04-28 14:25 UTC, dune-eng commented
Workflow run id 8868272075 approved.

2024-04-28 15:18 UTC, dune-eng commented
Workflow run id 8868559068 approved.

2024-04-28 15:18 UTC, dune-eng commented
Workflow run id 8868559113 approved.

2024-04-28 15:34 UTC, dune-eng commented
Workflow run id 8868639382 approved.

2024-04-28 15:34 UTC, dune-eng commented
Workflow run id 8868639361 approved.

2024-04-28 15:47 UTC, dune-eng commented
Workflow run id 8868697517 approved.

2024-04-28 15:47 UTC, dune-eng commented
Workflow run id 8868697557 approved.

2024-04-28 19:31 UTC, dune-eng commented
Workflow run id 8869910127 approved.

2024-04-28 19:31 UTC, dune-eng commented
Workflow run id 8869910107 approved.

2024-04-28 23:26 UTC, dune-eng commented
Workflow run id 8871148862 approved.

2024-04-28 23:26 UTC, dune-eng commented
Workflow run id 8871148879 approved.

2024-04-29 17:19 UTC, dune-eng commented
Workflow run id 8882710511 approved.

2024-04-29 17:19 UTC, dune-eng commented
Workflow run id 8882710833 approved.

2024-04-30 16:20 UTC, jeff-dude requested changes
@AnonJon i'd love to use this PR as an opportunity to introduce dbt macros to CCIP spells. since you're introducing a new spell, and the code looks repeatable across evm chains, it should fit perfectly.

please see here for initial context on how to approach:
https://github.com/duneanalytics/spellbook/blob/main/docs/macros/macro_overview.md

we can help you along the way if you happen to get stuck on anything.

2024-04-30 16:20 UTC, jeff-dude commented on models/chainlink/arbitrum/chainlink_arbitrum_ccip_tokens_transferred.sql
> +    {% endif %}
any time you are filtering on a table incrementally, you should apply the same filter in join conditions to other tables being brought in. please apply incremental filter on all joins which contain data in time-series format (i.e. prices, evt_transfer, other chainlink refs, etc.)

2024-05-01 01:45 UTC, dune-eng commented
Workflow run id 8904137029 approved.

2024-05-01 01:45 UTC, dune-eng commented
Workflow run id 8904137155 approved.

2024-05-01 02:16 UTC, AnonJon commented
@jeff-dude I implemented a macro for the latest spell. Tests are taking longer than expected so let me know if ive set up everything correctly.

2024-05-01 02:49 UTC, dune-eng commented
Workflow run id 8904655354 approved.

2024-05-01 02:49 UTC, dune-eng commented
Workflow run id 8904655416 approved.

2024-05-01 03:00 UTC, dune-eng commented
Workflow run id 8904718061 approved.

2024-05-01 03:00 UTC, dune-eng commented
Workflow run id 8904718225 approved.

2024-05-01 03:24 UTC, dune-eng commented
Workflow run id 8904918964 approved.

2024-05-01 03:24 UTC, dune-eng commented
Workflow run id 8904918972 approved.

2024-05-01 13:35 UTC, dune-eng commented
Workflow run id 8910055881 approved.

2024-05-01 13:35 UTC, dune-eng commented
Workflow run id 8910055997 approved.

2024-05-01 14:16 UTC, dune-eng commented
Workflow run id 8910478528 approved.

2024-05-01 15:33 UTC, jeff-dude requested changes

2024-05-01 15:33 UTC, jeff-dude commented on macros/models/_project/chainlink/chainlink_ccip_macro.sql
> +        WHERE {{ incremental_predicate('block_time') }}
```suggestion
        AND {{ incremental_predicate('sr.block_time') }}
```

2024-05-01 15:33 UTC, jeff-dude commented on macros/models/_project/chainlink/chainlink_ccip_macro.sql
> +    INNER JOIN {{ref('chainlink_' ~ blockchain ~ '_ccip_send_requested')}} sr ON le.tx_hash = sr.tx_hash
are there more join conditions we can add here to improve performance?
`block_number`? `block_date`? `block_time`? `evt_index`?

2024-05-01 15:33 UTC, jeff-dude commented on macros/models/_project/chainlink/chainlink_ccip_macro.sql
> +    INNER JOIN {{ref('chainlink_' ~ blockchain ~ '_ccip_send_requested')}} sr ON le.tx_hash = sr.tx_hash
joining only on varbinary hash values is a bit slow

2024-05-01 15:33 UTC, jeff-dude commented on macros/models/_project/chainlink/chainlink_ccip_macro.sql
> +    AND te.evt_tx_hash = le.tx_hash
similar question here on potential for more join conditions

2024-05-01 15:33 UTC, jeff-dude commented on macros/models/_project/chainlink/chainlink_ccip_macro.sql
> +        WHERE {{ incremental_predicate('block_time') }}
```suggestion
        AND {{ incremental_predicate('te.block_time') }}
```

2024-05-01 15:33 UTC, jeff-dude commented on macros/models/_project/chainlink/chainlink_ccip_macro.sql
> +    LEFT JOIN {{ source('tokens', 'erc20') }} t ON te.contract_address = t.contract_address
and blockchain = blockchain?

2024-05-01 15:33 UTC, jeff-dude commented on macros/models/_project/chainlink/chainlink_ccip_macro.sql
> +    {% endif %}
```suggestion

```

2024-05-01 15:33 UTC, jeff-dude commented on macros/models/_project/chainlink/chainlink_ccip_macro.sql
> +    {% endif %}
token metadata doesn't need to be filtered incrementally, it's just one row per address/chain

2024-05-01 15:33 UTC, jeff-dude commented on macros/models/_project/chainlink/chainlink_ccip_macro.sql
> +    AND p.minute = DATE_TRUNC ('minute', le.block_time)
and blockchain = blockchain?

2024-05-01 15:33 UTC, jeff-dude commented on macros/models/_project/chainlink/chainlink_ccip_macro.sql
> +        WHERE {{ incremental_predicate('block_time') }}
```suggestion
        AND {{ incremental_predicate('p.minute') }}
```

2024-05-01 15:33 UTC, jeff-dude commented on models/chainlink/chainlink_ccip_tokens_transferred.sql
> +
add schema property here plz

2024-05-01 16:37 UTC, dune-eng commented
Workflow run id 8912118743 approved.

2024-05-01 16:37 UTC, dune-eng commented
Workflow run id 8912119041 approved.

2024-05-01 16:50 UTC, dune-eng commented
Workflow run id 8912253235 approved.

2024-05-01 16:50 UTC, dune-eng commented
Workflow run id 8912253329 approved.

2024-05-01 17:52 UTC, dune-eng commented
Workflow run id 8912919336 approved.

2024-05-01 17:52 UTC, dune-eng commented
Workflow run id 8912919591 approved.

2024-05-01 18:48 UTC, dune-eng commented
Workflow run id 8913552733 approved.

2024-05-01 18:48 UTC, dune-eng commented
Workflow run id 8913552914 approved.

2024-05-01 19:49 UTC, dune-eng commented
Workflow run id 8914185787 approved.

2024-05-01 19:49 UTC, dune-eng commented
Workflow run id 8914185955 approved.

2024-05-01 20:58 UTC, dune-eng commented
Workflow run id 8914892198 approved.

2024-05-01 20:58 UTC, dune-eng commented
Workflow run id 8914892289 approved.

2024-05-02 14:09 UTC, dune-eng commented
Workflow run id 8925281619 approved.

2024-05-02 15:23 UTC, jeff-dude approved these changes
code is looking pretty good to me -- hope you find this approach useful 🙏  looking forward to seeing this more in the chainlink spells.

the performance is still a bit slow, but looks like it's a lot of data and joins to transfers tables.

2024-05-02 18:09 UTC, merged