add new tokens to price list [base]
duneanalytics/spellbook pull request #5918
Opened 2024-05-13 19:08 UTC by RantumBits

add new tokens to price list [base]

2024-05-13 19:09 UTC, dune-eng commented
Workflow run id 9068455963 approved.

2024-05-13 19:09 UTC, dune-eng commented
Workflow run id 9068456227 approved.

2024-05-13 19:09 UTC, dune-eng commented
Workflow run id 9068456223 approved.

2024-05-15 13:16 UTC, jeff-dude approved these changes

2024-05-15 13:25 UTC, jeff-dude requested changes

2024-05-15 13:25 UTC, jeff-dude commented on models/prices/base/prices_base_tokens.sql
> +    ('kurbi-kurbi', 'base', 'KURBI', 0x653a143b8d15c565c6623d1f168cfbec1056d872, 9)
missing comma

2024-06-03 19:21 UTC, dune-eng commented
Workflow run id 9356041405 approved.

2024-06-03 19:21 UTC, dune-eng commented
Workflow run id 9356041524 approved.

2024-06-03 19:21 UTC, dune-eng commented
Workflow run id 9356041553 approved.

2024-06-03 19:52 UTC, dune-eng commented
Workflow run id 9356382417 approved.

2024-06-03 19:52 UTC, dune-eng commented
Workflow run id 9356382543 approved.

2024-06-03 19:52 UTC, dune-eng commented
Workflow run id 9356382563 approved.

2024-06-03 20:25 UTC, dune-eng commented
Workflow run id 9356780124 approved.

2024-06-03 20:25 UTC, dune-eng commented
Workflow run id 9356780540 approved.

2024-06-04 19:31 UTC, RantumBits commented
this one is ready now @jeff-dude

2024-06-04 21:34 UTC, jeff-dude approved these changes

2024-06-05 13:33 UTC, merged