[WIP] Update Bebop dex-aggregator
duneanalytics/spellbook pull request #6035
Opened 2024-05-30 10:47 UTC by B1boid

2024-05-30 10:47 UTC, dune-eng commented
Workflow run id 9301267333 approved.

2024-05-30 10:47 UTC, dune-eng commented
Workflow run id 9301267436 approved.

2024-05-30 14:42 UTC, dune-eng commented
Workflow run id 9304503768 approved.

2024-05-30 14:42 UTC, dune-eng commented
Workflow run id 9304503850 approved.

2024-05-30 14:47 UTC, dune-eng commented
Workflow run id 9304567866 approved.

2024-05-30 19:35 UTC, dune-eng commented
Workflow run id 9308183401 approved.

2024-05-30 19:35 UTC, dune-eng commented
Workflow run id 9308183695 approved.

2024-05-31 11:09 UTC, dune-eng commented
Workflow run id 9317221346 approved.

2024-05-31 11:09 UTC, dune-eng commented
Workflow run id 9317221513 approved.

2024-05-31 11:42 UTC, dune-eng commented
Workflow run id 9317588045 approved.

2024-05-31 11:42 UTC, dune-eng commented
Workflow run id 9317588246 approved.

2024-05-31 13:22 UTC, dune-eng commented
Workflow run id 9318883908 approved.

2024-05-31 13:22 UTC, dune-eng commented
Workflow run id 9318884020 approved.

2024-06-03 08:04 UTC, Hosuke requested changes
We can use `incremental_predicate` for incremental filters.
Also there is a new format for the post_hook.

2024-06-03 08:04 UTC, Hosuke commented on models/bebop/arbitrum/bebop_blend_arbitrum_trades.sql
> +    AND evt.evt_block_time >= date_trunc('day', now() - interval '7' Day)
Same as above.

2024-06-03 08:04 UTC, Hosuke commented on models/bebop/arbitrum/bebop_blend_arbitrum_trades.sql
> +    AND tx.block_time >= date_trunc('day', now() - interval '7' Day)
Same as above.

2024-06-03 08:04 UTC, Hosuke commented on models/bebop/base/bebop_base_trades.sql
> +                        \'["alekss"]\') }}'
We can use the new format for post_hook here:
```suggestion
        materialized = 'view',
        post_hook='{{ expose_spells(blockchains = \'["base"]\',
                                    spell_type = "project",
                                    spell_name = "bebop",
                                    contributors = \'["alekss"]\') }}'
```

2024-06-03 08:04 UTC, Hosuke commented on models/bebop/base/bebop_blend_base_trades.sql
> +    AND evt.evt_block_time >= date_trunc('day', now() - interval '7' Day)
Same as above incremental filters.

2024-06-03 11:01 UTC, dune-eng commented
Workflow run id 9348948020 approved.

2024-06-03 11:01 UTC, dune-eng commented
Workflow run id 9348948142 approved.

2024-06-03 11:28 UTC, dune-eng commented
Workflow run id 9349307014 approved.

2024-06-03 11:28 UTC, dune-eng commented
Workflow run id 9349307165 approved.

2024-06-03 12:17 UTC, B1boid commented
> We can use `incremental_predicate` for incremental filters. Also there is a new format for the post_hook.

Thanks, fixed

2024-06-03 13:37 UTC, Hosuke approved these changes
LGTM.✅
Thank you @B1boid 

[Sample bebop.trades]()

2024-06-03 15:17 UTC, jeff-dude approved these changes

2024-06-03 15:17 UTC, merged