remake bridge.flows
duneanalytics/spellbook pull request #6051
Opened 2024-06-02 03:22 UTC by hildobby

## Thank you for contributing to Spellbook 🪄

### Contribution type
Please check the type of contribution this pull request is for:

- [x] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

2024-07-02 01:28 UTC, hildobby commented
I'm really confused here, how can uniqueness tests fail for `bridge.flows_beta` when the spell simply calls another spell (`bridge_ethereum.flows`) which itself has been tested and has no dupes. any clues @jeff-dude @aalan3 @0xRobin?

2024-07-02 07:38 UTC, 0xRobin commented
@hildobby if duplicates show up in the incremental run, but not in the first run of the CI. It has often been a problem with null values being present in one of the merge columns.

2024-08-02 13:30 UTC, jeff-dude commented
closing due to inactivity. feel free to reopen and describe what needs to happen next, if necessary. thank you.

2024-08-03 00:31 UTC, hildobby commented
Once my contract name change from `ovm` to `base` is approved, this pr should be close to ready

2024-10-16 19:09 UTC, jeff-dude commented
this won't run in CI until it's migrated over to new subproject structure. can this be moved to daily?

2024-10-23 20:30 UTC, 0xBoxer commented
Due to a dbt version change, you need to merge main into your branch before the Github action runner runs successfully again.

2025-01-23 19:23 UTC, jeff-dude commented
going through another cleanup effort on PRs. if reopen is necessary, plz do one at a time until finalized and merged 🙏

2025-04-16 15:07 UTC, 0xBoxer commented
@hildobby can you write a paragraph on what you are trying to build here, not really following the initialized, finalised schema.

2025-04-16 15:18 UTC, hildobby commented
> @hildobby can you write a paragraph on what you are trying to build here, not really following the initialized, finalised schema. 

Yeah i'll rewrite a detailed PR description once this is ready, which it almost is.

In short:

The initiated is the send tx on original chain and finalised is the receive tx on the destination chain.

Benefits are:
- when both chains are on dune: the final bridge.flows can have bridge time metric + total bridge fees data.
- when only 1 chain is on dune: deeper coverage, tracking sends+receives gets us a higher chance of catching bridge events since only 1/2 chains need data coverage. that's not relevant for base's canonical bridge but will be for global bridges like laterzero and across.

2025-07-04 11:09 UTC, hildobby commented
phew 103 commits of iteration so far ☝️

but i'm almost done!

2025-07-10 17:37 UTC, 0xBoxer approved these changes

2025-07-10 17:37 UTC, 0xBoxer commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_deposits.sql
> +        , bridge_id
bridge_id is very ambigious, `bridge_tx_id` or `bridge_transfer_id` would be more descriptive

2025-07-10 17:37 UTC, 0xBoxer commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_flows.sql
> +FULL OUTER JOIN {{ ref('bridges_withdrawals') }} w USING (bridge_name, bridge_version, deposit_chain, withdrawal_chain, bridge_id)
probably helps to add `block_date` to speed up the join?

on second thought probably did not use that by intention because that breaks the condition in extreme cases?

2025-07-10 17:37 UTC, 0xBoxer commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_flows.sql
> +FULL OUTER JOIN {{ ref('bridges_withdrawals') }} w USING (bridge_name, bridge_version, deposit_chain, withdrawal_chain, bridge_id)
do you strictly need all these conditions, wouldn't just id be sufficient?

2025-07-10 17:37 UTC, 0xBoxer commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_flows.sql
> +    schema = 'bridges',
all the schema here should be `bridges_evms.flows` etc., we will probably want to have a truely multichain bridges_crosschain.flows` eventually

2025-07-10 23:58 UTC, hildobby commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_flows.sql
> +FULL OUTER JOIN {{ ref('bridges_withdrawals') }} w USING (bridge_name, bridge_version, deposit_chain, withdrawal_chain, bridge_id)
no unfortunately joining on block_date would mean it's not catching all events, especially since we have intent based bridges where a user can execute withdrawal whenever he wants

yes, those ids are bridge+version specific. and every chain where there are deposits has its ids which is just the event nonce afaik. so these need to be all joined on

2025-07-11 00:00 UTC, hildobby commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_deposits.sql
> +        , bridge_id
i changed all references to `bridge_transfer_id`

2025-07-11 00:05 UTC, hildobby commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_flows.sql
> +    schema = 'bridges',
but what would that mean for ethereum>solana bridge transfers? they would be bound to be incomplete in both `bridges_evms.flows` and `bridges_solana.flows`, so i think it makes sense for `bridges_evms.deposits` and `bridges_evms.withdrawals` but probably not for the final `bridges.flows` model. wdyt?

2025-07-12 12:25 UTC, 0xBoxer commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_flows.sql
> +    schema = 'bridges',
yeah that makes sense to me, but that would mean that we should set this up as  `bridges_crosschain.flows` and not use any varbinary columns to start with IMO

2025-07-14 13:36 UTC, hildobby commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_flows.sql
> +    schema = 'bridges',
ah if you want output to be strings then `bridges_evms.flows` with varbinary values does make sense. this would really reduce compute costs when joining on other evm tables. and i guess other vms may have their specificities (datatypes and occasional different columns) so you're right that it's better to have a table for each vm type and have it all joined into a crosschain table

also, wouldn't `bridges_crosschain.flows` just be `bridges.flows`?

2025-07-14 13:53 UTC, hildobby commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_flows.sql
> +    schema = 'bridges',
i just moved it all into an `evms` subfolder and renamed `bridges.deposits/withdrawals/flows` to `bridges_evms.deposits/withdrawals/flows` and created a view for each on top, it might make sense to materialise those crosschain tables once bridge events from other vms are added

2025-07-14 16:20 UTC, 0xBoxer commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_flows.sql
> +    schema = 'bridges',
> also, wouldn't bridges_crosschain.flows just be bridges.flows?

in a perfect world that's how things would work, but now that we have the very confusing `dex.trades `and `tokens.transfers`  which are EVM specific, it kinda would make things even more confusing to have a truly multichain `bridges.flows`

2025-07-14 16:20 UTC, 0xBoxer commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_flows.sql
> +    schema = 'bridges',
I suggest `bridges.flows` just stay vacant, for now and ever, the tablename should specify what it contains

2025-07-14 16:22 UTC, 0xBoxer commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_flows.sql
> +FULL OUTER JOIN {{ ref('bridges_withdrawals') }} w USING (bridge_name, bridge_version, deposit_chain, withdrawal_chain, bridge_id)
fair enough, took a look myself and seems reasonable to match on these

2025-07-14 16:22 UTC, 0xBoxer commented
let me do another pass tmrw, looks pretty good already

2025-07-14 16:33 UTC, hildobby commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_flows.sql
> +    schema = 'bridges',
alright, done

2025-07-14 16:34 UTC, hildobby commented
i changed `bridges.` to `bridges_crosschain.` and updated the two slides in the PR description @0xBoxer

2025-07-16 13:41 UTC, 0xBoxer commented
This is good to go from my POV, fantastic job @hildobby. Thank you!

2025-07-21 18:14 UTC, jeff-dude requested changes
minor feedback below

2025-07-21 18:14 UTC, jeff-dude commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_crosschain_deposits.sql
> +    , alias = 'initiated'
```suggestion
    , alias = 'deposits'
```

2025-07-21 18:14 UTC, jeff-dude commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/bridges_crosschain_deposits.sql
> +    , alias = 'initiated'
assuming this should be deposits, similar to file name and the withdrawals equivalent model

2025-07-21 18:14 UTC, jeff-dude commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/evms/bridges_evms_deposits.sql
> +    , alias = 'initiated'
```suggestion
    , alias = 'deposits'
```

2025-07-21 18:14 UTC, jeff-dude commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/evms/bridges_evms_deposits.sql
> +    , alias = 'initiated'
assuming this should be deposits, similar to file name and the withdrawals equivalent model

2025-07-21 18:14 UTC, jeff-dude commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/chains/base/bridges_base_deposits.sql
> +    'bridges_base_cctp_v1_deposits'
not a must at all, but while in here, curious if you'd like to add the `blockchain` variable usage in these ref lists to futureproof typos of other chains when adding in the future

2025-07-21 18:14 UTC, jeff-dude commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/chains/base/bridges_base_deposits.sql
> +    'bridges_base_cctp_v1_deposits'
applies to all of these base/ethereum level models, will only comment once

2025-07-21 18:25 UTC, hildobby commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/chains/base/bridges_base_deposits.sql
> +    'bridges_base_cctp_v1_deposits'
i'm not sure what you mean here?

2025-07-21 18:27 UTC, jeff-dude commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/chains/base/bridges_base_deposits.sql
> +    'bridges_base_cctp_v1_deposits'
`'bridges_' + blockchain + '_cctp_v1_deposits'`
this type of format, like you do on schema names and such

2025-07-21 18:27 UTC, jeff-dude commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/chains/base/bridges_base_deposits.sql
> +    'bridges_base_cctp_v1_deposits'
to be clear, not 100% sure this is correct syntax, but hopefully gives the idea

2025-07-21 18:30 UTC, hildobby commented on dbt_subprojects/hourly_spellbook/models/_sector/bridges/flows/chains/base/bridges_base_deposits.sql
> +    'bridges_base_cctp_v1_deposits'
ah alright makes sense, just did that on all 4 files and pushed the PR

2025-07-23 18:29 UTC, merged