Add solana dex price hrs
duneanalytics/spellbook pull request #6080
Opened 2024-06-05 01:11 UTC by thanhlmm

## Thank you for contributing to Spellbook 🪄

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

2024-06-05 01:11 UTC, dune-eng commented
Workflow run id 9376550750 approved.

2024-06-05 01:11 UTC, dune-eng commented
Workflow run id 9376551184 approved.

2024-06-05 09:15 UTC, Hosuke reviewed
cc. @henrystats, do you think this spell may be related to `dex.prices`?

2024-06-05 09:15 UTC, Hosuke commented on models/dex/solana/dex_solana_price_hour.sql
> +        alias = 'dex_solana_price_hour',
```suggestion
        schema = 'dex_solana',
        alias = 'price_hour',
```

2024-06-05 09:15 UTC, Hosuke commented on models/dex/solana/dex_solana_price_hour.sql
> +            AND block_time >= DATE('2022-03-10')
We may use the jinja var `project_start_date` here.

2024-06-05 16:55 UTC, jeff-dude commented
thanks for starting the review @Hosuke 

keep in mind, we have similar spells at the project level, let's be sure to keep them consistent (even if that means modifying the orca ones to match):
https://github.com/duneanalytics/spellbook/blob/main/models/orca_whirlpool/orca_whirlpool_token_prices_hour.sql

2024-06-06 02:20 UTC, dune-eng commented
Workflow run id 9394106419 approved.

2024-06-06 02:20 UTC, dune-eng commented
Workflow run id 9394106552 approved.

2024-06-06 02:21 UTC, dune-eng commented
Workflow run id 9394124168 approved.

2024-06-06 02:22 UTC, dune-eng commented
Workflow run id 9394124261 approved.

2024-06-07 06:21 UTC, Hosuke requested changes

2024-06-07 06:21 UTC, Hosuke commented on models/dex/solana/dex_solana_price_hour.sql
> +            AND block_time >= DATE('{{project_start_date}}')
We may fix the syntax:
```suggestion
            AND block_time >= DATE '{{project_start_date}}'
```

2024-06-07 13:39 UTC, dune-eng commented
Workflow run id 9417987054 approved.

2024-06-07 13:39 UTC, dune-eng commented
Workflow run id 9417987387 approved.

2024-06-07 16:28 UTC, Hosuke commented on models/dex/solana/dex_solana_price_hour.sql
> +{ % set project_start_date = '2022-03-10' % } --grabbed min block time from whirlpool_solana.whirlpool_call_swap #}
Here is a syntax typo:
```suggestion
{% set project_start_date = '2022-03-10' %} --grabbed min block time from whirlpool_solana.whirlpool_call_swap
```

2024-06-13 07:01 UTC, thanhlmm commented
Hi there, could you please make this PR merged?

2024-06-13 16:12 UTC, jeff-dude commented
@Hosuke is this good to go from your perspective?

2024-06-13 21:07 UTC, Hosuke approved these changes
LGTM.✅
Thank you @thanhlmm 

[Sample dex_solana_price_hour](https://dune.com/queries/3828050)

2024-06-13 21:11 UTC, Hosuke commented on models/dex/solana/dex_solana_schema.yml
> +  - name: dex_solana_price_hour
```suggestion

  - name: dex_solana_price_hour
```

2024-06-13 21:14 UTC, Hosuke commented
> @Hosuke is this good to go from your perspective?

The spell alone is good to go.

However, the problem left is whether we need to integrate this spell into `dex.prices`?
https://github.com/duneanalytics/spellbook/blob/main/models/dex/dex_prices.sql

As they have similar (hourly price) schema, but different approach/implementation.
Also `dex.prices` does not cover solana currently.

2024-06-14 19:59 UTC, jeff-dude commented
> > @Hosuke is this good to go from your perspective?
> 
> The spell alone is good to go.
> 
> However, the problem left is whether we need to integrate this spell into `dex.prices`? https://github.com/duneanalytics/spellbook/blob/main/models/dex/dex_prices.sql
> 
> As they have similar (hourly price) schema, but different approach/implementation. Also `dex.prices` does not cover solana currently.



> > @Hosuke is this good to go from your perspective?
> 
> The spell alone is good to go.
> 
> However, the problem left is whether we need to integrate this spell into `dex.prices`? https://github.com/duneanalytics/spellbook/blob/main/models/dex/dex_prices.sql
> 
> As they have similar (hourly price) schema, but different approach/implementation. Also `dex.prices` does not cover solana currently.

no, we will leave solana out for now.

2024-06-17 17:49 UTC, jeff-dude approved these changes

2024-06-18 13:39 UTC, jeff-dude commented
fyi @aalan3 another solana spell to rebase into your PR

2024-06-18 13:39 UTC, merged