paraswap: add paraswap_zkevm model along with v6.1
duneanalytics/spellbook pull request #6100
Opened 2024-06-06 12:34 UTC by mwamedacen

This PR is a follow up of previous works and is mainly copy pasting. Previous PRs: https://github.com/duneanalytics/spellbook/pull/5597 and https://github.com/duneanalytics/spellbook/pull/6002

2024-06-06 12:35 UTC, dune-eng commented
Workflow run id 9400951863 approved.

2024-06-07 05:18 UTC, dune-eng commented
Workflow run id 9412036634 approved.

2024-06-07 05:18 UTC, dune-eng commented
Workflow run id 9412036833 approved.

2024-06-07 09:12 UTC, dune-eng commented
Workflow run id 9414598097 approved.

2024-06-07 09:12 UTC, dune-eng commented
Workflow run id 9414598476 approved.

2024-06-08 09:53 UTC, dune-eng commented
Workflow run id 9427890743 approved.

2024-06-08 09:53 UTC, dune-eng commented
Workflow run id 9427890791 approved.

2024-06-08 12:19 UTC, dune-eng commented
Workflow run id 9428665135 approved.

2024-06-08 12:19 UTC, dune-eng commented
Workflow run id 9428665218 approved.

2024-06-09 16:14 UTC, Hosuke requested changes

2024-06-09 16:14 UTC, Hosuke commented on models/paraswap/zkevm/paraswap_v6_zkevm_trades.sql
> +                                \'["eptighte", "mwamedacen"]\') }}'
We can apply the new format for post_hook here:
```suggestion
    post_hook='{{ expose_spells(blockchains = \'["zkevm"]\',
                                spell_type = "project",
                                spell_name = "paraswap_v6",
                                contributors = \'["eptighte", "mwamedacen"]\') }}'
```

2024-06-09 16:14 UTC, Hosuke commented on models/paraswap/zkevm/paraswap_v6_zkevm_trades.sql
> +    WHERE blockTime >= date_trunc('day', now() - interval '7' day)
We can use the `incremental_predicate` here and for all incremental filters:
```suggestion
    WHERE {{ incremental_predicate('blockTime') }}
```

2024-06-10 04:24 UTC, dune-eng commented
Workflow run id 9442458777 approved.

2024-06-10 04:24 UTC, dune-eng commented
Workflow run id 9442458858 approved.

2024-06-10 04:24 UTC, dune-eng commented
Workflow run id 9442460616 approved.

2024-06-10 04:25 UTC, dune-eng commented
Workflow run id 9442460771 approved.

2024-06-10 04:26 UTC, mwamedacen commented
thanks for the suggestions, applied @Hosuke both. Worth noting that those improvements are not normalised across the other spells (not only ParaSwap ones)

2024-06-10 06:52 UTC, Hosuke requested changes
These improvements are new standards that we are striving to implement in our development process. We will do our best to cover these in all new spells. Thank you for your understanding and support!

2024-06-10 06:52 UTC, Hosuke commented on models/paraswap/zkevm/paraswap_v6_zkevm_trades.sql
> +    AND tx.block_time >= date_trunc('day', now() - interval '7' day)
```suggestion
    AND {{ incremental_predicate('tx.block_time') }}
```

2024-06-10 06:52 UTC, Hosuke commented on models/paraswap/zkevm/paraswap_v6_zkevm_trades.sql
> +    AND p2.minute >= date_trunc('day', now() - interval '7' day)
```suggestion
    AND {{ incremental_predicate('p2.minute') }}
```

2024-06-10 06:52 UTC, Hosuke commented on models/paraswap/zkevm/paraswap_v6_zkevm_trades.sql
> +    AND p1.minute >= date_trunc('day', now() - interval '7' day)
```suggestion
    AND {{ incremental_predicate('p1.minute') }}
```

2024-06-19 17:31 UTC, jeff-dude commented
i've been letting this one sit, as it appears suggestion still remain. please do make the changes and look to finalize

2024-08-02 13:30 UTC, jeff-dude commented
closing due to inactivity. feel free to reopen and describe what needs to happen next, if necessary. thank you.

2024-08-02 13:30 UTC, closed without merging