Add Pancakeswap Linea Dex Trades
duneanalytics/spellbook pull request #6102
Opened 2024-06-06 14:53 UTC by chef-seaweed

## Thank you for contributing to Spellbook 🪄

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

2024-06-06 14:53 UTC, dune-eng commented
Workflow run id 9403117626 approved.

2024-06-06 14:53 UTC, dune-eng commented
Workflow run id 9403117761 approved.

2024-06-07 01:54 UTC, dune-eng commented
Workflow run id 9410432075 approved.

2024-06-07 01:54 UTC, dune-eng commented
Workflow run id 9410432223 approved.

2024-06-07 06:17 UTC, Hosuke requested changes

2024-06-07 06:17 UTC, Hosuke commented on seeds/_sector/dex/pancakeswap_linea_base_trades_seed.csv
We may miss the seed schema for this file.

2024-06-07 09:41 UTC, dune-eng commented
Workflow run id 9414981516 approved.

2024-06-07 09:41 UTC, dune-eng commented
Workflow run id 9414981798 approved.

2024-06-07 09:46 UTC, dune-eng commented
Workflow run id 9415034093 approved.

2024-06-07 09:46 UTC, dune-eng commented
Workflow run id 9415034418 approved.

2024-06-07 09:47 UTC, dune-eng commented
Workflow run id 9415052243 approved.

2024-06-07 09:47 UTC, dune-eng commented
Workflow run id 9415052460 approved.

2024-06-07 14:20 UTC, Hosuke approved these changes
LGTM.✅
Thank you @chef-seaweed 

[Sample pancakeswap_v2_linea_base_trades](https://dune.com/queries/3808586)
[Sample pancakeswap_v3_linea_base_trades](https://dune.com/queries/3808590)

2024-06-11 01:45 UTC, dune-eng commented
Workflow run id 9458236041 approved.

2024-06-11 01:45 UTC, dune-eng commented
Workflow run id 9458236246 approved.

2024-06-11 15:00 UTC, jeff-dude approved these changes

2024-06-11 15:00 UTC, merged