Update CoW Protocol sources and tables
duneanalytics/spellbook pull request #6221
Opened 2024-06-20 16:54 UTC by olgafetisova

Adding new sources and tables

2024-06-20 16:55 UTC, dune-eng commented
Workflow run id 9601372095 approved.

2024-06-20 16:55 UTC, dune-eng commented
Workflow run id 9601372548 approved.

2024-06-24 15:19 UTC, Hosuke requested changes

2024-06-24 15:19 UTC, Hosuke commented on sources/cow_protocol/arbitrum/cow_protocol_arbitrum_sources.yml
> +      - name: GPv2Settlement_evt_Settlement
We may insert this source at the wrong position, as `&tokens` definition is interrupted by this source.

2024-08-02 13:34 UTC, jeff-dude commented
closing due to inactivity. feel free to reopen and describe what needs to happen next, if necessary. thank you.

2024-08-02 13:34 UTC, closed without merging