Adding new tables to CoW Protocol Arbitrum chain
duneanalytics/spellbook pull request #6224
Opened 2024-06-20 17:40 UTC by olgafetisova

*Contribution type*

- [ X] New spell(s)

- **Spell name(s):** cow_protocol_arbitrum.solvers, cow_protocol_arbitrum.batches
- **Description:** The spell adds all CoW Protocol solvers and batches on Arbitrum chain. 
- **Who are the new spell(s) for?** General Community
- **Test instructions:** POC query can be found here https://dune.com/queries/3840594 and https://dune.com/queries/3840597

Thank you for your contribution!

2024-06-20 17:41 UTC, dune-eng commented
Workflow run id 9601958346 approved.

2024-06-20 17:41 UTC, dune-eng commented
Workflow run id 9601958727 approved.

2024-06-20 17:48 UTC, dune-eng commented
Workflow run id 9602033258 approved.

2024-06-20 17:48 UTC, dune-eng commented
Workflow run id 9602033588 approved.

2024-06-20 18:03 UTC, dune-eng commented
Workflow run id 9602204575 approved.

2024-06-20 18:03 UTC, dune-eng commented
Workflow run id 9602204694 approved.

2024-06-20 18:51 UTC, dune-eng commented
Workflow run id 9602817668 approved.

2024-06-20 18:51 UTC, dune-eng commented
Workflow run id 9602817856 approved.

2024-06-20 18:56 UTC, dune-eng commented
Workflow run id 9602872632 approved.

2024-06-20 18:56 UTC, dune-eng commented
Workflow run id 9602872818 approved.

2024-06-20 19:11 UTC, dune-eng commented
Workflow run id 9603059204 approved.

2024-06-20 19:11 UTC, dune-eng commented
Workflow run id 9603059555 approved.

2024-06-20 19:17 UTC, dune-eng commented
Workflow run id 9603129241 approved.

2024-06-20 19:17 UTC, dune-eng commented
Workflow run id 9603129509 approved.

2024-06-20 19:30 UTC, dune-eng commented
Workflow run id 9603266578 approved.

2024-06-20 19:30 UTC, dune-eng commented
Workflow run id 9603266901 approved.

2024-06-20 19:57 UTC, dune-eng commented
Workflow run id 9603551180 approved.

2024-06-20 19:57 UTC, dune-eng commented
Workflow run id 9603551257 approved.

2024-06-20 20:18 UTC, dune-eng commented
Workflow run id 9603809226 approved.

2024-06-20 20:18 UTC, dune-eng commented
Workflow run id 9603809109 approved.

2024-06-24 11:30 UTC, dune-eng commented
Workflow run id 9644544381 approved.

2024-06-24 11:30 UTC, dune-eng commented
Workflow run id 9644544483 approved.

2024-06-24 11:52 UTC, dune-eng commented
Workflow run id 9644821754 approved.

2024-06-24 11:53 UTC, dune-eng commented
Workflow run id 9644821980 approved.

2024-06-24 11:58 UTC, dune-eng commented
Workflow run id 9644885632 approved.

2024-06-24 11:58 UTC, dune-eng commented
Workflow run id 9644885950 approved.

2024-06-24 12:30 UTC, olgafetisova commented
@jeff-dude 
The Pr is ready to be merged from our side, please review

2024-06-24 15:25 UTC, Hosuke commented on models/cow_protocol/arbitrum/cow_protocol_arbitrum_batches.sql
> +
We need the `schema` here, and probably we can put `arbitrum` inside the `schema`:
```suggestion
        schema = 'cow_protocol_arbitrum',
        alias = 'batches',
```

2024-06-24 16:35 UTC, dune-eng commented
Workflow run id 9649056486 approved.

2024-06-24 16:35 UTC, dune-eng commented
Workflow run id 9649056763 approved.

2024-06-24 16:36 UTC, dune-eng commented
Workflow run id 9649059704 approved.

2024-06-24 16:36 UTC, dune-eng commented
Workflow run id 9649060050 approved.

2024-06-24 16:36 UTC, dune-eng commented
Workflow run id 9649062315 approved.

2024-06-24 16:36 UTC, dune-eng commented
Workflow run id 9649062088 approved.

2024-06-24 16:36 UTC, dune-eng commented
Workflow run id 9649064285 approved.

2024-06-24 16:36 UTC, dune-eng commented
Workflow run id 9649064474 approved.

2024-06-26 09:24 UTC, dune-eng commented
Workflow run id 9677069161 approved.

2024-06-26 09:24 UTC, dune-eng commented
Workflow run id 9677069521 approved.

2024-06-26 22:05 UTC, jeff-dude requested changes

2024-06-26 22:05 UTC, jeff-dude commented on models/cow_protocol/arbitrum/cow_protocol_arbitrum_batches.sql
> +    from cow_protocol_arbitrum.trades
since this spell now lives in the dex subproject, we will need to add to sources [here](https://github.com/duneanalytics/spellbook/blob/main/sources/_subprojects/dex/_sources.yml#L62). then we should update this to use jinja source syntax

2024-06-26 22:05 UTC, jeff-dude commented on models/cow_protocol/arbitrum/cow_protocol_arbitrum_schema.yml
> +  - name: cow_protocol_arbitrum_batches
can you add unique column test to this spell? we should validate the unique key used in model config block is unique. while the merge helps us do this, it's good to include the test to be safe

2024-06-26 22:05 UTC, jeff-dude commented on models/cow_protocol/arbitrum/cow_protocol_arbitrum_batches.sql
> +),
looks like you may repeat this logic from the solvers spell below, maybe we read from that here instead? create a clean lineage? 
(i could be wrong, only eyeballed it quickly)

2024-06-27 09:08 UTC, dune-eng commented
Workflow run id 9693825914 approved.

2024-06-27 09:08 UTC, dune-eng commented
Workflow run id 9693826090 approved.

2024-06-27 09:27 UTC, dune-eng commented
Workflow run id 9694105060 approved.

2024-06-27 09:27 UTC, dune-eng commented
Workflow run id 9694105464 approved.

2024-06-27 09:32 UTC, dune-eng commented
Workflow run id 9694192572 approved.

2024-06-27 09:32 UTC, dune-eng commented
Workflow run id 9694192998 approved.

2024-06-27 09:49 UTC, dune-eng commented
Workflow run id 9694422294 approved.

2024-06-27 10:27 UTC, dune-eng commented
Workflow run id 9694934337 approved.

2024-06-27 10:27 UTC, dune-eng commented
Workflow run id 9694934652 approved.

2024-06-27 10:33 UTC, dune-eng commented
Workflow run id 9695021324 approved.

2024-06-27 10:33 UTC, dune-eng commented
Workflow run id 9695021575 approved.

2024-06-27 10:34 UTC, olgafetisova commented on models/cow_protocol/arbitrum/cow_protocol_arbitrum_batches.sql
> +),
Yes, indeed; however, the CI keeps failing (I checked again). I can keep this logic for now here, and once the PR is merged, I can submit another one removing the duplicate logic and referencing the correct file.

2024-06-27 11:00 UTC, olgafetisova commented
@jeff-dude  addressed you comments, ready for review

2024-06-27 19:53 UTC, jeff-dude commented on models/cow_protocol/arbitrum/cow_protocol_arbitrum_batches.sql
> +),
okay, we can move this forward and fast follow with an enhancement. the issue you had in prior commit was using source instead of ref. since these spells are in same project, you can simply use ref() instead

2024-06-27 19:53 UTC, jeff-dude approved these changes

2024-06-27 19:54 UTC, merged