Add NMT price
duneanalytics/spellbook pull request #6316
Opened 2024-07-04 05:50 UTC by rivusdao

## Thank you for contributing to Spellbook 🪄

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

2024-07-04 05:51 UTC, dune-eng commented
Workflow run id 9789188440 approved.

2024-07-04 05:51 UTC, dune-eng commented
Workflow run id 9789188613 approved.

2024-07-04 05:51 UTC, dune-eng commented
Workflow run id 9789188597 approved.

2024-07-04 17:17 UTC, Hosuke requested changes

2024-07-04 17:17 UTC, Hosuke commented on models/prices/ethereum/prices_ethereum_tokens.sql
> +    ('nmt-netmind-token', 'ethereum', 'NMT', 0x03aa6298f1370642642415edc0db8b957783e8d6, 18)
This token may have been already defined here:
https://github.com/duneanalytics/spellbook/blob/4a480d57025551aa2051464b83e2f182e1cd8ddb/models/prices/ethereum/prices_ethereum_tokens.sql#L1753

2024-07-12 00:59 UTC, jeff-dude commented
closing due to duplicate token entry

2024-07-12 00:59 UTC, closed without merging