feat: add chainswap
duneanalytics/spellbook pull request #6332
Opened 2024-07-05 16:24 UTC by clizzard7

2024-07-05 16:25 UTC, dune-eng commented
Workflow run id 9811148524 approved.

2024-07-05 16:25 UTC, dune-eng commented
Workflow run id 9811148648 approved.

2024-07-05 17:42 UTC, dune-eng commented
Workflow run id 9811273295 approved.

2024-07-05 17:42 UTC, dune-eng commented
Workflow run id 9811273479 approved.

2024-07-05 17:47 UTC, dune-eng commented
Workflow run id 9811632666 approved.

2024-07-05 17:48 UTC, dune-eng commented
Workflow run id 9811405538 approved.

2024-07-05 17:51 UTC, dune-eng commented
Workflow run id 9811632793 approved.

2024-07-05 17:53 UTC, dune-eng commented
Workflow run id 9811790049 approved.

2024-07-05 17:59 UTC, dune-eng commented
Workflow run id 9811789963 approved.

2024-07-05 18:02 UTC, dune-eng commented
Workflow run id 9811924073 approved.

2024-07-05 18:02 UTC, dune-eng commented
Workflow run id 9811924061 approved.

2024-07-05 18:04 UTC, dune-eng commented
Workflow run id 9811981783 approved.

2024-07-06 15:44 UTC, Hosuke requested changes

2024-07-06 15:44 UTC, Hosuke commented on models/chain_swap/arbitrum/chain_swap_arbitrum_trades.sql
> +        alias="trades",
Please use `'` instead of `"` in the spellbook. As `"` may refer to column name.
```suggestion
        alias='trades',
```

2024-07-11 15:47 UTC, dune-eng commented
Workflow run id 9894534877 approved.

2024-07-11 15:47 UTC, dune-eng commented
Workflow run id 9894534986 approved.

2024-07-11 15:47 UTC, dune-eng commented
Workflow run id 9894537227 approved.

2024-07-11 15:47 UTC, dune-eng commented
Workflow run id 9894537614 approved.

2024-07-11 19:04 UTC, Hosuke requested changes

2024-07-11 19:04 UTC, Hosuke commented on models/chain_swap/arbitrum/chain_swap_arbitrum_trades.sql
> +        where
Please use single quotes (') in the code as much as possible. Double quotes (") can sometimes break the code.

2024-07-13 13:09 UTC, dune-eng commented
Workflow run id 9920193071 approved.

2024-07-13 13:09 UTC, dune-eng commented
Workflow run id 9920193130 approved.

2024-07-13 13:10 UTC, dune-eng commented
Workflow run id 9920196009 approved.

2024-07-13 13:10 UTC, dune-eng commented
Workflow run id 9920196094 approved.

2024-07-13 13:40 UTC, dune-eng commented
Workflow run id 9920379036 approved.

2024-07-13 13:40 UTC, dune-eng commented
Workflow run id 9920379064 approved.

2024-07-13 14:16 UTC, dune-eng commented
Workflow run id 9920578611 approved.

2024-07-13 14:34 UTC, dune-eng commented
Workflow run id 9920697985 approved.

2024-07-13 14:34 UTC, dune-eng commented
Workflow run id 9920698243 approved.

2024-07-13 14:42 UTC, dune-eng commented
Workflow run id 9920742605 approved.

2024-07-13 14:42 UTC, dune-eng commented
Workflow run id 9920742499 approved.

2024-07-13 14:49 UTC, dune-eng commented
Workflow run id 9920775014 approved.

2024-07-13 14:49 UTC, dune-eng commented
Workflow run id 9920775092 approved.

2024-07-13 15:01 UTC, dune-eng commented
Workflow run id 9920830494 approved.

2024-07-13 15:01 UTC, dune-eng commented
Workflow run id 9920830549 approved.

2024-07-13 15:04 UTC, whalehunting commented
@Hosuke the uniqueness test is failing on the incremental run only, initial run works fine.
any idea why this is happening? we probably need to set an incremental filter somewhere (fee_deposits CTE?)

2024-07-15 09:02 UTC, Hosuke commented
> @Hosuke the uniqueness test is failing on the incremental run only, initial run works fine. any idea why this is happening? we probably need to set an incremental filter somewhere (fee_deposits CTE?)

I think we may need to add `incremental` filters into these spells first.
Currently I cannot identify any incremental filters in these spells.

2024-07-24 06:39 UTC, dune-eng commented
Workflow run id 10071784899 approved.

2024-07-24 06:39 UTC, dune-eng commented
Workflow run id 10071785209 approved.

2024-07-24 06:39 UTC, whalehunting commented
> > @Hosuke the uniqueness test is failing on the incremental run only, initial run works fine. any idea why this is happening? we probably need to set an incremental filter somewhere (fee_deposits CTE?)
> 
> I think we may need to add `incremental` filters into these spells first. Currently I cannot identify any incremental filters in these spells.

ok will try that out and report back, thank you sir!

2024-07-28 14:57 UTC, dune-eng commented
Workflow run id 10132637251 approved.

2024-07-28 15:05 UTC, dune-eng commented
Workflow run id 10132686143 approved.

2024-07-28 15:11 UTC, dune-eng commented
Workflow run id 10132730375 approved.

2024-07-29 18:26 UTC, Hosuke requested changes

2024-07-29 18:26 UTC, Hosuke commented on models/chain_swap/arbitrum/chain_swap_arbitrum_trades.sql
> +
Maybe we can add an incremental filter here.

2024-07-29 18:26 UTC, Hosuke commented on models/chain_swap/arbitrum/chain_swap_arbitrum_trades.sql
> +        from {{ source('dex', 'trades') }} as trades
We can apply incremental filters to most selection from large tables/sources.

2024-07-29 18:26 UTC, Hosuke commented on models/chain_swap/arbitrum/chain_swap_arbitrum_trades.sql
> +        order by trades.block_time desc, trades.evt_index desc
Since this is not the final select, I am not sure if the `order by` works here.

2024-08-29 17:22 UTC, closed without merging