Raho1 scroll prices update 1
duneanalytics/spellbook pull request #6350
Opened 2024-07-09 15:53 UTC by raho1

## Thank you for contributing to Spellbook 🪄

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

2024-07-09 15:53 UTC, dune-eng commented
Workflow run id 9860269906 approved.

2024-07-09 18:12 UTC, Hosuke requested changes

2024-07-09 18:12 UTC, Hosuke commented on models/prices/scroll/prices_scroll_tokens.sql
> +    ('rseth-rseth', 'scroll', 'wrsETH ', 0xa25b25548B4C98B0c7d3d27dcA5D5ca743d68b7F, 18),
`wrsETH` has been defined at Line 29:
https://github.com/duneanalytics/spellbook/blob/ef2f8bd78e5b064e7e1962c6accccc97582977fd/models/prices/scroll/prices_scroll_tokens.sql#L29

2024-07-09 18:38 UTC, raho1 reviewed
Not sure what needs to be done here on my end, if anything?

2024-07-09 18:50 UTC, Hosuke requested changes

2024-07-09 18:50 UTC, Hosuke commented on models/prices/scroll/prices_scroll_tokens.sql
> +    ('rseth-rseth', 'scroll', 'wrsETH ', 0xa25b25548B4C98B0c7d3d27dcA5D5ca743d68b7F, 18),
We should remove the duplicated line:
```suggestion
```

2024-07-09 18:58 UTC, Hosuke approved these changes
LGTM.✅
Thank you @raho1

2024-07-10 21:00 UTC, jeff-dude approved these changes

2024-07-11 13:14 UTC, merged