feat: track both v6.1 and v6.2 paraswap volume
duneanalytics/spellbook pull request #6377
Opened 2024-07-16 09:25 UTC by alexshchur

## Thank you for contributing to Spellbook 🪄

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

2024-07-18 15:55 UTC, jeff-dude requested changes

2024-07-18 15:55 UTC, jeff-dude commented on macros/models/_project/paraswap/v6/paraswap_v6_trades_master.sql
can you move your macros from `macros/` to `dex/macros/`?
they must've been missed when we moved dex models over to new directory

2024-07-19 06:04 UTC, alexshchur commented on macros/models/_project/paraswap/v6/paraswap_v6_trades_master.sql
sure

2024-07-19 14:45 UTC, jeff-dude approved these changes
thank you!

2024-07-23 15:50 UTC, merged