Add ZeroEx Settler trades on Arbitrum
duneanalytics/spellbook pull request #6425
Opened 2024-07-24 19:01 UTC by RantumBits

### Contribution type
Please check the type of contribution this pull request is for:

- [x] New spell(s)
- [ ]Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name* zeroex_arbitrum.settler_trades
- **Description:** [Detailed description of the new spell(s) and their purpose] decode 0x API trades on new settler contracts on Arbitrum
- **Who are the new spell(s) for?** [Internal team or general community] both
- **How will the new spell(s) be used downstream?** [Description of downstream usage] merged into dex-agg.trades
- **Implementation details:** [Information on how the spell(s) are implemented]  gets taker and maker amounts only, no fills level data for intermediary swaps 
- **Test instructions:** [How to test the new spell(s)] https://dune.com/queries/3921632
- **Related issue(s):** [Link to related issues, if any]

2024-07-24 19:02 UTC, dune-eng commented
Workflow run id 10082481425 approved.

2024-07-24 19:02 UTC, dune-eng commented
Workflow run id 10082481828 approved.

2024-07-24 19:02 UTC, dune-eng commented
Workflow run id 10082481846 approved.

2024-07-24 19:09 UTC, dune-eng commented
Workflow run id 10082575962 approved.

2024-07-24 19:09 UTC, dune-eng commented
Workflow run id 10082575964 approved.

2024-07-24 19:22 UTC, dune-eng commented
Workflow run id 10082756445 approved.

2024-07-24 19:22 UTC, dune-eng commented
Workflow run id 10082756691 approved.

2024-07-24 19:22 UTC, dune-eng commented
Workflow run id 10082756690 approved.

2024-07-24 20:03 UTC, dune-eng commented
Workflow run id 10083237992 approved.

2024-07-24 20:03 UTC, dune-eng commented
Workflow run id 10083237673 approved.

2024-07-24 20:03 UTC, dune-eng commented
Workflow run id 10083237984 approved.

2024-07-24 20:37 UTC, dune-eng commented
Workflow run id 10083677725 approved.

2024-07-24 20:37 UTC, dune-eng commented
Workflow run id 10083678034 approved.

2024-07-24 20:37 UTC, dune-eng commented
Workflow run id 10083678022 approved.

2024-07-24 21:04 UTC, dune-eng commented
Workflow run id 10083990854 approved.

2024-07-24 21:04 UTC, dune-eng commented
Workflow run id 10083990850 approved.

2024-07-24 21:04 UTC, dune-eng commented
Workflow run id 10083990755 approved.

2024-07-24 21:27 UTC, dune-eng commented
Workflow run id 10084268192 approved.

2024-07-24 21:27 UTC, dune-eng commented
Workflow run id 10084268029 approved.

2024-07-24 21:27 UTC, dune-eng commented
Workflow run id 10084268182 approved.

2024-07-24 21:58 UTC, dune-eng commented
Workflow run id 10084584419 approved.

2024-07-24 21:58 UTC, dune-eng commented
Workflow run id 10084584740 approved.

2024-07-24 21:58 UTC, dune-eng commented
Workflow run id 10084584736 approved.

2024-07-25 17:10 UTC, Hosuke reviewed
LGTM.✅
Thank you @RantumBits 

[Sample zeroex_arbitrum_settler_trades]()

2024-07-25 17:10 UTC, Hosuke commented on dex/models/_projects/zeroex/arbitrum/zeroex_arbitrum_settler_trades.sql
You can reformat your other spells like this one.

2024-07-25 17:11 UTC, Hosuke commented on dex/models/_projects/zeroex/arbitrum/zeroex_arbitrum_schema.yml
> +  - name: zeroex_arbitrum_settler_trades
```suggestion
        description: "The protocol fee paid in ETH"

  - name: zeroex_arbitrum_settler_trades
```

2024-07-25 21:03 UTC, jeff-dude requested changes

2024-07-25 21:03 UTC, jeff-dude commented on dex/models/_projects/zeroex/arbitrum/zeroex_arbitrum_settler_trades.sql
> +            {% if not is_incremental() %}
```suggestion
            {% else %}
```

2024-07-25 21:03 UTC, jeff-dude commented on dex/models/_projects/zeroex/arbitrum/zeroex_arbitrum_settler_trades.sql
> +        {% if not is_incremental() %}
```suggestion
        {% else %}
```

2024-07-25 21:03 UTC, jeff-dude commented on dex/models/_projects/zeroex/arbitrum/zeroex_arbitrum_settler_trades.sql
> +        {% if not is_incremental() %}
```suggestion
        {% else %}
```

2024-07-25 21:03 UTC, jeff-dude commented on dex/models/_projects/zeroex/arbitrum/zeroex_arbitrum_settler_trades.sql
> +        {% if not is_incremental() %}
```suggestion
        {% else %}
```

2024-07-25 21:04 UTC, jeff-dude commented
i will hold off on reviewing the other chains, until we get this one finalized

2024-07-25 21:38 UTC, dune-eng commented
Workflow run id 10101890744 approved.

2024-07-25 21:38 UTC, dune-eng commented
Workflow run id 10101890874 approved.

2024-07-25 21:38 UTC, dune-eng commented
Workflow run id 10101890875 approved.

2024-07-25 21:40 UTC, dune-eng commented
Workflow run id 10101910962 approved.

2024-07-25 21:40 UTC, dune-eng commented
Workflow run id 10101911124 approved.

2024-07-25 21:40 UTC, dune-eng commented
Workflow run id 10101911133 approved.

2024-07-25 21:42 UTC, dune-eng commented
Workflow run id 10101923164 approved.

2024-07-25 21:42 UTC, dune-eng commented
Workflow run id 10101923426 approved.

2024-07-25 21:42 UTC, dune-eng commented
Workflow run id 10101923557 approved.

2024-07-25 21:44 UTC, dune-eng commented
Workflow run id 10101949885 approved.

2024-07-25 21:44 UTC, dune-eng commented
Workflow run id 10101950095 approved.

2024-07-25 21:44 UTC, dune-eng commented
Workflow run id 10101950090 approved.

2024-07-25 21:46 UTC, dune-eng commented
Workflow run id 10101968972 approved.

2024-07-25 21:46 UTC, dune-eng commented
Workflow run id 10101969367 approved.

2024-07-25 21:46 UTC, dune-eng commented
Workflow run id 10101969370 approved.

2024-07-25 21:53 UTC, dune-eng commented
Workflow run id 10102040123 approved.

2024-07-25 21:53 UTC, dune-eng commented
Workflow run id 10102040424 approved.

2024-07-25 21:53 UTC, dune-eng commented
Workflow run id 10102040423 approved.

2024-07-25 22:00 UTC, dune-eng commented
Workflow run id 10102101621 approved.

2024-07-25 22:00 UTC, dune-eng commented
Workflow run id 10102101873 approved.

2024-07-25 22:00 UTC, dune-eng commented
Workflow run id 10102101870 approved.

2024-07-25 22:07 UTC, RantumBits commented
> i will hold off on reviewing the other chains, until we get this one finalized

thanks for the review. all changes applied here. i'll update other chains to match

2024-07-25 23:16 UTC, RantumBits commented
> > i will hold off on reviewing the other chains, until we get this one finalized
> 
> thanks for the review. all changes applied here. i'll update other chains to match

all now updated to match changes requested here @jeff-dude

2024-07-26 17:16 UTC, closed without merging