Add oku_sei_base_trades
duneanalytics/spellbook pull request #6476
Opened 2024-07-31 18:34 UTC by Hosuke

#6474 

### Update!
Please build spells in the proper [subproject](../dbt_subprojects/) directory. For more information, please see the main [readme](../README.md), which also links to a GH discussion with the option to ask questions.

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [x] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

2024-07-31 19:17 UTC, Hosuke commented on dbt_subprojects/dex/models/trades/sei/_schema.yml
> +#          seed_file: ref('dragon_swap_sei_base_trades_seed')
```suggestion
      - check_dex_base_trades_seed:
          seed_file: ref('dragon_swap_sei_base_trades_seed')
```

2024-07-31 22:02 UTC, jeff-dude requested changes

2024-07-31 22:02 UTC, jeff-dude commented on sources/_sector/dex/trades/sei/_sources.yml
building a new file here makes me wonder where we store sources for `jelly_swap` 🤔 
can we move those sources here to this new file?

2024-08-01 10:18 UTC, Hosuke commented on sources/_sector/dex/trades/sei/_sources.yml
I am also having this question. (Potentially in the labels sources)
I will try to move the `jelly_swap` related sources here.

2024-08-01 15:00 UTC, jeff-dude approved these changes
great stuff, thanks again for the speed here!

2024-08-01 18:31 UTC, merged