Add new table to paraswap Base trades
duneanalytics/spellbook pull request #6483
Opened 2024-08-01 12:20 UTC by PablloZz

## Thank you for contributing to Spellbook 🪄

### Update!
Please build spells in the proper [subproject](../dbt_subprojects/) directory. For more information, please see the main [readme](../README.md), which also links to a GH discussion with the option to ask questions.

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [x] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:**
Add a `SwappedDirect` table to Paraswap Base trades to include missed transactions.
Examples: [1](https://basescan.org/tx/0x98d900c692582445f2d327a4a7dd7c3050c05d8148af38a0ac24721ccc52ba81), [2](https://basescan.org/tx/0xd1a6b3161fad8effde6280fd966fe606aea89692d001998291995080d6ab5d66), [3](https://basescan.org/tx/0x7be5df2195108dba496ecdebcd21b97646b2a2b0b14180b7e106662361023b2e)

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

2024-08-01 12:21 UTC, dune-eng commented
Workflow run id 10198172087 approved.

2024-08-01 12:21 UTC, dune-eng commented
Workflow run id 10198172270 approved.

2024-08-01 14:56 UTC, PablloZz commented
I have read the CLA Document and I hereby sign the CLA

2024-08-02 13:55 UTC, dune-eng commented
Workflow run id 10216797005 approved.

2024-08-02 13:55 UTC, dune-eng commented
Workflow run id 10216797167 approved.

2024-08-02 14:00 UTC, MaksHladun commented
I have read the CLA Document and I hereby sign the CLA

2024-08-02 18:13 UTC, Hosuke requested changes

2024-08-02 18:13 UTC, Hosuke commented on dbt_subprojects/dex/models/_projects/paraswap/base/paraswap_v5_base_trades.sql
> +    ,source('paraswap_base', 'AugustusSwapper_evt_SwappedDirect')
Please add the following source schema in `sources/paraswap/base/paraswap_base_sources.yml`:
```
      - name: AugustusSwapper_evt_SwappedDirect
        loaded_at_field: evt_block_time
```

2024-08-03 06:48 UTC, dune-eng commented
Workflow run id 10226088407 approved.

2024-08-03 06:48 UTC, dune-eng commented
Workflow run id 10226088564 approved.

2024-08-03 10:23 UTC, Hosuke approved these changes
LGTM.✅
Thank you @PablloZz

2024-08-05 13:42 UTC, jeff-dude approved these changes

2024-08-05 14:50 UTC, merged