Add Polygon TVL Balances spell
duneanalytics/spellbook pull request #6547
Opened 2024-08-13 08:02 UTC by safeintern

## Thank you for contributing to Spellbook 🪄

### Update!
Please build spells in the proper [subproject](../dbt_subprojects/) directory. For more information, please see the main [readme](../README.md), which also links to a GH discussion with the option to ask questions.

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

2024-08-13 08:02 UTC, dune-eng commented
Workflow run id 10365909590 approved.

2024-08-13 08:02 UTC, dune-eng commented
Workflow run id 10365909876 approved.

2024-08-13 08:05 UTC, dune-eng commented
Workflow run id 10365961845 approved.

2024-08-13 08:05 UTC, dune-eng commented
Workflow run id 10365961976 approved.

2024-08-13 08:07 UTC, dune-eng commented
Workflow run id 10365994234 approved.

2024-08-13 08:07 UTC, dune-eng commented
Workflow run id 10365994441 approved.

2024-08-13 08:10 UTC, dune-eng commented
Workflow run id 10366031376 approved.

2024-08-13 08:10 UTC, dune-eng commented
Workflow run id 10366031453 approved.

2024-08-13 08:13 UTC, dune-eng commented
Workflow run id 10366074290 approved.

2024-08-20 12:23 UTC, Hosuke commented on dbt_subprojects/hourly_spellbook/models/_project/safe/polygon/safe_polygon_balances.sql
> +                                    \'["safeintern"]\') }}'
```suggestion
        post_hook = '{{ expose_spells(blockchains = \'["polygon"]\',
                                      spell_type = "project",
                                      spell_name = "safe",
                                      contributors = \'["safeintern"]\') }}'
```

2024-08-20 12:23 UTC, Hosuke requested changes

2024-08-20 12:23 UTC, Hosuke commented on dbt_subprojects/hourly_spellbook/models/_project/safe/polygon/safe_polygon_balances.sql
> +    where day >= date('2021-07-01')
We can introduce '2021-07-01' as a jinja variable.

2024-08-20 14:58 UTC, dune-eng commented
Workflow run id 10474061370 approved.

2024-08-20 14:58 UTC, dune-eng commented
Workflow run id 10474061670 approved.

2024-08-21 10:11 UTC, Hosuke approved these changes
LGTM.✅
Thank you @safeintern 

[Sample safe_polygon_balances](https://dune.com/queries/4005187)

2024-08-21 20:29 UTC, jeff-dude approved these changes

2024-08-22 12:10 UTC, merged