add chains to contract labels spell
duneanalytics/spellbook pull request #6640
Opened 2024-08-30 22:51 UTC by RantumBits

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [x] Adding to existing spell lineage
- [ ] Bug fix

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

- add base, linea, scroll, mantle, blast, zksync to  contract_labels spell

2024-08-30 22:51 UTC, dune-eng commented
Workflow run id 10640103585 approved.

2024-08-30 22:51 UTC, dune-eng commented
Workflow run id 10640103678 approved.

2024-08-30 23:15 UTC, dune-eng commented
Workflow run id 10640285738 approved.

2024-08-30 23:15 UTC, dune-eng commented
Workflow run id 10640285925 approved.

2024-08-31 17:37 UTC, Hosuke requested changes

2024-08-31 17:37 UTC, Hosuke commented on dbt_subprojects/daily_spellbook/models/_sector/labels/addresses/__single_category_labels__/contracts/labels_contracts.sql
> +FROM {{ source('mantle','contracts') }}
Duped `mantle` contracts?
Line 140 and Line 164

2024-09-03 17:09 UTC, dune-eng commented
Workflow run id 10687465549 approved.

2024-09-03 17:09 UTC, dune-eng commented
Workflow run id 10687465992 approved.

2024-09-03 19:54 UTC, jeff-dude approved these changes

2024-09-03 22:17 UTC, closed without merging