Add core superfluid protocol events to daily spellbook
duneanalytics/spellbook pull request #6669
Opened 2024-09-04 21:09 UTC by leopk-code

## Thank you for contributing to Spellbook 🪄

### Update!
Please build spells in the proper [subproject](../dbt_subprojects/) directory. For more information, please see the main [readme](../README.md), which also links to a GH discussion with the option to ask questions.

### Contribution type
Please check the type of contribution this pull request is for:

- [x] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *dbt_subprojects/daily_spellbook/models/superfluid/**
- **Description:** Seven low-level events that together reflect most of the capabilities of superfluid protocol. 
- **Who are the new spell(s) for?** For Superfluid and community maintained dashboards
- **How will the new spell(s) be used downstream?** Directly in dashboards. Currently no downstream spellbook tables planned
- **Implementation details:** Incremental tables based on the logs table for each network
- **Test instructions:** na
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

2024-09-04 21:10 UTC, dune-eng commented
Workflow run id 10709560764 approved.

2024-09-04 21:10 UTC, dune-eng commented
Workflow run id 10709561144 approved.

2024-09-04 21:37 UTC, dune-eng commented
Workflow run id 10709907529 approved.

2024-09-04 21:37 UTC, dune-eng commented
Workflow run id 10709907625 approved.

2024-09-05 13:47 UTC, dune-eng commented
Workflow run id 10721700614 approved.

2024-09-05 15:52 UTC, dune-eng commented
Workflow run id 10723835250 approved.

2024-09-05 15:52 UTC, dune-eng commented
Workflow run id 10723836070 approved.

2024-09-05 17:53 UTC, dune-eng commented
Workflow run id 10725598156 approved.

2024-09-05 17:53 UTC, dune-eng commented
Workflow run id 10725598492 approved.

2024-09-14 07:56 UTC, Hosuke requested changes
Thank you for your contribution @leopk-code!
We may add `superfluid_ethereum` roll-up spells to aggregate chain-level spells, then add `post_hook` in roll-up spells' config block.

2024-09-14 07:56 UTC, Hosuke commented on dbt_subprojects/daily_spellbook/models/superfluid/arbitrum/superfluid_arbitrum_flow_distribution_updated_events.sql
> +    materialized = 'incremental',
Hi @leopk-code,
for `incremental` spells, 
we need to define the `unique_key` in config blocks.

2024-09-14 07:56 UTC, Hosuke commented on dbt_subprojects/daily_spellbook/models/superfluid/arbitrum/superfluid_arbitrum_schema.yml
> +      A table containing all flow updated events on Arbitrum.
Also we need to test apply 
```
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
```
test to `unique_key` in model schema.

2024-09-14 07:57 UTC, Hosuke commented on dbt_subprojects/daily_spellbook/models/superfluid/arbitrum/superfluid_arbitrum_flow_distribution_updated_events.sql
> +    materialized = 'incremental',
dbt docs:
https://docs.getdbt.com/docs/build/incremental-models#defining-a-unique-key-optional

2024-09-19 09:07 UTC, cincauhangus commented
Hi there, just FYI @leopk-code has left superfluid and I am taking over his role. 

@leopk-code would it be better if I forked your repo to add the changes (and you'll need to merge it in later) or shall I start a new PR from scratch?

2024-09-19 10:41 UTC, leopk-code commented
@cincauhangus might be easier to start a new pull request based on my fork!

2024-10-15 07:43 UTC, closed without merging