Add worldchain safes
duneanalytics/spellbook pull request #6870
Opened 2024-10-03 10:52 UTC by danielpartida

## Thank you for contributing to Spellbook 🪄

### Update!
Please build spells in the proper [subproject](../dbt_subprojects/) directory. For more information, please see the main [readme](../README.md), which also links to a GH discussion with the option to ask questions.

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

2024-10-03 10:52 UTC, dune-eng commented
Workflow run id 11160626821 approved.

2024-10-03 10:52 UTC, dune-eng commented
Workflow run id 11160627283 approved.

2024-10-03 14:17 UTC, jeff-dude commented
thanks for helping expand the chains here 🙌 
i don't believe the tables are ready yet, so i will mark as blocked / WIP for now

2024-10-04 08:04 UTC, danielpartida commented
Sounds good @jeff-dude. I just prepared the spell to be ready once the decoded schemas + raw tables are ready

2024-10-09 16:48 UTC, dune-eng commented
Workflow run id 11259445985 approved.

2024-10-09 16:48 UTC, dune-eng commented
Workflow run id 11259446343 approved.

2024-10-09 17:05 UTC, dune-eng commented
Workflow run id 11259689170 approved.

2024-10-09 17:05 UTC, dune-eng commented
Workflow run id 11259689608 approved.

2024-10-09 17:08 UTC, dune-eng commented
Workflow run id 11259736404 approved.

2024-10-09 17:08 UTC, dune-eng commented
Workflow run id 11259736269 approved.

2024-10-09 17:15 UTC, danielpartida commented
@jeff-dude fyi I implemented the base sources of Worldchain, we need those schemas for the safe_worldchain too.

On another note, I am receiving a strange error stating that the schema safe_worldchain_safes requires a schema safe_worldchain_singletons. But the safe_worldchain_singletons is implemented too. Do you know if I am missing something?

<img width="911" alt="Screenshot 2024-10-09 at 19 14 39" src="https://github.com/user-attachments/assets/98aadd58-ef47-47ec-86ee-fe0588829fc2">

2024-10-09 22:21 UTC, jeff-dude commented on sources/_base_sources/evm/worldchain_base_sources.yml
fyi @Hosuke on the sources for worldchain

2024-10-09 22:22 UTC, jeff-dude requested changes

2024-10-09 22:22 UTC, jeff-dude commented on dbt_subprojects/hourly_spellbook/models/_project/safe/worldchain/safe_worldchain_safes.sql
> +join {{ ref('safe_wolrdchain_singletons') }} s
```suggestion
join {{ ref('safe_worldchain_singletons') }} s
```

2024-10-09 22:22 UTC, jeff-dude commented on dbt_subprojects/hourly_spellbook/models/_project/safe/worldchain/safe_worldchain_safes.sql
> +join {{ ref('safe_wolrdchain_singletons') }} s
looks like just a typo?

2024-10-10 05:48 UTC, dune-eng commented
Workflow run id 11268204654 approved.

2024-10-10 05:49 UTC, dune-eng commented
Workflow run id 11268208093 approved.

2024-10-10 05:49 UTC, dune-eng commented
Workflow run id 11268208240 approved.

2024-10-10 12:01 UTC, jeff-dude commented
looks like you have source schema names incorrect?
should be just `safe_worldchain` rather than `gnosis_` prefix?

2024-10-10 12:19 UTC, danielpartida commented
The smart contract is developed by Safe. Hence, I would prefer if the decoded schema lives under gnosis_safe instead of safe_worldchain

2024-10-10 12:20 UTC, danielpartida commented
@jeff-dude The smart contract is developed by Safe. Hence, I would prefer it if the decoded schema goes under gnosis_safe instead of safe_worldchain. This is also where the rest of the decoded contracts are for the other chains

2024-10-10 12:34 UTC, jeff-dude commented
> @jeff-dude The smart contract is developed by Safe. Hence, I would prefer it if the decoded schema goes under gnosis_safe instead of safe_worldchain. This is also where the rest of the decoded contracts are for the other chains

gotcha, let me connect ya back with @agaperste then to get this cleaned up

2024-10-11 13:16 UTC, dune-eng commented
Workflow run id 11293068103 approved.

2024-10-11 13:16 UTC, dune-eng commented
Workflow run id 11293068456 approved.

2024-10-11 13:31 UTC, danielpartida commented
Hi @jeff-dude, Nia just told me that the tables are ready. However, when making the build I am still facing issues. Do you know if the name of the decoded tables are correct?

2024-10-11 14:10 UTC, jeff-dude commented
> Hi @jeff-dude, Nia just told me that the tables are ready. However, when making the build I am still facing issues. Do you know if the name of the decoded tables are correct?

can confirm it doesn't exist to your expectation:
```
select *
from gnosis_safe_worldchain.safeproxyfactory_v1_3_0_evt_proxycreation
limit 100
```

@thecaptncrunch @agaperste where do we stand on helping daniel on the safe naming standards for the new worldchain?

2024-10-11 15:56 UTC, agaperste commented
gnosis_safe_worldchain.safeproxyfactory_v_1_3_0_evt_proxycreation

gnosis_safe_worldchain.safeproxyfactory_v_1_4_1_evt_proxycreation


these are the two tables actually -- I see a small discrepancy on the
contract name also (T_T)


started a TG chat for me, Jeff and Daniel --> let's decide what to do
quickly together



On Fri, Oct 11, 2024 at 10:10 AM jeff-dude ***@***.***> wrote:

> Hi @jeff-dude <https://github.com/jeff-dude>, Nia just told me that the
> tables are ready. However, when making the build I am still facing issues.
> Do you know if the name of the decoded tables are correct?
>
> can confirm it doesn't exist to your expectation:
>
> select *
> from gnosis_safe_worldchain.safeproxyfactory_v1_3_0_evt_proxycreation
> limit 100
>
> @thecaptncrunch <https://github.com/thecaptncrunch> @agaperste
> <https://github.com/agaperste> where do we stand on helping daniel on the
> safe naming standards for the new worldchain?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/duneanalytics/spellbook/pull/6870#issuecomment-2407499043>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABMOUKWWYRTBGC6N4DYUAU3Z27L5LAVCNFSM6AAAAABPJQYO3CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBXGQ4TSMBUGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-11 18:57 UTC, dune-eng commented
Workflow run id 11297821394 approved.

2024-10-11 18:57 UTC, dune-eng commented
Workflow run id 11297821659 approved.

2024-10-11 19:02 UTC, dune-eng commented
Workflow run id 11297890191 approved.

2024-10-11 19:02 UTC, dune-eng commented
Workflow run id 11297890345 approved.

2024-10-11 19:03 UTC, dune-eng commented
Workflow run id 11297892059 approved.

2024-10-11 19:03 UTC, dune-eng commented
Workflow run id 11297892507 approved.

2024-10-11 19:05 UTC, dune-eng commented
Workflow run id 11297928062 approved.

2024-10-11 19:05 UTC, dune-eng commented
Workflow run id 11297928263 approved.

2024-10-11 19:08 UTC, dune-eng commented
Workflow run id 11297967526 approved.

2024-10-11 19:08 UTC, dune-eng commented
Workflow run id 11297967688 approved.

2024-10-11 19:15 UTC, dune-eng commented
Workflow run id 11298049011 approved.

2024-10-11 19:15 UTC, dune-eng commented
Workflow run id 11298049147 approved.

2024-10-11 19:20 UTC, danielpartida commented
Green light! @jeff-dude @Hosuke

2024-10-12 15:35 UTC, Hosuke approved these changes
LGTM.✅
Thank you @danielpartida 

[Sample safe_worldchain_safes](https://dune.com/queries/4155389)

2024-10-14 15:03 UTC, jeff-dude requested changes

2024-10-14 15:03 UTC, jeff-dude commented on models/safe/zkevm/safe_zkevm_trasactions.sql
is this `zkevm` entry an accident?
it's in the old directory, so it won't run in prod anywhere. it didn't run in CI either (as expected)

2024-10-14 21:50 UTC, danielpartida commented on models/safe/zkevm/safe_zkevm_trasactions.sql
That is odd, I will remove it in an extra commit. It should not be there. Thank you for spotting this @jeff-dude

2024-10-14 21:52 UTC, dune-eng commented
Workflow run id 11335544490 approved.

2024-10-14 21:52 UTC, dune-eng commented
Workflow run id 11335544603 approved.

2024-10-14 21:53 UTC, dune-eng commented
Workflow run id 11335545740 approved.

2024-10-14 21:53 UTC, dune-eng commented
Workflow run id 11335545623 approved.

2024-10-14 22:24 UTC, jeff-dude approved these changes
great, thanks!

we'll get this merged asap

2024-10-15 07:57 UTC, merged