Solana block prices
duneanalytics/spellbook pull request #7037
Opened 2024-10-25 19:07 UTC by couralex6

2024-10-25 19:20 UTC, couralex6 commented
Should probably move this model to the solana subproject

2024-10-25 19:21 UTC, jeff-dude commented
> Should probably move this model to the solana subproject

yes for sure

2024-10-25 19:28 UTC, jeff-dude requested changes

2024-10-25 19:28 UTC, jeff-dude commented on dbt_subprojects/dex/models/prices/dex_prices_block_solana.sql
> +    schema = 'dex'
```suggestion
    schema = 'dex_solana'
```

2024-10-25 19:28 UTC, jeff-dude commented on dbt_subprojects/dex/models/prices/dex_prices_block_solana.sql
> +    , alias = 'prices_block_solana'
```suggestion
    , alias = 'prices_block'
```

2024-10-25 19:28 UTC, jeff-dude commented on dbt_subprojects/dex/models/prices/dex_prices_block_solana.sql
dbt_subprojects/dex/models/prices/dex_solana_prices_block.sql

2024-10-25 19:28 UTC, jeff-dude commented on dbt_subprojects/dex/models/prices/dex_prices_block_solana.sql
> +        , token_bought_address
column names differ a bit in `dex_solana.trades`, you will likely hit errors on this select

2024-10-25 19:28 UTC, jeff-dude commented on dbt_subprojects/dex/models/prices/dex_prices_block_solana.sql
> +    inner join {{ source('prices', 'trusted_tokens') }} as tt
will want to validate we have solana tokens in here

2024-10-25 19:28 UTC, jeff-dude commented on dbt_subprojects/dex/models/prices/dex_prices_block_solana.sql
> +    inner join {{ source('tokens', 'erc20') }} as t
not sure we have solana in this table

we will need to check in the solana lineage how it leverages decimals to calculate amount_usd and then do similar here

doubtful our automated source for erc20 has solana tokens

2024-10-25 19:29 UTC, jeff-dude commented
until you get CI passing, i would suggest hardcoding a date filter for non-incremental to last few days to expedite

2024-10-31 16:38 UTC, jeff-dude requested changes

2024-10-31 16:38 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/dex/prices/dex_prices_block_solana.sql
> +        {% endif %} #}
```suggestion
        {% if is_incremental() %}
        and {{ incremental_predicate('block_time') }}
        {% endif %}
```

2024-10-31 16:38 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/dex/prices/dex_prices_block_solana.sql
> +        {% endif %} #}
lets keep this enabled along with the historical hardcoded filter

2024-10-31 16:38 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/dex/prices/dex_prices_block_solana.sql
> +        on t.blockchain = 'solana'
```suggestion
        on t.blockchain = tt.blockchain
```

2024-10-31 16:38 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/dex/prices/dex_prices_block_solana.sql
> +        on d.blockchain = 'solana'
```suggestion
        on d.blockchain = ptt.blockchain
```

2024-10-31 16:38 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/dex/prices/dex_prices_block_solana.sql
> +        on d.token_bought_mint_address = t.token_mint_address
```suggestion
        on d.token_sold_mint_address = t.token_mint_address
```

2024-10-31 16:38 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/dex/prices/dex_prices_block_solana.sql
> +        on d.blockchain = 'solana'
```suggestion
        on d.blockchain = ptt.blockchain
```

2024-10-31 16:40 UTC, jeff-dude requested changes

2024-10-31 16:40 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/dex/prices/dex_prices_block_solana.sql
> +    , incremental_strategy = 'merge'
```suggestion
    , incremental_strategy = 'delete+insert'
```

2024-10-31 16:40 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/dex/prices/dex_prices_block_solana.sql
> +    , cast(date_trunc('month', block_time) as date) as block_month -- for partitioning
```suggestion
    , cast(date_trunc('day', block_time) as date) as block_date -- for partitioning
```

2024-10-31 16:40 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/dex/prices/dex_prices_block_solana.sql
> +    , partition_by = ['block_month']
```suggestion
    , partition_by = ['block_date']
```

2024-10-31 17:03 UTC, jeff-dude requested changes

2024-10-31 17:03 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/dex/prices/dex_prices_block_solana.sql
> +    , incremental_predicates = [incremental_predicate('DBT_INTERNAL_DEST.block_time')]
can remove this after moving away from merge strategy, that's only useful there

2024-10-31 17:45 UTC, jeff-dude requested changes
in addition to file name below, can you put in schema.yml file similar to how evm version?

2024-10-31 17:45 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/dex/prices/dex_prices_block_solana.sql
dbt_subprojects/solana/models/_sector/dex/prices/dex_solana_prices_block.sql

2024-10-31 17:45 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/dex/prices/dex_prices_block_solana.sql
can you update file name to match table name?

2024-10-31 20:43 UTC, merged