Add Hyperjump trades
duneanalytics/spellbook pull request #7096
Opened 2024-11-03 02:35 UTC by bertastr

## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:

Add Hyperjump trades to dex.trades

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

2024-11-04 09:50 UTC, Hosuke requested changes

2024-11-04 09:50 UTC, Hosuke commented on dbt_subprojects/dex/models/trades/bnb/platforms/hyperjump_bnb_base_trades.sql
Hi @bertastr 
please add the schema for `hyperjump_bnb.base_trades` in the following file:
https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/dex/models/trades/bnb/_schema.yml

Thank you.

2024-11-04 16:57 UTC, bertastr commented on dbt_subprojects/dex/models/trades/bnb/platforms/hyperjump_bnb_base_trades.sql
I just did. Thank you @Hosuke

2024-11-04 17:17 UTC, Hosuke approved these changes
LGTM.✅
Thank you @bertastr 

[Sample hyperjump_bnb_base_trades](https://dune.com/queries/4243975)

2024-11-06 06:38 UTC, jeff-dude approved these changes

2024-11-06 07:06 UTC, merged