solana stablecoin balances
duneanalytics/spellbook pull request #7134
Opened 2024-11-11 19:05 UTC by Synthquest

## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:

Solana balances util table has gaps that exceed query capacity when trying to run. This fills null values on a subset of tokens

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

2024-11-11 19:26 UTC, Synthquest commented
cc: @jeff-dude

2024-11-17 09:25 UTC, Hosuke requested changes

2024-11-17 09:25 UTC, Hosuke commented on dbt_subprojects/solana/models/tokens/solana/tokens_solana_stablecoins.sql
> +      , unique_key = ['address']
unique_key is only required for incremental views.
```suggestion
```

2024-11-17 09:25 UTC, Hosuke commented on dbt_subprojects/solana/models/tokens/solana/_schema.yml
> +      - name: decimals
```suggestion
      - name: address
        description: "The address of the stablecoin on the Solana blockchain"
        data_tests:
          - unique
      - name: decimals
```

2024-11-17 23:01 UTC, Synthquest commented
Thanks @Hosuke 🙏

2024-11-18 16:38 UTC, jeff-dude approved these changes

2024-11-18 17:39 UTC, merged