Solana Daily Stablecoin Balances
duneanalytics/spellbook pull request #7154
Opened 2024-11-18 18:37 UTC by Synthquest

## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:

[...]

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

2024-11-19 21:03 UTC, Synthquest commented
@Hosuke 
Any idea why the schema isnt getting picked up?

it almost seems like the schema isnt getting configured right when it runs the test

2024-11-21 15:51 UTC, Synthquest commented
@jeff-dude any ideas here? I'm not sure why the schema isn't getting picked up

2024-11-21 18:52 UTC, jeff-dude commented
> @jeff-dude any ideas here? I'm not sure why the schema isn't getting picked up

i'm fairly certain it's due to where you placed the source. if you look at dbt project file, it expects to be in root directory sources:
https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/solana/dbt_project.yml#L23

since you have in subproject sources, it can't find it?

2024-11-21 20:57 UTC, Synthquest commented
> > @jeff-dude any ideas here? I'm not sure why the schema isn't getting picked up
> 
> i'm fairly certain it's due to where you placed the source. if you look at dbt project file, it expects to be in root directory sources: https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/solana/dbt_project.yml#L23
> 
> since you have in subproject sources, it can't find it?

Still getting issues with "schema does not exist" on the run after moving sources to the root model . If you create a new folder do you have to define it anywhere for solana? I don't think I've had to do that with the other envs

2024-11-21 21:06 UTC, jeff-dude commented
> Still getting issues with "schema does not exist" on the run after moving sources to the root model . If you create a new folder do you have to define it anywhere for solana? I don't think I've had to do that with the other envs

by root, i meant out of the subproject altogether. this source should live here:
https://github.com/duneanalytics/spellbook/blob/main/sources/_subprojects_outputs/solana/_sources.yml

2024-11-21 21:28 UTC, Synthquest commented
> > Still getting issues with "schema does not exist" on the run after moving sources to the root model . If you create a new folder do you have to define it anywhere for solana? I don't think I've had to do that with the other envs
> 
> by root, i meant out of the subproject altogether. this source should live here: https://github.com/duneanalytics/spellbook/blob/main/sources/_subprojects_outputs/solana/_sources.yml

still no luck

2024-11-21 21:28 UTC, jeff-dude requested changes

2024-11-21 21:28 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/stablecoins/stablecoins_solana_balances.sql
> +            inner join (select address, symbol from stable_definitions) sd on sd.address = bal.token_mint_address
```suggestion
            inner join (select address, symbol from stablecoin_tokens) sd on sd.address = bal.token_mint_address
```

2024-11-21 21:28 UTC, jeff-dude commented on dbt_subprojects/solana/models/_sector/stablecoins/stablecoins_solana_balances.sql
> +            inner join (select address, symbol from stable_definitions) sd on sd.address = bal.token_mint_address
ah, i think this is it, CTE name mismatch. i knew i had seen that error before, couldn't recall exactly what. need to document this!

2024-11-27 17:31 UTC, closed without merging