add udex trades
duneanalytics/spellbook pull request #7215
Opened 2024-11-30 09:31 UTC by clizzard7

Create spellbook vor udex on bnb
-> Dashboard is https://dune.com/whale_hunter/udex

2024-11-30 09:45 UTC, whalehunting requested changes

2024-11-30 09:45 UTC, whalehunting commented on dbt_subprojects/dex/models/bot_trades/udex/udex_bsc_bot_trades.sql
> +      LEFT JOIN erc20_bnb.evt_transfer as fee_payments ON (
change to {{source}} syntax

2024-11-30 09:45 UTC, whalehunting commented on dbt_subprojects/dex/models/bot_trades/udex/udex_bsc_bot_trades.sql
> +        AND to = 0x1df00191a32184675baA3fc0416A57009C386ed9 -- Vault
define vault address as variable

2024-11-30 09:45 UTC, whalehunting commented on dbt_subprojects/dex/models/bot_trades/udex/udex_bsc_bot_trades.sql
> +        token_sold_address = 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c, -- WBNB
use wbnb variable here

2024-11-30 11:01 UTC, whalehunting commented on dbt_subprojects/dex/models/bot_trades/udex/udex_bsc_bot_trades.sql
> +      'BSC' AS blockchain,
Use blockchain variable here

2024-11-30 11:01 UTC, whalehunting commented on dbt_subprojects/dex/models/bot_trades/udex/udex_bsc_bot_trades.sql
> +        AND date_trunc('minute', block_time) = minute
add incremental filter

2024-11-30 12:08 UTC, whalehunting requested changes

2024-11-30 12:08 UTC, whalehunting commented on dbt_subprojects/dex/models/bot_trades/udex/udex_bsc_bot_trades.sql
> +        AND date_trunc('minute', block_time) = minute
add incremental filter on block_time (see banana gun spellbook)

2024-11-30 12:08 UTC, whalehunting commented on dbt_subprojects/dex/models/bot_trades/udex/udex_bsc_bot_trades.sql
> +      {{'blockchain'}} AS blockchain,
change to '{{ blockchain }}'

2024-11-30 12:08 UTC, whalehunting commented on dbt_subprojects/dex/models/bot_trades/udex/udex_bsc_bot_trades.sql
> +  bot_trades.*,
manually add each column, keep column order same as in schema

2025-01-02 21:02 UTC, jeff-dude commented
closing due to inactivity. if needed, feel free to reopen a new PR with code + fixes.

2025-01-02 21:02 UTC, closed without merging