Add flashliquidity dex to trades
duneanalytics/spellbook pull request #7219
Opened 2024-12-02 09:01 UTC by archie17277

## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:

Add flashliquidity dex on base chain

2024-12-02 15:34 UTC, Hosuke commented
Is this the same PR as #7218?

2024-12-02 22:35 UTC, jeff-dude requested changes

2024-12-02 22:35 UTC, jeff-dude commented on dbt_subprojects/dex/models/trades/base/platforms/flashliquidity_base_base_trades.sql
> +        project = 'flashliquidity_base',
```suggestion
        project = 'flashliquidity',
```

2024-12-03 04:03 UTC, archie17277 commented on dbt_subprojects/dex/models/trades/base/platforms/flashliquidity_base_base_trades.sql
> +        project = 'flashliquidity_base',
Thank You @jeff-dude

2024-12-03 18:28 UTC, merged