Only keep validators with an assigned index in `staking_ethereum.flows`
duneanalytics/spellbook pull request #7234
Opened 2024-12-03 22:37 UTC by hildobby

…_ethereum.flows

## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:

[...]

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

2024-12-04 10:10 UTC, 0xRobin commented
@hildobby can you give more details on the external dataset you're using here?

2024-12-04 10:22 UTC, hildobby commented
> @hildobby can you give more details on the external dataset you're using here?

This dataset only contains validator_index and their corresponding pubkey values. This is because the BLS key check happens offchain due to it being quite compute heavy. So this dataset was fetched from beaconcha.in and using it as an inner join ensures that validator_index is correct while excluding non-valid deposits (there are a few, currently throwing off the validator_index values the current spell calculates by counting incrementally).

TLDR; this fixes a bug I've had for a while and makes the data accurate

2024-12-04 14:22 UTC, 0xRobin commented
Ok, thanks for explaining, how is the dataset maintained?

2024-12-04 16:45 UTC, hildobby commented
I defined the source (+ included it in a sources.yml) like on here: https://github.com/duneanalytics/spellbook/blob/588ca2762f9436ecf79a57b147f01c8d49ad91c3/dbt_subprojects/tokens/models/prices/prices_solana_day.sql#L25


But it's still failing, is there something I'm missing?

2024-12-05 07:13 UTC, 0xRobin commented on dbt_subprojects/hourly_spellbook/models/_sector/staking/ethereum/staking_ethereum_flows.sql
> +}}
@hildobby you duplicated the full model below, which uses incorrect syntax for the source (hence the compile error)

2024-12-17 18:44 UTC, jeff-dude commented
minor note: we are also in sync in TG group for design patterns related to the source in this PR

2025-01-03 10:13 UTC, 0xRobin commented
@hildobby we have new data available from Lido which should be able to resolve this bug without us depending on external scripts.
Can you look at the `beacon_lido.validators` table to resolve the index <> pubkey matching?

2025-01-07 17:33 UTC, hildobby commented
how should I reference an external dataset in spellbook? where should i place the schema file? and should the jinja part be a ref or a source? @0xRobin @jeff-dude

2025-01-07 17:39 UTC, 0xRobin commented
@hildobby from spellbooks view, this is just a normal source like a raw blockchain table.
So you can add a sources yaml file with it and use `{{source(..)}}`

I would add it under `/sources/lido/beacon`

2025-01-08 13:17 UTC, hildobby commented
> @hildobby from spellbooks view, this is just a normal source like a raw blockchain table. So you can add a sources yaml file with it and use `{{source(..)}}`
> 
> I would add it under `/sources/lido/beacon`
<img width="1190" alt="Screenshot 2025-01-08 at 14 17 10" src="https://github.com/user-attachments/assets/41cbd316-38f6-4ed9-bb48-25fd40429a47" />


seems like there's something weird here, what am I missing that's causing the CI error @0xRobin ?

2025-01-15 01:31 UTC, jeff-dude requested changes
looks good, just one minor request to remove old source file

2025-01-15 01:31 UTC, jeff-dude commented on sources/_subprojects_outputs/staking/_sources.yml
you should be good to remove this file now

2025-01-15 12:37 UTC, hildobby commented on sources/_subprojects_outputs/staking/_sources.yml
done

2025-01-15 13:02 UTC, jeff-dude approved these changes

2025-01-15 13:03 UTC, merged