Saddle Finance DEX on Optimism Chain
duneanalytics/spellbook pull request #7282
Opened 2024-12-10 04:41 UTC by PatelPrinci

## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:

[...]

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

2024-12-10 13:39 UTC, Hosuke requested changes
Minor fixes to make sure the seed test working properly.

2024-12-10 13:39 UTC, Hosuke commented on dbt_subprojects/dex/models/trades/optimism/platforms/saddle_finance_optimism_base_trades.sql
> +    unique_key = ['block_date', 'blockchain', 'project', 'version', 'tx_hash', 'evt_index']
```suggestion
    unique_key = ['tx_hash', 'evt_index']
```

2024-12-10 13:39 UTC, Hosuke commented on dbt_subprojects/dex/models/trades/optimism/_schema.yml
> +            version: 2
```suggestion
```

2024-12-12 17:05 UTC, Hosuke commented
Please run `git merge main` to update this PR.
Thank you.

2024-12-17 13:55 UTC, Hosuke approved these changes
LGTM.✅
Thank you @PatelPrinci

2024-12-17 18:52 UTC, jeff-dude approved these changes

2024-12-20 10:40 UTC, merged