Swapline DEX on Base
duneanalytics/spellbook pull request #7284
Opened 2024-12-10 07:03 UTC by PatelPrinci

## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:

[...]

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

2024-12-10 13:47 UTC, Hosuke requested changes
Filter version does not match the seed version, we may need to remove the filter in this case.

2024-12-12 14:59 UTC, Hosuke commented on dbt_subprojects/dex/models/trades/base/platforms/swapline_base_base_trades.sql
> +    unique_key = ['block_date', 'blockchain', 'project', 'version', 'tx_hash', 'evt_index']
```suggestion
    unique_key = ['tx_hash', 'evt_index']
```

2024-12-30 10:24 UTC, Hosuke requested changes

2024-12-30 10:24 UTC, Hosuke commented on sources/_sector/dex/trades/base/_sources.yml
> +      - name: SwaplinePair_evt_Swap
```suggestion
  - name: swapline_base
    tables:
      - name: SwaplinePair_evt_Swap
      - name: LBPair_evt_Swap
      - name: LBFactory_evt_LBPairCreated
```

2024-12-30 10:24 UTC, Hosuke commented on dbt_subprojects/dex/models/trades/base/platforms/swapline_base_base_trades.sql
> +)
Maybe we need to apply `uniswap_compatible_v2_trades` macro here with `LBFactory_evt_LBPairCreated` table to produce dex.trades.

2025-01-23 19:24 UTC, jeff-dude commented
closing due to inactivity

2025-01-23 19:24 UTC, closed without merging