DUX-808 Init viction dex
duneanalytics/spellbook pull request #7294
Opened 2024-12-11 08:07 UTC by Hosuke

Init viction dex.
Sync with my latest progress.

2024-12-12 16:53 UTC, Hosuke commented on sources/_sector/dex/trades/viction/_sources.yml
> +      - name: CONTRACT_FACTORY_evt_PairCreated
```suggestion
      - name: BaryonFactory_evt_PairCreated
```

2025-01-07 17:35 UTC, jeff-dude requested changes

2025-01-07 17:35 UTC, jeff-dude commented on sources/_sector/dex/trades/viction/_sources.yml
> +  #     - name: UniswapV3Factory_evt_PoolCreated
we can remove mori completely from the PR, no longer adding at this time

2025-01-07 17:35 UTC, jeff-dude commented on sources/_sector/dex/trades/viction/_sources.yml
> +      # - name: RabbitSwapV3Pool_evt_Swap
nia is actively looking to decode these, more to come soon 🙏

2025-01-07 18:10 UTC, Hosuke commented on sources/_sector/dex/trades/viction/_sources.yml
> +  #     - name: UniswapV3Factory_evt_PoolCreated
```suggestion
```

2025-01-07 18:11 UTC, Hosuke commented on dbt_subprojects/dex/models/trades/viction/_schema.yml
> +            - evt_index
```suggestion
```

2025-02-16 20:03 UTC, jeff-dude commented
still blocked here, i have notified the team.

2025-02-19 16:50 UTC, jeff-dude commented
the team has decided to move on from adding these, as we aren't getting what we need from the chain

2025-02-19 16:50 UTC, closed without merging