Add Mavis Market to nft.trades
duneanalytics/spellbook pull request #7355
Opened 2024-12-19 08:10 UTC by peterrliem

## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:

[...]

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

2024-12-20 10:13 UTC, Murshadddd commented
#7234

2024-12-23 10:59 UTC, 0xRobin requested changes
Left some questions/comments around data QA.
It would also be nice to add a seed test to the model. 
You can see how that is done for collectionswap here:
seed: https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/nft/seeds/trades/base_trades/collectionswap_ethereum_base_trades_seed.csv
schema: https://github.com/duneanalytics/spellbook/blob/6a2d09f5025520e2b1db53453c73e75a7e303ad2/dbt_subprojects/nft/seeds/trades/base_trades/_schema.yml#L196-L206
test: https://github.com/duneanalytics/spellbook/blob/6a2d09f5025520e2b1db53453c73e75a7e303ad2/dbt_subprojects/nft/models/_sector/trades/chains/ethereum/platforms/_schema.yml#L573-L586

2024-12-23 10:59 UTC, 0xRobin commented on dbt_subprojects/nft/models/_sector/trades/chains/ronin/platforms/mavis_ronin_base_trades.sql
> +  '' as trade_category,
This should be 'Buy' or 'Sell'.
If it's not possible to determine the trade direction, feel free to just set 'Buy' as the default.

2024-12-23 10:59 UTC, 0xRobin commented on dbt_subprojects/nft/models/_sector/trades/chains/ronin/platforms/mavis_ronin_base_trades.sql
> +  '' as trade_type,
This should be 'secondary'

2024-12-23 10:59 UTC, 0xRobin commented on dbt_subprojects/nft/models/_sector/trades/chains/ronin/platforms/mavis_ronin_base_trades.sql
> +  cast(json_extract_scalar(replace(json_extract_scalar(json_parse(json_extract_scalar("order", '$.info')),'$.assets[0]'),'\\', ''),'$.quantity') as double) as quantity,
This seems to return 0 in quite some cases, it should always be 1 or greater

2024-12-23 10:59 UTC, 0xRobin commented on dbt_subprojects/nft/models/_sector/trades/chains/ronin/platforms/mavis_ronin_base_trades.sql
> +  platform_fee_amount_raw,
This always returns `200` currently which seems to be the ratio and not the actual raw value?

2024-12-23 10:59 UTC, 0xRobin commented on dbt_subprojects/nft/models/_sector/trades/chains/ronin/platforms/mavis_ronin_base_trades.sql
> +  -- ronin_treasury_fee_amount_raw,
if you want, you can keep these in this model. 
They won't make it into `nft.trades` but at least they'll be available in the project specific model.

2024-12-27 11:59 UTC, 0xRobin approved these changes

2024-12-30 08:41 UTC, merged