OTSea DEX on Base
duneanalytics/spellbook pull request #7390
Opened 2024-12-27 09:33 UTC by PatelPrinci

## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:

[...]

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

2024-12-29 10:22 UTC, 0xRobin requested changes

2024-12-29 10:22 UTC, 0xRobin commented on dbt_subprojects/dex/models/trades/base/platforms/otsea_base_base_trades.sql
> +        {{ source('otsea_base', 'OTSeaV2_evt_SwappedTokensForETH') }}
Seems like this only covers 1 event type, are there other events that this should cover? (swapping for other token, swapping eth for token,..).

2024-12-29 10:22 UTC, 0xRobin commented on dbt_subprojects/dex/models/trades/base/platforms/otsea_base_base_trades.sql
> +        account AS token_sold_address,
This isn't accurate as it takes the swappers address as the token address

2025-01-02 05:10 UTC, PatelPrinci commented on dbt_subprojects/dex/models/trades/base/platforms/otsea_base_base_trades.sql
> +        {{ source('otsea_base', 'OTSeaV2_evt_SwappedTokensForETH') }}
Thank you for informing me! I will make sure to add other events, such as swapping for other tokens or swapping ETH for tokens, to ensure comprehensive coverage. 😊

2025-01-03 05:13 UTC, PatelPrinci commented
Thank you for addressing the issue. I have made the modifications for the
token address

On Sun, 29 Dec 2024 at 15:52, 0xRob ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> dbt_subprojects/dex/models/trades/base/platforms/otsea_base_base_trades.sql
> <https://github.com/duneanalytics/spellbook/pull/7390#discussion_r1899103125>
> :
>
> > +
> +WITH token_swaps AS (
> +    SELECT
> +        evt_block_number AS block_number,
> +        CAST(evt_block_time AS timestamp(3) with time zone) AS block_time,
> +        evt_tx_from AS maker,
> +        evt_tx_to AS taker,
> +        swapped AS token_sold_amount_raw,
> +        received AS token_bought_amount_raw,
> +        account AS token_sold_address,
> +        token AS token_bought_address,
> +        contract_address AS project_contract_address,
> +        evt_tx_hash AS tx_hash,
> +        evt_index AS evt_index
> +    FROM
> +        {{ source('otsea_base', 'OTSeaV2_evt_SwappedTokensForETH') }}
>
> Seems like this only covers 1 event type, are there other events that this
> should cover? (swapping for other token, swapping eth for token,..).
> ------------------------------
>
> In
> dbt_subprojects/dex/models/trades/base/platforms/otsea_base_base_trades.sql
> <https://github.com/duneanalytics/spellbook/pull/7390#discussion_r1899103167>
> :
>
> > +    partition_by = ['block_month'],
> +    materialized = 'incremental',
> +    file_format = 'delta',
> +    incremental_strategy = 'merge',
> +    unique_key = ['block_date', 'blockchain', 'project', 'version', 'tx_hash', 'evt_index']
> +) }}
> +
> +WITH token_swaps AS (
> +    SELECT
> +        evt_block_number AS block_number,
> +        CAST(evt_block_time AS timestamp(3) with time zone) AS block_time,
> +        evt_tx_from AS maker,
> +        evt_tx_to AS taker,
> +        swapped AS token_sold_amount_raw,
> +        received AS token_bought_amount_raw,
> +        account AS token_sold_address,
>
> This isn't accurate as it takes the swappers address as the token address
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/duneanalytics/spellbook/pull/7390#pullrequestreview-2524918975>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BNGN7KMTSHF7E22NWR4M3CD2H7EPNAVCNFSM6AAAAABUIL5OG6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRUHEYTQOJXGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-03 06:30 UTC, Hosuke requested changes
This may not be the ideal implementation for OTSea on Base.
However, currently OTSea event sources are limited.

We need to fix the address value first:
https://dune.com/queries/4514265

2025-01-03 06:30 UTC, Hosuke commented on dbt_subprojects/dex/models/trades/base/platforms/otsea_base_base_trades.sql
> +        CAST('0x0000000000000000000000000000000000000000' AS varbinary) AS token_bought_address,
```suggestion
        0x0000000000000000000000000000000000000000 AS token_bought_address,
```

2025-01-03 06:30 UTC, Hosuke commented on dbt_subprojects/dex/models/trades/base/platforms/otsea_base_base_trades.sql
> +        CAST('0x0000000000000000000000000000000000000000' AS varbinary) AS token_sold_address,
```suggestion
        0x0000000000000000000000000000000000000000 AS token_sold_address,
```

2025-01-03 17:53 UTC, Hosuke requested changes

2025-01-03 17:53 UTC, Hosuke commented on dbt_subprojects/dex/seeds/trades/otsea_base_base_trades_seed.csv
> +base,otsea,1,2024-05-01 00:00,2024-05-02 00:00,2024-05-02 07:41,13923182,88652482269503546099290,4000000000000000,0x9c1a0802fbe08bf7c68bb336820b7b2a7e4eb697,0x0000000000000000000000000000000000000000
Please verify the trade:
https://basescan.org/tx/0xb6038c12bff786acb485fef9402d4215c97242a757c3f21ffebd0fe1aee7e92d

2025-01-03 17:53 UTC, Hosuke commented on dbt_subprojects/dex/seeds/trades/otsea_base_base_trades_seed.csv
> +base,otsea,1,2024-05-01 00:00,2024-05-09 00:00,2024-05-09 23:24,14253851,122404014850000000,1000000000000000000,0xf41c500e45868f7cf73098c5699c1343d6d30051,0x0000000000000000000000000000000000000000,0
Please verify the trade:
https://basescan.org/tx/0x9d02c7614fc425df8614259e6b80890d13db5b8545a9095e3529d430fb6fc44f#eventlog
One trading token should be `0xfD0F44da2a76e61585032dE6E54174a4b0c1CfB8`.

2025-01-04 06:31 UTC, PatelPrinci commented
Okay, I'll look into the issue and resolve it as soon as possible!!


On Fri, 3 Jan 2025 at 23:24, Huang Geyang ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In dbt_subprojects/dex/seeds/trades/otsea_base_base_trades_seed.csv
> <https://github.com/duneanalytics/spellbook/pull/7390#discussion_r1902025304>
> :
>
> > @@ -0,0 +1,3 @@
> +blockchain,project,version,block_month,block_date,block_time,block_number,token_sold_amount_raw,token_bought_amount_raw,token_sold_address,token_bought_address,maker,taker,project_contract_address,tx_hash,evt_index
> +base,otsea,1,2024-05-01 00:00,2024-05-02 00:00,2024-05-02 07:41,13923182,88652482269503546099290,4000000000000000,0x9c1a0802fbe08bf7c68bb336820b7b2a7e4eb697,0x0000000000000000000000000000000000000000,0x9c1a0802fbe08bf7c68bb336820b7b2a7e4eb697,0xa836af59d35b3da3c9fb5cfd6f84d9e3bd8c5fd5,0xa836af59d35b3da3c9fb5cfd6f84d9e3bd8c5fd5,0xb6038c12bff786acb485fef9402d4215c97242a757c3f21ffebd0fe1aee7e92d,161
>
> Please verify the trade:
>
> https://basescan.org/tx/0xb6038c12bff786acb485fef9402d4215c97242a757c3f21ffebd0fe1aee7e92d
> ------------------------------
>
> In dbt_subprojects/dex/seeds/trades/otsea_base_base_trades_seed.csv
> <https://github.com/duneanalytics/spellbook/pull/7390#discussion_r1902027080>
> :
>
> > @@ -0,0 +1,3 @@
> +blockchain,project,version,block_month,block_date,block_time,block_number,token_sold_amount_raw,token_bought_amount_raw,token_sold_address,token_bought_address,maker,taker,project_contract_address,tx_hash,evt_index
> +base,otsea,1,2024-05-01 00:00,2024-05-02 00:00,2024-05-02 07:41,13923182,88652482269503546099290,4000000000000000,0x9c1a0802fbe08bf7c68bb336820b7b2a7e4eb697,0x0000000000000000000000000000000000000000,0x9c1a0802fbe08bf7c68bb336820b7b2a7e4eb697,0xa836af59d35b3da3c9fb5cfd6f84d9e3bd8c5fd5,0xa836af59d35b3da3c9fb5cfd6f84d9e3bd8c5fd5,0xb6038c12bff786acb485fef9402d4215c97242a757c3f21ffebd0fe1aee7e92d,161
> +base,otsea,1,2024-05-01 00:00,2024-05-09 00:00,2024-05-09 23:24,14253851,122404014850000000,1000000000000000000,0xf41c500e45868f7cf73098c5699c1343d6d30051,0x0000000000000000000000000000000000000000,0xf41c500e45868f7cf73098c5699c1343d6d30051,0xa836af59d35b3da3c9fb5cfd6f84d9e3bd8c5fd5,0xa836af59d35b3da3c9fb5cfd6f84d9e3bd8c5fd5,0x9d02c7614fc425df8614259e6b80890d13db5b8545a9095e3529d430fb6fc44f,226
>
> Please verify the trade:
>
> https://basescan.org/tx/0x9d02c7614fc425df8614259e6b80890d13db5b8545a9095e3529d430fb6fc44f#eventlog
> One trading token should be 0xfD0F44da2a76e61585032dE6E54174a4b0c1CfB8.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/duneanalytics/spellbook/pull/7390#pullrequestreview-2529485724>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BNGN7KPMIQF25E66TSOXITT2I3FDZAVCNFSM6AAAAABUIL5OG6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRZGQ4DKNZSGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-18 11:49 UTC, Hosuke approved these changes
LGTM.✅
Thank you @PatelPrinci 

[Sample otsea_base_base_trades]()

2025-01-18 11:49 UTC, Hosuke commented on dbt_subprojects/dex/models/trades/base/platforms/otsea_base_base_trades.sql
> +        0x0000000000000000000000000000000000000000 AS token_sold_address,
Which one is better for `ETH` address on base?
`0x4200000000000000000000000000000000000006`
or
`0x0000000000000000000000000000000000000000`

2025-01-20 09:17 UTC, 0xRobin commented on dbt_subprojects/dex/models/trades/base/platforms/otsea_base_base_trades.sql
> +        0x0000000000000000000000000000000000000000 AS token_sold_address,
`0x0000000000000000000000000000000000000000` for ETH
`0x4200000000000000000000000000000000000006` for WETH

2025-01-21 09:52 UTC, Hosuke reviewed
We can remove extra comments to keep the code clean.

2025-01-21 09:52 UTC, Hosuke commented on dbt_subprojects/dex/models/trades/base/platforms/otsea_base_base_trades.sql
> +        -- CAST('0x0000000000000000000000000000000000000000' AS varbinary) AS token_sold_address,
```suggestion
```

2025-01-21 09:52 UTC, Hosuke commented on dbt_subprojects/dex/models/trades/base/platforms/otsea_base_base_trades.sql
> +        -- CAST('0x0000000000000000000000000000000000000000' AS varbinary) AS token_bought_address,
```suggestion
```

2025-01-21 11:58 UTC, closed without merging