I added the Spectra token price
duneanalytics/spellbook pull request #7395
Opened 2024-12-27 14:53 UTC by okolicodes7

### Description:
I added the Spectra (APW) token details and the coinpaprika id 

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

2025-01-02 23:05 UTC, jeff-dude requested changes

2025-01-02 23:05 UTC, jeff-dude commented on dbt_subprojects/tokens/models/prices/ethereum/prices_ethereum_tokens.sql
> +    ('apw-spectra','ethereum', 'APW', 0x4104b135dbc9609fc1a9490e61369036497660c8, 18)
```suggestion
    ('sovrn-sovrun','ethereum', 'SOVRN', 0x031B8d752d73d7Fe9678ACEf26e818280D0646b4, 18),
    ('apw-spectra','ethereum', 'APW', 0x4104b135dbc9609fc1a9490e61369036497660c8, 18)
```

2025-01-02 23:06 UTC, jeff-dude commented
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/duneanalytics/spellbook/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

welcome to spellbook. in order to contribute, plz follow directions here to sign license agreement 🙏

2025-01-07 21:52 UTC, okolicodes7 commented
I have read the CLA Document and I hereby sign the CLA

2025-01-08 20:55 UTC, jeff-dude approved these changes

2025-01-09 17:06 UTC, merged