init beets dex models
duneanalytics/spellbook pull request #7399
Opened 2024-12-30 10:50 UTC by viniabussafi

## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:

[...]

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

2024-12-30 11:18 UTC, viniabussafi commented
Hey, @Hosuke! Apparently I'm blocked by https://github.com/duneanalytics/spellbook/pull/7341. Any ETA here? thanks!

2024-12-30 12:15 UTC, Hosuke commented
> Hey, @Hosuke! Apparently I'm blocked by #7341. Any ETA here? thanks!

The PR may be merged in the next batch merging.

2025-01-02 23:08 UTC, jeff-dude commented
i will look to merge foundation PR linked above tomorrow 🙏 
it may take some time for prices to ingest, we should ensure we get that data built out and test `amount_usd` calculations on CI tables when ready, prior to merge

2025-01-03 09:38 UTC, viniabussafi commented
> it may take some time for prices to ingest, we should ensure we get that data built out and test amount_usd calculations on CI tables when ready, prior to merge

sounds good, Jeff! Hopefully we'll be able to test this on monday. thank you!

2025-01-03 19:20 UTC, viniabussafi commented
Current check is here: https://dune.com/queries/4516954
About 50% of swaps have amount_usd = 0.
Have another PR to improve pricing here: https://github.com/duneanalytics/spellbook/pull/7414
Sonic team is in contact with coinpaprika to add stS, which should drastically improve this number as well

2025-01-03 19:45 UTC, jeff-dude commented
> about pricing of trades, @jeff-dude:
> 
> Current check is here: https://dune.com/queries/4516954 About 45% of swaps have amount_usd = 0. I have another PR to improve pricing here: #7414 which will help in about 25% of those no value swaps (as you can see here) Sonic team is in contact with coinpaprika to add stS, which should drastically improve this number as well (as you can see [here](https://dune.com/queries/4517180))
> 
> Code-wise, regarding the beets spell, it all works on my end, so will mark ready for review, but I'm open to work on any points you have

thanks for getting this moving!

i'm using this query to help determine most swapped tokens, as a good indicator for which handful should be in [trusted tokens](https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/tokens/models/prices/prices_trusted_tokens.sql#L146-L149) for amount calculations. it's clear that `stS` is a must, we should add to trusted tokens for sure. we can also determine if we want to leave this open until we get it approved and included in coinpaprika, following sonic team's lead on that. in addition to that token, we should likely add [this](https://sonicscan.org/token/0xd3DCe716f3eF535C5Ff8d041c1A41C3bd89b97aE?a=0xd3f925042d39c23e7126e140ad1423142721c97c) one too, which is third in swaps.

```
with
    tokens as (
        select
            token_bought_address as token,
            count(tx_hash) as swaps
        FROM
            test_schema.git_dunesql_c990747_beets_trades
        group by
            token_bought_address
        union distinct
        select
            token_sold_address as token,
            count(tx_hash) as swaps
        FROM
            test_schema.git_dunesql_c990747_beets_trades
        group by
            token_sold_address
    )
select
    token,
    sum(swaps)
from
    tokens
group by
    token
order by
    2 desc
```

can you make those tweaks to trusted tokens / prices spells in #7414 ?

2025-01-03 22:08 UTC, viniabussafi commented
Thanks, jeff!
Will hold until monday to see if coinpaprika gets updated with at least stS so I can update the other PR and we can merge this one with better data.

2025-01-06 19:18 UTC, jeff-dude commented
> Thanks, jeff! Will hold until monday to see if coinpaprika gets updated with at least stS so I can update the other PR and we can merge this one with better data.

let me know if you don't hear back from CP team, i think i have a contact to help expedite (or i can at least try)

2025-01-06 19:53 UTC, viniabussafi commented
Would be awesome if they could help, @jeff-dude! Still haven't heard back

2025-01-07 20:22 UTC, jeff-dude approved these changes
do you want to continue to wait a bit, to ensure prices are built as expected in prod, to get clean historical build here?

(marking blocked until other comment resolved + answer to above question)

2025-01-07 20:22 UTC, jeff-dude commented on dbt_subprojects/dex/models/trades/dex_base_trades.sql
> +    ref('dex_sonic_base_trades')
let's be sure to revert this exclusion prior to merge, if you're good with CI output 🙏

2025-01-07 20:41 UTC, viniabussafi commented on dbt_subprojects/dex/models/trades/dex_base_trades.sql
> +    ref('dex_sonic_base_trades')
will update on the next commit. 
I'm comfortable with merging if you are, given that token amounts are correct.

2025-01-07 20:46 UTC, viniabussafi commented on dbt_subprojects/dex/models/trades/dex_base_trades.sql
> +    ref('dex_sonic_base_trades')
skipped CI since testing is no longer needed, btw
thanks for the help as always, jeff and hosuke

2025-01-08 20:59 UTC, jeff-dude requested changes

2025-01-08 20:59 UTC, jeff-dude commented on dbt_subprojects/dex/models/trades/dex_base_trades.sql
> -    , ref('dex_flare_base_trades')
likely due to recent merge / accident in commit, but can you re-enable flare too?

2025-01-09 08:01 UTC, viniabussafi commented on dbt_subprojects/dex/models/trades/dex_base_trades.sql
> -    , ref('dex_flare_base_trades')
done!

2025-01-09 17:01 UTC, jeff-dude approved these changes

2025-01-09 17:14 UTC, merged