Added hourly interest for Aave on Base
duneanalytics/spellbook pull request #7404
Opened 2024-12-31 17:51 UTC by mikeghen

## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:
* Added hourly interest for Aave on Base. 
* Follows the existing implementation implementation for Aave interest rates on Optimism. 

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

2024-12-31 17:52 UTC, mikeghen commented
I have read the CLA Document and I hereby sign the CLA.

2025-01-02 08:11 UTC, Hosuke requested changes

2025-01-02 08:11 UTC, Hosuke commented on dbt_subprojects/daily_spellbook/models/aave/base/aave_base_schema.yml
> +    columns:
```suggestion
    description: "Hourly aave interest rates on base"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - reserve
            - symbol
            - hour
    columns:
```

2025-01-02 08:11 UTC, Hosuke commented on dbt_subprojects/daily_spellbook/models/aave/base/aave_v3_base_interest_rates.sql
> +  , post_hook='{{ expose_spells(blockchains = \'["base"]\',
```suggestion
   schema = 'aave_v3_base'
  , alias = 'interest_rates'
  , materialized = 'incremental'
  , file_format = 'delta'
  , incremental_strategy = 'merge'
  , unique_key = ['reserve', 'symbol', 'hour']
  , post_hook='{{ expose_spells(blockchains = \'["base"]\',
```

2025-01-02 08:11 UTC, Hosuke commented on dbt_subprojects/daily_spellbook/models/aave/base/aave_v3_base_interest_rates.sql
> +on a.reserve = t.contract_address
`symbol` is currently null.

2025-01-02 08:11 UTC, Hosuke commented on dbt_subprojects/daily_spellbook/tests/aave/base/aave_base_interests_test.sql
> +        where  symbol = 'USDC'
This test may not work properly.

2025-01-02 08:12 UTC, Hosuke commented
Current [aave_v3_base_interest_rates](https://dune.com/queries/4510183)

2025-01-02 15:37 UTC, mikeghen commented
@Hosuke Thank you for the review, and for sharing a link to the table, I was having trouble finding the table in the test_schema. I'll work on fixing the issues and let you know when it's ready for another review.

2025-01-02 16:38 UTC, mikeghen commented on dbt_subprojects/daily_spellbook/models/aave/base/aave_v3_base_interest_rates.sql
> +on a.reserve = t.contract_address
I changed to use `tokens.erc20`: https://github.com/duneanalytics/spellbook/pull/7404/commits/ceb747b6922de227703938a8fe5a0c9aca2f9dee

2025-01-02 16:40 UTC, mikeghen commented on dbt_subprojects/daily_spellbook/tests/aave/base/aave_base_interests_test.sql
> +        where  symbol = 'USDC'
I updated this test to use correct values and a valid token symbol: https://github.com/duneanalytics/spellbook/pull/7404/commits/2f80416f3c5d351218f2d34fa4c048f1e9110fc3

2025-01-02 16:47 UTC, mikeghen commented on dbt_subprojects/daily_spellbook/tests/aave/base/aave_base_interests_test.sql
> +        where  symbol = 'USDC'
I updated these values to use real ones and the token symbol is now WETH instead: https://github.com/duneanalytics/spellbook/pull/7404/commits/2f80416f3c5d351218f2d34fa4c048f1e9110fc3

2025-01-02 18:25 UTC, mikeghen commented
@Hosuke, I addressed the comments you left above if you would check they are resolved. 

Also, I was wondering if you might know why the table created has it's most recent data as "2023-11-11 08:00," over a year ago. Is this because of the way `test_schema` works? I would have expected dates as recent as today 2025-01-02.

2025-01-02 19:33 UTC, Hosuke commented
> @Hosuke, I addressed the comments you left above if you would check they are resolved.
> 
> Also, I was wondering if you might know why the table created has it's most recent data as "2023-11-11 08:00," over a year ago. Is this because of the way `test_schema` works? I would have expected dates as recent as today 2025-01-02.

The reason is the source you used `aave_v3_base.Pool_evt_ReserveDataUpdated` only has the latest data at `2023-11-11 08:54`:
https://dune.com/queries/4512697

We may need to verify this source, or use/submit another better contract's evt.

2025-01-02 20:12 UTC, mikeghen commented
@Hosuke, I took a look and I think I found the right table to use: `aave_v3_base.L2Pool_evt_ReserveDataUpdated` which looks like the current deployment of the Aave Pool contract, the other table is the an old pool contract I think.

2025-01-03 06:35 UTC, Hosuke approved these changes
LGTM.✅
Thank you @mikeghen 

[Sample aave_v3_base_interest_rates](https://dune.com/queries/4514285)

2025-01-03 13:17 UTC, mikeghen commented
Great, thanks for your help @Hosuke 🙏

2025-01-03 16:16 UTC, jeff-dude approved these changes
thanks for joining us and building in spellbook!

2025-01-03 16:18 UTC, merged